### ISSUE TITLE
dvc import: misleading warnings and outputs

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#2839] opened 2019-11-23 01:07 UTC
```
$ dvc -V
0.70.0+3de46d
```

One data file was updated in the imported repo. However, it was not a file that I'm trying to update.
```
$ dvc update data/data.xml.dvc
WARNING: DVC-file 'data/data.xml.dvc' changed.
WARNING: Stage 'data/data.xml.dvc' changed.
Importing 'data.xml (https://github.com/dmpetrov/dataset)' -> 'data/data.xml'
Output 'data/data.xml' didn't change. Skipping saving.
```

- [x] UI issues 1: It should not be imported since there are no changes. **Output: Importing 'data.xml (https://github.com/dmpetrov/dataset)' -> 'data/data.xml'**
- [x] UI issues 2: Warning duplication **DVC-file 'data/data.xml.dvc' changed.** and **Stage 'data/data.xml.dvc' changed.**

PS: Updated file was `dir1/file2` which is corresponding to stage file `dir1.dvc`

EDITED:

- [ ] Issue 3 (not UI): It turned out that `data/data.xml.dvc` was actually updated after the update command - the repo checksum was changed (while checksum was not updated in the changed file `dir1.dvc`) with dvc-file checksum. Is it expected?

- [x] Issue 4 (not UI): When I update a stage that was actually changed I still see this **output ... didn't change** message while the outputs were changed and even cache was updated. This happens even when I import a single artifact from a repo (I've check in another project).  Code:
```
$ dvc update dir1.dvc
WARNING: DVC-file 'dir1.dvc' changed.
WARNING: Stage 'dir1.dvc' changed.
Importing 'dir1 (https://github.com/dmpetrov/dataset)' -> 'dir1'
Output 'dir1' didn't change. Skipping saving.
```

**Comment by pared** [comment] 2019-11-25 18:05
Reproduction script:

```
#!/bin/bash

rm -rf repo remote_repo storage git_repo
mkdir repo remote_repo storage git_repo

pushd remote_repo
git init >> /dev/null && dvc init -q

set -x
set -e
echo data >> data
echo data2 >> data2
dvc remote add -d str /home/prd/development/playground/2839/storage
dvc add -q data data2
git add .dvc/config data.dvc .gitignore data2.dvc
git commit -m "add data"
dvc push -q

popd
pushd repo

git init >> /dev/null && dvc init -q
dvc import -q ../remote_repo data

popd
pushd remote_repo

echo data_new >> data2
dvc add data2
git add data2.dvc
git commit -m "modify data2"

dvc push

popd 
pushd repo
dvc update data.dvc
```

**Comment by dberenbaum** [comment] 2022-02-18 21:05
This is much improved since the issue was opened.

The output of the script @pared provided in the old version was:

```
WARNING: DVC-file 'data.dvc' changed.
WARNING: Stage 'data.dvc' changed.
Importing 'data (../remote_repo)' -> 'data'
Output 'data' didn't change. Skipping saving.
```

Currently, it is:

```
Importing 'data (../remote_repo)' -> 'data'
```

This looks like everything other than issue 3 above has been addressed. Not sure what expected behavior is in this case where the repo has been updated but without changes to the specified file. @pared @efiop Any thoughts on this?

**Comment by efiop** [comment] 2023-12-08 12:09
Seems like point 3 is expected as that's the level of granularity we are dealing with in dvc update. Closing.

**Closed by efiop** 2023-12-08 12:09 UTC
Labels: p2-medium, ui, research
