### ISSUE TITLE
[minor bug] Dvc pull files count (fetched different from total)

### ISSUE THREAD

**Issue by andrethrill** [iterative/dvc#1689] opened 2019-03-06 10:51 UTC
```
dvc --version
0.30.1
```

Just finished executing `dvc pull`  successfully.

Nevertheless noticed this, which may be considered a bug (the total count is smaller than the actually downloaded files) and thought it was worth reporting.

<img width="476" alt="image" src="https://user-images.githubusercontent.com/25300892/53875858-68db7780-3ffd-11e9-8621-9e2ba0bb34a6.png">

**Comment by pared** [comment] 2019-03-06 12:16
Thanks @andrethrill. It definitely seems like bug!

**Comment by shcheklein** [comment] 2019-03-06 18:12
@pared is it progress bar related bug? pull itself is not affected I hope?

**Comment by mroutis** [comment] 2019-03-06 19:39
@shcheklein , is not, I think the problem is in the recently added `progress_aware` decorator (under `dvc/progress.py`) I'll take a look into it.

**Comment by mroutis** [comment] 2019-03-19 02:31
@pared , I think this related https://github.com/iterative/dvc/issues/1643 I'll unassign me

**Comment by pared** [comment] 2019-04-26 23:52
@andrethrill I was trying to reproduce this issue, and am unable to do that. I tried nesting some directories with files inside, but numbers do match. Can you retry this on your side?

**Comment by andrethrill** [comment] 2019-04-29 09:53
@pared since it's a costly operation I can let you know once I need to run it again. But it may take a while.

**Comment by efiop** [comment] 2019-04-29 16:57
@andrethrill Let's close it for now then, please feel free to reopen if you encounter this issue again. Thanks for the feedback! :)

**Closed by efiop** 2019-04-29 16:57 UTC
Labels: bug
