### ISSUE TITLE
add: Filenames containing the : character give an error.

### ISSUE THREAD

**Issue by Astro-mh** [iterative/dvc#8773] opened 2023-01-06 14:57 UTC
# Bug Report

## Description

DVC doesn't recognise file paths containing the : character, and instead tries to treat them as URLs, giving the error (for the file filena:me):

```console
ERROR: config file error: Unsupported URL type filena:// 
```

### Reproduce

1. dvc init
2. touch filena:me
3. dvc add filena:me
### Expected

File should be added to the dvc repository.
### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.38.1 (conda)
---------------------------------
Platform: Python 3.11.0 on macOS-13.1-arm64-arm-64bit
Subprojects:
	dvc_data = 0.28.4
	dvc_objects = 0.14.0
	dvc_render = 0.0.15
	dvc_task = 0.1.8
	dvclive = 1.3.0
	scmrepo = 0.1.4
Supports:
	http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	ssh (sshfs = 2022.6.0)
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
```

**Additional Information (if any):**

**Comment by karajan1001** [comment] 2023-01-07 11:22
I can reproduce it. it's a bug of `dvc add`

**Comment by pmrowla** [comment] 2023-01-08 09:42
related: https://github.com/iterative/dvc-objects/issues/177

**Comment by karanjakhar** [comment] 2023-01-08 16:50
It is happening because we consider the filename also a URL. And urlparse returns filena as scheme.

**Comment by pmrowla** [comment] 2023-02-07 04:41
This should be resolved by https://github.com/iterative/dvc-objects/pull/179

**Comment by daavoo** [comment] 2023-02-07 09:00
> This should be resolved by https://github.com/iterative/dvc-objects/pull/179

@pmrowla This one is different. It fails at config validation because the `:`causes DVC to interpret the path as a remote URL:

https://github.com/iterative/dvc/blob/f68a12558aac7da25c721877e855d5c115d07261/dvc/config_schema.py#L50-L55

**Closed** 2023-02-14 11:21 UTC
Labels: bug, A: data-management
