### ISSUE TITLE
dvc list: option to specify dvc remote

### ISSUE THREAD

**Issue by nik123** [iterative/dvc#6196] opened 2021-06-18 15:15 UTC
I have a project with several DVC remotes. When I execute `dvc list . data/some/dirs` in my workspace sometimes I need to specify dvc remote. Similar with `-r` option in `pull`/`push` commands.

**Comment by efiop** [comment] 2021-06-18 21:17
Hi @nik123 , thanks for the request!

Supporting remotes in `list` is tied to `get/import` as well, so we need to consider more things in order to provide a holistic experience.

Could you elaborate on the scenario in which you don't have that remote already set as default? Do you use multiple remotes to isolate artifacts with different permissions?

Duplicate of https://github.com/iterative/dvc/issues/2466

**Comment by nik123** [comment] 2021-06-19 07:11
> Could you elaborate on the scenario in which you don't have that remote already set as default? Do you use multiple remotes to isolate artifacts with different permissions?

My use case: I have two remotes which I access via ssh from my laptop. Both remotes in fact point to the same server but with different IP addresses: I use "internal" remote to access remote from internal network, and "external" remote to access remote from  external network. Which remote I use at the given moment depends on my location - most of the time it's "internal" which is way faster (therefore it is set as default) but from time to time I have to access remote from external network. For `pull` and `push` it works fine cose I may specify remote with `-r` option but it's not the case for `dvc list`.

**P.S.:** even if I set "external" remote as default I still encounter problems with `dvc list`. It seems that `dvc list` doesn't take custom port into account. But I guess it's another issue.

**Comment by efiop** [comment] 2021-06-19 14:36
> My use case: I have two remotes which I access via ssh from my laptop. Both remotes in fact point to the same server but with different IP addresses: I use "internal" remote to access remote from internal network, and "external" remote to access remote from external network. Which remote I use at the given moment depends on my location - most of the time it's "internal" which is way faster (therefore it is set as default) but from time to time I have to access remote from external network. For pull and push it works fine cose I may specify remote with -r option but it's not the case for dvc list.

Thanks for sharing! Very interesting use case. I guess what you are really looking for here is a mirroring mechanism, where your `fast` remote would have a higher priority, but when/if we are failing to connect to it - we would ideally automatically switch to the next one - your external remote. Or am I misinterpreting your use case?

> P.S.: even if I set "external" remote as default I still encounter problems with dvc list. It seems that dvc list doesn't take custom port into account. But I guess it's another issue.

Is port part of url? If it is, could you try configuring it explicitly with `dvc remote modify myremote port myport`, please?

**Comment by nik123** [comment] 2021-06-20 08:11
> > P.S.: even if I set "external" remote as default I still encounter problems with dvc list. It seems that dvc list doesn't take custom port into account. But I guess it's another issue.
> 
> Is port part of url? If it is, could you try configuring it explicitly with `dvc remote modify myremote port myport`, please?

It helped. Thanks!

**Comment by nik123** [comment] 2021-06-20 09:19
> Thanks for sharing! Very interesting use case. I guess what you are really looking for here is a mirroring mechanism, where your `fast` remote would have a higher priority, but when/if we are failing to connect to it - we would ideally automatically switch to the next one - your external remote. Or am I misinterpreting your use case?

There is no misinterpretation of my use case. But honestly, I didn't think about it in this way. Since I often use `-r` option with `pull`/`push` commands, I was concentrated on expanding this workflow on `list` command.

However, having a mechanism which automatically switches from one remote to another is a neat solution. It eliminates the need for `-r` option in `list` command for me. If such mechanism will cover other commands like `pull`/`push` then in my case there would be no need in `-r` option at all. In sum, the proposed mechanism fits me perfectly, but it seems it should go well beyond `list` command.

**Comment by efiop** [comment] 2021-06-21 19:40
> It helped. Thanks!

Could you show how it was specified before? Be sure to anonymize the IP if it is not a VPN one, of course ;) Looks like there might be a bug in parsing the url or something.

> There is no misinterpretation of my use case. But honestly, I didn't think about it in this way. Since I often use -r option with pull/push commands, I was concentrated on expanding this workflow on list command.

> However, having a mechanism which automatically switches from one remote to another is a neat solution. It eliminates the need for -r option in list command for me. If such mechanism will cover other commands like pull/push then in my case there would be no need in -r option at all. In sum, the proposed mechanism fits me perfectly, but it seems it should go well beyond list command.


Sounds good. I think `-r` for `list` is possible too, since in your use case you only want to pick a remote that is already configured in that project. We've received requests for specifying outside remotes (e.g. from a host repo in which you run `dvc import`), where it is quite a bit less trivial. But looks like we really need to get back to this general problem in the near future.

Ok, let's then close this issue in favor of #2466 Since mirroring wasn't really intuitive for you (user) and it is not close in terms of implementation (there are questions about pushing, for example) and is overall a more of a stretch, we can put it aside for now, until we get a better scenario.

**Comment by nik123** [comment] 2021-06-29 19:55
> Ok, let's then close this issue in favor of #2466 Since mirroring wasn't really intuitive for you (user) and it is not close in terms of implementation (there are questions about pushing, for example) and is overall a more of a stretch, we can put it aside for now, until we get a better scenario.

@efiop I don't mind closing it in favor of #2466. Probably description of that issue should be changed and mention not only `get` but also `import` and `list`.

**Comment by efiop** [comment] 2021-06-30 23:44
Sounds good. Closing for now.

**Closed by efiop** 2021-06-30 23:44 UTC
Labels: awaiting response

**Comment by nik123** [comment] 2021-07-04 16:59
> > It helped. Thanks!
> 
> Could you show how it was specified before? Be sure to anonymize the IP if it is not a VPN one, of course ;) Looks like there might be a bug in parsing the url or something.

I'm not sure if the issue is URL related. I've run several tests today and I can't reproduce this behavior again. My only guess now is that I've made a typo then manually editing `.dvc/config.local`. I feel silly, sorry for wasting your time :disappointed: 

Anyway, here is definition remote in my `.dvc/config`:

```
['remote "slow"']
url = ssh://user@ip_address/path/to/dir
port = 8888
ask_password = false
```

**Comment by efiop** [comment] 2021-07-04 20:21
@nik123 That might be because you've upgraded to 2.5.0, in which we've fixed that bug :slightly_smiling_face: Thanks for the feedback! :pray:
