### ISSUE TITLE
dvc exp run: '/data/dvccache/*' does not start with '/data/user/repo'

### ISSUE THREAD

**Issue by schuhschuh** [iterative/dvc#5471] opened 2021-02-16 01:36 UTC
# Bug Report

## Description

The first time I run `dvc exp run`, it checked out all the cached data files (even of stages and pipelines in other folders that I was not interested in, but will report as separate issue). I am using symbolic links because reflinks are not supported by our server FS. Since then subsequent `dvc exp run` fail because of an error which suggests that the symlinks are being resolved and the resulting real paths do not match the root of my Git repository.

```
> CUDA_VISIBLE_DEVICES=1 dvc exp run --name exp_name --single-item train
ERROR: unexpected error - '/data/dvccache/51/985c61898087396d5cc3a007b6b621' does not start with '/data/user/repo'
```

### Environment information

**Output of `dvc version`:**

```console
$ dvc version
DVC version: 2.0.0a0+273b02
---------------------------------
Platform: Python 3.7.9 on Linux-3.10.0-1127.8.2.el7.x86_64-x86_64-with-centos-7.8.2003-Core
Supports: http, https, s3
```

**Additional Information (if any):**

`/data/user/repo/subdir/.dvc/config`:
```
[core]
    remote = store
    analytics = false
[cache]
    dir = /data/dvccache
    shared = group
    type = reflink,symlink
    slow_link_warning = true
```

**Comment by pared** [comment] 2021-02-16 16:06
@schuhschuh Is there anything special about the stage, besides the fact of using links and cache outside the repo?
I tried reproducing for a simple pipeline, but no success (or rather failure) so far.
Would it be possible to post some more logged information?

**Comment by efiop** [comment] 2021-02-16 17:37
@schuhschuh Could you please run your command again with `-v` flag added and post full log? It contains things like traceback, which really help pinpoint particular issue.

**Comment by aschuh-hf** [comment] 2021-02-17 16:18
Stage (with minor adaptations):
```
  train_patches:
    cmd: python -m train --log-dir data/{now} --config patches.yaml --save {logdir}/model.pt --metrics metrics.json
    deps:
      - data/patches.h5
    params:
      - patches.yaml:
        - model
        - train
    metrics:
      - metrics.json:
          cache: false
```
Here, `deps` entry `data/patches.h5` is the output of data generation stage.

Verbose command output:
```
> CUDA_VISIBLE_DEVICES=0 dvc exp run -v --name issue-5471 --single-item train_patches
2021-02-17 16:14:30,985 DEBUG: Check for update is enabled.
2021-02-17 16:14:30,986 DEBUG: '/data/aschuh/hfresearch/projects/istn/.dvc/tmp/updater' is outdated
2021-02-17 16:14:31,027 DEBUG: Trying to spawn '['daemon', '-q', 'updater']'
2021-02-17 16:14:31,028 DEBUG: Spawned '['daemon', '-q', 'updater']'
2021-02-17 16:14:35,531 ERROR: unexpected error - '/data/dvccache/research/istn/51/985c61898087396d5cc3a007b6b621' does not start with '/data/aschuh/hfresearch'
------------------------------------------------------------
Traceback (most recent call last):
  File "/hf/home/aschuh/source/dvc/dvc/main.py", line 50, in main
    ret = cmd.run()
  File "/hf/home/aschuh/source/dvc/dvc/command/experiments.py", line 528, in run
    **self._repro_kwargs,
  File "/hf/home/aschuh/source/dvc/dvc/repo/experiments/__init__.py", line 833, in run
    return run(self.repo, *args, **kwargs)
  File "/hf/home/aschuh/source/dvc/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/hf/home/aschuh/source/dvc/dvc/repo/experiments/run.py", line 38, in run
    targets=targets, params=params, tmp_dir=tmp_dir, **kwargs
  File "/hf/home/aschuh/source/dvc/dvc/repo/experiments/__init__.py", line 354, in reproduce_one
    staged, _, _ = self.scm.status()
  File "/hf/home/aschuh/source/dvc/dvc/scm/git/__init__.py", line 338, in _backend_func
    return func(*args, **kwargs)
  File "/hf/home/aschuh/source/dvc/dvc/scm/git/backend/dulwich.py", line 560, in status
    self.root_dir, ignored=ignored
  File "/hf/home/aschuh/tools/conda/envs/istn/lib/python3.7/site-packages/dulwich/porcelain.py", line 1203, in status
    untracked_changes = list(untracked_paths)
  File "/hf/home/aschuh/tools/conda/envs/istn/lib/python3.7/site-packages/dulwich/porcelain.py", line 1255, in get_untracked_paths
    ip = path_to_tree_path(basepath, ap)
  File "/hf/home/aschuh/tools/conda/envs/istn/lib/python3.7/site-packages/dulwich/porcelain.py", line 252, in path_to_tree_path
    relpath = path.relative_to(repopath)
  File "/hf/home/aschuh/tools/conda/envs/istn/lib/python3.7/pathlib.py", line 900, in relative_to
    .format(str(self), str(formatted)))
ValueError: '/data/dvccache/research/istn/51/985c61898087396d5cc3a007b6b621' does not start with '/data/aschuh/hfresearch'
------------------------------------------------------------
2021-02-17 16:14:43,649 DEBUG: Version info for developers:
DVC version: 2.0.0a0+273b02
---------------------------------
Platform: Python 3.7.9 on Linux-3.10.0-1127.8.2.el7.x86_64-x86_64-with-centos-7.8.2003-Core
Supports: http, https, s3
Cache types: hardlink, symlink
Cache directory: xfs on /dev/sda1
Caches: local
Remotes: s3, s3
Workspace directory: xfs on /dev/sda1
Repo: dvc (subdir), git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-02-17 16:14:43,654 DEBUG: Analytics is disabled.
```

**Comment by pmrowla** [comment] 2021-02-18 02:19
Looks like a dulwich issue, I filed a report for it: https://github.com/dulwich/dulwich/issues/842

Will try to get an upstream fix done w/the other ongoing git work

**Comment by pmrowla** [comment] 2021-02-23 06:29
Should be closed by https://github.com/dulwich/dulwich/pull/843

**Closed** 2021-03-04 10:37 UTC
Labels: bug
