### ISSUE TITLE
get: sometimes a temp file still remains

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/dvc#6210] opened 2021-06-22 16:04 UTC
# Description

I have a data registry. Sometimes when I do ```dvc get``` I can see that tmp folders and files are created but happens that after finished there are still remaining a temp file like this example

```
fashion_mnis.kHYTLfUKVsuR7dgLHtNDcp.tmp
```

### Reproduce

Very hard to reproduce

```
dvc get your-registry yourdataset -o data
```

### Expected

Not having that file? I guess

### Environment information

```console
VC version: 2.3.0 (deb)
---------------------------------
Platform: Python 3.8.10 on Linux-5.10.25-linuxkit-x86_64-with-glibc2.7
Supports: All remotes
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: fuse.grpcfuse on grpcfuse
Repo: dvc, git
```

My data registry is in S3

**Comment by skshetry** [comment] 2021-06-22 16:06
Duplicate of https://github.com/iterative/dvc/issues/5355

**Comment by skshetry** [comment] 2021-06-22 16:07
@DavidGOrtega, thanks for creating the issue. We are tracking that in #5355, so I am going to close this issue.

**Comment by skshetry** [comment] 2021-06-22 16:09
Btw, does that happen on success too?

**Comment by skshetry** [comment] 2021-07-05 10:26
Closing, most likely it's #5355 which happens on failure (as happy path moves stuff).

https://github.com/iterative/dvc/blob/2485779d59143799d4a489b42294ee6b7ce52a80/dvc/fs/base.py#L337-L343

We should be handling exception, and deleting tmp_file on failure there.

**Closed by skshetry** 2021-07-05 10:26 UTC
Labels: awaiting response
