### ISSUE TITLE
repro: auto-pull a file if needed for a pipeline

### ISSUE THREAD

**Issue by bon** [iterative/dvc#1791] opened 2019-03-27 16:27 UTC
If a data file that dvc knows about is needed for a pipeline it needs to be present. If it's not, it has to be pulled before running the pipeline. Couldn't dvc pull the file as part of the pipeline so it doesn't have to be pulled manually?

**Comment by efiop** [comment] 2019-03-27 16:38
Hi @bon !

Thanks for a feature request! :slightly_smiling_face: 
I've transferred it from dvc.org repo(where dvc.org site lives) to dvc repo (where actual dvc project lives).

**Comment by bon** [comment] 2019-03-27 20:50
Oops! Sorry for not checking carefully. Thanks for the correction @efiop

**Comment by efiop** [comment] 2019-08-28 11:01
Related discord discussion https://discordapp.com/channels/485586884165107732/485596304961962003/616223478722461697

**Comment by raimannma** [comment] 2020-09-17 22:50
Auto-pull would be great, because we have large data sets and want them to be loaded into the CI only when needed.

Maybe just display a warning to avoid unexpected behaviour.

**Comment by efiop** [comment] 2021-05-03 15:16
Closing in favor of https://github.com/iterative/dvc/issues/4742

**Closed by efiop** 2021-05-03 15:16 UTC
Labels: feature request, p3-nice-to-have
