### ISSUE TITLE
remove: Confusing error message 

### ISSUE THREAD

**Issue by karajan1001** [iterative/dvc#7382] opened 2022-02-15 08:56 UTC
# Bug Report

DVC gives confusing error message on `dvc remove`

## Description
In a repository without any pipelines. DVC didn't give proper a suggestion for users that `dvc remove` can only remove `.dvc` file. But returns a confusing error message `ERROR: 'dvc.yaml' does not exist`.  

### Reproduce
```bash
$ mkdir tmp
$ cd tmp
$ git init
$ dvc init
$ touch data
$ dvc add data
$ dvc remove data
ERROR: 'dvc.yaml' does not exist
```

### Expected
Suggests user to use `dvc remove data.dvc`.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.9.4.dev118+g2efe90d0
---------------------------------
Platform: Python 3.8.8 on macOS-10.16-x86_64-i386-64bit
Supports:
	azure (adlfs = 2021.10.0, knack = 0.8.0, azure-identity = 1.5.0),
	gdrive (pydrive2 = 1.9.4),
	gs (gcsfs = 2022.1.0),
	hdfs (fsspec = 2022.1.0, pyarrow = 3.0.0),
	webhdfs (fsspec = 2022.1.0),
	http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
	https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
	s3 (s3fs = 2022.1.0, boto3 = 1.20.24),
	ssh (sshfs = 2021.11.2),
	oss (ossfs = 2021.8.0),
	webdav (webdav4 = 0.9.3),
	webdavs (webdav4 = 0.9.3)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
```

**Additional Information (if any):**

**Comment by skshetry** [comment] 2022-02-15 09:47
This is because `remove` does not support specifying output, just the `.dvc` file or stage name.

**Comment by skshetry** [comment] 2022-02-15 09:47
Duplicate of #5288.

**Closed by skshetry** 2022-02-15 09:47 UTC
Labels: ui
