### ISSUE TITLE
import: does not work with repositories using params

### ISSUE THREAD

**Issue by pared** [iterative/dvc#7307] opened 2022-01-25 22:59 UTC
Importing some data from parametrized repository does not work.

reproduction:
```bash
#!/bin/bash

set -ex

pushd $TMPDIR

wsp=test_wspace
imp_repo=import_repo
rep=test_repo

rm -rf $wsp && mkdir $wsp && pushd $wsp
base=$(pwd)
mkdir $base/$imp_repo
mkdir $base/$rep

pushd $base/$imp_repo
git init
dvc init

echo data >> data
echo "m: 1" >> params.yaml

dvc add data
dvc run -d data -p m -o out -n train cp data out
git add -A
git commit -am "init"

pushd $base/$rep
git init
dvc init

dvc import $base/$imp_repo out -o my_out -v
```

Result:

```
dvc.parsing.ResolveError: failed to parse 'vars' in 'dvc.yaml': 'params.yaml' does not exist
```

On the first sight the culprit seems to be `dvc/repo/stage.py::_maybe_collect_from_dvc_yaml` which passes `dvc.yaml` to `StageLoad.load_all`, while it seems that it should be a path to the file.
https://github.com/iterative/dvc/blob/d882e21b9b013f69abff960a8bad62d822024b59/dvc/repo/stage.py#L66

Kudos to @oslobowl for discovering the problem.

**Comment by skshetry** [comment] 2022-01-26 12:59
Looks like the issue is how we use `wdir` instead of git repo's root, which happens here:
https://github.com/iterative/dvc/blob/d882e21b9b013f69abff960a8bad62d822024b59/dvc/parsing/context.py#L402

This is definitely serious bug, and may need serious consideration on how to fix on filesystem side. Assigning it myself.

**Comment by efiop** [comment] 2022-02-15 13:19
Depends on moving repofs to relative paths. Will take a look after that.

**Comment by mnrozhkov** [comment] 2022-02-22 13:40
@skshetry are there any workarounds for this until we fix it?

**Comment by pared** [comment] 2022-02-22 13:43
@mnrozhkov downgrading to `2.8.1` seems to help, we are trying to pinpoint the exact change introducing the bug.

**Comment by skshetry** [comment] 2022-02-22 14:03
`bisect` points me to e8e1c76504895f846ef5724c02f5414f4a251f7f as being the culprit.

**Comment by mh-synth** [comment] 2022-04-07 12:15
Having the same issue, and downgrading to `2.8.1` does _not_ seem to help in my case.

**Comment by series8217** [comment] 2022-04-08 22:53
We have had to roll back to 2.8.1 as well to get around this issue.

**Comment by pared** [comment] 2022-04-14 14:59
@mh-synth What error do you get?

**Closed** 2022-04-18 11:19 UTC
Labels: :bug: bug, p1-important, A: templating, A: params

**Comment by oslobowl** [comment] 2022-06-09 08:59
@pared Hello :)
Was this problem ever solved? I still have to roll back to 2.8.1.
(.venv) asdf@1234:/workspaces/my_pipeline$ dvc --version
2.9.3
(.venv) asdf@1234:/workspaces/my_pipeline$ dvc update data/data.gz.parquet.dvc 
Importing 'data/data.gz.parquet (https://github.com/me/my_pipeline.git)' -> 'data/data.gz.parquet'     
ERROR: failed update data - failed to parse 'vars' in 'dvc.yaml': 'params.yaml' does not exist

**Comment by oslobowl** [comment] 2022-06-09 09:12
@efiop Yes, sorry. Using 2.11.0 I just get another error:
**ERROR**: failed update data - Failed to clone repo 'https://github.com/me/my_pipeline.git' to '/tmp/tmpb9j9yyrudvc-clone'

**Comment by efiop** [comment] 2022-06-09 10:07
@oslobowl Do you have access to that repo? Does `git clone` work for it? Are you using https://www.git-scm.com/docs/gitcredentials ?

**Comment by oslobowl** [comment] 2022-06-09 10:11
@efiop Yes, I have access. Git clone and everything else works. My git is setup correctly :)

**Comment by efiop** [comment] 2022-06-09 10:26
@oslobowl Could you post a full verbose log, please? (add `-v` to the command you are running). Possibly you are using git credentials and so will have to wait for https://github.com/jelmer/dulwich/pull/976

**Comment by oslobowl** [comment] 2022-06-09 10:32
I don't think my organization is using git credentials. I would be happy to figure it out, but as you probably already inferred I'm not an IT-wizard :)

verbose log:
(.venv) asdf@1234:/workspaces/my_pipeline$ dvc update -v data/data.gz.parquet.dvc
2022-06-09 10:02:07,396 DEBUG: Creating external repo https://github.com/me/my_repo.git@None
2022-06-09 10:02:07,396 DEBUG: erepo: git clone 'https://github.com/me/my_repo.git' to a temporary dir
2022-06-09 10:02:07,753 ERROR: failed update data - Failed to clone repo 'https://github.com/me/my_repo.git' to '/tmp/tmpfufp8r7advc-clone'
------------------------------------------------------------
Traceback (most recent call last):
  File "scmrepo/git/backend/dulwich/__init__.py", line 196, in clone
  File "dulwich/porcelain.py", line 443, in clone
  File "dulwich/client.py", line 747, in clone
  File "dulwich/client.py", line 824, in fetch
  File "dulwich/client.py", line 2079, in fetch_pack
  File "dulwich/client.py", line 1938, in _discover_references
  File "dulwich/client.py", line 2219, in _http_request
dulwich.client.HTTPUnauthorized: No valid credentials provided

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "dvc/scm.py", line 145, in clone
  File "scmrepo/git/__init__.py", line 143, in clone
  File "scmrepo/git/backend/dulwich/__init__.py", line 199, in clone
scmrepo.exceptions.CloneError: Failed to clone repo 'https://github.com/me/my_repo.git' to '/tmp/tmpfufp8r7advc-clone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dvc/commands/update.py", line 16, in run
  File "dvc/repo/__init__.py", line 49, in wrapper
  File "dvc/repo/update.py", line 34, in update
  File "dvc/stage/__init__.py", line 439, in update
  File "dvc/stage/imports.py", line 21, in update_import
  File "dvc/dependency/repo.py", line 85, in update
  File "contextlib.py", line 113, in __enter__
  File "dvc/external_repo.py", line 39, in external_repo
  File "dvc/external_repo.py", line 169, in _cached_clone
  File "funcy/decorators.py", line 45, in wrapper
  File "funcy/flow.py", line 274, in wrap_with
  File "funcy/decorators.py", line 66, in __call__
  File "dvc/external_repo.py", line 239, in _clone_default_branch
  File "dvc/scm.py", line 150, in clone
dvc.scm.CloneError: Failed to clone repo 'https://github.com/me/my_repo.git' to '/tmp/tmpfufp8r7advc-clone'
------------------------------------------------------------
2022-06-09 10:02:07,761 DEBUG: Analytics is enabled.
2022-06-09 10:02:07,763 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpugwhdpe_']'
2022-06-09 10:02:07,765 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpugwhdpe_']'

**Comment by oslobowl** [comment] 2022-06-09 11:41
@dtrifiro Yes, I redacted the log for anonymization purposes :) I'll ask a colleague that actually knows what he is talking about wrt. the authentication to github

**Comment by oslobowl** [comment] 2022-06-09 13:26
@dtrifiro hello again! So, apparently we authenticate to github with git credentials via username/PAT or Git Credential Manager

**Comment by efiop** [comment] 2022-06-09 17:04
@oslobowl With dvc already installed through pip, try
```
pip install git+https://github.com/dtrifiro/dulwich.git@feature/credential-helper
```
and try running your command again.

Some explanation on what is going on: we've stopped using CLI git (to not depend on it, so that dvc works in limited setups like docker containers, where you might not want to install cli git) and using `dulwich` now (pure-python git implementation), which is lacking some features, like this gitcredentials support. @dtrifiro is working hard to get that feature supported in dulwich and in dvc 🙏

**Comment by oslobowl** [comment] 2022-06-09 18:36
@efiop Thanks for the explanation Ruslan :) we are cheering for you and we are very grateful for the great support we get with issues :)

I tried what you said, and I still get the same error unfortunately:

```
(.venv) asdf@1234:/workspaces/my_pipeline$ dvc update -v data/output.gz.parquet.dvc 
2022-06-09 18:32:09,558 DEBUG: Creating external repo https://github.com/me/my_repo.git@None
2022-06-09 18:32:09,558 DEBUG: erepo: git clone 'https://github.com/me/my_repo.git' to a temporary dir
2022-06-09 18:32:09,840 ERROR: failed update data - Failed to clone repo 'https://github.com/me/my_repo.git' to '/tmp/tmppnijk_gydvc-clone'
------------------------------------------------------------
Traceback (most recent call last):
  File "/workspaces/my_pipeline/.venv/lib/python3.8/site-packages/scmrepo/git/backend/dulwich/__init__.py", line 196, in clone
    repo = clone_from()
  File "/workspaces/my_pipeline/.venv/lib/python3.8/site-packages/dulwich/porcelain.py", line 443, in clone
    return client.clone(
  File "/workspaces/my_pipeline/.venv/lib/python3.8/site-packages/dulwich/client.py", line 747, in clone
    result = self.fetch(path, target, progress=progress, depth=depth)
  File "/workspaces/my_pipeline/.venv/lib/python3.8/site-packages/dulwich/client.py", line 824, in fetch
    result = self.fetch_pack(
  File "/workspaces/my_pipeline/.venv/lib/python3.8/site-packages/dulwich/client.py", line 2079, in fetch_pack
    refs, server_capabilities, url = self._discover_references(
  File "/workspaces/my_pipeline/.venv/lib/python3.8/site-packages/dulwich/client.py", line 1938, in _discover_references
    resp, read = self._http_request(url, headers)
  File "/workspaces/my_pipeline/.venv/lib/python3.8/site-packages/dulwich/client.py", line 2219, in _http_request
    raise HTTPUnauthorized(resp.getheader("WWW-Authenticate"), url)
dulwich.client.HTTPUnauthorized: No valid credentials provided

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspaces/my_pipeline/.venv/lib/python3.8/site-packages/dvc/scm.py", line 145, in clone
    git = Git.clone(url, to_path, progress=pbar.update_git, **kwargs)
  File "/workspaces/my_pipeline/.venv/lib/python3.8/site-packages/scmrepo/git/__init__.py", line 143, in clone
    backend.clone(url, to_path, **kwargs)
  File "/workspaces/my_pipeline/.venv/lib/python3.8/site-packages/scmrepo/git/backend/dulwich/__init__.py", line 199, in clone
    raise CloneError(url, to_path) from exc
scmrepo.exceptions.CloneError: Failed to clone repo 'https://github.com/me/my_repo.git' to '/tmp/tmppnijk_gydvc-clone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspaces/my_pipeline/.venv/lib/python3.8/site-packages/dvc/commands/update.py", line 16, in run
    self.repo.update(
  File "/workspaces/my_pipeline/.venv/lib/python3.8/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/workspaces/my_pipeline/.venv/lib/python3.8/site-packages/dvc/repo/update.py", line 34, in update
    stage.update(rev, to_remote=to_remote, remote=remote, jobs=jobs)
  File "/workspaces/my_pipeline/.venv/lib/python3.8/site-packages/dvc/stage/__init__.py", line 439, in update
    update_import(
  File "/workspaces/my_pipeline/.venv/lib/python3.8/site-packages/dvc/stage/imports.py", line 21, in update_import
    stage.deps[0].update(rev=rev)
  File "/workspaces/my_pipeline/.venv/lib/python3.8/site-packages/dvc/dependency/repo.py", line 85, in update
    with self._make_repo(locked=False) as repo:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/workspaces/my_pipeline/.venv/lib/python3.8/site-packages/dvc/external_repo.py", line 39, in external_repo
    path = _cached_clone(url, rev, for_write=for_write)
  File "/workspaces/my_pipeline/.venv/lib/python3.8/site-packages/dvc/external_repo.py", line 169, in _cached_clone
    clone_path, shallow = _clone_default_branch(url, rev, for_write=for_write)
  File "/workspaces/my_pipeline/.venv/lib/python3.8/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/workspaces/my_pipeline/.venv/lib/python3.8/site-packages/funcy/flow.py", line 274, in wrap_with
    return call()
  File "/workspaces/my_pipeline/.venv/lib/python3.8/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/workspaces/my_pipeline/.venv/lib/python3.8/site-packages/dvc/external_repo.py", line 239, in _clone_default_branch
    git = clone(url, clone_path)
  File "/workspaces/my_pipeline/.venv/lib/python3.8/site-packages/dvc/scm.py", line 150, in clone
    raise CloneError(str(exc))
dvc.scm.CloneError: Failed to clone repo 'https://github.com/me/my_repo.git' to '/tmp/tmppnijk_gydvc-clone'
------------------------------------------------------------
2022-06-09 18:32:09,865 DEBUG: Analytics is enabled.
2022-06-09 18:32:09,905 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpxn7_j_t9']'
2022-06-09 18:32:09,907 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpxn7_j_t9']'
```

**Comment by efiop** [comment] 2022-06-09 21:03
@oslobowl Please show outputs of these three commands

```
dvc doctor
pip freeze | grep dvc
pip freeze | grep dulwich
```

**Comment by oslobowl** [comment] 2022-06-10 07:35
@efiop 

**dvc doctor:**
```
DVC version: 2.11.0 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-3.10.0-1160.15.2.el7.x86_64-x86_64-with-glibc2.29
Supports:
        hdfs (fsspec = 2022.5.0, pyarrow = 8.0.0),
        webhdfs (fsspec = 2022.5.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6)
Cache types: hardlink, symlink
Cache directory: xfs on /dev/mapper/rootvg-home_lv
Caches: local
Remotes: azure
Workspace directory: xfs on /dev/mapper/rootvg-home_lv
Repo: dvc, git
```

**pip freeze | grep dvc**
```
dvc==2.11.0
dvc-data==0.0.2
dvc-objects==0.0.2
dvc-render==0.0.5
dvclive==0.8.2
```
**pip freeze | grep dulwich**
`dulwich==0.20.43`

**Comment by efiop** [comment] 2022-06-10 09:06
@oslobowl Looks like you've installed dulwich into some other env, that is not the same as dvc's. If you do it correctly, `pip freeze | grep dulwich` should look like this:

```
dulwich @ git+https://github.com/dtrifiro/dulwich.git@452bc9afca5feee95b85f1dd96a5b22517edf398
```
