### ISSUE TITLE
push: add `--force` option to force push without `.dir` optimization

### ISSUE THREAD

**Issue by pmrowla** [iterative/dvc#7532] opened 2022-04-01 05:54 UTC
Hello! First of all I wanted to thank you for how well you always answer, it's really nice and trustworthy.

We have had the same problem, a dvc push of a folder with 41 files, which ended correctly (apparently, because there were no error messages) and yet only 40 files were uploaded.

Doing dvc pull on another server got us the error.

Now there has been no way to force the push where the files are because it only checks that the folder.dvc (f9c8def4b2a1a6b783209d933e26a6.dir) exists on the remote and not the files that are inside the folder.

Is there a way to do dvc push --recursive or maybe dvc push --force it to try to upload the files again?

By the way, we deleted the file f9c8def4b2a1a6b783209d933e26a6.dir from the remote and this time the missing files were uploaded, but now we have the doubt if it has happened to us in other projects.

_Originally posted by @atekoa in https://github.com/iterative/dvc/issues/4164#issuecomment-1084650211_

**Comment by dberenbaum** [comment] 2022-04-01 11:57
Duplicate of #7268?

**Closed** 2022-04-01 12:59 UTC
Labels: feature request, p2-medium, A: data-sync
