### ISSUE TITLE
External files monitoring and production vs modeling pipelines

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#642] opened 2018-04-10 07:47 UTC
People are constantly asking for external data files support. Which means that  `dvc repro` should understand that some external file (S3 or HDFS for example) was changed and affected steps have to be reproduced.

At the first glance, DVC should support of external files monitoring on `dvc add` level:
```
$ dvc add s3://mybucket/ml/img_segment/sources/file.zip .
```
or even on the `dvc run` level:
```
$ dvc run -d s3://mybucket/ml/img_segment/sources/file.zip -o images/ python unpack_and _preprocess.py
```
The next `dvc repro` command will validate S3 checksum and upload the file again if needed.

Whether this approach simplifies production\data engineering scenarios **it conflicts with modeling scenarios and data+code consistency**.
1. A DVC repro loses reproducibility since a data set is outside of the DVC cache.
2. We force data scientists to work in a more complicated production environment when files can change any time.

We should clearly separate the production and the modeling scenarios with a priority to the modeling one. Base on the separation it is better to keep DVC API as is and inject S3\HDFS connection only for a specific `dvc repro` run.

This might look like:
```
$ aws s3 cp s3://mybucket/ml/img_segment/sources/file.zip .
$ dvc add file.zip
...
# Inject external dependency to S3:
$ dvc external s3://mybucket/ml/img_segment/sources/file.zip files.zip
# Reproduce with respect to external dependencies
$ dvc repro --check-externals
```
or
```
$ dvc add --external s3://mybucket/ml/img_segment/sources/file.zip files.zip
$ dvc repro --check-externals
```

Ideally data scientist should build models without even thinking about the production stuff (like S3\HDFS updates). For data engineers DVC should looks like a black box with a set of inputs (externals) and outputs. This black box can be injected to a production pipeline like Airflow, Luigi or a custome one. It is important to manage the externals in the data engineering side (pipeline and ETL) independently from data scientist.

**Creating lightweight, modeling specific pipelines and separating them from the complicated data enginering and ETL pipelines (Airflow, Luigi, Ozzie) is one of the DVC innovations.** But these two worlds should coexist a production environment and we should develop connectors.

Open questions:
1. API/commands for the externals.
2. How to localize all the externals in a single file? So, a data scientist can work with a file copy where `production` branch can have a special external settings which points to production S3 files?
3. What is the best name/term for externals?

We should think more about the externals API (and a proper name).

**Comment by villasv** [comment] 2018-04-10 13:47
I believe that having this feature hidden inside a flag like `--check-externals` should be OK. Reproducibility is untouched as far as default DVC behavior goes.

`dvc add --external` is pretty close to what `dvc import` used to be? I believe that's a fine feature, because one aspect of reproducible pipelines is also documenting where that data came from, I case you want to reproduce from scratch (ignore cached files) even the external data collection step.

**Comment by efiop** [comment] 2018-04-10 14:57
Since we plan to start supporting external files as dependencies anyway, I suggest we leave `dvc add` alone and just bring back the `dvc import` as a separate command that downloads and tracks external files. I think it will be much nicer and will reflect the purpose much better than any optional flags could.
So in the end we will have:

- `dvc add path` adds local files to dvc cache
- `dvc import url` works as a "downloader + tracker stage" (so it is the same as `dvc run -d s3://bucket/file -o file aws s3 cp s3://bucket/file`), downloading and tracking external file

As to `dvc repro` flags and enabling/disabling tracking for externals, it is clear to me that our previous `dvc lock` concept applies here very well, because enabling/disabling tracking for external data file is the same as locking/unlocking respective stage. The `lock` concept is more generic and might come in handy for other uses as well. As an alternative to `--check-external` flag, I would propose `--unlock` flag, that will simply ignore if the stage is locked or not, allowing for stages produced with `dvc import` and locked to check their external dependencies. Notice that `--unlock` is not the same as `--force`, so they complement each other.

**Comment by efiop** [comment] 2018-04-10 14:59
> How to localize all the externals in a single file? So, a data scientist can work with a file copy where production branch can have a special external settings which points to production S3 files?

I think we don't need a special separate file. `dvc lock` concept from the previous comment should fit nicely instead.

**Comment by dmpetrov** [comment] 2018-04-13 08:41
It looks like this "external" interface should support two more cases:
1. run a few DVC repo as a single pipeline where an output is connected to another repo input.
2. specify how many CPU\GPU each step should use.
Probably "decorator" is a better name than "external".

**Comment by efiop** [comment] 2018-05-15 12:41
After quite a few of discussions with @dmpetrov , we've decided to release 0.9.7 and then really get to implementing external files support in 0.9.8(including hadoop).

**Comment by efiop** [comment] 2018-06-10 19:37
For the record: partially fixed by https://github.com/iterative/dvc/pull/759 .

**Comment by efiop** [comment] 2018-06-15 15:51
Plus https://github.com/iterative/dvc/pull/780 . Closing.

**Closed by efiop** 2018-06-15 15:51 UTC
Labels: question
