### ISSUE TITLE
DVC import file hashing only runs on one CPU thread

### ISSUE THREAD

**Issue by raimannma** [iterative/dvc#5546] opened 2021-03-04 12:37 UTC
# Bug Report

## Description

I want to import data from one repo into another, but hashing takes forever for me. As ruslan pointed out on [discord](https://discord.com/channels/485586884165107732/563406153334128681/817004690197577748), this is caused due to single thread only hashing on DVC imports.

For me this is a big problem, as pulling data takes more than an hour only for computing the hashes.

### Reproduce

1. Create 2 hosted repos (REPO_1, REPO_2)
2. Add large dataset to REPO_1
3. In REPO_2 `dvc import` the data from REPO_2 

### Expected

I expect the same performance as normal dvc file hashing on all my cpu threads, which should take for my 60k image dataset under 5min

### Environment information

- Ubuntu 20.04
- Self-hosted GitLab
- S3 Remote
- Dataset with ~60k images

**Output of `dvc version`:**

```console
$ dvc version
DVC version: 2.0.1 (pip)
---------------------------------
Platform: Python 3.8.5 on Linux-5.8.0-44-generic-x86_64-with-glibc2.29
Supports: All remotes
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p5
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/nvme0n1p5
Repo: dvc, git
```

**Comment by efiop** [comment] 2021-03-04 12:45
Discord context: https://discord.com/channels/485586884165107732/563406153334128681/817013134782890004

**Comment by BeatWolf** [comment] 2021-03-18 15:21
I'm also affected by this bug, and it sadly doesn't make dvc import useable right now (for datasets with many files)

**Comment by BeatWolf** [comment] 2021-03-31 07:06
Here is the cprofile of a dvc update. I took maybe 24 hours. There is one "issue" with it. It updated 2 folders, but as it took about 10 hours for the first, it asked for authentication again (for the git repository) so it must have been stuck for many hours. I hope that doesn't cause a problem with the profiling.
Here is the profile, i hope it helps! (as this is a huge issue for my use-case with DVC) https://drive.switch.ch/index.php/s/IKN2M5cRCOe3hwf

**Comment by zimka** [comment] 2021-06-03 14:09
Is there any news regarding this issue?
It looks like the speed difference between `dvc pull` and `dvc import` is not caused only by threading problem (in code ThreadPoolExecutor is used in both cases).
I have made some tests, and even on single core machine with --jobs=1 `dvc pull` worked for me several times faster than `dvc import` on `data/cat_dogs' dataset from dvc-bench

**Comment by giaco5988** [comment] 2021-06-04 17:01
Same issue here, when I try to `dvc get` a folder from an external project I get very slow download compared to `dvc pull` the same folder from inside the repository (~50x slower). The folder that I am trying to get containing ~50k files.

**Comment by efiop** [comment] 2021-06-04 21:25
@zimka @giaco5988 Hi guys. Could you please post additional info? E.g. `dvc doctor` output.

**Comment by giaco5988** [comment] 2021-06-04 21:48
below the output from `dvc doctor`. As a workaround, I have tried to compress the dataset and run `dvc get` from outside the repository on the zipped file, in this way the download is as fast again, so it seems that the slow-down comes from having a large number of files?

`DVC version: 2.3.0 (snap)
---------------------------------
Platform: Python 3.6.9 on Linux-5.4.0-74-generic-x86_64-with-Ubuntu-18.04-bionic
Supports: azure, gdrive, gs, http, https, s3, ssh
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p3
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/nvme0n1p3
Repo: dvc, git`

**Comment by zimka** [comment] 2021-06-09 05:20
My dvc doctor:
```
$ dvc doctor
DVC version: 2.1.0 (pip)
---------------------------------
Platform: Python 3.7.6 on Windows-10-10.0.19041-SP0
Supports: http, https
Cache types: hardlink
Cache directory: NTFS on C:\
Caches: local
Remotes: local
Workspace directory: NTFS on C:\
Repo: dvc, git
```
I have reproduced the issue on Ubuntu and fedora on other 2.0+ dvc versions too.

**Comment by efiop** [comment] 2021-06-16 18:44
For the record: same as in https://github.com/iterative/dvc/issues/6019, pre-requisites for this are: #6109 and the following save()/transfer() unification. We'll double-check this issue after those changes are merged, will likely be fixed automatically though.

**Comment by efiop** [comment] 2021-07-09 22:38
Quick update: @pmrowla has been working hard :muscle: :hammer_and_wrench: on a bunch of PRs that make `import` use the same logic as `pull` right now in multiple places and on 2.5.4 I get ~7m for both pull and import (`dvc import https://github.com/iterative/dvc-bench data/cats_dogs`) on my machine. These are very early results as we are not done there yet and the aforementioned logic doesn't yet work for any non-dvc-tracked files (e.g. if you have any git-tracked file in the batch) @pmrowla is now working hard on unifying `save/transfer` and after that, we'll take a closer look at this issue again. Please feel free to give 2.5.4 a shot and let us know how it goes.

**Comment by giaco5988** [comment] 2021-07-12 10:01
@efiop `dvc import` from dvc 2.5.4 now is fast, while using `dvc get` from outside a dvc-tracked repository is still slow (~50x slower) when downloading many files (~40k files).

**Comment by efiop** [comment] 2021-07-12 10:34
@giaco5988 Thanks for the feedback! Yes, we will get to `dvc get` soon as well. Sorry for inconvenience and stay tuned :)

**Comment by pmrowla** [comment] 2021-07-13 03:35
@giaco5988 please follow #6019 for updates on `dvc get`. Since the `get` and `import` performance issues aren't entirely caused by the same things, it'll be cleaner to keep the discussions in separate tickets

**Comment by efiop** [comment] 2021-08-09 21:43
Fixed by https://github.com/iterative/dvc/pull/6360 . Thanks @pmrowla ! :pray:

For the record: we have a fix for `get` ready as well, see linked PR in https://github.com/iterative/dvc/issues/6019

**Closed by efiop** 2021-08-09 21:43 UTC
Labels: p1-important, performance, optimize
