### ISSUE TITLE
Speed up dvc status for large projects

### ISSUE THREAD

**Issue by Ykid** [iterative/dvc#3280] opened 2020-02-04 11:57 UTC
**Please provide information about your setup**
DVC version(i.e. `dvc --version`), Platform and method of installation (pip, homebrew, pkg Mac, exe (Windows), DEB(Linux), RPM(Linux))

```
dvc version

DVC version: 0.82.8
Python version: 3.7.6
Platform: Linux-5.0.0-37-generic-x86_64-with-debian-buster-sid
Binary: False
Package: pip
Cache: reflink - not supported, hardlink - not supported, symlink - supported
Filesystem type (cache directory): ('ext4', '/dev/sda1')
Filesystem type (workspace): ('ext4', '/dev/nvme0n1p2')
```

expect `dvc status` can return in a shorter time, currently it takes 30s.

a few stats
```
du -shL my-project # 107G
```

```
dvc status -v
```
[log.txt](https://github.com/iterative/dvc/files/4153107/log.txt)

**Comment by pared** [comment] 2020-02-04 12:19
I think we should try to reproduce such big repo and see what takes so much time, I suspect db access.

**Comment by shcheklein** [comment] 2020-02-04 15:34
@pared @Ykid could we run it with a profiler please:

`python -m cProfile -o status.prof -m dvc status -v`

**Comment by Suor** [comment] 2020-02-04 15:57
Reading through discord dialog and looking at the log I don't think this is about big repo. This is probably about many imported files, which create many clones on `dvc status`.

**Comment by Ykid** [comment] 2020-02-05 00:58
@Suor `grep --include=\*.{dvc,} -rn my-data-dir -e ".git" | wc -l` gives me 64. I think more or less like that. I have a dvc data registry and import some directories and files from there into the project. So it seems better if I do `dvc get` followed by `dvc add` ? those imported files is not going to be updated very frequently.

num of  files versioned by dvc is around 9k from `find -L . -type f ! -name "*.dvc" | wc -l`. dvc pull shows 8.31k ( the number changes in each line of dvc pull though, but 8.31k is the most time consuming one )

may I know if there's any way to improve it ?

**Comment by Suor** [comment] 2020-02-05 11:25
> So does it sound better if I do dvc get followed by dvc add

This is obviously an issue on our end. I will think how this may be sped up.

**Comment by Suor** [comment] 2020-02-05 11:38
@Ykid Can you say how many different sources do you use in those 64 import stages? Source is a pair of `(url, rev)` in `deps.repo`.

**Comment by Ykid** [comment] 2020-02-06 01:35
@Suor There is one url as it is our data registry. I follow `data registries` to set it up. For the number of pairs, here it is:

* 60: (repo, revA)
* 4: (repo, revB)

**Comment by Suor** [comment] 2020-02-06 13:00
@Ykid thanks.

**Comment by Suor** [comment] 2020-02-06 13:15
A note from discord - git repo is big, both history and checked out things:
```
84K ./tools
1.8M  ./.dvc
988M  ./notebooks
20K ./my-project.egg-info
16K ./configs
870M  ./.git
16M ./my-project
92K ./dockerfiles
28K ./tests
6.3M  ./data
24K ./pipeline
1.9G  .
```
The last change only caches single instance of repo, not all of them, which prevents us from needing new `git clone`, but makes a copy of the whole repo sans dvc cache each time. The reason for that is we do `git pull` each time, i.e. modifying the directory, which means caching cannot be used for it. Things are furthermore complicated by summon publishing stuff, which modifies the directory returned by `external_repo()`, which also requires a separate copy.

I am trying to untangle it now.

**Comment by Ykid** [comment] 2020-02-07 06:32
> The last change only caches single instance of repo, not all of them
May I know what this means ?

**Comment by Suor** [comment] 2020-02-11 06:30
> May I know what this means ?

Sorry for slow response.

This means that when you have many imports from the same repo `dvc` will make a fresh copy of its clone many times, while clone is only done once. This is not the issue generally, but since you have huge git repo - all those notebooks doesn't really play nice - it takes time.

Anyway, this should be fixed after https://github.com/iterative/dvc/pull/3286 lands. You can try it right now with:
```bash
pip install git+https://github.com/Suor/dvc.git@erepo-ro
```
If you do, can you please tell how well does it work for you?

**Comment by Ykid** [comment] 2020-02-13 04:10
DVC version: 0.82.9+f73900
Python version: 3.7.4
Platform: Linux-5.0.0-37-generic-x86_64-with-debian-buster-sid
Binary: False
Package: None
Cache: reflink - not supported, hardlink - not supported, symlink - supported

ERROR: failed to obtain data status - 'Git' object has no attribute 'is_known'

**Comment by efiop** [comment] 2020-02-13 04:17
Reopening and escalating the priority. @Suor Please take a look ASAP, we need to release a new version with the fix ASAP as well.

**Comment by casperdcl** [comment] 2020-02-13 12:40
Looks like `is_known` should've been `is_tracked`. Surely we should have some sort of test which should've found thia bug

**Comment by Suor** [comment] 2020-02-14 07:12
Handled in https://github.com/iterative/dvc/pull/3323.

**Comment by efiop** [comment] 2020-02-15 01:12
@Ykid 0.85.0 is out on pip and conda, please upgrade, give it a try and let us know if it fixed the issue for you. Thanks for the feedback! :slightly_smiling_face:

**Comment by Ykid** [comment] 2020-02-15 10:42
The bug related to git is fixed, but there seem to be not much performance improved. :(. 

```
DVC version: 0.85.0
Python version: 3.7.6
Platform: Linux-5.0.0-37-generic-x86_64-with-debian-buster-sid
Binary: False
Package: pip
Cache: reflink - not supported, hardlink - not supported, symlink - supported
Filesystem type (cache directory): ('ext4', '/dev/sda1')
Filesystem type (workspace): ('ext4', '/dev/nvme0n1p2')
```

```
time dvc status

real	0m30.635s
user	0m21.884s
sys	0m6.815s
```

**Comment by efiop** [comment] 2020-02-15 17:50
@Suor Please take a look.

**Comment by Suor** [comment] 2020-02-25 14:07
So the optimization works for me, no unneeded clones or copies done. `git checkout` takes significantly more time than expected though. Need to investigate @Ykid situation more before jumping on some advanced optimizations.

**Comment by Suor** [comment] 2020-02-25 14:12
@Ykid I made a branch, which has more erepo logging, can you try it to see what is actually happening on your side and how much time that takes?

```bash
pip install git+https://github.com/Suor/dvc.git@erepo-log
dvc status -v
# And paste output here
```

**Comment by efiop** [comment] 2020-03-10 13:35
Closing due to inactivity.

**Closed by efiop** 2020-03-10 13:35 UTC
Labels: awaiting response, bug, p1-important, performance, research
