### ISSUE TITLE
get: opened temp files are not removed upon an error

### ISSUE THREAD

**Issue by pmrowla** [iterative/dvc#6063] opened 2021-05-26 07:16 UTC
Can be reproduced by running `dvc get` with any invalid path

```
$ dvc get https://github.com/iterative/example-get-started.git foo -o bar
ERROR: unexpected error - : Unable to find DVC file with output '../../../../../private/var/folders/s_/j8cg24s945dcvlh77c677f080000gn/T/tmpsc4xz292dvc-clone/foo'

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!

$ ls -l
total 0
-rw-r--r-- 1 pmrowla staff 0 May 26 16:12 bar.6SdQVkeDFFTUuNcSes23u7.tmp

$ dvc doctor
DVC version: 2.1.0 (brew)
---------------------------------
Platform: Python 3.9.5 on macOS-11.4-x86_64-i386-64bit
Supports: azure, gdrive, gs, http, https, s3, ssh, oss, webdav, webdavs
```

discord context: https://discord.com/channels/485586884165107732/485596304961962003/847005225164341288

**Comment by skshetry** [comment] 2021-05-26 07:31
Duplicate of https://github.com/iterative/dvc/issues/5355

**Closed by skshetry** 2021-05-26 07:31 UTC
Labels: :bug: bug, p1-important
