### ISSUE TITLE
DVC "Collecting information from remote cache..." even for unchanged remotes with local cache

### ISSUE THREAD

**Issue by JohanMollevik** [iterative/dvc#2408] opened 2019-08-19 10:27 UTC
dvc --version
0.55.0
installed via pip on debian

I have a dvc repo with a few datasets

* On system A I have everything in local cache
* On system B I create a new dataset, checks the dvc file into git and pushes that to Azure
* On system A I checkout from git and run dvc status showing that I have a new small dataset not in cache
* On system A I run dvc pull without any parameters

This last run of dvc pull collects information about all the datasets in the remote and takes 2 hours even when dvc status detected that they had not changed

Is this intended behaviour or a bug?
This is potentially a duplicate of https://github.com/iterative/dvc/issues/1839 but I am not certain

**Comment by efiop** [comment] 2019-08-19 13:18
Hi @JohanMollevik !

How small is that `small dataset` in terms of files and their sizes?

**Comment by JohanMollevik** [comment] 2019-08-19 13:38
The small dataset is two files, one empty and one with 1 byte of content

**Comment by JohanMollevik** [comment] 2019-08-19 13:39
I also have a large dataset that is unchanged of 100000 files and 120GB

**Comment by efiop** [comment] 2019-08-19 15:19
@JohanMollevik So you have small.dvc and big.dvc, right? And `dvc pull`(no arguments) is slow on A. In that case, it is caused by dvc collecting info for big.dvc, which is known to be not fast (we are actively working on figuring out the best solution for it in https://github.com/iterative/dvc/issues/2147). But `dvc pull small.dvc` should be much-much faster, because passing the dvc file narrows it down for the dvc, so it doesn't have to check all the other dvc files too.

**Comment by JohanMollevik** [comment] 2019-08-20 07:32
Yes exactly, as far as I can see it should not need to check big.dvc as it knows it to be unmodified according to dvc status but if that is discussed in #2147 then this might be a duplicate.

**Comment by efiop** [comment] 2019-08-20 11:55
@JohanMollevik `dvc status` and `dvc status -c` are different beasts. First one has a few tricks to make the check fast, but the second one doesnt and has to manually verify local <-> correspondence. We will indeed introduce more tricks for it in #2147 . For now, please use more granular `dvc pull small.dvc` in such cases. Agreed, I'll close this issue in favour of #2147 . Thank you for the feedback! :slightly_smiling_face:

**Closed by efiop** 2019-08-20 11:55 UTC
