### ISSUE TITLE
plot axis labels displaying "<DVC_METRIC_X_TITLE>"

### ISSUE THREAD

**Issue by andronovhopf** [iterative/dvc#3997] opened 2020-06-09 19:49 UTC
I'm using pre-release v. 1.0.0a10+568333. When I run

`dvc plots show estimators.csv` or `dvc plots diff --target estimators.csv`, I'm getting the axis labels from the vega-lite template, not my *.csv file. Even if I use the `-x` and `'-y` flags, nothing happens. This didn't happen previously; did we change the flag to assign axis titles? 

![visualization (1)](https://user-images.githubusercontent.com/29716724/84192799-5c8b6900-aa4f-11ea-9d7e-3e152d068289.png)

**Comment by efiop** [comment] 2020-06-09 21:05
Related https://github.com/iterative/dvc/issues/3968. 

@andronovhopf Could you show your template, please? Have you adjusted it or is it the stock one?

**Comment by andronovhopf** [comment] 2020-06-09 21:05
It's the stock template!

**Comment by efiop** [comment] 2020-06-09 21:06
@andronovhopf Could you delete `.dvc/plots` and run your command again, please?

**Comment by andronovhopf** [comment] 2020-06-09 21:08
Yeah that worked, now my plots are looking as expected
![visualization (3)](https://user-images.githubusercontent.com/29716724/84199866-b6ddf700-aa5a-11ea-84be-35529e8189e9.png)

**Comment by efiop** [comment] 2020-06-09 21:18
@andronovhopf Nice! Ok, looks like we've changed the template(or template related logic, can't put my finger on anything specific yet) at some point during the pre-release, so you had old templates from that time that don't really work with the new dvc version. Do you remember when you've generated those `.dvc/plots` ? If it is in one of the private projects, please let me know, I'll double-check it myself to make sure there is nothing seriously bad going on.

**Comment by efiop** [comment] 2020-06-09 21:18
@andronovhopf Btw, the plots you've shared differ a bit, is that expected?

**Comment by andronovhopf** [comment] 2020-06-09 21:19
So the project is in this public repo: it was working last week, so we can
check how the .dvc/plots changed
https://github.com/andronovhopf/prettypretty

**Comment by efiop** [comment] 2020-06-09 21:26
@andronovhopf Yep, we've changed the anchors since then https://github.com/andronovhopf/prettypretty/commit/e231b37ce93e43154a201da6d97b964f6dfb6ab2#diff-b70c67e8b4c164d2c005e4dcd35b4552 

![Screenshot from 2020-06-10 00-24-23](https://user-images.githubusercontent.com/5367102/84201784-c0924980-aab0-11ea-8f61-2e9d55effc3f.png)

So nothing too serious here, it was caused by #3948 . No action required here, I don't think.

**Comment by andronovhopf** [comment] 2020-06-09 21:26
haha was just commenting to send you that exact screenshot. looks good!

**Comment by efiop** [comment] 2020-06-09 21:27
Looks like it is resolved. Closing.

**Closed by efiop** 2020-06-09 21:27 UTC
Labels: p0-critical, research
