### ISSUE TITLE
dvc gc: leaves empty folders, which should also be cleaned out

### ISSUE THREAD

**Issue by roytseng-tw** [iterative/dvc#6590] opened 2021-09-10 10:49 UTC
# Bug Report

## Description

I ran `dvc gc -A`  to clean any cache that is not committed. The cache **files** are indeed removed. However, the original enclosing folders are left untouched.

### Expected

Those folders should also be deleted.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.5.4
---------------------------------
Platform: Python 3.7.10 on Linux-4.4.0-210-generic-x86_64-with-debian-stretch-sid
Supports:
        http (requests = 2.25.1),
        https (requests = 2.25.1),
        ssh (paramiko = 2.7.2),
```

**Additional Information (if any):**

**Comment by efiop** [comment] 2021-09-10 10:57
Closing as a duplicate of https://github.com/iterative/dvc/issues/3375

**Closed by efiop** 2021-09-10 10:57 UTC
Labels: enhancement

**Comment by dberenbaum** [comment] 2021-09-10 19:00
@roytseng-tw Does this cause problems for you? I don't think we have considered this issue a high priority at least partly because the leftover files are likely relatively small.
