### ISSUE TITLE
checkout: fails if stage output changed from file to directory

### ISSUE THREAD

**Issue by ahasha** [iterative/dvc#9534] opened 2023-06-02 15:44 UTC
# Bug Report

## Description

I changed stage outputs in my pipeline from a single large parquet file to partitioned parquet files (which are directories with multiple parquet files inside) for scalability reasons.  When I switch between an old tag where the stage output was a file to the more recent tag where it's a directory, dvc checkout fails with the following error: `ERROR: unexpected error - [Errno 17] File exists: '<filename that is now a directory>'`

### Reproduce

Minimal steps to reproduce:

1. git clone git@github.com:ahasha/dvc-issue-9534.git
2. dvc repro
3. git checkout file_out
4. dvc repro
5. git checkout dir_out
6. dvc checkout

You should see:
```
ERROR: unexpected error - [Errno 17] File exists: '/Users/alexhasha/repos/dvc-issue-9534/data/foo.txt'     
```

### Expected

Expect that dvc checkout can handle this case by removing the tracked file from the workspace and replacing it with the tracked directory.

### Environment information

I will update this shortly.

**Output of `dvc doctor`:**

```
DVC version: 2.58.2 (pip)
-------------------------
Platform: Python 3.9.12 on macOS-13.1-x86_64-i386-64bit
Subprojects:
	dvc_data = 0.51.0
	dvc_objects = 0.22.0
	dvc_render = 0.5.3
	dvc_task = 0.2.1
	scmrepo = 1.0.3
Supports:
	http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3)
Config:
	Global: /Users/alexhasha/Library/Application Support/dvc
	System: /Library/Application Support/dvc
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s3s1
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk1s3s1
Repo: dvc, git
Repo.site_cache_dir: /Library/Caches/dvc/repo/7bffdf7c3095ddbca681da3d048a61ba
```

**Comment by daavoo** [comment] 2023-06-06 08:32
Thanks for the detailed reproduction @ahasha , I am taking a look

**Comment by efiop** [comment] 2023-06-23 23:42
Fixed by https://github.com/iterative/dvc/pull/9444

@ahasha Please give latest dvc a try and let us know if you still see this error or not. I was able to confirm that your example works for me (btw, thanks a lot for a reproducible example 🙏 ).

**Closed by efiop** 2023-06-23 23:42 UTC
Labels: bug, A: data-management

**Comment by ahasha** [comment] 2023-06-28 18:24
Thanks for the quick turnaround!  I can confirm it's working for my simple example.  You're the best!

DVC Doctor output
```
DVC version: 3.2.2 (pip)
------------------------
Platform: Python 3.11.4 on macOS-13.1-x86_64-i386-64bit
Subprojects:
	dvc_data = 2.3.1
	dvc_objects = 0.23.0
	dvc_render = 0.5.3
	dvc_task = 0.3.0
	scmrepo = 1.0.4
Supports:
	http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3)
Config:
	Global: /Users/alexhasha/Library/Application Support/dvc
	System: /Library/Application Support/dvc
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: None
Workspace directory: apfs on /dev/disk1s3s1
Repo: dvc, git
Repo.site_cache_dir: /Library/Caches/dvc/repo/7bffdf7c3095ddbca681da3d048a61ba
```

```
% git checkout 0981069948953f83
% dvc checkout
% ls -ltrh data/foo.txt
-rw-r--r--  1 alexhasha  staff    16B Jun  2 11:56 data/foo.txt
% git checkout b053003a2f
% dvc checkout
M       data/foo.txt/
% ls -ltrh data/foo.txt
total 16
-rw-r--r--  1 alexhasha  staff    16B Jun  2 11:56 chunk1.txt
-rw-r--r--  1 alexhasha  staff    13B Jun  2 11:56 chunk2.txt
```
