### ISSUE TITLE
[Question] Can I recover previous version of a data file that was already reproduced?

### ISSUE THREAD

**Issue by andrethrill** [iterative/dvc#881] opened 2018-07-12 16:39 UTC
Here's a sequence of commands I executed:

```shell
# dvc --version
dvc 0.11.0+c63658
# mkdir test_repo
# cd test_repo/
# git init
Initialized empty Git repository in /workspace/schedulers/andre/test_repo/.git/
# dvc init
# echo aeiou > file.txt
# dvc add file.txt
# git status                                         #here the content of file.txt is "aeiou"
On branch master

Initial commit

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

        new file:   .dvc/.gitignore
        new file:   .dvc/config

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        .gitignore
        file.txt.dvc

# git add .dvc/.gitignore
# git add .dvc/config
# git add .gitignore
# git add file.txt.dvc
# git commit -m "firt commit"
# echo aaeiou > file.txt
# less file.txt
# dvc status
file.txt.dvc
        outs
                changed:  file.txt
# dvc repro file.txt.dvc
Reproducing 'file.txt.dvc'
Verifying data sources in 'file.txt.dvc'.               #here the content of file.txt is "aaeiou"

# git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   file.txt.dvc

no changes added to commit (use "git add" and/or "git commit -a")

# git checkout file.txt.dvc
# dvc checkout
Corrupted cache file .dvc/cache/67/6d4898a0811e140ee237952d860def
Cache '676d4898a0811e140ee237952d860def' not found. File 'file.txt' won't be created.
```

Shouldn't I be able to, somehow, recover the original file with the content "aeiou"?

**Comment by efiop** [comment] 2018-07-12 20:08
Hi @andrethrill !

The problem here is that in this case dvc uses hardlink to link your data to your cache, which leaves it exposed to such corruption(and automatic deletion by dvc) when you try to modify the file in place. What you should do here is remove the file (either yourself or with `dvc remove file.txt.dvc`) before you run `# echo aaeiou > file.txt`, so that original cache file is not linked to the file.txt and not being corrupted. After that, you should have both cache versions.

Thanks,
Ruslan

**Comment by efiop** [comment] 2018-07-12 20:18
This is effectively a tradeoff that we had to make to have fast links for big files on systems where there is no reflink support. Reflink and `copy` link types are not affected by such issues, because both of them effectively copy your data from cache to the workspace, so there is no direct writable link between them. We will also soon introduce ro-hardlink, that will also make cache read only, so you can't accidentally write over it, similar to what `git annex` does.

**Comment by efiop** [comment] 2018-07-13 09:38
Hi @andrethrill !

> If I then edit file1_v2.txt directly I guess I'm corrupting the cache right?
> But, in this case, I would be able to recover it by doing dvc repro -f, am I correct?

You don't need to specify `-f`, because dvc will detect broken output of script1.py, will mark that stage as `changed` and automatically reproduce it when you run `dvc repro` for that pipeline. Other than that small caveat, you are absolutely right.

Thanks,
Ruslan

**Comment by andrethrill** [comment] 2018-07-13 09:55
Thank you once again @efiop 

What about my last question (that I guess you missed because it was an edit I did):
> Assuming yes, would the corrupted file still be kept in cache on the side or would it be overwritten?

---

Sorry for insisting but I was thinking further and now my head is spinning eheh
Consider the following scenario:

The same DAG as before: `file1_v1.txt --> [script1.py] --> file1_v2.txt --> [script2.py] --> file1_v3.txt`.
After this there are 3 files in cache, when for each original `.txt`. Assume here I `git commit -m "commit1"`

Now I want to improve, let's say, script2.py and I start experimenting with it. While I'm experimenting (without git commiting or DVC reproing), each run writes to `file1_v3.txt` and thus to the cache.

Once I reach a stable state that I feel confortable with, I will `dvc repro file1_v3.txt.dvc`. At this point, I guess, a new cache file for `file1_v3.txt` is created. So there will be two cache files for this `file1_v3.txt`: the first one which is now corrupted and the new one which is coherent with the current state.

Now I `git commit -m "commit2"`

Now there is no way to checkout to `commit1` and get into a coherent state without rerunning `script2.py` because the cache is corrupted, right?


I'm just thinking in cases where the scripts take a long time to run and I want to avoid running them as much as possible.

---

Is the scenario above correct?
Maybe the way I describe above is not the best way to include DVC in my workflow, any input would be much appreciated.

Thanks is advance,
André

**Comment by efiop** [comment] 2018-07-13 11:08
> What about my last question (that I guess you missed because it was an edit I did):
>> Assuming yes, would the corrupted file still be kept in cache on the side or would it be overwritten?

Oops, sorry, totally missed it. In that particular scenario from your second to last comment, corrupted cache will be deleted and a new one created.

Now to the last scenario:

> Now there is no way to checkout to commit1 and get into a coherent state without rerunning script2.py because the cache is corrupted, right?

Right, that corrupted cache will be detected as one that is corrupt and will be removed. One way to work around it is to push your cache to the cloud after commit1, so you could later `dvc pull` to replace corrupted cache.

Another way to workaround it would be to run `dvc remove `file_v3.txt.dvc` that will remove your `file_v3.txt` unlinking it from cache and then safely experiment with your `script_2.py`.

If you need your original `file_v3.txt`(maybe to append to it while working on your `script_2.py`) you could first copy it to `file_v3.txt.backup`, remove `file_v3.txt`(e.g. with `dvc remove file_v3.txt.dvc`) and then move `file_v3.txt.backup` to `file_v3.txt` thus making it unlinked from the cache, preventing cache corruption.

Yet another way, if you don't care about having an overhead of one copy for each data file in your current branch, you could use `copy` cache type(`dvc config cache.type copy`) to avoid such problems altogether. And if you do indeed care about the overhead but really don't want the hustle of looking after your files, you could consider moving your project and your cache to XFS or Btrfs partition(i suppose you are running Linux) that support `reflinks`, so you'll get both the convenience and safety of `copy` with the performance of `hardlinks`.

**Comment by andrethrill** [comment] 2018-07-13 12:20
Thanks @efiop .

Your explanation was very insightful. I believe we can close this issue now if you want :)

**Comment by efiop** [comment] 2018-07-13 23:31
@andrethrill Thank you so much for the feedback! Closing for now, feel free to reopen. :)

**Closed by efiop** 2018-07-13 23:31 UTC
