### ISSUE TITLE
push: name of remote does not have trailing spaces removed from name

### ISSUE THREAD

**Issue by michael-mayo** [iterative/dvc#7410] opened 2022-02-21 22:12 UTC
# Bug Report

## Issue name

push: name of remote does not have trailing spaces removed from name

## Description

After setting up a new repository with an external cache, issuing a push to the remote repository fails if there is a trailing space after the name of the remote repository. While the extra space is detected, it might be more user friendly to automatically trim trailing spaces from the command.

### Reproduce

created dvc_sample_dir directory, cd into it
```console
$ git init
$ dvc init
$ dvc remote add s3cache s3://path_to_my_buckets/sample_dvc_bucket/cache/
$ mkdir dataset
```
add four directories of sample images to the folder
```console
$ echo dataset/ > .gitignore
$ dvc add dataset
$ dvc push -r s3cache
ERROR: failed to push data to the cloud - config file error: remote 's3cache ' doesn't exist --> error caused by space after name
$ dvc push -r s3cache
18 files pushed
```

Output of DVC doctor:
```
$ dvc doctor
DVC version: 2.9.5 (pip)
---------------------------------
Platform: Python 3.9.7 on macOS-12.2.1-arm64-arm-64bit
Supports:
	webhdfs (fsspec = 2022.1.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	s3 (s3fs = 2022.1.0, boto3 = 1.20.24)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: s3
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
```

Shell:
```
echo $SHELL
/bin/zsh
```

### Expected

Spaces should be trimmed from the cache name when a dvc push is performed via the command line.

**Comment by pmrowla** [comment] 2022-02-22 05:49
I'm not able to reproduce this. Could you please run `dvc doctor` and post the output here, and also note what shell you are using (bash/zsh/fish/etc)

**Comment by michael-mayo** [comment] 2022-02-22 06:57
Issue updated with the output of DVC doctor... shell is zsh

**Comment by pmrowla** [comment] 2022-02-22 07:51
I'm still unable to reproduce this issue, DVC (via argparse) expects this whitespace stripping to happen in your shell. It seems like this might be something specific to your shell/env setup?

With on macos, `$ dvc push -r local  ` still works as expected for me with this DVC config (`local` with no trailing spaces is what gets passed into `sys.argv`)
```
['remote "local"']
    url = ../../remote
```

I tested this with my regular zsh setup and with `/bin/zsh -d -f -i` (to force running zsh without my own zshrc configuration)

**Comment by michael-mayo** [comment] 2022-02-22 08:04
The error does not occur in a new project with the same environment, so I will look into it some more and provide more info if I can reproduce it. Thanks.

**Comment by pmrowla** [comment] 2022-02-22 08:12
Closing this issue for now then, feel free to reopen it if you run into the problem again in the future.

**Closed by pmrowla** 2022-02-22 08:12 UTC
Labels: awaiting response
