### ISSUE TITLE
dvc get: git auth with deploy token raises "HTTP Git authentication is not supported: 'origin'"

### ISSUE THREAD

**Issue by tyomj** [iterative/dvc#7689] opened 2022-05-03 15:45 UTC
# Bug Report

## Description
`dvc get` with a provided URL that contains deploy token fails with 
```HTTP Git authentication is not supported: 'origin' ```  
since 2.10.2.
It happens after [the recent update](https://github.com/iterative/dvc/commit/69acbe33c9b9e863b88b1e7a85f81bb7cbc896ec#diff-e69f69ddbf5d27ac0a490756f4e150e6ba146a7b74125bf7481167ac747c4422R109-R110) in `clone` function which finally resulted in the error [here](https://github.com/iterative/dvc/commit/69acbe33c9b9e863b88b1e7a85f81bb7cbc896ec#diff-9ebf228ef7c1669c0a8ff8387d963aca9f2c7800c0ca9628d89ca44fc1e21434R198).
One possible way to tackle the problem I was thinking of is to prevent usage of `fetch_all_exps` for remotes with HTTP, but I'm not sure if it's good hack tbh.

### Reproduce
```
dvc get https://gitlab+deploy-token:password@gitlab.com/group/repo.git some_file.txt
```

### Expected

`some_file.txt` is successful downloaded from the specified remote repo.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor

DVC version: 2.10.2 (pip)
---------------------------------
Platform: Python 3.8.8 on Linux-5.13.0-39-generic-x86_64-with-glibc2.10
Supports:
        hdfs (fsspec = 2022.3.0, pyarrow = 6.0.1),
        webhdfs (fsspec = 2022.3.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2022.3.0, boto3 = 1.21.21)
```

**Additional Information (if any):**

**Comment by pmrowla** [comment] 2022-05-04 02:51
Closing as duplicate of https://github.com/iterative/dvc/issues/7670

**Closed by pmrowla** 2022-05-04 02:51 UTC
