### ISSUE TITLE
`pull`: fails unless target specified

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#9786] opened 2023-08-01 16:57 UTC
# Bug Report

## Description

`dvc pull` fails but `dvc pull target` succeeds for the same file.

Reported multiple times in discord:

https://discord.com/channels/485586884165107732/563406153334128681/1131979446379888853
https://discord.com/channels/485586884165107732/485596304961962003/1135912803086119043

### Reproduce

Reproduction script:

```bash
rm -rf /Library/Caches/dvc/repo/63a86d1aa938a14ed3f3014e34dbe38a
rm -rf example-get-started-http-private-fixture
git clone git@github.com:iterative/example-get-started-http-private-fixture.git
cd example-get-started-http-private-fixture
dvc pull
dvc remote modify private-http auth basic
dvc remote modify private-http user user1
dvc remote modify private-http password password1
dvc pull
dvc pull data/features
```

The 1st and 2nd pull both fail to pull `data/features`, but the final `dvc pull data/features` succeeds.

### Expected

The 2nd `dvc pull` (after the remote config has been fixed) should succeed.

**Comment by daavoo** [comment] 2023-08-02 14:18
Taking a look

**Comment by daavoo** [comment] 2023-08-03 08:08
The issue is the same as https://github.com/iterative/dvc/issues/9785 

The only thing that makes the last `dvc pull {target}` work is that it bypasses the cache corruption because the corrupted index was generated with a different target ( In this case, the repo root: `dvc pull` no target).

The point can be proved by doing the opposite flow: corrupting `dvc pull {target}` and then running it with a different o no `{target}` :

```console
$ rm -rf /Library/Caches/dvc/repo/63a86d1aa938a14ed3f3014e34dbe38a
$ rm -rf example-get-started-http-private-fixture
$ git clone git@github.com:iterative/example-get-started-http-private-fixture.git
$ cd example-get-started-http-private-fixture
$ dvc pull data/features
A       data/features/
1 file added
```

The above "success" by creating an empty directory and corrupts the cache for `data/features` target, so now, the following fails:

```console
$ dvc remote modify private-http auth basic
$ dvc remote modify private-http user user1
$ dvc remote modify private-http password password1
$ dvc pull data/features
1 file fetched
ERROR: failed to pull data from the cloud - Checkout failed for following targets:
data/features
Is your cache up to date?
<https://error.dvc.org/missing-files>
```

But now, you can actually run `dvc pull` (no targets) and it will succeed:

```console
$ dvc pull
A       model.pkl
A       data/features/
A       data/data.xml
A       data/prepared/
A       eval/prc/
A       eval/importance.png
A       eval/live/metrics.json
A       eval/live/plots/
8 files added and 17 files fetched
```

**Comment by dberenbaum** [comment] 2023-08-03 11:55
@daavoo Assigning to you to check that the scenario works as expected once @efiop pushes any fixes (and to work with @efiop on the fix if you have ideas or can help in any way).

**Comment by daavoo** [comment] 2023-08-04 07:51
> @daavoo Assigning to you to check that the scenario works as expected once @efiop pushes any fixes (and to work with @efiop on the fix if you have ideas or can help in any way).

This is fixed on `main`

**Closed by daavoo** 2023-08-04 07:51 UTC
Labels: bug, p0-critical, A: data-sync
