### ISSUE TITLE
Use directory as output for dvc run when using hdfs as target

### ISSUE THREAD

**Issue by amjadsaadeh** [iterative/dvc#1275] opened 2018-10-30 13:56 UTC
Hello,

I would like to track directories on hdfs for my pipeline. E.g. I run:

`dvc run -d ./images -o hdfs://<hostname>:<port>/image_data hdfs dfs -put ./images /image_data`

but currently this fails because hadoop cli cannot calculate the checksum of a directory.

**Comment by efiop** [comment] 2018-11-24 09:16
Duplicate of https://github.com/iterative/dvc/issues/1083 .

**Comment by mroutis** [comment] 2019-02-04 23:06
@efiop, why did you reopened the issue? Was it a mistake?

**Comment by efiop** [comment] 2019-02-22 14:37
Moving to https://github.com/iterative/dvc/issues/1654

**Closed by efiop** 2019-02-22 14:37 UTC
