### ISSUE TITLE
dvc init in MatrixDS environment

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#1823] opened 2019-04-03 05:55 UTC
`dvc init` got stuck in MatrixDS environment:

![image](https://user-images.githubusercontent.com/10081867/55455829-0349bf00-559a-11e9-9149-863d2862c889.png)

One of guesses - it is related to NFS:
![image](https://user-images.githubusercontent.com/10081867/55455804-e7deb400-5599-11e9-8cab-66cd8e073344.png)

That's all I know for today :(
@FavioVazquez might have more details.

**Comment by FavioVazquez** [comment] 2019-04-03 06:06
Thanks @dmpetrov. Tagging @isaacfab here too

**Comment by isaacfab** [comment] 2019-04-03 06:25
That's a good guess about issues related to the NFS. We have had to tweak the user privileges for many of the containers.

**Comment by efiop** [comment] 2019-04-03 08:49
Hi @isaacfab ! For how long did you leave it running?

**Comment by FavioVazquez** [comment] 2019-04-03 15:27
It ran for a long time, but nothing happened. I couldn't even use Ctrl+C @efiop

**Comment by efiop** [comment] 2019-04-03 15:44
@FavioVazquez Right, if you were not able to CTRL+C, then the program was still in kernel space, meaning that it is probably an NFS issue. Is it still running? If not, mind running it again and then:

1) find it's PID with something like `ps xaf | grep dvc`;
2) show us `cat /proc/$PID/stack`;

Thanks,
Ruslan

**Comment by shcheklein** [comment] 2019-04-05 08:05
@efiop :

```
matrix@tool-5ca6d6e08f48fd83c6cc6069-mcn6f:/home/test$  cat /proc/248/stack
cat: /proc/248/stack: Operation not permitted
```

trace is disabled in docker by default.

@isaacfab is there a way to run one of your docker images with NFS with SYS_PTRACE enabled? We need to see the stack trace at least to understand what's happening. Otherwise it's extremely hard to debug this. 

I also've tried to run NFS on my machine (server and client), dvc worked fine.

**Comment by efiop** [comment] 2019-04-05 12:22
@shcheklein Is that docker image running on linux host?

**Comment by shcheklein** [comment] 2019-04-05 17:09
@efiop most likely, yes. @isaacfab do you have more details?

**Comment by isaacfab** [comment] 2019-04-05 17:34
The container is running on GCP GKE so yes. All of our containers (with docker files) can be found here. https://github.com/matrixds/tools

**Comment by isaacfab** [comment] 2019-04-05 17:37
You can use custom containers on the site (see the repo for instructions). Feel free to enable whatever variables you think would be useful. Have you checked the logs on the environments from the webui? 

![Screenshot 2019-04-05 10 36 36](https://user-images.githubusercontent.com/10081334/55645941-bda21780-578e-11e9-9e55-6282cad7e779.png)

**Comment by shcheklein** [comment] 2019-04-05 17:46
@isaacfab I've checked them, don't see anything interesting.

Re custom tool - I'm not sure I understand which field should I be using to pass `docker run` arguments. Is there any documentation how those options translate to CLI and how could I adjust for the `docker run`?

**Comment by shcheklein** [comment] 2019-04-05 17:47
@isaacfab to be more specific, we need something like `docker run --cap-add SYS_PTRACE ...`

**Comment by isaacfab** [comment] 2019-04-05 18:09
in the UI for the custom tool, you can add a specific docker run command. here is an example.
![Screenshot 2019-04-05 11 08 02](https://user-images.githubusercontent.com/10081334/55647701-2d1a0600-5793-11e9-94f6-c594c2b9fd94.png)

**Comment by isaacfab** [comment] 2019-04-05 18:13
you could also build the container from scratch and change the run command in the entrypoint script. If you put a test container on docker hub you can build it from the custom UI. (see the example above I've just referenced our current jupyterlab image.

**Comment by isaacfab** [comment] 2019-04-05 18:16
We had a similar issue with our shiny tool. The system runs the applications as a different user (shiny) so we had to specifically add privileges to that user or NFS would block any updates. maybe something similar is going on here? You can see in the shiny docker file how we handled it. lines ~30-40 
https://github.com/matrixds/tools/blob/master/shiny/Dockerfile

**Comment by shcheklein** [comment] 2019-04-05 18:20
@isaacfab as far as I understand entrypoint script does not change `docker run` arguments, it changes a script the container runs first when you start it. We need to run the container in a little bit different mode, it means that we need to modify settings of the GKE most likely. I'm not sure if we can do it for a single container though.

**Comment by isaacfab** [comment] 2019-04-05 18:22
Okay, I see. Maybe we should jump on a call for this.

**Comment by shcheklein** [comment] 2019-04-07 00:06
@isaacfab hi! We were able to pinpoint the source of this problem - file locks over NFS. We are using file locking in two places - one is to prevent user from running two commands simultaneously, second indirectly used in SQLLite. For example, if try to run the following snippet, you can reproduce the problem very easily:

```python
import sqlite3
db  = sqlite3.connect('db')
cursor = db.cursor()
cmd = "CREATE TABLE IF NOT EXISTS 'state' (count INTEGER)"
cursor.execute(cmd)
```

It looks like a pretty general problem and I would expect some other tools that use SQLLite to hang.

The first thing to try that comes to my mind (before we consider possible workarounds on the DVC side) - check and adjust the NFS settings or even NFS version. It looks like you are using NFS 3 which is pretty old. Was there a specific reason for that? Could you provide more information - server/client versions, settings, commands you run to mount it, etc? That would help us to brainstorm this.

**Comment by isaacfab** [comment] 2019-04-07 21:31
@shcheklein the other tools that use sqllite have it installed in another volume (or on the container itself) so we don't have issues like this. The problem here is that the matrixds project directory is special. It is a public collection of files that any user on the project can use by creating a new tool. This directory is intended to shared and only contain project artifacts (data, code and dependencies). Because of this we have some specific (permissive) rules set on that volume to ensure there are not any problems with sharing. If we allow some files to be locked here it causes some issues. This might need some deeper thinking on our end. 

I'm not sure about the NFS 3 version... 

One (hacky) workaround is to put the dvc project somewhere other than the home directory for now (like /home/dvc_project or something like that).

**Comment by shcheklein** [comment] 2019-04-07 23:18
I'm not sure I completely understand the setup you have. Does it mean that I can share the same directory (`tool-<id>`) on NFS between two different docker containers (two different tools)? I thought that this directory was unique to the container (thus it has a unique id in its path). Could you give me an example how do I share it?

Is this directory intended to run git in it, btw?

Saying that, I have also another question. You mentioned that "If we allow some files to be locked here it causes some issues". First, what kind of issues do you mean? And my thinking was that locking files is the mechanism specifically made to prevent data (data in general, not in data science sense) corruption in a shared environment. For example, git is also using locking (through symlinks, probably because they had a lot of troubles with NFS :)) when you run a command. Specifically to prevent multiple users from executing something simultaneously.

We can definitely force users to put DVC project outside NFS. It's hard for me to "feel" how hacky is it for your environment.

**Comment by shcheklein** [comment] 2019-04-10 22:25
@isaacfab hey, any updates on your end? ) could you clarify those things I asked above ^^

**Comment by isaacfab** [comment] 2019-04-23 01:38
@shcheklein got busy :). The workaround referenced above worked so we are good right now (we have a number of users doing this). We are working on a more permanent NFS solution that will take a bit more time to implement. I'll ping you once we have it done.

**Comment by shcheklein** [comment] 2019-04-23 01:41
@isaacfab glad to hear that, Isaac! I'm going to close the issue for now since we have a workaround and looks like no action items from the DVC end for now. Please, feel free to reopen it when you get to the NFS redesign and if you need our help. Thanks.

**Closed by shcheklein** 2019-04-23 01:41 UTC
Labels: bug
