### ISSUE TITLE
add: preserve metric flag

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#1632] opened 2019-02-19 00:53 UTC
Steps to reproduce:

```
echo "1" > metrics.txt
dvc add metrics.txt
dvc metrics add metrics.txt
cat metrics.txt.dvc | grep metric:
    metric: true

echo "2" > metrics.txt
dvc add metrics.txt
cat metrics.txt.dvc | grep metric:
    metric: false
```

EDIT:
these days we preserve desc field, so metric should be preserved the same way. E.g. see https://github.com/iterative/dvc/blob/f09c27e74c0a79c30c2c09a6b82201f4930ba63b/dvc/repo/add.py#L184

**Comment by efiop** [comment] 2019-02-19 06:24
Good catch! This is caused by `dvc add` not trying to read an old dvc file. We should carry over such params from and old dvc file, unless `--overwrite-dvcfile` is specified. Maybe `dvc run` also needs such a fix, need to take a look. Thanks!

**Comment by pared** [comment] 2019-03-06 16:15
I am wondering, whether we should let user add in such case and automatically pass params, or rather raise exception and expect him to use `--overwrite-dvcfile`?

**Comment by efiop** [comment] 2019-03-07 13:00
@pared it feels like we should let user add and not touch `metric:` unless he specifies `--overwrite-dvcfile`. Probably the same case with `locked:` field too, btw. Also, it will also affect `dvc run` command and `dvc imp`, since they are so closely related. I think we could adopt the same strategy there as well. What do you think?

**Comment by pared** [comment] 2019-03-12 15:41
At the beginning I was more toward exception, but I guess that it is not that important to break up everything if someone reuses metrics file name.

**Comment by dberenbaum** [comment] 2022-06-16 19:42
I think this is no longer relevant @pared @efiop? I'm closing. Feel free to reopen if I misunderstood.

**Closed by dberenbaum** 2022-06-16 19:42 UTC
Labels: :bug: bug, help wanted, good first issue, p3-nice-to-have
