### ISSUE TITLE
params: bulk params from file

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#6605] opened 2021-09-13 20:05 UTC
Params need to be specified individually, which can be repetitive and inconvenient where users want to simply include all parameters from a file. 

For background, see:

* https://github.com/iterative/dvc/issues/3393#issuecomment-599896828
* https://github.com/iterative/dvc/discussions/6506#discussioncomment-1273357

Instead of specifying every parameter individually, it should be possible to do `dvc stage add foo -p my_params.yaml python foo.py` or `dvc stage add foo -p "my_params.yaml:*" python foo.py`, which could generate this `dvc.yaml`:

```yaml
stages:
  foo:
    cmd: python foo.py
    params:
    - my_params.yaml
```

or

```yaml
stages:
  foo:
    cmd: python foo.py
    params:
    - my_params.yaml:*
```

After running `dvc repro`, `dvc.lock` could treat `my_params.yaml` like a regular file dependency:

```yaml
stages:
  foo:
    cmd: python foo.py
    deps:
    - path: my_params.yaml
    - md5: abc123
```

However, commands that collect parameters to show info about them, like `dvc params diff` and `dvc exp show`, would parse `my_params.yaml` and show each individual parameter.

**Comment by skshetry** [comment] 2021-10-05 06:20
Some questions that I have:
1. Does this mean tracking all the params of the file at a time or all the time? Do we need support for both?
    See https://github.com/iterative/dvc/issues/4112.
2. Do we want to save the contents of it or the complete file?
    We have never saved the params file before. We have only used the data from dvc.lock to see if they have changed.

Regarding the structure, I prefer `dvc.lock` mirror `dvc.yaml`, having `params` section from `dvc.yaml` to not refer to `params` section in `dvc.lock` maybe confusing.

This will also affect run-cache. It's not a big issue, as it's just a `dvc.lock` like file, but this change will also affect run-cache.

**Comment by dberenbaum** [comment] 2022-01-04 19:01
@skshetry Returning to this. Thanks for the reference to #4112. I would probably go so far as to mark this a duplicate, close this, and continue conversation there. WDYT?

**Comment by skshetry** [comment] 2022-01-24 11:40
Duplicate of #4112

**Comment by skshetry** [comment] 2022-01-24 11:41
Let's close this then @dberenbaum.

**Closed by skshetry** 2022-01-24 11:41 UTC
Labels: A: pipelines
