### ISSUE TITLE
dvc: destroy: do unprotect instead of remove on working space data files

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#1802] opened 2019-03-28 22:34 UTC
Internally destroy is using `remove()` which is probably too destructive. It's better to use `unprotect()` instead.

**Comment by efiop** [comment] 2019-04-04 22:01
Closing as a duplicate of https://github.com/iterative/dvc/issues/1802

**Closed** 2019-04-04 23:57 UTC
Labels: c3-small-fix, enhancement, p2-medium
