### ISSUE TITLE
`dvc metrics show` — binaries built with `pyinstaller` produce traceback

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/dvc#7542] opened 2022-04-05 02:36 UTC
# Bug Report

## Description

DVC 2.10.0 releases bundled using `pyinstaller` fail when running `dvc metrics show` producing a traceback. Not sure it it's specific to that subcommand.

### Reproduce

```console
$ dvc metrics show
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod03_importers.py", line 298, in get_code
  File "PyInstaller/loader/pyimod02_archive.py", line 287, in extract
TypeError: unhashable type: 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dvc/__main__.py", line 7, in <module>
  File "dvc/cli/__init__.py", line 121, in main
  File "dvc/analytics.py", line 37, in collect_and_send_report
  File "dvc/daemon.py", line 109, in daemon
  File "inspect.py", line 1554, in stack
  File "inspect.py", line 1531, in getouterframes
  File "inspect.py", line 1505, in getframeinfo
  File "inspect.py", line 829, in findsource
  File "inspect.py", line 746, in getmodule
  File "importlib/util.py", line 245, in __getattribute__
  File "PyInstaller/loader/pyimod03_importers.py", line 478, in exec_module
  File "PyInstaller/loader/pyimod03_importers.py", line 300, in get_code
TypeError: can only concatenate str (not "dict") to str
[1747] Failed to execute script '__main__' due to unhandled exception!
```

### Expected

```console
$ dvc metrics show
```

### Environment information

Tested on both Ubuntu 20.04 and macOS 11.6 with identical results.

## `dvc doctor`

```console
$ dvc doctor
DVC version: 2.10.0 (deb)
---------------------------------
Platform: Python 3.9.10 on Linux-5.13.0-1017-azure-x86_64-with-glibc2.31
Supports:
	azure (adlfs = 2022.2.0, knack = 0.9.0, azure-identity = 1.8.0),
	gdrive (pydrive2 = 1.10.0),
	gs (gcsfs = 2022.2.0),
	hdfs (fsspec = 2022.2.0, pyarrow = 7.0.0),
	webhdfs (fsspec = 2022.2.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	s3 (s3fs = 2022.2.0, boto3 = 1.20.24),
	ssh (sshfs = 2022.3.1),
	oss (ossfs = 2021.8.0),
	webdav (webdav4 = 0.9.5),
	webdavs (webdav4 = 0.9.5)
```

### Ubuntu
```yaml
on: workflow_dispatch
jobs:
  fails:
    runs-on: ubuntu-latest
    steps:
    - run: wget https://github.com/iterative/dvc/releases/download/2.10.0/dvc_2.10.0_amd64.deb && sudo apt install ./dvc_2.10.0_amd64.deb
    - run: dvc doctor && dvc metrics show
  succeeds:
    runs-on: ubuntu-latest
    steps:
    - run: pip3 install dvc==2.10.0
    - run: dvc doctor && dvc metrics show
```

### macOS
```yaml
on: workflow_dispatch
jobs:
  fails:
    runs-on: macos-latest
    steps:
    - run: wget https://github.com/iterative/dvc/releases/download/2.10.0/dvc-2.10.0.pkg && sudo installer -pkg dvc-2.10.0.pkg -target /
    - run: dvc doctor && dvc metrics show
  succeeds:
    runs-on: macos-latest
    steps:
    - run: pip3 install dvc==2.10.0
    - run: dvc doctor && dvc metrics show
```

**Comment by skshetry** [comment] 2022-04-05 02:41
Duplicate of #531

**Closed by skshetry** 2022-04-05 02:41 UTC

**Comment by 0x2b3bfa0** [comment] 2022-04-05 02:48
Thanks! 🤦🏼‍♂️
