### ISSUE TITLE
Add hardlinks to cache

### ISSUE THREAD

**Issue by johnyaku** [iterative/dvc#10601] opened 2024-10-23 12:35 UTC
I've recently moved to a new file system that supports hardlinks, and have set `cache.type` to `hardlink,symlink`. This greatly reduces my inode count, which makes the sys admins happy, and a number of tools that struggle to "see through" symlinks now work without having to `dvc unprotect` first.

When I `dvc checkout --relink` to replace my old symlinks by hardlinks, the process is delightfully fast, even for thousands of files summing to several TB in storage.

However, when I `dvc add` a folder with several TB of data I still have to wait hours for DVC to _copy_ the data to the cache and then create links. When I was stuck with symlinks, I accepted this as the price to pay for the many benefits of DVC. But now that I have become accustomed to hardlinks, I wonder if all this copying is really necessary?

Surely DVC could just create a hardlink in the cache for the files in the workspace? The net result -- to file names pointing to the same inode -- will be the same, but the process should be orders of magnitude faster.

Obviously, this only makes sense on file systems that support hardlinks (and perhaps reflinks, altho I'm less certain there). And even then there might be ownership obstacles sometimes.  But when possible this would be a great boost .. unless I'm missing something.

**Comment by skshetry** [comment] 2024-10-23 12:46
Hi, did you try with latest dvc version: [`3.56.0`](https://github.com/iterative/dvc/releases/tag/3.56.0)? #10557 changed that to only hard-link stuff to the cache and does some additional processing to determine if we need to relink files back to the workspace. But since the `cache.type` is `hardlink`, it will not require any relinking, so effectively, we'll only hardlink files.

**Comment by skshetry** [comment] 2024-10-23 12:53
Even though I merged that change, I am considering it as an optimization rather than a guaranteed behavior at this point. So I may roll that back in the future.

> Surely DVC could just create a hardlink in the cache for the files in the workspace? 

The issue is that doing a hardlink might corrupt the cache on failure. Eg: if `dvc add` fails after hardlinking file, but if it's not made read-only, it might corrupt cache as users can modify it in their workspace so you have to be careful with those files.

We could do atomic hardlinking, but that's not what we are doing at the moment IIRC.

**Closed** 2024-10-24 02:53 UTC
Labels: awaiting response
