### ISSUE TITLE
VS Code Extension

### ISSUE THREAD

**Issue by phitoduck** [iterative/dvc#7389] opened 2022-02-16 06:07 UTC
VS Code's built-in `git` feature is excellent, especially when you download something like "Gitlens". It would be *so* cool if we had a similar extension for DVC that exposed a similar visual interface for seeing which data files are tracked/staged, viewing/editing configurations, etc.

<img width="1745" alt="image" src="https://user-images.githubusercontent.com/32227767/154206292-5620c7aa-bd1a-40ef-955d-c470ca129316.png">

**Comment by pmrowla** [comment] 2022-02-16 06:14
Closing as duplicate of https://github.com/iterative/dvc/discussions/6047

@phitoduck we are currently have an in-development extension, please see the linked discussion and join the discord if you are interested in requesting access

**Closed by pmrowla** 2022-02-16 06:14 UTC

**Comment by shcheklein** [comment] 2022-02-16 06:15
@phitoduck It's in progress :)

I've invited you to the project. Please give it a try. Feel free to create any issues, feedback, discussions in the repo. We need as much feedback there as possible.

**Comment by phitoduck** [comment] 2022-02-16 21:10
I am so sorry for creating a duplicate! I did a search for "VS Code" and didn't dig any further when nothing came up from that search. This is awesome to hear :D
