### ISSUE TITLE
dvc pull: sqlite3.OperationalError: database is locked while running on Azure

### ISSUE THREAD

**Issue by SlimakSlimak** [iterative/dvc#9145] opened 2023-03-09 12:15 UTC
# Bug Report

## Description

dvc is not working on the Azure ML instance, even though it is working on local computer. After cloning repo with dvc and trying to run any command, even `dvc doctor` the following error pops up:
```
(venv) (azureml_py38) azureuser@test-compute:~/cloudfiles/code/Users/example-dvc-experiments$ dvc doctor -vv
2023-03-08 22:40:03,295 DEBUG: v2.46.0 (pip), CPython 3.8.10 on Linux-5.15.0-1031-azure-x86_64-with-glibc2.17
2023-03-08 22:40:03,295 DEBUG: command: /mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/bin/dvc doctor -vv
2023-03-08 22:40:03,295 TRACE: Namespace(cd='.', cmd='doctor', cprofile=False, cprofile_dump=None, func=<class 'dvc.commands.version.CmdVersion'>, instrument=False, instrument_open=False, parser=DvcParser(prog='dvc', usage=None, description='Data Version Control', formatter_class=<class 'argparse.RawTextHelpFormatter'>, conflict_handler='error', add_help=False), pdb=False, quiet=0, show_stack=False, verbose=2, viztracer=False, viztracer_async=False, viztracer_depth=None, yappi=False, yappi_separate_threads=False)
2023-03-08 22:41:14,143 ERROR: unexpected error - database is locked
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/cli/__init__.py", line 210, in main
    ret = cmd.do_run()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/cli/command.py", line 40, in do_run
    return self.run()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/commands/version.py", line 16, in run
    dvc_info = get_dvc_info()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/info.py", line 38, in get_dvc_info
    with Repo() as repo:
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/repo/__init__.py", line 236, in __init__
    self.state = State(self.root_dir, state_db_dir, self.dvcignore)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc_data/hashfile/state.py", line 89, in __init__
    self.links = Cache(links_dir)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc_data/hashfile/cache.py", line 59, in __init__
    super().__init__(
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/diskcache/core.py", line 478, in __init__
    self.reset(key, value, update=False)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/diskcache/core.py", line 2440, in reset
    sql('PRAGMA %s = %s' % (pragma, value)).fetchall()
sqlite3.OperationalError: database is locked

Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/cli/__init__.py", line 210, in main
    ret = cmd.do_run()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/cli/command.py", line 40, in do_run
    return self.run()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/commands/version.py", line 16, in run
    dvc_info = get_dvc_info()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/info.py", line 38, in get_dvc_info
    with Repo() as repo:
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/repo/__init__.py", line 236, in __init__
    self.state = State(self.root_dir, state_db_dir, self.dvcignore)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc_data/hashfile/state.py", line 89, in __init__
    self.links = Cache(links_dir)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc_data/hashfile/cache.py", line 59, in __init__
    super().__init__(
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/diskcache/core.py", line 478, in __init__
    self.reset(key, value, update=False)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/diskcache/core.py", line 2440, in reset
    sql('PRAGMA %s = %s' % (pragma, value)).fetchall()
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/bin/dvc", line 8, in <module>
    sys.exit(main())
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/cli/__init__.py", line 236, in main
    ret = _log_exceptions(exc) or 255
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/cli/__init__.py", line 145, in _log_exceptions
    _log_unknown_exceptions()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/cli/__init__.py", line 47, in _log_unknown_exceptions
    logger.debug("Version info for developers:\n%s", get_dvc_info())
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/info.py", line 38, in get_dvc_info
    with Repo() as repo:
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/repo/__init__.py", line 236, in __init__
    self.state = State(self.root_dir, state_db_dir, self.dvcignore)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc_data/hashfile/state.py", line 89, in __init__
    self.links = Cache(links_dir)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc_data/hashfile/cache.py", line 59, in __init__
    super().__init__(
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/diskcache/core.py", line 478, in __init__
    self.reset(key, value, update=False)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/diskcache/core.py", line 2440, in reset
    sql('PRAGMA %s = %s' % (pragma, value)).fetchall()
sqlite3.OperationalError: database is locked
(venv) (azureml_py38) azureuser@test-compute:~/cloudfiles/code/Users/example-dvc-experiments$ dvc doctor -vv
2023-03-08 22:40:03,295 DEBUG: v2.46.0 (pip), CPython 3.8.10 on Linux-5.15.0-1031-azure-x86_64-with-glibc2.17
2023-03-08 22:40:03,295 DEBUG: command: /mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/bin/dvc doctor -vv
2023-03-08 22:40:03,295 TRACE: Namespace(cd='.', cmd='doctor', cprofile=False, cprofile_dump=None, func=<class 'dvc.commands.version.CmdVersion'>, instrument=False, instrument_open=False, parser=DvcParser(prog='dvc', usage=None, description='Data Version Control', formatter_class=<class 'argparse.RawTextHelpFormatter'>, conflict_handler='error', add_help=False), pdb=False, quiet=0, show_stack=False, verbose=2, viztracer=False, viztracer_async=False, viztracer_depth=None, yappi=False, yappi_separate_threads=False)
2023-03-08 22:41:14,143 ERROR: unexpected error - database is locked
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/cli/__init__.py", line 210, in main
    ret = cmd.do_run()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/cli/command.py", line 40, in do_run
    return self.run()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/commands/version.py", line 16, in run
    dvc_info = get_dvc_info()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/info.py", line 38, in get_dvc_info
    with Repo() as repo:
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/repo/__init__.py", line 236, in __init__
    self.state = State(self.root_dir, state_db_dir, self.dvcignore)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc_data/hashfile/state.py", line 89, in __init__
    self.links = Cache(links_dir)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc_data/hashfile/cache.py", line 59, in __init__
    super().__init__(
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/diskcache/core.py", line 478, in __init__
    self.reset(key, value, update=False)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/diskcache/core.py", line 2440, in reset
    sql('PRAGMA %s = %s' % (pragma, value)).fetchall()
sqlite3.OperationalError: database is locked

Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/cli/__init__.py", line 210, in main
    ret = cmd.do_run()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/cli/command.py", line 40, in do_run
    return self.run()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/commands/version.py", line 16, in run
    dvc_info = get_dvc_info()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/info.py", line 38, in get_dvc_info
    with Repo() as repo:
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/repo/__init__.py", line 236, in __init__
    self.state = State(self.root_dir, state_db_dir, self.dvcignore)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc_data/hashfile/state.py", line 89, in __init__
    self.links = Cache(links_dir)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc_data/hashfile/cache.py", line 59, in __init__
    super().__init__(
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/diskcache/core.py", line 478, in __init__
    self.reset(key, value, update=False)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/diskcache/core.py", line 2440, in reset
    sql('PRAGMA %s = %s' % (pragma, value)).fetchall()
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/bin/dvc", line 8, in <module>
    sys.exit(main())
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/cli/__init__.py", line 236, in main
    ret = _log_exceptions(exc) or 255
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/cli/__init__.py", line 145, in _log_exceptions
    _log_unknown_exceptions()
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/cli/__init__.py", line 47, in _log_unknown_exceptions
    logger.debug("Version info for developers:\n%s", get_dvc_info())
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/info.py", line 38, in get_dvc_info
    with Repo() as repo:
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc/repo/__init__.py", line 236, in __init__
    self.state = State(self.root_dir, state_db_dir, self.dvcignore)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc_data/hashfile/state.py", line 89, in __init__
    self.links = Cache(links_dir)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/dvc_data/hashfile/cache.py", line 59, in __init__
    super().__init__(
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/diskcache/core.py", line 478, in __init__
    self.reset(key, value, update=False)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/test-compute/code/Users/venv/lib/python3.8/site-packages/diskcache/core.py", line 2440, in reset
    sql('PRAGMA %s = %s' % (pragma, value)).fetchall()
sqlite3.OperationalError: database is locked
```

### Reproduce

1. run Azure Machine Learning compute instance and connect to it
2. clone some dvc repo, for example: `git clone https://github.com/iterative/example-dvc-experiments.git`
3. create venv with packages: `python -m venv venv` and `pip install -r requirements.txt `
4. try to run any dvc command, example: `dvc doctor` or `dvc pull`

### Expected

Same output as in the local computer - pulling data while running `dvc pull` and displaying diagnostic info while running `dvc doctor`

### Environment information

dvc 2.46
Python 3.8
Linux 
Azure ML Compute instance comes with some preinstalled drivers and libraries, listed here: https://learn.microsoft.com/en-us/azure/machine-learning/concept-compute-instance

**Comment by shcheklein** [comment] 2023-03-09 20:42
Since it's a cifs:

```
Workspace directory: cifs on //mlworkspace8747263594.file.core.windows.net/code-391ff5ac-6576-460f-ba4d-7e03433c68b6
```

Most likely this is a duplicate of https://github.com/iterative/dvc/issues/5562

@SlimakSlimak could you please read that thread and try some things from it?

**Comment by shcheklein** [comment] 2023-03-09 20:44
Closing as a duplicate for now, @SlimakSlimak please feel free to reopen it / or chime in that thread.

**Closed by shcheklein** 2023-03-09 20:44 UTC
