### ISSUE TITLE
dvc repro: make the --pull flag work with --downstream flag

### ISSUE THREAD

**Issue by ettadar** [iterative/dvc#4871] opened 2020-11-10 13:48 UTC
Currently the `--pull` flag have no impact when used together with the `--downstream` flag. When working in a new repo, one must pull manually all the `deps` of stage `A` (if there is too much data handled with dvc to run  `dvc pull`) before running `dvc repro --downstream A`. It would be great if `dvc repro --downstream --pull A` would automatically pull `A` deps.

Linked to #4870 
Discord discussion: https://discord.com/channels/485586884165107732/485596304961962003/775412039321387008

**Comment by ettadar** [comment] 2020-11-10 15:19
Thinking more about it it would be great if `--pull` would work with `-s|--single-item` too.

**Comment by dberenbaum** [comment] 2022-02-23 19:00
This looks like a duplicate of #4742 to me since it falls under "pull whatever is missing and necessary for this repro." Closing in favor of that, but definitely want to make sure this use case is covered. I'll transfer the comments over to that issue.

**Closed by dberenbaum** 2022-02-23 19:00 UTC
Labels: feature request, p2-medium
