### ISSUE TITLE
exp show: branch names are toggling randomly

### ISSUE THREAD

**Issue by aguschin** [iterative/dvc#6051] opened 2021-05-24 12:27 UTC
# Bug Report

## Description

I cloned repo get-started-experiments and created new branch. Now `dvc exp show` shows me different  branch names from time to time. It also happens if you move back to `main` branch.

<img width="1160" alt="image" src="https://user-images.githubusercontent.com/6797716/119347212-e3a71080-bca3-11eb-9bfa-ccfd663a5718.png">

### Reproduce

1. git clone https://github.com/iterative/get-started-experiments 
2. cd get-started-experiments
3. dvc pull
4. git checkout -b other-branch
5. dvc exp show --no-pager

Run last command few times

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.1.0 (brew)
---------------------------------
Platform: Python 3.9.5 on macOS-10.16-x86_64-i386-64bit
Supports: azure, gdrive, gs, http, https, s3, ssh, oss, webdav, webdavs
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s5s1
Caches: local
Remotes: https
Workspace directory: apfs on /dev/disk1s5s1
Repo: dvc, git
```

**Additional Information (if any):**

Tried the same with the latest dev version 2.1.0+9dda6b, the bug persists

**Comment by casperdcl** [comment] 2021-05-24 13:06
Ideally all aliases (refs with the same `HEAD`) should be shown, or at least the same one consistently (e.g. first alphabetically. I don't think Git keep a record of when an alias branch was created so no way to take last created, I think).

**Comment by pmrowla** [comment] 2021-05-25 02:46
`exp show` is being changed to always show git SHA's by default, along with a single branch or tag name (w/tag's given higher priority) for that SHA. The SHA will remain unchanged, and ideally we should consistently choose a ref, but I don't think this is high priority right now.

**Comment by dberenbaum** [comment] 2021-05-25 12:18
@pmrowla Isn't `exp show` limited to the experiments derived from the current HEAD by default? If so, would it make sense to at least prioritize the current branch over others?

**Comment by pmrowla** [comment] 2021-05-25 12:42
@dberenbaum sure, that's one way we could make it more consistent, at least for the case where HEAD is actually a branch, and there are no tags that also point to HEAD.

**Comment by karajan1001** [comment] 2021-12-02 09:00
@aguschin Does it still happen on your computer? I tried on my one can't reproduce it for now.

[![asciicast](https://asciinema.org/a/bV9qCnz5Ckr8eZwTzaAeug2Rd.svg)](https://asciinema.org/a/bV9qCnz5Ckr8eZwTzaAeug2Rd)

**Comment by aguschin** [comment] 2021-12-02 10:03
@karajan1001, it's because the tag has the higher priority (see @pmrowla answer above). Try to delete tag and then repeat this for few times:
<img width="811" alt="image" src="https://user-images.githubusercontent.com/6797716/144400503-1afe82c0-ffbc-4a42-973f-b718e4fd1493.png">

**Comment by karajan1001** [comment] 2021-12-07 12:43
The current status for this after the next `scmrepo` version is that if one of the branch names is active it will get priority, but if we are using `exp show -A` for some other branches, it will still toggling randomly 
> we are on branch `master`, and use `exp show -A` for some previous commit that branch `A`, `B`, and `C` all point to.

**Comment by skshetry** [comment] 2021-12-08 03:32
@karajan1001 @pmrowla, please make a release if you need it, or let me know.

**Comment by daavoo** [comment] 2021-12-10 17:43
> The current status for this after the next `scmrepo` version is that if one of the branch names is active it will get priority, but if we are using `exp show -A` for some other branches, it will still toggling randomly
> 
> > we are on branch `master`, and use `exp show -A` for some previous commit that branch `A`, `B`, and `C` all point to.

Is there anything else possible to improve or could we close this?

**Comment by pmrowla** [comment] 2021-12-13 06:26
> Is there anything else possible to improve or could we close this?

There are still potential improvements like

> Ideally all aliases (refs with the same HEAD) should be shown, or at least the same one consistently

The main issue being that collecting all aliases (and sorting them either alphabetically or by timestamp) will come at a potential cost to performance (especially in repo with lots of refs and/or exps).

**Comment by karajan1001** [comment] 2021-12-13 10:35
> The main issue being that collecting all refs that point to a given commit (and sorting them either alphabetically or by timestamp) will come at a potential cost to performance (especially in repos with lots of refs and/or exps).

In `.git/refs/heads` we can get the last modified time of each reference, and that gives an order of them. We  can choose the oldest reference. And In this case, the `describe` result will be stable if we lately create new branches on the current revision.

But all of these involve new features on the backend side, or maybe we can implement them in `scmrepo`?

**Comment by pmrowla** [comment] 2021-12-13 12:51
> In `.git/refs/heads` we can get the last modified time of each reference, and that gives an order of them. We can choose the oldest reference.

This doesn't work if the refs are packed

> But all of these involve new features on the backend side, or maybe we can implement them in `scmrepo`?

This would all have to be implemented in scmrepo (and it would likely need to be added in each backend's `_describe`)

**Comment by dberenbaum** [comment] 2023-03-02 20:21
@aguschin Closing as stale, but feel free to reopen if you are still seeing this

**Comment by dberenbaum** [comment] 2023-08-04 14:39
I think it's also happening with `exp show`. I think the problem is that there are multiple tags referencing the same commit. See below:

```bash
$ dvc exp show
 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────>
  Experiment           Created        train.box_loss   train.seg_loss   train.cls_loss   train.dfl_loss   metrics.precision(B)   metrics.recall(B)   metrics.mAP50(B)   metrics.m>
 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────>
  workspace            -                           -                -                -                -                      -                   -                  -            >
  1-notebook-dvclive   Jul 29, 2023           3.2606           4.5661           3.8355           1.9272              0.0013889              0.1087         0.00077617            >
 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────>

$ dvc exp show
 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────>
  Experiment            Created        train.box_loss   train.seg_loss   train.cls_loss   train.dfl_loss   metrics.precision(B)   metrics.recall(B)   metrics.mAP50(B)   metrics.>
 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────>
  workspace             -                           -                -                -                -                      -                   -                  -           >
  dvclive=best@v0.1.0   Jul 29, 2023           3.2606           4.5661           3.8355           1.9272              0.0013889              0.1087         0.00077617           >
 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────>
```

It also impacts the VS Code extension (cc @mattseddon):


https://github.com/iterative/dvc/assets/2308172/eab681fe-08a6-4739-9bec-387ed3fe7e04


https://github.com/iterative/dvc/assets/2308172/41d8224e-3a46-4d4f-bbb9-384ebd1dcfbe

_Originally posted by @dberenbaum in https://github.com/iterative/dvc/issues/9794#issuecomment-1664640369_

**Comment by dberenbaum** [comment] 2023-08-04 16:13
> @dberenbaum just to be clear, that's happening when there is not a branch checked out, correct? This is expected behavior since multiple tags point to the same commit.

Yes, I was working from a tag in the repo.

**Closed** 2024-03-05 02:58 UTC
Labels: p3-nice-to-have, ui, product: VSCode, A: experiments, diff/show
