### ISSUE TITLE
Unable to run dvc pull command

### ISSUE THREAD

**Issue by khushkore** [iterative/dvc#9997] opened 2023-10-04 14:40 UTC
Cannot able to run the dvc pull command. Check the below description for it. 
Error Message:
```
ERROR: failed to connect to azure - module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
ERROR: failed to pull data from the cloud - 1 files failed to download
```
DVC and Deps Versions on python 3.8 (Ubuntu 20.04):
```
pip install dvc-azure==2.22.1
pip install fsspec==2023.9.2
pip install azure-storage-blob==12.18.1
```

**Comment by efiop** [comment] 2023-10-04 22:12
@khushkore Please post `dvc doctor` output.

**Comment by khushkore** [comment] 2023-10-04 22:39
```
DVC version: 3.23.0 (pip)
-------------------------
Platform: Python 3.10.12 on Linux-6.2.0-1012-azure-x86_64-with-glibc2.35
Subprojects:
	dvc_data = 2.16.4
	dvc_objects = 1.0.1
	dvc_render = 0.6.0
	dvc_task = 0.3.0
	scmrepo = 1.3.1
Supports:
	azure (adlfs = 2023.9.0, knack = 0.11.0, azure-identity = 1.14.0),
	http (aiohttp = 3.8.5, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.5, aiohttp-retry = 2.8.3)
Config:
	Global: /home/vsts/.config/dvc
	System: /etc/xdg/dvc

```

```
Traceback (most recent call last):
  File "/home/vsts/.local/lib/python3.10/site-packages/dvc_data/index/index.py", line 541, in _load_from_storage
    _load_from_object_storage(trie, entry, storage)
  File "/home/vsts/.local/lib/python3.10/site-packages/dvc_data/index/index.py", line 477, in _load_from_object_storage
    obj = Tree.load(storage.odb, root_entry.hash_info, hash_name=storage.odb.hash_name)
  File "/home/vsts/.local/lib/python3.10/site-packages/dvc_data/hashfile/tree.py", line 193, in load
    with obj.fs.open(obj.path, "r") as fobj:
  File "/home/vsts/.local/lib/python3.10/site-packages/dvc_objects/fs/base.py", line 228, in open
    return self.fs.open(path, mode=mode, **kwargs)
  File "/home/vsts/.local/lib/python3.10/site-packages/funcy/objects.py", line 47, in __get__
    return prop.__get__(instance, type)
  File "/home/vsts/.local/lib/python3.10/site-packages/funcy/objects.py", line 25, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "/home/vsts/.local/lib/python3.10/site-packages/dvc_azure/__init__.py", line 175, in fs
    from .spec import AzureBlobFileSystem
  File "/home/vsts/.local/lib/python3.10/site-packages/dvc_azure/spec.py", line 1, in <module>
    from adlfs import AzureBlobFileSystem as _AzureBlobFileSystem
  File "/home/vsts/.local/lib/python3.10/site-packages/adlfs/__init__.py", line 2, in <module>
    from .gen1 import AzureDatalakeFileSystem
  File "/home/vsts/.local/lib/python3.10/site-packages/adlfs/gen1.py", line 9, in <module>
    from azure.datalake.store import AzureDLFileSystem, lib
  File "/home/vsts/.local/lib/python3.10/site-packages/azure/datalake/store/__init__.py", line 11, in <module>
    from .core import AzureDLFileSystem
  File "/home/vsts/.local/lib/python3.10/site-packages/azure/datalake/store/core.py", line 27, in <module>
    from .lib import DatalakeRESTInterface
  File "/home/vsts/.local/lib/python3.10/site-packages/azure/datalake/store/lib.py", line 61, in <module>
    enforce_no_py_open_ssl()
  File "/home/vsts/.local/lib/python3.10/site-packages/azure/datalake/store/lib.py", line 42, in enforce_no_py_open_ssl
    from requests.packages.urllib3.contrib.pyopenssl import extract_from_urllib3
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL

```

**Comment by efiop** [comment] 2023-10-04 23:35
@khushkore Seems like it is a problem in your environment, try `pip install -U pyopenssl cryptography`.

**Comment by khushkore** [comment] 2023-10-05 01:05
@efiop Thank you for your answer. I already tried to install pyopenssl but it's not working. Moreover, its not the environment issue because the same code was working great until yesterday and it broke my multiple projects which uses dvc.

**Comment by efiop** [comment] 2023-10-05 19:16
@khushkore Something changed in your environment. Sorry, but I can't reproduce and it looks unrelated to dvc itself. There are multiple hits when searching for `module 'lib' has no attribute 'OpenSSL_add_all_algorithms'`, but I can't put a finger on what specifically is wrong in your environment. Unfortunately, you are on your own here. Closing for now.

**Closed by efiop** 2023-10-05 19:16 UTC
Labels: awaiting response

**Comment by dberenbaum** [comment] 2023-10-05 19:44
@khushkore You may want to try rebuilding your environment from scratch
