### ISSUE TITLE
 invalid start byte

### ISSUE THREAD

**Issue by Sunny-Day200** [iterative/dvc#3698] opened 2020-04-29 09:16 UTC
windows 10
dvc-0.92.0
git-bash 2.26.2.1
------------------------------
This is a very clean system
I cannot perform any DVC operations
Could it be because of the system environment?
--------------------------------

---------------------------------------
ERROR: unexpected error - 'utf-8' codec can't decode byte 0x87 in position 0: invalid start byte

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
Traceback (most recent call last):
  File "dvc\__main__.py", line 7, in <module>
  File "dvc\main.py", line 90, in main
  File "dvc\analytics.py", line 58, in is_enabled
  File "dvc\config.py", line 235, in __init__
  File "dvc\config.py", line 284, in load
  File "dvc\config.py", line 297, in load_one
  File "dvc\config.py", line 357, in _load_config
  File "site-packages\configobj.py", line 1229, in __init__
  File "site-packages\configobj.py", line 1287, in _load
  File "site-packages\configobj.py", line 1485, in _handle_bom
  File "site-packages\configobj.py", line 1517, in _decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x87 in position 0: invalid start byte
[30444] Failed to execute script __main__
[0x7FFD3CAFD3F0] ANOMALY: meaningless REX prefix used

----------------------------------------------------
And I want to ask about the cache link type, does it control the 'remote repository' and 'local cache' links?Or does it only work on 'local cache' links, and if it only works on 'local cache' links, can I change the 'DVC cache type, controlling the link type of the local cache data every time I pull git repository from a different platform?My English is not very good, I am not sure if I describe clearly, can you understand?

**Comment by efiop** [comment] 2020-04-29 09:28
Hi @Sunny-Day200 !

Please show us `$ dvc version` output (it contains more than a version).

Correct, cache link type only controls local cache links. :slightly_smiling_face: 

> can I change the 'DVC cache type, controlling the link type of the local cache data every time I pull git repository from a different platform

Yes, you could use `.dvc/config.local`(used when you specify --local flag in your dvc config commands) for that. It is not tracked by git so it just stays in your local git repo instance.

**Comment by Sunny-Day200** [comment] 2020-04-29 09:38
Thanked your reply
I tried it, but it didn't make any difference, right
----------------------------------------------

$ dvc version
ERROR: unexpected error - 'utf-8' codec can't decode byte 0x87 in position 0: invalid start byte

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
Traceback (most recent call last):
  File "dvc\__main__.py", line 7, in <module>
  File "dvc\main.py", line 90, in main
  File "dvc\analytics.py", line 58, in is_enabled
  File "dvc\config.py", line 235, in __init__
  File "dvc\config.py", line 284, in load
  File "dvc\config.py", line 297, in load_one
  File "dvc\config.py", line 357, in _load_config
  File "site-packages\configobj.py", line 1229, in __init__
  File "site-packages\configobj.py", line 1287, in _load
  File "site-packages\configobj.py", line 1485, in _handle_bom
  File "site-packages\configobj.py", line 1517, in _decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x87 in position 0: invalid start byte
[28480] Failed to execute script __main__
[0x7FFD3CAFD3F0] ANOMALY: meaningless REX prefix used

**Comment by karajan1001** [comment] 2020-04-29 14:39
I think this is because your system uses a different encoding method beside `utf-8` (for example chinese charactor may encode into `gbk` ).   Cleaning any none English character in your path name will solve your problems. But it's only a temporary solution.

```
def _load_config(filename):
    conf_obj = configobj.ConfigObj(filename)
    return _parse_remotes(_lower_keys(conf_obj.dict()))
```

**Comment by karajan1001** [comment] 2020-05-01 13:00
![image](https://user-images.githubusercontent.com/6745454/80806865-530c1700-8bee-11ea-82e9-38af75672819.png)
I can't reproduce your error. It seems that UTF8 encoding had been set to default since Windows 10 version 1903. Could you give me the result from the following python script?
```
import sys
sys.getfilesystemencoding()
```

**Comment by Sunny-Day200** [comment] 2020-05-07 09:06
It is indeed in utf-8 format. I haven't figured out what the problem is yet. It didn't happen on my other computers.I need to reinstall the system to try

**Comment by Sunny-Day200** [comment] 2020-05-07 09:08
> ![图片](https://user-images.githubusercontent.com/6745454/80806865-530c1700-8bee-11ea-82e9-38af75672819.png)
> 我无法重现您的错误。自Windows 10 1903版以来，似乎UTF8编码已设置为默认值。您能否从以下python脚本中获取结果？
> 
> ```
> import sys
> print(sys.getfilesystemencoding())
> ```



It is indeed in utf-8 format. I haven't figured out what the problem is yet. It didn't happen on my other computers.I need to reinstall the system to try

**Comment by Sunny-Day200** [comment] 2020-05-07 09:08
> ![图片](https://user-images.githubusercontent.com/6745454/80806865-530c1700-8bee-11ea-82e9-38af75672819.png)
> 我无法重现您的错误。自Windows 10 1903版以来，似乎UTF8编码已设置为默认值。您能否从以下python脚本中获取结果？
> 
> ```
> import sys
> print(sys.getfilesystemencoding())
> ```

It is indeed in utf-8 format. I haven't figured out what the problem is yet. It didn't happen on my other computers.I'm going to reinstall the system and try again

**Comment by karajan1001** [comment] 2020-05-07 09:20
> > ![图片](https://user-images.githubusercontent.com/6745454/80806865-530c1700-8bee-11ea-82e9-38af75672819.png)
> > 我无法重现您的错误。自Windows 10 1903版以来，似乎UTF8编码已设置为默认值。您能否从以下python脚本中获取结果？
> > ```
> > import sys
> > print(sys.getfilesystemencoding())
> > ```
> 
> It is indeed in utf-8 format. I haven't figured out what the problem is yet. It didn't happen on my other computers.I'm going to reinstall the system and try again

Have you tried using a folder name without any non-English characters?

**Comment by Sunny-Day200** [comment] 2020-05-07 09:28
> > > ![图片](https://user-images.githubusercontent.com/6745454/80806865-530c1700-8bee-11ea-82e9-38af75672819.png)
> > > 自Windows 10 1903版以来，似乎UTF8编码已设置为替换值。您能否从以下python脚本中获取结果？
> > > ```
> > > import sys
> > > print(sys.getfilesystemencoding())
> > > ```
> > 
> > 
> > 它确实是utf-8格式。我还没有弄清楚问题出在哪里。在其他计算机上没有发生。我要重新安装系统，然后重试
> 
> 您是否尝试使用没有任何非英文字符的文件夹名称？

The path does not contain any non-english characters
![b473e7df0fdfda76006986ed487f3ed](https://user-images.githubusercontent.com/53826251/81278369-28a3d900-9088-11ea-8b22-307696d5037d.png)

**Comment by Sunny-Day200** [comment] 2020-05-07 09:40
I have some other questions:

**Comment by Sunny-Day200** [comment] 2020-05-07 09:40
I have some other questions
------------------------------------
As described in the documentation, the hardlink, symlink link types make the workspace trace data file read-only (this prevents the user from accidentally corrupting the cache by modifying the file link).
As mentioned above, if I locally clone git from a remote location and change the copy of the cache link type to a symbolic link, is the trace file".dvc file" still not protected, and ".dvc file" will become read-only only after rebuilding "DVC add"
Sorry, I seem a little confused

**Comment by efiop** [comment] 2020-05-07 09:49
@Sunny-Day200 That is expected behaviour. What is important is that the cache file in .dvc/cache stays read-only and is not corrupted. `dvc add` will create a new cache entry for a modified file and will link it as read-only back into your workspace.

**Comment by karajan1001** [comment] 2020-05-09 08:14
> ## I have some other questions
> As described in the documentation, the hardlink, symlink link types make the workspace trace data file read-only (this prevents the user from accidentally corrupting the cache by modifying the file link).
> As mentioned above, if I locally clone git from a remote location and change the copy of the cache link type to a symbolic link, is the trace file".dvc file" still not protected, and ".dvc file" will become read-only only after rebuilding "DVC add"
> Sorry, I seem a little confused

Thank you, so strange. Maybe there is non-English char in your user name? And the error raises from loading global configuration.

**Comment by Sunny-Day200** [comment] 2020-05-09 08:38
> > ## 我还有其他问题
> > 如文档中所述，硬链接，符号链接链接类型使工作空间跟踪数据文件为只读（这可以防止用户通过修改文件链接意外破坏缓存）。
> > 如上所述，如果我从远程位置本地克隆git并将缓存链接类型的副本更改为符号链接，则跟踪文件“ .dvc文件”是否仍不受保护，而“ .dvc文件”将变为已读取-仅在重建“ DVC添加”之后，
> > 对不起，我似乎有些困惑
> 
> 谢谢，真奇怪。您的用户名中是否可能包含非英语字符？错误是由于加载全局配置引起的。

![b473e7df0fdfda76006986ed487f3ed](https://user-images.githubusercontent.com/53826251/81468653-76008180-9213-11ea-82f7-278e4fb2008f.png)

**Comment by Sunny-Day200** [comment] 2020-05-09 08:39
> > > ## 我还有其他问题
> > > 如文档中所述，硬链接，符号链接链接类型使工作空间跟踪数据文件为替换（这可以防止用户通过修改文件链接意外破坏缓存）。
> > > 替换，如果我从远程位置本地复制git缓存链接类型的副本更改为符号链接，则跟踪文件“ .dvc文件”是否仍未受到保护，而“ .dvc文件”将变为已重新读取-仅在重建“ DVC添加”之后，
> > > 对不起，我好像有些奇迹
> > 
> > 
> > 谢谢，真奇怪。您的用户名中是否可能包含非英语字符？错误是由于加载拆分配置引起的。
> 

![b473e7df0fdfda76006986ed487f3ed](https://user-images.githubusercontent.com/53826251/81468669-89135180-9213-11ea-842b-ba360b67470c.png)
It does not contain any non-english characters

**Comment by Sunny-Day200** [comment] 2020-05-09 08:41
> > ## I have some other questions
> > As described in the documentation, the hardlink, symlink link types make the workspace trace data file read-only (this prevents the user from accidentally corrupting the cache by modifying the file link).
> > As mentioned above, if I locally clone git from a remote location and change the copy of the cache link type to a symbolic link, is the trace file".dvc file" still not protected, and ".dvc file" will become read-only only after rebuilding "DVC add"
> > Sorry, I seem a little confused
> 
> Thank you, so strange. Maybe there is non-English char in your user name? And the error raises from loading global configuration.

It does not contain any non-english characters
![b473e7df0fdfda76006986ed487f3ed](https://user-images.githubusercontent.com/53826251/81468730-ead3bb80-9213-11ea-9b4e-c8831866eb42.png)

**Comment by Sunny-Day200** [comment] 2020-05-09 08:44
> > ## I have some other questions
> > As described in the documentation, the hardlink, symlink link types make the workspace trace data file read-only (this prevents the user from accidentally corrupting the cache by modifying the file link).
> > As mentioned above, if I locally clone git from a remote location and change the copy of the cache link type to a symbolic link, is the trace file".dvc file" still not protected, and ".dvc file" will become read-only only after rebuilding "DVC add"
> > Sorry, I seem a little confused
> 
> Thank you, so strange. Maybe there is non-English char in your user name? And the error raises from loading global configuration.

Not really, so I'm confused

**Comment by Sunny-Day200** [comment] 2020-05-09 08:45
> > ## I have some other questions
> > As described in the documentation, the hardlink, symlink link types make the workspace trace data file read-only (this prevents the user from accidentally corrupting the cache by modifying the file link).
> > As mentioned above, if I locally clone git from a remote location and change the copy of the cache link type to a symbolic link, is the trace file".dvc file" still not protected, and ".dvc file" will become read-only only after rebuilding "DVC add"
> > Sorry, I seem a little confused
> 
> Thank you, so strange. Maybe there is non-English char in your user name? And the error raises from loading global configuration.

No , so I'm confused

**Comment by efiop** [comment] 2020-06-03 06:23
Not able to reproduce :( Closing for now.

@Sunny-Day200 were you able to work around this issue?

**Closed by efiop** 2020-06-03 06:23 UTC
Labels: awaiting response
