### ISSUE TITLE
asyncssh/sftp.py, line 2386, in _process_status -> asyncssh.sftp.SFTPPermissionDenied: Permission denied

### ISSUE THREAD

**Issue by psydok** [iterative/dvc#7789] opened 2022-05-19 21:27 UTC
# Bug Report
## Description

I'm trying to push data to the server via ssh, but I am getting this error.
`$ dvc push file.csv.dvc`

```bash
2022-05-20 02:16:45,183 ERROR: failed to transfer 'md5: <hash>' - Permission denied
------------------------------------------------------------
Traceback (most recent call last):
  File "/var/anaconda/envs/nemo_asr/lib/python3.7/site-packages/dvc/objects/transfer.py", line 25, in wrapper
    func(path_info, *args, **kwargs)
  File "/var/anaconda/envs/nemo_asr/lib/python3.7/site-packages/dvc/objects/transfer.py", line 164, in func
    hardlink=hardlink,
  File "/var/anaconda/envs/nemo_asr/lib/python3.7/site-packages/dvc/objects/db/base.py", line 117, in add
    self._add_file(fs, path_info, cache_info, hash_info, hardlink=hardlink)
  File "/var/anaconda/envs/nemo_asr/lib/python3.7/site-packages/dvc/objects/db/base.py", line 88, in _add_file
    self.makedirs(to_info.parent)
  File "/var/anaconda/envs/nemo_asr/lib/python3.7/site-packages/dvc/objects/db/base.py", line 67, in makedirs
    self.fs.makedirs(path_info)
  File "/var/anaconda/envs/nemo_asr/lib/python3.7/site-packages/dvc/fs/fsspec_wrapper.py", line 198, in makedirs
    self._with_bucket(path_info), exist_ok=kwargs.pop("exist_ok", True)
  File "/home/user/.local/lib/python3.7/site-packages/fsspec/asyn.py", line 86, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/fsspec/asyn.py", line 66, in sync
    raise return_result
  File "/home/user/.local/lib/python3.7/site-packages/fsspec/asyn.py", line 26, in _runner
    result[0] = await coro
  File "/home/user/.local/lib/python3.7/site-packages/sshfs/utils.py", line 27, in wrapper
    return await func(*args, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/sshfs/spec.py", line 231, in _makedirs
    await channel.makedirs(path, exist_ok=exist_ok, attrs=attrs)
  File "/home/user/.local/lib/python3.7/site-packages/asyncssh/sftp.py", line 4045, in makedirs
    await self.mkdir(curpath, attrs)
  File "/home/user/.local/lib/python3.7/site-packages/asyncssh/sftp.py", line 4989, in mkdir
    await self._handler.mkdir(path, attrs)
  File "/home/user/.local/lib/python3.7/site-packages/asyncssh/sftp.py", line 2770, in mkdir
    attrs.encode(self._version))
  File "/home/user/.local/lib/python3.7/site-packages/asyncssh/sftp.py", line 2370, in _make_request
    result = self._packet_handlers[resptype](self, resp)
  File "/home/user/.local/lib/python3.7/site-packages/asyncssh/sftp.py", line 2386, in _process_status
    raise exc
asyncssh.sftp.SFTPPermissionDenied: Permission denied
------------------------------------------------------------
2022-05-20 02:16:45,186 ERROR: failed to push data to the cloud - 1 files failed to upload 
```
### Reproduce
```bash
dvc remote default sshremote
dvc add file.csv
dvc push -v file.csv.dvc
```
### Expected

That data will be pushed to remote storage.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor

DVC version: 2.8.3 (pip)
---------------------------------
Platform: Python 3.7.11 on Linux-5.15.0-3-amd64-x86_64-with-debian-bookworm-sid
Supports:
        hdfs (fsspec = 2022.5.0, pyarrow = 6.0.1),
        webhdfs (fsspec = 2022.5.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2022.5.0, boto3 = 1.17.106),
        ssh (sshfs = 2022.3.1)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/mapper/sys-var
Caches: local
Remotes: s3, ssh
Workspace directory: ext4 on /dev/mapper/sys-var
Repo: dvc, git
```
I removed dvc 2.10.2, installed the old version 2.8.3, tried to repeat with the settings - it doesn't work.

**Additional Information (if any):**

At some point, updating `pip install dvc[ssh] --upgrade` or `pip install sshfs --upgrade` or `s3fs` helped.
But pulled from the repository in s3 broke, `pip install dvc[s3] --upgrade` again and got back to the original problem.
Earlier stood `dvc==2.8.3`.

**Comment by psydok** [comment] 2022-05-19 22:46
I tried updating `dvc==2.10.2` again and putting
`pip install git+https://github.com/pmrowla/asyncssh.git@develop#egg=asyncssh` error in the same place.

**Comment by psydok** [comment] 2022-05-19 22:50
In general, from a funny thing: when I managed to set up push via ssh, they pulled pull from s3. And vice versa, when resurrecting pull from s3.

**Comment by pmrowla** [comment] 2022-05-20 01:44
Closing as a duplicate of https://github.com/iterative/dvc/issues/7174

You need to install from the main asyncssh develop branch to use the fix, not my fork:
```
pip install git+https://github.com/ronf/asyncssh.git@develop#egg=asyncssh
```

**Closed by pmrowla** 2022-05-20 01:44 UTC
