### ISSUE TITLE
Blobs get deleted after second dvc push to Azure Blob Storage

### ISSUE THREAD

**Issue by SimonDahrs** [iterative/dvc#10271] opened 2024-01-31 13:55 UTC
# Bug Report

## Description

I set up Azure Blob Storage as remote. When I add files to dvc, and push them with `dvc push`, they show up as expected in my blob container. However if I run `dvc push` again, without any changes whatsoever, the blobs get the deleted status in Azure. They are only visible when you toggle 'show deleted blobs'. This prevents me from using the blobs elsewhere.

### Reproduce

1. Set up Azure Blob Storage as a remote (I enabled version_aware with `dvc remote modify myremote version_aware true` as per docs)
2. Add some file to dvc (`dvc add somefile.json`)
3. Push the file to the remote (`dvc push`)
4. Verify it is stored in Azure Blob Storage
5. Push again (`dvc push`)
6. Verify the blob has now got 'deleted' (toggle 'show deleted blobs' to see it)

### Expected

I would think the second push would simply have no effect as no changes have been made.

### Environment information

1. Windows 10 computer
2. Azure cloud

**Output of `dvc doctor`:**

```console
DVC version: 3.42.0 (pip)
-------------------------
Platform: Python 3.9.12 on Windows-10-10.0.19045-SP0
Subprojects:
        dvc_data = 3.8.0
        dvc_objects = 3.0.6
        dvc_render = 1.0.1
        dvc_task = 0.3.0
        scmrepo = 2.0.4
Supports:
        azure (adlfs = 2023.12.0, knack = 0.11.0, azure-identity = 1.15.0),
        http (aiohttp = 3.9.1, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.9.1, aiohttp-retry = 2.8.3)
Config:
        Global: C:\Users\***\AppData\Local\iterative\dvc
        System: C:\ProgramData\iterative\dvc
Cache types: hardlink
Cache directory: NTFS on C:\
Caches: local
Remotes: azure
Workspace directory: NTFS on C:\
Repo: dvc, git
Repo.site_cache_dir: C:\ProgramData\iterative\dvc\Cache\repo\56cae8b680a8b303fa411414c780a7d6
```

**Additional Information (if any):**

I first raised a question on [Stackoverflow](https://stackoverflow.com/questions/77880603/dvc-with-azure-blob-storage-blobs-get-deleted-after-second-dvc-push?noredirect=1#comment137353158_77880603) about this.

**Comment by pmrowla** [comment] 2024-02-15 07:14
I can reproduce this, the issue is that we are double quoting an etag somewhere for azure and it ends up causing us to think the current file has changed:
```python
Change(
  typ='modify',
  old=DataIndexEntry(
    ..., meta=Meta(..., version_id='2024-02-15T07:03:18.7016417Z', etag='0x8DC2DF43065CEE1')
  ),
  new=DataIndexEntry(
    ..., meta=Meta(..., version_id='2024-02-15T07:03:18.7016417Z', etag='"0x8DC2DF43065CEE1"'), 
  ),
)
```

**Comment by pmrowla** [comment] 2024-02-15 07:48
It looks like this is due to a behavior difference across azure API calls.

When using `BlobClient.get_blob_properties()` the returned etag property is enclosed in `"` quotes. However, when using `BlobContainer.walk_blobs()` the etag property for iterated blobs is not enclosed in quotes. This causes adlfs to have different behavior for the etag field when using `ls(detail=True)` vs `info()`.

**Comment by pmrowla** [comment] 2024-02-15 08:27
I opened an issue in adlfs but I'm not sure it's even something that should be fixed there since adlfs is just returning what the azure API returns
https://github.com/fsspec/adlfs/issues/461

(the linked PR to fix this issue is on our end in dvc-data)

**Closed** 2024-02-15 20:41 UTC
Labels: bug, p0-critical, A: data-sync, A: cloud-versioning
