### ISSUE TITLE
Status, push fail to recognize changes following `add` in subfolders.

### ISSUE THREAD

**Issue by kalingibbons** [iterative/dvc#5964] opened 2021-05-04 18:11 UTC
# Bug Report

## Description

On a new initialization, version control is only working on files in the root workspace directory, but not on any files within subdirectories. Tested with Google Drive as remote storage, as well as a local folder.

### Reproduce

```shell
> dvc init

Initialized DVC repository.

You can now commit the changes to git.

+---------------------------------------------------------------------+
|                                                                     |
|        DVC has enabled anonymous aggregate usage analytics.         |
|     Read the analytics documentation (and how to opt-out) here:     |
|             <https://dvc.org/doc/user-guide/analytics>              |
|                                                                     |
+---------------------------------------------------------------------+

What's next?
------------
- Check out the documentation: <https://dvc.org/doc>
- Get help and share ideas: <https://dvc.org/chat>
- Star us on GitHub: <https://github.com/iterative/dvc>
```

```shell
> dvc remote add --default google-drive gdrive://<private>/<private>

Setting 'google-drive' as a default remote.
```

```shell
> dvc remote modify google-drive gdrive_client_id <private>
```

```shell
> dvc remote modify google-drive gdrive_client_secret <private>
```

```shell
> dvc add data/external/stanford

Computing md5 for a large file 'data\external\stanford\train.tar.gz'. This is only done once.
100% Add|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|1/1 [00:15, 15.22s/file]
To track the changes with git, run:

        git add 'data\external\stanford.dvc'
```

```shell
> dvc status

There are no data or pipelines tracked in this project yet.
See <https://dvc.org/doc/start> to get started!
```

```shell
> dvc push

Everything is up to date.
```

### Expected

Actually backing up the data to the remote storage.

### Environment information

**Output of `dvc doctor`:**

DVC version: 2.0.18 (conda)
---------------------------------
Platform: Python 3.9.2 on Windows-10-10.0.17763-SP0
Supports: gdrive, http, https
Cache types: hardlink, symlink
Cache directory: NTFS on C:\
Caches: local
Remotes: gdrive
Workspace directory: NTFS on C:\
Repo: dvc, git
```console
$ dvc doctor
```

**Additional Information (if any):**
![image](https://user-images.githubusercontent.com/11838956/117046658-2fcaea80-acce-11eb-8848-923bfc58e9d1.png)

**Comment by efiop** [comment] 2021-05-04 18:18
Hi @kalingibbons . Is data/external/stanford or any parent in it gitignored as a whole? If it is, then it is the problem as dvc doesn't walk into gitignored directories, so it can't see `standford.dvc` file.

**Comment by dberenbaum** [comment] 2021-05-04 18:23
@efiop Should `dvc add` to a gitignored path be allowed?

**Comment by kalingibbons** [comment] 2021-05-04 18:31
![image](https://user-images.githubusercontent.com/11838956/117051396-ba621880-acd3-11eb-8bbd-b509db86351c.png)

Oh it was setup by pyscaffold originally, so there's quite a few ignores in there. I've got numerous projects using the pyscaffold/dvc setup, and I hadn't run into this issue before. I guess I'll have to compare the checksums to see if I've only been partially backing up the data in those other projects!

For the image, there's some breadcrumbs near the tabs showing which .gitignore is referenced.

**Comment by kalingibbons** [comment] 2021-05-04 18:35
All the green highlighting in the file explorer on the previous comment should mean that git can see the directory and files, so I don't think this is set up differently from my other projects. 

Also, thanks for the fast responses @efiop and @dberenbaum.

**Comment by kalingibbons** [comment] 2021-05-04 18:44
Got it. That repo was set up using PyScaffold 4.0rc2, which had the `data/x/` ignores instead of `data/x` versions. 

Can you point me out to the earliest point in the onboarding documentation that mentions that limitation? I spent a couple of hours trying to self-debug before opening this issue, and I would like to bookmark the doc page for next time.

**Comment by pmrowla** [comment] 2021-05-05 03:38
> Should `dvc add` to a gitignored path be allowed?

@dberenbaum it's no longer allowed after https://github.com/iterative/dvc/pull/5907

**Comment by kalingibbons** [comment] 2021-05-15 05:21
Alright now I'm trying to bring in a dataset from a freshly cloned repo and running into more false positives on the gitignores, and I would say this behavior is related: 
![image](https://user-images.githubusercontent.com/11838956/118348890-76101d00-b50a-11eb-8577-31688abb9c6a.png)

How is DVC checking these .gitignore files? It seems like it's breaking out of the recursion too early, or isn't recognizing the negation statements?

Let me know if I need to create a new issue for false positives on the ignore checks @efiop.

**Comment by pmrowla** [comment] 2021-05-15 08:17
@kalingibbons do you have other `.gitignore`s in the parent directories there? I'm unable to reproduce your issue in master or the latest DVC release (2.1.0)

```
$ tree
.
└── subdir
    ├── data.xml
    ├── data.xml.dvc
    ├── foo
    └── foo.dvc

1 directory, 4 files

$ cat subdir/.gitignore
*
!*.dvc

$ cat .gitignore
cat: .gitignore: No such file or directory

$ git check-ignore subdir/*
subdir/data.xml
subdir/foo

$ dvc check-ignore subdir/*

$ dvc update

$ cat subdir/data.xml.dvc
md5: 12fdbcb77dc0329dc72aa13f11b201fb
frozen: true
deps:
- path: data/data.xml
  repo:
    url: git@github.com:iterative/example-get-started
    rev_lock: a4046f6d3d954663f1d8a8d9812b61121e14d996
outs:
- md5: a304afb96060aad90176268345e10355
  size: 37891850
  path: data.xml

$ dvc update ./subdir/data.xml.dvc
'subdir/data.xml.dvc' didn't change, skipping
```

**Comment by kalingibbons** [comment] 2021-05-16 17:15
*I'm on vacation until the 20th, so my responses will be intermittent.*

@pmrowla Yes, it's actually the same structure from the previous screenshots, I had just cloned everything to my laptop before heading out for a vacation. I've recreated some of your steps, although I'm on Windows. I didn't have DVC version pinned for this conda environment, so the laptop is now on the 2.1.0 version.

Sorry, `tree` would be a bit too large in this project. I can work on cloning into a second folder and deleting extraneous stuff for a better minimal example if we don't get this figured out:

```
PS> conda list dvc
# packages in environment at C:\Users\kalin\Miniconda3\envs\autosegment:
#
# Name                    Version                   Build  Channel
dvc                       2.1.0            py37h03978a9_0    conda-forge
dvc-gdrive                2.1.0            py37h03978a9_0    conda-forge

```
```
PS> ls

   Directory: .

.dvc                                 .vscode
configs                              data
docs                                 models
notebooks                            references
reports                              scratch
scripts                              src
tests                                working
working_old                          .coveragerc
.dvcignore                           .gitignore
.isort.cfg                           .pre-commit-config.yaml
.readthedocs.yml                     AUTHORS.md
CHANGELOG.md                         environment.lock.yml
environment.yml                      LICENSE.txt
pyproject.toml                       README.md
setup.cfg                            setup.py
tox.ini

```
```
PS> cat .gitignore
# Temporary and binary files
**/variables.data.*
**/variables.index
*~
*.py[cod]
*.so
*.cfg
!.isort.cfg
!setup.cfg
*.orig
*.log
*.pot
__pycache__/*
.cache/*
.*.swp
*/.ipynb_checkpoints/*
.DS_Store

# Project files
.ropeproject
.project
.pydevproject
.settings
.idea
.vscode
tags

# Package files
*.egg
*.eggs/
.installed.cfg
*.egg-info

# Unittest and coverage
htmlcov/*
.coverage
.coverage.*
.tox
junit*.xml
coverage.xml
.pytest_cache/

# Build and docs folder/files
build/*
dist/*
sdist/*
docs/api/*
docs/_rst/*
docs/_build/*
cover/*
MANIFEST

# Per-project virtualenvs
.venv*/
.conda*/

```
```
PS> ls data

   Directory: .\automesh\data

external      interim       preprocessed  raw           .gitignore

PS> cat data/.gitignore
# Ignore everything in this directory
*
# Except this file and .gitignore in sub directories
!.gitignore
!raw
!external
!preprocessed
!interim

```
```
PS> ls .\data\preprocessed\

   Directory: .\data\preprocessed

imorphics               training_original       .gitignore
imorphics.dvc           training_original.dvc

PS> cat .\data\preprocessed\.gitignore
# Ignore everything in this directory
*
# Except this file
!.gitignore
!*.dvc
/training_original
/training_original

```
```
PS> git check-ignore .\data\preprocessed\*

```
```
PS> dvc check-ignore .\data\preprocessed\*

```
```
PS> dvc update .\data\preprocessed\imorphics.dvc
ERROR: failed update data - '.\data\preprocessed\imorphics.dvc' is git-ignored.

```

**Comment by kalingibbons** [comment] 2021-05-16 17:18
I suspect you'll ask for this, next:

```
PS> dvc update --verbose .\data\preprocessed\imorphics.dvc
2021-05-16 13:17:33,852 DEBUG: Check for update is enabled.
2021-05-16 13:17:33,889 DEBUG: Trying to spawn '['daemon', '-q', 'updater']'
2021-05-16 13:17:33,953 DEBUG: Spawned '['daemon', '-q', 'updater']'
2021-05-16 13:17:34,005 ERROR: failed update data - '.\data\preprocessed\imorphics.dvc' is git-ignored.
------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\kalin\Miniconda3\envs\autosegment\lib\site-packages\dvc\command\update.py", line 21, in run
    jobs=self.args.jobs,
  File "C:\Users\kalin\Miniconda3\envs\autosegment\lib\site-packages\dvc\repo\__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "C:\Users\kalin\Miniconda3\envs\autosegment\lib\site-packages\dvc\repo\update.py", line 31, in update
    stages.update(self.stage.collect(target, recursive=recursive))
  File "C:\Users\kalin\Miniconda3\envs\autosegment\lib\site-packages\dvc\repo\stage.py", line 362, in collect
    stages = self.from_target(target, accept_group=accept_group, glob=glob)
  File "C:\Users\kalin\Miniconda3\envs\autosegment\lib\site-packages\dvc\repo\stage.py", line 201, in from_target
    path=path, name=name, accept_group=accept_group, glob=glob,
  File "C:\Users\kalin\Miniconda3\envs\autosegment\lib\site-packages\dvc\repo\stage.py", line 272, in load_all
    stages = dvcfile.stages  # type: ignore
  File "C:\Users\kalin\Miniconda3\envs\autosegment\lib\site-packages\dvc\dvcfile.py", line 175, in stages
    data, raw = self._load()
  File "C:\Users\kalin\Miniconda3\envs\autosegment\lib\site-packages\dvc\dvcfile.py", line 139, in _load
    self._check_gitignored()
  File "C:\Users\kalin\Miniconda3\envs\autosegment\lib\site-packages\dvc\dvcfile.py", line 123, in _check_gitignored
    raise FileIsGitIgnored(self.path)
dvc.dvcfile.FileIsGitIgnored: '.\data\preprocessed\imorphics.dvc' is git-ignored.
------------------------------------------------------------
2021-05-16 13:17:34,009 DEBUG: Analytics is enabled.
2021-05-16 13:17:34,009 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', 'C:\\Users\\kalin\\AppData\\Local\\Temp\\tmpefwbvw4r']'
2021-05-16 13:17:34,089 DEBUG: Spawned '['daemon', '-q', 'analytics', 'C:\\Users\\kalin\\AppData\\Local\\Temp\\tmpefwbvw4r']'
```

**Comment by pmrowla** [comment] 2021-05-17 00:54
Ok, your problem is a duplicate of this issue: https://github.com/iterative/dvc/issues/5748

It will need to be fixed upstream in dulwich

**Closed** 2022-09-22 20:39 UTC
