### ISSUE TITLE
`repro --downstream` with multiple targets should still honour dependencies

### ISSUE THREAD

**Issue by z0u** [iterative/dvc#3556] opened 2020-03-31 05:36 UTC
DVC 0.91.0, installed with pipx on Ubuntu 18.04 with Python 3.6.9

The `repro` command seems to ignore dependency order when multiple targets are specified. For example, if I'm doing transfer learning from model `A` to model `B`, then training stage `B` depends on `A`:

```
01-prep-a            01-prep-b
    *    ****            *
    *        ****        *
    *            ****    *
02-train-a ********* 02-train-b
```

When reproducing just the models, I would like to run:

```
dvc repro -f --downstream 02-train-*
```

But sometimes, this causes `02-train-B` to run before `02-train-A`. Perhaps it depends on the order that results when the shell expands the wildcard.

I think inter-stage dependencies should resolved by DVC when multiple targets are given.

**Comment by efiop** [comment] 2020-03-31 13:26
Hi @z0u !

So `A` and `B` somehow depend on each other, right? In that case, it seems it wont make a difference in `-f` case, as all of them and their dependencies will be reproduced anyway. Or do you mean that it would be nice to avoid reproducing common deps multiple times in that scenario?

**Comment by z0u** [comment] 2020-03-31 22:17
Hi @efiop ,

Sorry for not being clear about the dependencies. Yep, `B` depends on `A`. So what I expect to happen is: `A` always executes before `B`.

|Command|Effect|
|---|---|
|`dvc repro`|Runs 01-prep-A, 01-prep-B, 02-train-A, 02-train-B|
|`dvc repro -f 02-train-A`|Runs 01-prep-A, 01-prep-B, 02-train-A|
|`dvc repro -f --downstream 02-train-A`|Runs 02-train-A, 02-train-B|
|`dvc repro -f --downstream 02-train-B 02-train-A`|Runs 02-train-A, 02-train-B|
|`dvc repro -sf 02-train-*`|Runs 02-train-A, 02-train-B|

**Comment by efiop** [comment] 2020-04-01 11:21
Got it @z0u . So to implement it we will need to pass all targets in https://github.com/iterative/dvc/blob/0.91.3/dvc/command/repro.py#L41 and then properly collect them and put them into the common stages to run in https://github.com/iterative/dvc/blob/0.91.3/dvc/repo/reproduce.py#L53 . Unfortunately we will not be able to get to implementing this right away ourselves, but we would definitely help out if anyone else is interested in contributing a PR :slightly_smiling_face:

**Comment by nik123** [comment] 2020-06-30 16:03
I don't think issue is reproducable in latest releases of dvc (at least in commit `0275a0d8`).

If stages  are stored in dvc.yaml then output of `dvc repro -f --downstream 02-train-*` is:

```
ERROR: "Stage '02-train-*' not found inside 'dvc.yaml' file"
```

If stages are stored in old-fashioned way (i.e. dvc files), then output of  `dvc repro -f --downstream 02-train-*` is:

```
ERROR: 'dvc.yaml' does not exist.
```

**P.S.:** it seems that it is impossible to use wildcards with `dvc repro` in the latest releases. Not sure if it is a bug though.

**Comment by efiop** [comment] 2020-06-30 16:41
@nik123

dvc itself doesn't evaluate the wildcards and never did - your shell does that and then passes it to dvc. What shell do you use? And do you have our completion scripts installed? If so, could you check that you have the latest ones?

**Comment by nik123** [comment] 2020-06-30 17:00
@efiop , I use standard Ubuntu intepreter (which is bash AFAIK). `bash --version` gives me: `4.4.20(1)-release (x86_64-pc-linux-gnu)`

I've reinstalled latest version (1.1.1) via pip (`pip install dvc`) and rerun `dvc repro -f --downstream 02-train-*`. Now I get the same error for dvc.yaml file but error disappeared with old-fashioned dvc files.

**Comment by skshetry** [comment] 2020-06-30 17:04
@nik123, why are you moving back-and-forth with different formats?

Also, when you are using `02-train-*`, there's no `.dvc` files, so it's complaining as no file exists with that matching glob.
`dvc repro` cannot understand globs right now. Regarding when it was `.dvc` files, it was getting interpreted by your shell
and the expanded version was being sent to `dvc`. Now that you don't have any files matching the glob, it is sent as-is to `dvc`.

**Comment by nik123** [comment] 2020-06-30 17:16
> @nik123, why are you moving back-and-forth with different formats?

Once I failed to reproduce the issue with new dvc.yaml format, I've tried to reproduce it with dvc-files. That's the only reason.

> Also, when you are using `02-train-*`, there's no `.dvc` files, so it's complaining as no file exists with that matching glob.
> `dvc repro` cannot understand globs right now. Regarding when it was `.dvc` files, it was getting interpreted by your shell
> and the expanded version was being sent to `dvc`. Now that you don't have any files matching the glob, it is sent as-is to `dvc`.

@skshetry I've checked it with debugger and it seems you are absolutely right. Thanks for the help!

**P.S.:** I don't know what are the plans for old format support but it will  probably  be canceled at some point. That means that `dvc repro -f --downstream 02-train-*` probably won't be the valid command and it raises the question if this issue should be fixed at all.

**Comment by efiop** [comment] 2020-06-30 17:22
> P.S.: I don't know what are the plans for old format support but it will probably be canceled at some point. That means that dvc repro -f --downstream 02-train-* probably won't be the valid command and it raises the question if this issue should be fixed at all.

@nik123 It will be valid with our completion scripts, we just didn't get to working on that feature yet.

**Comment by z0u** [comment] 2020-07-02 00:00
Hi! Thanks for continuing to look into this, but I think the current discussion misses the point of this issue. The wildcard was just a concise way to describe the problem. The point is: `02-train-B` should not run before `02-train-A` if both are specified. The corresponding example in the new syntax is (I think; untested):

```
dvc repro -f --downstream 02-train-B 02-train-A
```

Which should execute `02-train-A` and then `02-train-B`.

**Comment by pmrowla** [comment] 2021-11-23 07:06
Another user is running into this issue, in the current DVC release the issue here is unrelated to `-f/--force`. The problem is just that `--downstream` does not work when multiple targets are specified.

Given the following pipeline and dag:
```
stages:
  a:
    cmd: echo a > a
    outs:
    - a
  b:
    cmd: echo b > b
    outs:
    - b
  c:
    cmd: echo c > c
    deps:
    - a
    - b
    outs:
    - c
```
```
+---+     +---+
| a |     | b |
+---+     +---+
     *    *
      *  *
       **
     +---+
     | c |
     +---+
```

In 2.8.x, if you try `dvc repro --downstream a b`, DVC will run either `a` or `b` first (but not both), and then immediately try to run the downstream `c` (instead of also running the remaining dependency stage):

```
$ dvc repro -v --downstream a b
...
2021-11-23 16:02:34,751 DEBUG: Assuming 'a' to be a stage inside 'dvc.yaml'
2021-11-23 16:02:34,783 DEBUG: Lockfile for 'dvc.yaml' not found
2021-11-23 16:02:34,784 DEBUG: Assuming 'b' to be a stage inside 'dvc.yaml'
2021-11-23 16:02:34,788 DEBUG: Lockfile for 'dvc.yaml' not found
2021-11-23 16:02:34,791 DEBUG: Lockfile for 'dvc.yaml' not found
2021-11-23 16:02:35,074 DEBUG: Output 'b' of stage: 'b' changed because it is 'deleted'
2021-11-23 16:02:35,075 DEBUG: stage: 'b' changed.
2021-11-23 16:02:35,077 DEBUG: Removing output 'b' of stage: 'b'.
2021-11-23 16:02:35,077 DEBUG: Removing '/Users/pmrowla/git/scratch/glob-downstream/b'
Running stage 'b':
> echo b > b
...
2021-11-23 16:02:35,129 DEBUG: stage: 'b' was reproduced
Generating lock file 'dvc.lock'
Updating lock file 'dvc.lock'

2021-11-23 16:02:35,137 DEBUG: Dependency 'a' of stage: 'c' changed because it is 'deleted'.
2021-11-23 16:02:35,138 DEBUG: stage: 'c' changed.
2021-11-23 16:02:35,139 DEBUG: Removing output 'c' of stage: 'c'.
2021-11-23 16:02:35,140 DEBUG: Removing '/Users/pmrowla/git/scratch/glob-downstream/c'
2021-11-23 16:02:35,144 ERROR: failed to reproduce 'dvc.yaml': [Errno 2] No such file or directory: '/Users/pmrowla/git/scratch/glob-downstream/a'
------------------------------------------------------------
Traceback (most recent call last):
...
FileNotFoundError: [Errno 2] No such file or directory: '/Users/pmrowla/git/scratch/glob-downstream/a'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
...
  File "/Users/pmrowla/git/dvc/dvc/repo/reproduce.py", line 221, in _reproduce_stages
    raise ReproductionError(stage.relpath) from exc
dvc.exceptions.ReproductionError: failed to reproduce 'dvc.yaml'
------------------------------------------------------------
```

**Comment by pmrowla** [comment] 2021-11-23 07:11
I think given the way we now collect stages and pass the full dependency graph in repro, this is a bug regarding `--downstream` behavior.

There is minor expected behavior question in that if I start with a fresh repo and do:
```
dvc repro --downstream a
```
The command will currently fail when trying to run `c`, since `b` has never been run at all. I think the failure in this case could be considered expected behavior.

But for the case where the user does specify all of the required upstream dependencies in the target stages (along with `--downstream`), the repro command should succeed.

**Closed** 2024-03-03 21:37 UTC
Labels: bug, p2-medium
