### ISSUE TITLE
exp apply: try to apply from other commits

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#8481] opened 2022-10-27 12:54 UTC
`dvc exp apply` will fail if run from a commit that isn't the experiment baseline. Instead, it should:

1. Attempt to apply on top of any commit.
2. Fail and rollback if there is a conflict.

**Comment by mattseddon** [comment] 2022-12-02 00:31
@dberenbaum we are running into this with the extension. See https://github.com/iterative/vscode-dvc/issues/2855#issuecomment-1330453162

**Comment by dberenbaum** [comment] 2022-12-02 18:22
@mattseddon FYI, `dvc exp apply` has always been limited to the current commit and it's expected and documented behavior (see https://dvc.org/doc/command-reference/exp/apply#description). I wonder if this got lost when the extension went from showing 1 commit to 3 commits. There could be other places this might cause issues. Hopefully, we can address this soon so it won't be a problem regardless, but it's not planned this sprint.

**Comment by dberenbaum** [comment] 2022-12-06 18:29
@shcheklein You mean: apply exp1 == workspace looks identical to exp1 end state?

**Comment by shcheklein** [comment] 2022-12-07 02:47
@dberenbaum yep.

**Comment by dberenbaum** [comment] 2022-12-07 17:01
@dberenbaum do we know why we have this limitation? (what is the core reason). I'm not sure I understand what is the difference between commits tbh.

_Originally posted by @shcheklein in https://github.com/iterative/vscode-dvc/issues/2855#issuecomment-1335875361_
      

@pmrowla Do you have any insight here?

**Comment by pmrowla** [comment] 2022-12-09 00:37
Finished experiments are an actual commit. Doing `exp apply my-exp` is the same as `git merge --no-commit my-exp`. And supporting merges into any arbitrary commit increases the chances of encountering merge conflicts. The original behavior just limits `apply` to the one commit we know will not have conflicts (as long as the user does not have additional uncommitted changes), since the exp commit is a direct descendant of the experiment baseline.

There's nothing preventing us from trying the merge onto other commits. When we did the original implementation we decided that the current limited implementation was acceptable and that it was not worth increasing the complexity/scope of `exp apply` at that time.

**Comment by pmrowla** [comment] 2022-12-09 00:43
There is also https://github.com/iterative/dvc/issues/5782, where we have discussed supporting rebasing experiments. So in scenarios where the user has added new commits to their main branch we could just rebase experiments so the baseline is the new HEAD. At that point, `exp apply` (onto the new head) would work as expected even with the current `apply` implementation

**Comment by dberenbaum** [comment] 2022-12-09 13:18
Discussed with @shcheklein that the prerequisite for any of this would be https://github.com/iterative/dvc/issues/7955. We can try do any operation on top of any commit as long as it's easy to get back if the user isn't happy with the result.

**Comment by dberenbaum** [comment] 2022-12-22 16:30
@pmrowla Assuming we address #7955, what do you think about the suggestion that exp apply should ignore/overwrite dirty changes and make the workspace identical to the experiment state?

**Comment by pmrowla** [comment] 2022-12-26 07:57
> @pmrowla Assuming we address #7955, what do you think about the suggestion that exp apply should ignore/overwrite dirty changes and make the workspace identical to the experiment state?

This is doable, but one question would be how to handle untracked files? Untracked files may conflict with the experiment (since they may be a non-dvc dependency that is untracked in the workspace but forced to be tracked in the experiment)

**Comment by shcheklein** [comment] 2022-12-26 17:27
@pmrowla qq - how do we handle them now?

>  but forced to be tracked in the experiment

could you clarify please?

**Comment by pmrowla** [comment] 2022-12-27 02:06
> @pmrowla qq - how do we handle them now?
> 
> > but forced to be tracked in the experiment
> 
> could you clarify please?

Anything defined in a `dvc.yaml` stage's `deps` that is not a DVC tracked file (either another stage output or `dvc add`ed data) gets force added to git on `exp run` so that we can always reproduce the entire experiment state. In most cases, non-dvc `deps` are already git tracked files and this behavior doesn't matter. But in some cases, a user may have `deps` that are not git or DVC tracked.

My understanding of the proposed changes here are to handle #7955 (and preserve the user's workspace before applying via `git stash --include-untracked` so the user can recover it), and then have `exp apply` forcefully apply exp changes to the workspace state (since we are assuming the user could then recover/undo this with `git stash pop`). But when dealing with the untracked deps case, I think the recovery `git stash pop` will fail due to conflicts with untracked files. Normally, git would generate merge conflict markers, but does not do this for untracked files. I think the way to recover from this situation would be to just remove the untracked deps before popping the recovery stash, but this may not be clear to the user
```
rm <untracked-dep-file(s)>
git stash pop
```

**Comment by dberenbaum** [comment] 2022-12-27 18:39
@pmrowla I think it's okay (and maybe preferable) if #7955 is a dvc command (`dvc exp revert` or similar) instead of having to rely on `git stash pop`. That gives more control for how dvc can handle recovery, and it keeps the user's stash clean.

**Comment by pmrowla** [comment] 2023-02-09 05:10
One issue with preserving the changes from an apply and then adding something like `dvc exp revert` is that `revert` is also a potentially destructive command.

Essentially, if we just keep the last workspace state prior to `exp apply` stashed somewhere, and then the user does other things in the git repo, and then runs `dvc exp revert`, we would end up forcefully dropping any of the user's uncommitted changes and restoring our stashed state.

Is there a fixed set of conditions in which `exp revert` is allowed to be used?
- Can we drop the stashed state (and disallow `dvc revert`) as soon as the user does any other `dvc` command in the workspace after `dvc exp apply`?
- Should we only allow `revert` when the git HEAD matches the HEAD from when the user did `exp apply`? (This does not prevent all the scenarios in which `revert` would be destructive, but I'm not sure what else we can do here)

**Comment by dberenbaum** [comment] 2023-02-09 17:59
I think `dvc exp revert` should be described as `revert to the state prior to the last call to either 'dvc exp apply' or 'dvc exp revert'`. In other words:

* It should be possible to undo `dvc exp revert`.
* It should do the inverse of `dvc exp apply`. Let's say I started on `ref1` with dirty changes and do `dvc exp apply ref2`. I then make other changes and maybe even make more commits. When I do `dvc exp revert`, it should stash the dirty changes I have from `ref2`, checkout `ref1`, and apply the dirty changes I had from `ref1`. If I do `dvc exp revert` again, it should stash my changes again, checkout `ref2`, and apply the dirty changes I had from `ref2`.
* It should always keep the stashed state from the last call to either `dvc exp apply` or `dvc exp revert`. That way, there's always a way to undo/recover even if it's complicated.

**Comment by pmrowla** [comment] 2023-02-10 05:49
I think that may be getting to be unnecessarily complex and seems like it will be prone to the same kind of bugs we already have with `exp apply`, where we end up losing or modifying things that we shouldn't upon multiple subsequent `exp apply/exp revert` calls.

I'm wondering if what we really want is to drop `exp apply` entirely in favor of something more like how github's CLI handles [`gh pr checkout`](https://cli.github.com/manual/gh_pr_checkout). What github does is just create a regular local branch of their custom pull request ref, and then they do a regular `git checkout` of that local branch. If the checkout would fail (due to conflicts w/their workspace, or the branch already existing, and so on), it's on the user to resolve it themselves (whether that means using `git stash` to stash their conflicting workspace changes, or `gh pr checkout --force` to force overwrite the existing branch, etc). We could easily do the exact same thing with `dvc exp checkout`.

This does put more on the user, but it may also clarify & simplify things for the user as well. After `dvc exp checkout`, the user would then just use regular git commands and regular git workflows, whether thats using `git stash` to preserve workspace changes, or using `git switch`/`git checkout` to move between the checked-out exp branch and back to whatever branch they were on before they ran `exp checkout`.

This would also let us drop `exp apply` and `exp branch`, and potentially `exp push/pull` as well (in favor of just telling users to checkout the exp branch and then use regular git push/pull)

**Comment by dberenbaum** [comment] 2023-02-10 17:50
> I think that may be getting to be unnecessarily complex and seems like it will be prone to the same kind of bugs we already have with `exp apply`, where we end up losing or modifying things that we shouldn't upon multiple subsequent `exp apply/exp revert` calls.

👍  Yep, feels like it's getting complicated.

> This would also let us drop `exp apply` and `exp branch`, and potentially `exp push/pull` as well (in favor of just telling users to checkout the exp branch and then use regular git push/pull)

I have had the same thoughts many times (`dvc exp checkout`, getting rid of these commands) 😄 but I'm not so sure we should drop any of them.

I think we need to keep `dvc exp apply`. For the "happy path" of experimenting on the head commit, it feels like a useful lightweight operation as is. We still need:
* to fix #8674 
* some way to recover if we do anything unexpected. `dvc exp revert` might be too much, but we need to at least keep the stash somewhere and have a troubleshooting guide to explain how to recover if you overwrite something by accident.

Same for `dvc exp push/pull`. For a single experiment, branching makes sense, but to push a bunch of experiments, it would be nice to keep them as exp refs (it's easier and avoids polluting the remote repo). 

`exp branch` vs `exp checkout` feels like not much difference -- we can add a `exp branch --checkout` and modify the behavior to match whatever's missing (like auto-naming the branch if it's not provided).

**Comment by pmrowla** [comment] 2023-02-13 05:55
> For the "happy path" of experimenting on the head commit, it feels like a useful lightweight operation as is.

This is precisely what detached checkout is for in git. IMO something like `exp checkout --detach` makes it much clearer what is happening vs `exp apply`.

> some way to recover if we do anything unexpected.

The problem with `exp apply` as it current stands is that nothing it does is clearly defined (and the entire thing ends up being unexpected). With the way we modify untracked (or uncommitted) changes in the workspace, it's always on DVC to guess what the user actually wants us to do.

IMO it was probably better before when the default `exp apply` behavior was `--no-force`, and we would fail on any conflicts, because at least at that point it was obvious that `exp apply` could have negative side effects. The default behavior for a DVC command should not be potentially destructive (even when we think we know that the most common use case is going to be running the command with `-f/--force`)

Changing the behavior to be more analogous to CLI git (where `git checkout` only succeeds when there are no conflicting changes that would be overwritten) would force the user to be explicit (and avoids cases where DVC can do something unexpected).

**Comment by pmrowla** [comment] 2023-02-13 05:58
Either way, it sounds like what we should do for now is just merge https://github.com/iterative/dvc/pull/8994, which keeps the existing `exp apply` workflow, fixes the `git merge` related bugs (by no longer using merge) and at least gives us the ability to revert changes once we decide what `exp revert` should actually look like

**Comment by dberenbaum** [comment] 2023-02-14 20:46
@shcheklein @mattseddon There's a working implementation of this in #8994. I'd be curious to get other thoughts on whether it's useful.

For example, using https://github.com/iterative/vscode-dvc-demo, I can try to apply an experiment from before the DVCLive 2.0 changes on top of the most recent commit, but this will undo all the DVCLive 2.0 updates that were made in the subsequent commits:

```bash
# Checkout the commit before migrating to dvclive 2.0
$ git checkout 6375a

# Run an experiment
$ dvc exp run -S lr=0.001 -n old-exp

# Checkout the tip of the main branch 
$ git restore .
$ git checkout main

# Apply old-exp
$ dvc exp apply old-exp

# See that dvc.yaml loses all the changes made for DVCLive 2.0
$ git diff -- dvc.yaml
diff --git a/dvc.yaml b/dvc.yaml
index 7cf7e37..9e6294c 100644
--- a/dvc.yaml
+++ b/dvc.yaml
@@ -2,14 +2,14 @@ plots:
   - Accuracy:
       x: step
       y:
-        training/plots/metrics/train/acc.tsv: acc
-        training/plots/metrics/test/acc.tsv: acc
+        training/plots/metrics/train/acc.tsv: train/acc
+        training/plots/metrics/test/acc.tsv: test/acc
       y_label: accuracy
   - Loss:
       x: step
       y:
-        training/plots/metrics/train/loss.tsv: loss
-        training/plots/metrics/test/loss.tsv: loss
+        training/plots/metrics/train/loss.tsv: train/loss
+        training/plots/metrics/test/loss.tsv: test/loss
       y_label: loss
   - Confusion matrix:
       template: confusion
```

I think this is the "correct" behavior, but I'm not sure it's useful. It also may overwrite dirty changes (although we will now keep the stash to recover them), so I'm not sure whether it's worthwhile apply from commits other than the baseline.

I might still use `exp apply` from other commits and only selectively commit certain files like `params.yaml`, but at that point I might rather attempt a merge. On the other hand, a merge risks that `params.yaml` won't reflect the exact parameters of `old-exp`, so there's no perfect solution here.

**Comment by shcheklein** [comment] 2023-02-15 01:02
Dave, my assumption here that people will be doing commits with minor changes (up to even some hyper-parameters). In that case this limitation feels unexpected and artificial. As far as I understand we are generalizing this, no? I'm still not sureI understand why applying an experiment from a baseline only is something different / more easier to implement tbh. Or is your concern at this point is only from the product perspective? Like there is an argument could be made that even though we can do this and it's the same, etc, etc it doesn't mean we should still allow this in the product?

**Comment by pmrowla** [comment] 2023-02-15 02:26
The open PR removes the limitation of only being able to apply from the original baseline. What @dberenbaum is pointing out is that if you run an experiment A, and then make additional changes to files in your repo (and git commit them), and then do `exp apply A`, those additional changes will now be overwritten with the contents of `A`. And the question is now whether or not this is the expected behavior.

In regular git terms, if you consider this workflow:
```
$ echo 'foo: 1' > foo
$ echo 'bar: 1' > bar
$ git add; git commit
# main contains foo: 1, bar: 1

$ git checkout -b branch
$ echo 'foo: 2' > foo
$ git add; git commit
# branch contains foo: 2, bar 1

$ git checkout main
$ echo 'foo: 3' > foo
$ echo 'bar: 2' > bar
$ git add; git commit
$ echo 'foo: 4' > foo
$ git add; git commit
# main contains foo: 4, bar: 2
```
What is the expected result of `exp apply branch` now?

With the checkout-equivalent behavior in the open PR, we checkout the explicit state of everything in the experiment commit (in `branch` from this example), so the resulting workspace would contain `foo: 2, bar: 1`. Even though `bar` was not modified in the experiment/branch commit, the state of `bar` in that commit contains `1`. After `apply`, the intermediate `main` commit which modified `bar` to contain `2` is ignored, and we overwrite `bar` to contain the state from `branch`.

The alternative would be to go back to using `git merge`. In this case, when we try `git merge branch`, we will get conflicts in `foo`, but the intermediate changes to `bar` would be preserved. So the result of `apply` would be `foo: conflicted, bar: 2`. At this point, DVC has to determine whether or not to force overwriting `foo` (the previous default) or to fail (via `--no-force`). However, using `merge` here introduces other issues:
- DVC is less easy to use in CI (since merge operations require fetch-depth > 0)
- The problem from https://github.com/iterative/dvc/issues/8764. Going back to the example, if `bar` is actually a git-tracked params file, the result of `exp apply` after the merge workflow is wrong. After merge-based `apply`, the workspace state would now imply "the applied experiment contained params `bar: 2` and resulted in output `foo: 2`", when in fact the experiment that was run was actually "params `bar: 1` resulted in output `foo: 2`".

**Comment by pmrowla** [comment] 2023-02-15 02:30
One of the reasons for requiring `exp apply` only be run from the original baseline was to try and avoid this type of scenario, where the expected result is ambiguous.

When running from the original baseline, #8764 is an outright bug, and the expected result is always `foo: 2, bar: 1` (since both the baseline and experiment contained `bar: 1`, and any uncommitted workspace changes should be dropped in favor of `bar: 1`)

But when allowing `apply` from any commit, it is no longer clear whether the user wants `bar` from  their current commit, or `bar` from the experiment commit we are trying to apply.

**Comment by pmrowla** [comment] 2023-02-15 02:45
And just as a further example, this becomes even more ambiguous/problematic when you consider that `bar` could be git-tracked code (that is run in a pipeline stage). What if the user actually wants to just `apply` the params values used in experiment A, and then run the latest version of their pipeline from main. In this case, the user does not want the equivalent of merge or checkout, what they really want is rebase (https://github.com/iterative/dvc/issues/5782)

**Comment by shcheklein** [comment] 2023-02-15 03:08
Thanks @pmrowla ! Here are my thoughts on this (from briefly reading the latest update, I might have missed something, sorry about that): 

> And the question is now whether or not this is the expected behavior.

Yes, and my answer was yes. Same question applies to the baseline experiments (not Git mechanics, but from the user perspective), unless I'm missing something. What should I do to the changes in the workspace when I'm applying an experiment? Should I merge them, stash them? 

> and any uncommitted workspace changes should be dropped in favor of bar: 1)
>  What if the user actually wants to just apply the params values used in experiment A, and then run the latest version of their pipeline from main

This is not clear why and how this is different from committed changes from the users perspective. I would try to think from the user perspective, not branches, merges, commits, etc.

> But when allowing apply from any commit, it is no longer clear whether the user wants bar from their current commit, or bar from the experiment commit we are trying to apply.

No difference here - we want `bar from the experiment commit we are trying to apply.`. Since that's exactly what it does already for the baseline. We don't want to have (at least for now) two different mechanics for this, etc. It well might turn out we can't fit all the expectations, but it feels it's a simpler model for now.

>  What if the user actually wants to just apply the params values used in experiment A, and then run the latest version of their pipeline from main

Same question. How is it different from the current "baseline" approach? It has exactly the same issue I think.

----

My logic (high level) stems from a few assumptions:

- An experiment is a snapshot of all the things - params, code, data.
- We can't provide a granular way to apply some of the things and not apply others. We don't know (at least yet) what exactly would user want to apply. Neither we don't want to make a granular default (only params).
- Merging is complicated and can lead to unexpected results from the user perspective.
- It's way better to have the same mechanics for all experiments. No special cases. It's easier to explain, less confusion (hopefully).

**Comment by pmrowla** [comment] 2023-02-15 03:27
> What should I do to the changes in the workspace when I'm applying an experiment? Should I merge them, stash them?

IMO users should be stashing them themselves, and using git themselves for almost all of these scenarios, but that's already been discussed.

With the open PR, we stash the changes for the user, and at least provide a way for them to recover the changes if `exp apply` turns out to not be what they wanted (this will need to be documented)

> No difference here - we want bar from the experiment commit we are trying to apply.. Since that's exactly what it does already for the baseline
> Same question. How is it different from the current "baseline" approach? It has exactly the same issue I think.

The open PR just gives you the behavior as if you ran it from the baseline (regardless of whether or not you are actually on the original baseline commit). It sounds like this is acceptable, so I think we can just merge the open PR.

> We can't provide a granular way to apply some of the things and not apply others. We don't know (at least yet) what exactly would user want to apply. Neither we don't want to make a granular default (only params).

Right, but git does provide the way to do these things (which is why I'd still prefer dropping `exp apply` in favor of an explicit `git checkout` equivalent + documenting the git workflows to handle these various scenarios)

**Comment by daavoo** [comment] 2023-02-15 11:46
> Right, but git does provide the way to do these things, which is why I'd still prefer dropping exp apply in favor of an explicit git checkout equivalent + documenting the git workflows to handle these various scenarios (but I realize I'm biased as someone that uses git regularly)

I am not git savvy but still, from my user perspective, I would also prefer this.

It does put more work on the user, but IMO it's for a good reason. 
Users do need to be aware of all the different scenarios discussed above and figure out what they want on a case-by-case basis. 

By expecting users to blindly trust in the assumptions we made for `exp apply`, we are potentially introducing quite more problems/unexpected results than benefits. We are not even discussing git-tracked results of an execution like `dvc.lock` files.

IMO, we need **good** docs for the different git workflows (including `exp branch`) that users can use to handle an experiment and let them decide.

**Comment by dberenbaum** [comment] 2023-02-16 18:43
>     * It's way better to have the same mechanics for all experiments. No special cases. It's easier to explain, less confusion (hopefully).

I agree and lean towards merging as is for this reason. I think the `checkout` is less complicated than the `merge` behavior.

@pmrowla @daavoo As long as it is transparent, and we document that the experiments are also commits that can be merged, is there a reason not to have it? I would still use it for the "happy path" of switching between different sets of parameters and find it less work and mental load than having to do `git stash && git checkout && git reset && dvc checkout`. As a user, I personally wouldn't be happy about deprecating it (usage looks to be not that high but more than `exp branch`).

> Like there is an argument could be made that even though we can do this and it's the same, etc, etc it doesn't mean we should still allow this in the product?

Yes, the workflow I mentioned above using the vscode-dvc-demo repo reflects what I think is a common pattern:
1. Make some parameter changes or other minor changes in an experiment.
2. Do some other unrelated commits.
3. Apply the experiment with the intent of getting the parameters and other changes from that experiment, but without losing the updates made in the unrelated commits.

The difference with the baseline commit is that there is no risk of losing the work from unrelated commits in between.

**Closed** 2023-02-20 05:36 UTC
Labels: p1-important, product, A: experiments
