### ISSUE TITLE
push: SFTP Backend Hangs Querying Cache After Connecting

### ISSUE THREAD

**Issue by rothn** [iterative/dvc#5759] opened 2021-04-02 00:53 UTC
# Bug Report

## Description

The SFTP backend connects to the SFTP server several times, but then hangs at "0% Querying Cache"

### Reproduce

1. dvc init
2. Copy dataset.zip to the directory
3. dvc add dataset.zip
4. dvc remote add some-sftp ssh://sftp.somesite.com/dvc/
5. dvc remote modify some-sftp user SOME_USERNAME
6. dvc remote modify --local some-sftp SOME_PASSWORD
7. dvc push

Note that sftp.somesite.com does not allow users to create a shell and log in to an operating system. If you try, you will get this message:
```
PTY allocation request failed on channel 0
shell request failed on channel 0
```

### Expected

DVC should push the files to the remote

### Verbose Output

```
$ dvc push -vv
2021-04-01 19:47:45,788 TRACE: Namespace(cprofile=False, cprofile_dump=None, pdb=False, instrument=False, instrument_open=False, quiet=0, verbose=2, version=None, cd='.', cmd='push', jobs=None, targets=[], remote=None, all_branches=False, all_tags=False, all_commits=False, with_deps=False, recursive=False, run_cache=False, glob=False, func=<class 'dvc.command.data_sync.CmdDataPush'>)
2021-04-01 19:47:45,877 DEBUG: Check for update is enabled.
2021-04-01 19:47:45,929 TRACE: Assuming '/Users/nicholasroth/<CENSORED>/.dvc/cache/65/33ec4d541e9aebc13e7bf7cc0ebafe.dir' is unchanged since it is read-only
2021-04-01 19:47:45,930 TRACE: Assuming '/Users/nicholasroth/<CENSORED>/.dvc/cache/65/33ec4d541e9aebc13e7bf7cc0ebafe.dir' is unchanged since it is read-only
2021-04-01 19:47:46,029 DEBUG: Preparing to upload data to 'ssh://<CENSORED>@<CENSORED>.com/kungfu/dvc/'
2021-04-01 19:47:46,029 DEBUG: Preparing to collect status from ssh://<CENSORED>@<CENSORED>.com/kungfu/dvc/
2021-04-01 19:47:46,029 DEBUG: Collecting information from local cache...
2021-04-01 19:47:46,030 TRACE: Assuming '/Users/nicholasroth/<CENSORED>/.dvc/cache/ac/ff2e4b73c088841b6c1a82171974ae' is unchanged since it is read-only
2021-04-01 19:47:46,030 TRACE: Assuming '/Users/nicholasroth/<CENSORED>/.dvc/cache/f8/9ca37ae4c8fbe29af937c5a04762f4' is unchanged since it is read-only
2021-04-01 19:47:46,031 TRACE: Assuming '/Users/nicholasroth/<CENSORED>/.dvc/cache/6d/96fea844a1a5ed9c3a41d4acdfd433' is unchanged since it is read-only
2021-04-01 19:47:46,031 TRACE: Assuming '/Users/nicholasroth/<CENSORED>/.dvc/cache/16/b3fb707cb6f7b92f7215c598e24ba2' is unchanged since it is read-only
2021-04-01 19:47:46,031 TRACE: Assuming '/Users/nicholasroth/<CENSORED>/.dvc/cache/65/33ec4d541e9aebc13e7bf7cc0ebafe.dir' is unchanged since it is read-only
2021-04-01 19:47:46,032 TRACE: Assuming '/Users/nicholasroth/<CENSORED>/.dvc/cache/40/37e4f6ff75e819318e6f6ec9949cb2' is unchanged since it is read-only
2021-04-01 19:47:46,032 TRACE: Assuming '/Users/nicholasroth/<CENSORED>/.dvc/cache/81/5bbc4bde387af7eb28d3161ab9ae6e' is unchanged since it is read-only
2021-04-01 19:47:46,032 TRACE: Assuming '/Users/nicholasroth/<CENSORED>/.dvc/cache/b5/039da77b64d6784e62cdf7133b5320' is unchanged since it is read-only
2021-04-01 19:47:46,033 TRACE: Assuming '/Users/nicholasroth/<CENSORED>/.dvc/cache/f4/8a4ed183039c67fca3a6a3c2959f9d' is unchanged since it is read-only
2021-04-01 19:47:46,033 TRACE: Assuming '/Users/nicholasroth/<CENSORED>/.dvc/cache/60/6b5137f847c1924a68cf8b98a40d70' is unchanged since it is read-only
2021-04-01 19:47:46,033 TRACE: Assuming '/Users/nicholasroth/<CENSORED>/.dvc/cache/0a/659c6b52f41b98b06883932561f9bc' is unchanged since it is read-only
2021-04-01 19:47:46,034 TRACE: Assuming '/Users/nicholasroth/<CENSORED>/.dvc/cache/88/2f6ec02f708225fa4affda0186b395' is unchanged since it is read-only
2021-04-01 19:47:46,034 TRACE: Assuming '/Users/nicholasroth/<CENSORED>/.dvc/cache/33/d3da2ed88dc2a1ec5f399f47d03ba6' is unchanged since it is read-only
2021-04-01 19:47:46,034 TRACE: Assuming '/Users/nicholasroth/<CENSORED>/.dvc/cache/ad/552ed121516d2e9e07a95982ddfd56' is unchanged since it is read-only
2021-04-01 19:47:46,035 TRACE: Assuming '/Users/nicholasroth/<CENSORED>/.dvc/cache/a0/5b6f80bcfada72bbec50d294ba14ec' is unchanged since it is read-only
2021-04-01 19:47:46,035 TRACE: Assuming '/Users/nicholasroth/<CENSORED>/.dvc/cache/49/fed311a73a302200c7ffd84a43153c' is unchanged since it is read-only
2021-04-01 19:47:46,035 TRACE: Assuming '/Users/nicholasroth/<CENSORED>/.dvc/cache/5b/78f113a331804db5b33fce638ceadd' is unchanged since it is read-only
2021-04-01 19:47:46,035 TRACE: Assuming '/Users/nicholasroth/<CENSORED>/.dvc/cache/e3/92e4b78d24a7b73c2355dec1d95080' is unchanged since it is read-only
2021-04-01 19:47:46,036 TRACE: Assuming '/Users/nicholasroth/<CENSORED>/.dvc/cache/1f/c24508edcd43c797954642d3b2ac0a' is unchanged since it is read-only
2021-04-01 19:47:46,036 TRACE: Assuming '/Users/nicholasroth/<CENSORED>/.dvc/cache/20/051c6845126a75afc112564612c314' is unchanged since it is read-only
2021-04-01 19:47:46,036 TRACE: Assuming '/Users/nicholasroth/<CENSORED>/.dvc/cache/ef/75ba7454953c1ff8fbc6ec83e49a8b' is unchanged since it is read-only
2021-04-01 19:47:46,037 DEBUG: Collecting information from remote cache...                                                           
2021-04-01 19:47:46,037 DEBUG: Querying 1 hashes via object_exists
2021-04-01 19:47:46,038 DEBUG: Establishing ssh connection with '<CENSORED>.com' through port '22' as user 'KungFu'              
2021-04-01 19:47:46,320 DEBUG: Matched '0' indexed hashes                                                                            
2021-04-01 19:47:46,322 DEBUG: Establishing ssh connection with '<CENSORED>.com' through port '22' as user 'KungFu'              
2021-04-01 19:47:46,323 DEBUG: Establishing ssh connection with '<CENSORED>.com' through port '22' as user 'KungFu'              
2021-04-01 19:47:46,324 DEBUG: Establishing ssh connection with '<CENSORED>.com' through port '22' as user 'KungFu'              
  0% Querying cache in ssh://KungFu@<CENSORED>.com/kungfu/dvc/|                                      |0/21 [00:00<?,     ?file/s]
```

When I kill this with Ctrl+C, I get the following output and it hangs again without ever creating the temporary folder printed out at the bottom of this message:

```
2021-04-01 19:40:41,468 ERROR: interrupted by the user                                                                                        
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/dvc/2.0.15/libexec/lib/python3.9/site-packages/dvc/objects/db/ssh.py", line 73, in hashes_exist
    ret = list(itertools.compress(hashes, in_remote))
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 600, in result_iterator
    yield fs.pop().result()
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 435, in result
    self._condition.wait(timeout)
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/dvc/2.0.15/libexec/lib/python3.9/site-packages/dvc/main.py", line 55, in main
    ret = cmd.run()
  File "/usr/local/Cellar/dvc/2.0.15/libexec/lib/python3.9/site-packages/dvc/command/data_sync.py", line 56, in run
    processed_files_count = self.repo.push(
  File "/usr/local/Cellar/dvc/2.0.15/libexec/lib/python3.9/site-packages/dvc/repo/__init__.py", line 49, in wrapper
    return f(repo, *args, **kwargs)
  File "/usr/local/Cellar/dvc/2.0.15/libexec/lib/python3.9/site-packages/dvc/repo/push.py", line 41, in push
    return len(used_run_cache) + self.cloud.push(used, jobs, remote=remote)
  File "/usr/local/Cellar/dvc/2.0.15/libexec/lib/python3.9/site-packages/dvc/data_cloud.py", line 66, in push
    return remote.push(
  File "/usr/local/Cellar/dvc/2.0.15/libexec/lib/python3.9/site-packages/dvc/remote/base.py", line 56, in wrapper
    return f(obj, *args, **kwargs)
  File "/usr/local/Cellar/dvc/2.0.15/libexec/lib/python3.9/site-packages/dvc/remote/base.py", line 466, in push
    ret = self._process(
  File "/usr/local/Cellar/dvc/2.0.15/libexec/lib/python3.9/site-packages/dvc/remote/base.py", line 323, in _process
    dir_status, file_status, dir_contents = self._status(
  File "/usr/local/Cellar/dvc/2.0.15/libexec/lib/python3.9/site-packages/dvc/remote/base.py", line 175, in _status
    self.hashes_exist(
  File "/usr/local/Cellar/dvc/2.0.15/libexec/lib/python3.9/site-packages/dvc/remote/base.py", line 132, in hashes_exist
    return indexed_hashes + self.odb.hashes_exist(list(hashes), **kwargs)
  File "/usr/local/Cellar/dvc/2.0.15/libexec/lib/python3.9/site-packages/dvc/objects/db/ssh.py", line 74, in hashes_exist
    return ret
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 628, in __exit__
    self.shutdown(wait=True)
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 229, in shutdown
    t.join()
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 1033, in join
    self._wait_for_tstate_lock()
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 1049, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
------------------------------------------------------------
2021-04-01 19:40:41,472 DEBUG: Analytics is enabled.
2021-04-01 19:40:41,571 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/var/folders/77/60hw4dqx3k7cw7sxggpwv0hc0000gn/T/tmpa0r4944p']'
2021-04-01 19:40:41,574 DEBUG: Spawned '['daemon', '-q', 'analytics', '/var/folders/77/60hw4dqx3k7cw7sxggpwv0hc0000gn/T/tmpa0r4944p']'
```

When I hit Ctrl+C again, I see this message and the program exits:

```
^CException ignored in: <module 'threading' from '/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py'>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 1415, in _shutdown
    atexit_call()
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 31, in _python_exit
    t.join()
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 1033, in join
    self._wait_for_tstate_lock()
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 1049, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt: 
```

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.0.15 (brew)
---------------------------------
Platform: Python 3.9.2 on macOS-10.15.7-x86_64-i386-64bit
Supports: azure, gs, http, https, s3, ssh, oss, webdav, webdavs
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s7
Caches: local
Remotes: ssh
Workspace directory: apfs on /dev/disk1s7
Repo: dvc, git
```

**Comment by pmrowla** [comment] 2021-04-02 06:43
> Note that sftp.somesite.com does not allow users to create a shell and log in to an operating system. If you try, you will get this message:

DVC `ssh` remotes require shell access, and are not intended to work solely in an SFTP environment.
 
This limitation is noted in our docs for adding an SSH remote: https://dvc.org/doc/command-reference/remote/add#supported-storage-types

> ⚠️ DVC requires both SSH and SFTP access to work with remote SSH locations. Please check that you are able to connect both ways with tools like ssh and sftp (GNU/Linux).

**Comment by pmrowla** [comment] 2021-04-02 06:47
Closing this as expected behavior. @rothn if you are actually able to ssh into that machine, feel free to re-open this issue.

**Closed by pmrowla** 2021-04-02 06:47 UTC

**Comment by rothn** [comment] 2021-04-02 15:33
The way I interpreted the docs, it seemed like dvc would only need access to the SSH protocol -- not the ability to open a shell -- so thanks for taking the time to clarify here! I wonder if other people would benefit from a note about this in the docs.

**Comment by shcheklein** [comment] 2021-04-02 19:41
@rothn 

> if other people would benefit from a note about this in the docs

thanks for the feedback! Sometimes it's hard for us to even see possible improvements to the docs since we spend so much time doing them :) could you please create an issue in the https://github.com/iterative/dvc.org? Would be great if you can share how should it look like to make it explicit that other people don't hit this problem.
