### ISSUE TITLE
Create a troubleshooting entry for the lock error message

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#4325] opened 2020-08-03 16:53 UTC
From time to time users are getting a message like this:

`ERROR: cannot perform the command because another DVC process seems to be running on this project. If that is not the case, manually remove `.dvc/tmp/lock` and try again.`

(and even removing `.dvc/tmp/lock` doesn't help in this case)

when they run DVC on some Network fs (NFS, Lustre, etc).

Example: https://discordapp.com/channels/485586884165107732/563406153334128681/727222314080665682

Usually solution is simple and user needs to enable the `core.hardlink_lock`, but it's hard to get that from the error message.

To save us and users time we should create a troubleshooting entry and include link to the error message.

**Comment by moinnadeem** [comment] 2020-09-24 20:22
I'm getting this issue; how would I enable the `core.hardlink_lock`?

**Comment by efiop** [comment] 2020-09-24 20:24
@moinnadeem 

```
dvc config core.hardlink_lock true
```

:slightly_smiling_face:

**Comment by shcheklein** [comment] 2020-09-24 20:26
@moinnadeem hi! just to clarify and make sure that this ticket is the right one- have you tried to remove the `.dvc/tmp/lock` file (first make sure that no DVC commands are running) first? Do you use NFS or Lustre or some other network/distributed file system?

**Comment by moinnadeem** [comment] 2020-09-24 20:33
@shcheklein Yes, and yes! I'm on a networked filesystem that doesn't allow file-level locking either. Using hardlinking solved it! 

I appreciate the quick response!

**Comment by shcheklein** [comment] 2020-09-24 20:35
@moinnadeem perfect! :) thanks for clarifying.

**Comment by harsh8398** [comment] 2020-10-05 17:15
Hi @shcheklein I would like to take this issue. Could you please assign it to me? Also, where is this troubleshooting entry supposed to be added?

**Comment by shcheklein** [comment] 2020-10-05 17:20
@harsh8398 sure! feel free to work on this. Here is the place https://dvc.org/doc/user-guide/troubleshooting . Here is the guide on how to deal with the docs updates - https://dvc.org/doc/user-guide/contributing/docs

**Comment by jorgeorpinel** [comment] 2020-10-06 21:00
Hi!

> Usually solution is simple and user needs to enable the core.hardlink_lock, but it's hard to get that from the error message.

so should the error message in this repo also improve a little? (and link to the new troubleshooting anchor in docs)

**Comment by harsh8398** [comment] 2020-10-07 17:23
@shcheklein I'm having trouble with `tests/func/test_lock.py::test_cli` test case. The test case uses `assert FAILED_TO_LOCK_MESSAGE in caplog.text` check. The issue is that the `FAILED_TO_LOCK_MESSAGE` contains link with ascii escape codes added using one of the utility functions `format_link()` whereas the `caplog.text` only has the printed text which doesn't have the escape codes. So the test case will check two different strings and fail.

I am thinking to add assert statement for URL only like `assert TROUBLESHOOTING_URL in caplog.text`. Any suggestions? Thanks in advance 🙂.

**Comment by shcheklein** [comment] 2020-10-07 18:11
@efiop @pmrowla @pared @skshetry could you please help @harsh8398 with the tests here ^^ 🙏

**Comment by pared** [comment] 2020-10-14 16:26
@harsh8398 
I am very sorry for such a long time to respond.

As you might see in other our tests, we are usually duplicating the error messages that we want to check.
For example:
https://github.com/iterative/dvc/blob/b11fe83828fd5c65973a5ad7da3d95a5ea2c60e9/tests/func/test_data_cloud.py#L219

So in this case, what would be sufficient, would be to create the expected message and verify it is showing up in `caplog.text`.

**Comment by harsh8398** [comment] 2020-10-14 17:34
Thanks @pared for your help. 🙂

@shcheklein I've raised the PR with the changes!

**Closed** 2020-10-19 17:47 UTC
Labels: enhancement, good first issue, hacktoberfest, p2-medium, ui
