### ISSUE TITLE
params/metrics/exp diff: consistent output

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#5515] opened 2021-02-24 18:11 UTC
> Extracted from https://github.com/iterative/dvc.org/pull/2200#discussion_r581757584

* `metrics diff` currently shows old, new, change
* `params diff` currently shows old, new
* `exp diff` currently shows new, change

Should they all be Old, New, Change? (Possibly with some flag to skip Old or Change)

**Comment by jorgeorpinel** [comment] 2021-02-24 18:11
cc @dberenbaum

**Comment by dberenbaum** [comment] 2021-02-24 20:09
Thanks, @jorgeorpinel! Let's refer this back to #5392. 

> Should they all be Old, New, Change?

👍

**Comment by jorgeorpinel** [comment] 2021-02-25 05:01
What do you mean? 🙂

**Comment by jorgeorpinel** [comment] 2021-02-25 05:04
BTW @pmrowla do you know if we've considered merging `dvc params/metrics/exp diff` into a single command (e.g. `dvc compare`)? Or maybe flags of `dvc diff`

**Comment by pmrowla** [comment] 2021-02-25 05:51
@jorgeorpinel the idea has come up before as something that we could consider doing in the future, but not seriously considered yet

**Comment by dberenbaum** [comment] 2021-02-25 13:22
> What do you mean @dberenbaum? 🙂

I just wanted to mention it so we have all of these UI issues linked in that one issue. No other action needed!

**Comment by jorgeorpinel** [comment] 2021-02-25 21:09
Git it 👍

**Comment by daavoo** [comment] 2021-07-21 06:30
Was about to comment this in #5392 (haven't seen any other related issues). I think that the terms `Old` / `New` used in `diff` sometimes could be confusing, given that users can pass `refs` in any order. 

For example they could run `dvc metrics diff {newer commit hash} {older commit hash}` and the table will show the values of the newer commit under the column `Old`.

**Comment by dberenbaum** [comment] 2021-07-21 17:38
cc @skshetry 

I'd prefer having the ref names instead of Old and New.

**Comment by daavoo** [comment] 2021-10-29 18:51
Two questions:

A) Should `Change` be included by default ?? 

I might be biased but in my personal experience, but the "Change" value is kind of awkward mostly (sometimes overflowing the float diff, others mixing diffs that don't make sense).

I would vote for hiding it by default and making it optional.

B) Should there be an option to hide `a_rev` (previously "Old") at all?

IMO the only case where it could make sense to not show `a_rev` is when calling `dvc {X} diff {b_rev}` (where `a_rev` is set to `HEAD` by default.)

Maybe instead of a flag for opting out `a_rev`, we could just hide it when equals to `HEAD`.

**Comment by dberenbaum** [comment] 2021-11-15 18:51
@daavoo @jorgeorpinel Is there anything left to do on this issue?

**Comment by daavoo** [comment] 2021-11-15 19:05
> @daavoo @jorgeorpinel Is there anything left to do on this issue?

Showing `Change` in `dvc params diff` (If we agree that `Change` should be showed by default)

**Comment by jorgeorpinel** [comment] 2021-11-15 19:48
Not sure, I'd expect some PR to close this at some point but feel free to do so manually when you think it's addressed. Thanks

**Comment by dberenbaum** [comment] 2021-11-15 20:54
Params are not always numeric, so I'm not sure what should be shown in `Change`. Maybe it's a boolean for non-numeric params?

I agree that `Change` is not generally something I find that useful, but I also don't see it as really harmful.

**Comment by daavoo** [comment] 2021-11-15 21:00
> Params are not always numeric, so I'm not sure what should be shown in `Change`. Maybe it's a boolean for non-numeric params?

But we are showing `Change` in the params section of `dvc exp diff` 🤷

**Comment by dberenbaum** [comment] 2021-11-15 21:29
Ah, okay, it's handled like:

```
$ dvc exp diff
Path         Param    HEAD    workspace    Change
params.yaml  foo      a       b            diff not supported
```

I'd vote to keep `Change` since I see little harm and it seems like a less breaking change, but I don't feel that strongly about it.

**Comment by daavoo** [comment] 2021-11-15 23:28
> Ah, okay, it's handled like:
> 
> ```
> $ dvc exp diff
> Path         Param    HEAD    workspace    Change
> params.yaml  foo      a       b            diff not supported
> ```
> 
> I'd vote to keep `Change` since I see little harm and it seems like a less breaking change, but I don't feel that strongly about it.

We could improve the non scalar support by replacing the 'diff not supported' with bool resulting of direct comparisson

**Comment by daavoo** [comment] 2022-08-01 10:55
To clarify, what's left to close the issue is:

- Showing `Change` in dvc params diff

**Comment by mesejo** [comment] 2023-07-20 16:01
If this is still open, I would like to take it.

**Comment by filippopellizzari** [comment] 2024-02-25 20:59
If no one is currently working on this, I would like to take it.

**Closed** 2024-03-04 21:27 UTC
Labels: enhancement, good first issue, p3-nice-to-have, ui, diff/show
