### ISSUE TITLE
plots show: Cryptic error message when trying to plot csv files written from pandas

### ISSUE THREAD

**Issue by igordertigor** [iterative/dvc#7844] opened 2022-06-05 10:09 UTC
## Description

When I try to plot a csv file written by pandas, I receive an extraordinarily cryptic error message
```
ERROR: unexpected error - Empty string keys not allowed without dpath.options.ALLOW_EMPTY_STRING_KEYS=True: ('workspace', 'data', 'example.csv', 'data', 0, '')
```
This seems to bubble up from the json module and appears to be related to the empty column header that pandas writes for its default index column. So it is not difficult to fix (for example, by calling `.to_csv` with index=False). However, the error message is entirely useless and does not help a user figure out where the problem is.

### Reproduce
```bash
python3 -m venv venv

source venv/bin/activate

pip install -U pip
pip install dvc pandas

git init
dvc init

echo "import pandas as pd" > example.py
echo "pd.DataFrame({'a': [1, 2, 3], 'b': [1, 4, 9]}).to_csv('example.csv')" >> example.py

dvc run -n "example" \
        -d example.py \
        --plots example.csv \
        python example.py

dvc plots show
```

### Expected

I expected a plot of the "step" variable introduced by dvc as default for the x-axis and the variable "a" (first column in the dataset).

### Environment information

I initially observed this on ubuntu 20.04 with python 3.9, but reproduced it on ubuntu 20.04 with python 3.8 and on mac in the meantime.

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.10.2 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.4.0-96-generic-x86_64-with-glibc2.29
Supports:
        webhdfs (fsspec = 2022.5.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sda2
Caches: local
Remotes: None
Workspace directory: ext4 on /dev/sda2
Repo: dvc, git
```

**Comment by dberenbaum** [comment] 2022-06-07 18:55
Would it be better to allow empty column names or to show a more informative error message?

**Comment by pared** [comment] 2022-10-11 10:10
We dropped `dpath` in #7811, reproduction script seems to be working now. Closing. Please reopen if I missed something.

**Closed by pared** 2022-10-11 10:10 UTC
Labels: p2-medium, ui, A: plots
