### ISSUE TITLE
Web UI for DVC (GSoC 2021)

### ISSUE THREAD

**Issue by rakesh4real** [iterative/dvc#5305] opened 2021-01-21 11:43 UTC
Hey, dealing with ML models and data is an integral part of day-to-day activity. I came across this amazing project couple of days back and I love it. I want to contribute to this project as a part of GSoC applicant. I believe your organisation will enter GSoC this year as well.

Kindly let me know if building web UI for dvc is in your roadmap.
  
Cheers,
Rakesh

**Comment by efiop** [comment] 2021-01-21 12:00
Hi @rakesh4real 

Thanks or the suggestion! We are already working on a UI https://viewer.iterative.ai :slightly_smiling_face: 

Closing as a duplicate of https://github.com/iterative/dvc/issues/1074

**Closed by efiop** 2021-01-21 12:00 UTC

**Comment by rakesh4real** [comment] 2021-01-21 17:43
Thankyou @efiop
