### ISSUE TITLE
Multiple `dvc exp run --temp` runs

### ISSUE THREAD

**Issue by ciaochiaociao** [iterative/dvc#5718] opened 2021-03-27 15:10 UTC
Dear DVC, I am very happy to join this community. I have been working with it and I really love this tool to manage my ML experiments. However, currently (2.0.11 as I post this issue), running multiple `dvc exp run --temp` will have 

```
ERROR: Unable to acquire lock. Most likely another DVC process is running or was terminated abruptly. Check the page <https://dvc.org/doc/user-guide/troubleshooting#lock-issue> for other possible reasons and to learn how to resolve this.
```

Is it possible to do that? Or are you including this feature in your schedule?

The reason why I want this is 
> I want to run some other experiments when I was running one. And I know I can use `dvc exp run --run-all`. But sometimes it is hard for me to plan ahead all experiments.

**Comment by pmrowla** [comment] 2021-03-30 05:37
Unfortunately it's not currently possible to do this, but we do have plans to eventually improve the queue/run-all functionality so that you can modify the queue in place as needed.

Closing this as a duplicate of https://github.com/iterative/dvc/issues/5615 (this issue is the same as the suggested `queue --add`).

**Closed by pmrowla** 2021-03-30 05:37 UTC

**Comment by dberenbaum** [comment] 2021-03-30 12:40
@pmrowla It makes sense to put this under the umbrella of #5615, but the description for `queue --add` is the same as `run --queue`, which would be insufficient to address this issue. Seems like this is an additional feature that might make sense as part of `queue --add`?
