### ISSUE TITLE
dvc import not working

### ISSUE THREAD

**Issue by johnyaku** [iterative/dvc#9400] opened 2023-05-04 03:05 UTC
# Bug Report

`dvc import` is not working in some cases

## Description

Suppose that the source data registry contains directory `x/y` that is tracked by `x/y.dvc`.

The following command results in an empty directory:
```
dvc import <source_url> x/y
```
On the other hand, the following command does import the data, albeit via a download from the remote rather than symlinking to cache, as described in #9385:
```
dvc import <source_url> x
```

### Reproduce

See description

### Expected

Expected `y.dvc` to be created at the current location, along with directory `y/` containing the same files as the source registry.

### Environment information

Verified with DVC versions 2.53, 2.55 and 2.56

DVC v2.39 works as expected.

### Additional information

Together with #9385 and #9346, this bug makes me suspect that recent changes have fundamentally broken imports.

For now, we are reverting to v2.39 but perhaps I can suggest adding a few unit tests for basic import behaviour.

**Comment by efiop** [comment] 2023-05-04 21:53
I think I've fixed a similar problem not that long ago but didn't submit a PR yet. I'll take a look. Thanks for reporting this!

**Comment by efiop** [comment] 2023-05-04 22:54
@johnyaku Hm, maybe I'm missing something, but I can't seem to reproduce. Do you have a reproducible example by any chance? Is `source_url` a local path?

**Comment by johnyaku** [comment] 2023-05-08 14:06
I first tried creating a simple reprex based on https://github.com/iterative/dataset-registry but everything worked.

Then I went back to the actual instance of the `dvc import` command that failed a few days ago and check the source data registry (which was an SSH git URL for a data registry whose default remote was on an SSH host). 

Running `dvc data status` implied that quite a few files were "not in the remote", so I ran `dvc push` to rectify that but the message indicated that only one file was pushed. So that was a bit weird but it is too late at night for me to open another issue ...

Anyway, after pushing that file the `dvc import` command that prompted me to open this issue now works. So it turns out that this is less of a "bug" and more a case of "user error". Still, in my defense, a lot of weird stuff has been happening with imports lately!

FWIW, I think the single file that got pushed was probably a `.dir` file. Going back over my bash history, I think the last thing that I did (in the source registry) to the directory I was trying to import was to delete an unwanted file and then `dvc commit` the change. I think I `git commit`ed the resulting `.dvc` file but didn't `dvc push` the new `.dir` file.

Time to run `dvc install`, as I have on all my other registries!

At the same time, it might be nice to get a more useful error message when `dvc import` can't find the `.dir` file referenced by the `.dvc` file. Creating an empty directory and throwing a warning about its emptiness is a bit confusing.

**Comment by dberenbaum** [comment] 2023-05-09 18:18
@johnyaku Thanks for the detailed report!

> Running `dvc data status` implied that quite a few files were "not in the remote", so I ran `dvc push` to rectify that but the message indicated that only one file was pushed. So that was a bit weird but it is too late at night for me to open another issue ...

It might be related/duplicate of #9346.

> At the same time, it might be nice to get a more useful error message when `dvc import` can't find the `.dir` file referenced by the `.dvc` file. Creating an empty directory and throwing a warning about its emptiness is a bit confusing.

Makes sense. Do you have a minimal example of how to reproduce this?

**Comment by efiop** [comment] 2023-06-18 22:43
Closing for now as not able to reproduce.

**Closed by efiop** 2023-06-18 22:43 UTC
Labels: bug, awaiting response
