### ISSUE TITLE
PySocks DependencyWarning

### ISSUE THREAD

**Issue by def-mycroft** [iterative/dvc#2061] opened 2019-05-28 21:33 UTC
Hello, 

I just installed on W7 using the executable installer, and I keep getting this message: 

```
C:\PROGRA~2\DATAVE~1\aliyunsdkcore\vendored\requests\packages\urllib3\contrib\socks.py:37: DependencyWarning: SOCKS support in urllib3 requires the installation of optional dependencies: specifically, PySocks.  For more information, see https://urllib3.readthedocs.io/en/latest/contrib.html#socks-proxies
```

Other than that, the installation seems to work okay. 

**Please provide information about your setup**
DVC version(i.e. `dvc --version`), Platform and method of installation (pip, homebrew, pkg Mac, exe (Windows), DEB(Linux), RPM(Linux))

```
DVC version: 0.40.7
Python version: 2.7.16
Platform: Windows-7-6.1.7601-SP1
```

**Comment by def-mycroft** [comment] 2019-05-28 21:35
I'm not sure why dvc shows Python 2.7.16 when I run `dvc version`, I don't recall having py2 installed on my machine.

**Comment by efiop** [comment] 2019-05-29 00:43
Hi @def-mycroft !

Thanks a lot for reporting this!

> I'm not sure why dvc shows Python 2.7.16 when I run dvc version, I don't recall having py2 installed on my machine.

You are using a binary package, which is built with python 2.7 inside. If you'd like to use your own python, then the best way would be to install dvc using pip. Btw, we've just released 0.41.0 that is built with python3.7 inside, would you mind trying it out? :slightly_smiling_face: 

The warning comes from a newly supported `oss` remote, that is automatically included into binary packages. If you would be willing to use pip instead, then you could choose to not install `oss` dependencies(or rather just choose which remote support you want, e.g. `pip install dvc[s3,ssh]`), so you won't get that warning again. Still, this warning should be either fixed or explicitly ignored on our side, so we'll take a look.

**Comment by def-mycroft** [comment] 2019-05-29 14:03
Hello @efiop, thanks for your response. `dvc` is such a great project, I've been really happy with `dvc` so far and I plan on using it in most of my data-heavy projects going forward. 

I installed via pip on my Ubuntu 19 machine, no problem, but my W7 machine at the office is a different story. If I install via pip on windows, will `dvc` still be available on my [git bash][1]? The only other question I have about installing via pip would be how it interacts with my conda installation of python and environments.

I downloaded the 0.41.3 exe file (from [here][1]) and below is the output of `dvc version`.  Is there an step I have to take to uninstall the python 2 ? I tried deleting the directory C:/Program Files/Data Version Control/ before running the exe and I still see the python 2 version. 

```
$ dvc version
C:\PROGRA~2\DATAVE~1\aliyunsdkcore\vendored\requests\packages\urllib3\contrib\socks.py:37: DependencyWarning: SOCKS support in urllib3 requires the installation of optional dependencies: specifically, PySocks.  For more information, see https://urllib3.readthedocs.io/en/latest/contrib.html#socks-proxies
DVC version: 0.41.3
Python version: 2.7.16
Platform: Windows-7-6.1.7601-SP1
```

[1]:https://gitforwindows.org/
[2]:https://github.com/iterative/dvc/releases/tag/0.41.3

**Comment by efiop** [comment] 2019-05-29 23:24
>  If I install via pip on windows, will dvc still be available on my git bash? The only other question I have about installing via pip would be how it interacts with my conda installation of python and environments.

With conda it should be even simpler, since it has pip on board. `pip install dvc` should work fine.

> I downloaded the 0.41.3 exe file (from here) and below is the output of dvc version. Is there an step I have to take to uninstall the python 2 ? I tried deleting the directory C:/Program Files/Data Version Control/ before running the exe and I still see the python 2 version.

Hm, that is weird, we might have a bug there, need to check. Deleting that directory should've deleted the python 2, since it is used internally and not linked to the outside in any way. Maybe we have a bug and still building our windows binary with python2.

**Comment by def-mycroft** [comment] 2019-05-30 18:33
@efiop okay! I'll try installing with pip and see how that works. 

I guess I could be doing something wrong on my end re exe installation. Here is what I did, maybe it will help troubleshooting on your end: 

* installed 0.40.7 using the exe (without any prior dvc installation) 
* downloaded the 0.41.3 exe and just ran it again (with no prior steps). 
* ran `dvc version` and got `DVC version: 0.41.3` and `Python version: 2.7.16` 
* deleted the "Data Version Control" folder 
* ran the 0.41.3 exe again 
* ran `dvc version` and still got `DVC version: 0.41.3` and `Python version: 2.7.16` 

...at least to the best of my memory.

**Comment by efiop** [comment] 2019-05-30 18:37
@def-mycroft Thanks for a detailed backtrace! :) Turned out that we were indeed building windows binary package with python2. I've added a fix for it in https://github.com/iterative/dvc/commit/dba34ec3f1d86506b45842ad5c7529645172b56c . Our next release should be python3. But still, that warning will persist in the binary, because it is caused by one of the dependencies. We'll look into mitigating that one as well. Thanks again for the feeback! :slightly_smiling_face: Let us know how it goes with the `pip`.

**Comment by efiop** [comment] 2019-06-21 20:43
Moving to py3 for the binary solved the issue. I can no longer reproduce it on my windows machine. Current dvc is still py2, but the next release will be py3 and will have that issue solved. Thanks a lot for the feedback @def-mycroft ! :slightly_smiling_face:

**Closed by efiop** 2019-06-21 20:43 UTC
Labels: bug, c3-small-fix, p2-medium
