### ISSUE TITLE
dvc: `lock` file ignored when command is run more than one time

### ISSUE THREAD

**Issue by algomaster99** [iterative/dvc#2822] opened 2019-11-20 13:00 UTC
#### Version

```
DVC version: 0.70.0
Python version: 3.7.3
Platform: Linux-5.0.0-36-generic-x86_64-with-Ubuntu-18.04-bionic
Binary: False
Package: pip
Cache: reflink - False, hardlink - True, symlink - True
```
#### Problem

`.dvc/lock` is ignored when a `dvc` command is run for the second time.
![Screenshot from 2019-11-20 18-21-29](https://user-images.githubusercontent.com/35191225/69240647-f62e1e80-0bc2-11ea-9b19-002ed20ec1ec.png)

#### Expected behaviour

When `dvc status` is run for the second time, it should throw an error since `.dvc/lock` isn't deleted yet so it should have prevented the command from running.

#### Reproduce
1. Manually created `lock` file.
```
$ touch .dvc/lock
```
2. Run `dvc status`. (Throws error)
```
>>>
ERROR: failed to obtain data status - cannot perform the command because another DVC process seems to be running on this project. If that is not the case, manually remove `.dvc/lock` and try again.
```
3. Run `ls .dvc` to check if `lock` is still present.
```
$ ls .dvc
>>> cache  config  lock  state  tmp  updater
```
4. Run `dvc status` again.
**Runs successfully**. It should not since `lock` is still present.

**Comment by shcheklein** [comment] 2019-11-20 18:32
@mroutis could you triage this and see if it's an actual bug or expected?

**Comment by mroutis** [comment] 2019-11-22 00:34
@shcheklein , @algomaster99 , this is the expected behavior.
The lock is being broken because its lifetime expired already.
The lifetime of a `flufl.lock` is based on its `mtime`.
If you do instead: `touch -mt 2001010000 .dvc/lock`, the lock will be unbreakable until January 1st, 2020

Reading https://github.com/retinator/flufl.lock source code was delightful; @algomaster99 , if you are interested to know how it works internally, I truly recommend you to grab a glass/cup of your favorite beverage and go through the code in one sit, it is short and well documented :ok_hand: 

By the way, you can go to `dvc/logger.py` and turn down the level for `flufl.lock` logger to `DEBUG` and you'll get plenty of useful messages to understand what's happening :slightly_smiling_face: 

I'll close this issue since the lock created by DVC doesn't get ignored:
```bash
dvc run sleep 1000 &
dvc status
dvc status
```

**Comment by efiop** [comment] 2019-11-22 03:00
@mroutis That seems pretty weird. We set the lifetime to be over a year https://github.com/iterative/dvc/blob/master/dvc/lock.py#L62 so why does it break after one check? CC @Suor

**Comment by mroutis** [comment] 2019-11-22 03:38
@efiop , @algomaster99 was trying to emulate a _lockfile_ by using `touch .dvc/lock` directly.
DVC sets the time correctly to 1 year :slightly_smiling_face:

**Comment by efiop** [comment] 2019-11-22 03:41
@mroutis Oh! Makes total sense! Sorry, didn't get that one right away. Great research! 🙏

**Closed by efiop** 2019-11-22 03:41 UTC
Labels: bug, p0-critical, research

**Comment by algomaster99** [comment] 2019-11-22 09:25
@mroutis @efiop Thanks for the explanation! How come its (`lock` created manually) expiry  finishes just after the first run?

**Comment by Suor** [comment] 2019-11-22 09:36
As far as I remember there is a grace period of several second built in, to compensate for time being not in sync across network. So if you touch it and then run status fast enough you'll get locked. Just a guess.
