### ISSUE TITLE
dvc.api.read doesn't read data from Azure Blob Storage

### ISSUE THREAD

**Issue by upul** [iterative/dvc#6209] opened 2021-06-22 12:52 UTC
# Bug Report

## Description

I'm trying to read a DVC-tracked dataset stored in Azure blob storage and getting the following error. 

`dvc.fs.azure.AzureAuthError: Authentication to Azure Blob Storage requires either account_name or connection_string.`

### Reproduce

1. Initialize your DVC repo with `dvc init`
2. Set remote and Azure blob storage connection string with the following commends.
    `dvc remote add -d risk_model_remote azure://container_name/object_name`
    `dvc remote modify --local risk_model_remote connection_string '<your_connection_string>'`
3. Push your dataset with `dvc push` command
4. Execure following Python code snippet
    ```python
   data = dvc.api.read(
        "datasets/dataset.csv",
        repo="git@ssh.dev.azure.com:v3/aaa/bbb/repo",
        remote="risk_model_remote",
       )
    ````
  
### Expected

dvc.api.read loads the file from azure blob storage into memory, so that it can be further processed with python.

### Actual

```bash
Traceback (most recent call last):
  File "dvc_test.py", line 20, in <module>
    data = dvc.api.read(
  File "/home/airudi/office/python_codes/test/venv/lib/python3.8/site-packages/dvc/api.py", line 88, in read
    with open(
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/airudi/office/python_codes/test/venv/lib/python3.8/site-packages/dvc/api.py", line 76, in _open
    with _repo.open_by_relpath(
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/airudi/office/python_codes/test/venv/lib/python3.8/site-packages/dvc/repo/__init__.py", line 488, in open_by_relpath
    with fs.open(
  File "/home/airudi/office/python_codes/test/venv/lib/python3.8/site-packages/dvc/fs/repo.py", line 143, in open
    return dvc_fs.open(path_info, mode=mode, encoding=encoding, **kwargs)
  File "/home/airudi/office/python_codes/test/venv/lib/python3.8/site-packages/dvc/fs/dvc.py", line 79, in open
    remote_obj = self.repo.cloud.get_remote(remote)
  File "/home/airudi/office/python_codes/test/venv/lib/python3.8/site-packages/dvc/data_cloud.py", line 29, in get_remote
    return self._init_remote(name)
  File "/home/airudi/office/python_codes/test/venv/lib/python3.8/site-packages/dvc/data_cloud.py", line 49, in _init_remote
    return get_remote(self.repo, name=name)
  File "/home/airudi/office/python_codes/test/venv/lib/python3.8/site-packages/dvc/remote/__init__.py", line 8, in get_remote
    fs = cls(**config)
  File "/home/airudi/office/python_codes/test/venv/lib/python3.8/site-packages/dvc/fs/azure.py", line 83, in __init__
    super().__init__(**config)
  File "/home/airudi/office/python_codes/test/venv/lib/python3.8/site-packages/dvc/fs/fsspec_wrapper.py", line 19, in __init__
    self.fs_args.update(self._prepare_credentials(**kwargs))
  File "/home/airudi/office/python_codes/test/venv/lib/python3.8/site-packages/dvc/fs/azure.py", line 122, in _prepare_credentials
    raise AzureAuthError(
dvc.fs.azure.AzureAuthError: Authentication to Azure Blob Storage requires either account_name or connection_string.
```

### Environment information

```bash
(venv) ➜  .dvc git:(master) ✗ dvc doctor
DVC version: 2.3.0 (pip)
---------------------------------
Platform: Python 3.8.5 on Linux-5.8.0-55-generic-x86_64-with-glibc2.29
Supports: azure, http, https
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: azure
Workspace directory: ext4 on /dev/nvme0n1p2
Repo: dvc, git

```

**Comment by pmrowla** [comment] 2021-06-23 00:54
@upul do you have a copy of your repo cloned locally? If so, you should pass the local path to that repo in the `repo=` parameter. If you are using `api.open()` with a remote git URL, DVC will not have access to any `config.local` authentication information

**Comment by upul** [comment] 2021-06-23 16:01
@pmrowla Thank you for your reply. I tested your suggestion, and it works. However, cloning the repository is not an elegant solution in my use case. 

Let me briefly explain my scenario. I have two repositories:

1. Frist first repository (**Training Repo**) is used for data exploration, experiment, and training the ML model. We use DVC dataset versioning and pipeline (and MLFlow for tracking) in this repo. Once we trained our model we push our model (with DVC training) into an Azure blob.
2. The second one (**Production Repo**) is our production repository. I'm going to download the DVC versioned model created in the first repository using `dvc.api.read`. 

To get my DVC-versioned model, it is odd to clone both repositories to the production server. 
 
It is nice to use the following code to read my model if I correctly configure DVC remote and connection string.

```python
data = dvc.api.read(
    "models/model.h5",
    repo="git@ssh.dev.azure.com:v3/aaa/bbb/repo",
    remote="risk_model_remote",
   )
```

Best regards,
Upul

**Comment by pmrowla** [comment] 2021-06-24 01:38
@upul the issue is `api.read` does not have access to anything configured with `--local`. It will only have access to credentials which are stored in `git@ssh.dev.azure.com:v3/aaa/bbb/repo` (meaning whatever is git-committed in `.dvc/config`). Since your connection string is `--local` only, `api.read` cannot use it when reading from `git@...`.

One workaround is to have your users set the connection string with `dvc remote modify --global` instead of `--local`, which will essentially set default credentials for that user any time they connect to a remote named `risk_model_remote`.

Another possibility is to configure default read-only credentials for your remote in `.dvc/config`. If you git-commit these credentials, all users would be able to use `dvc pull` or `api.read()`, but would not be able to `dvc push` to your remote. Users who need to `dvc push` can then configure their own `--local` credentials which will override the default read-only ones.

**Comment by efiop** [comment] 2021-07-15 14:26
Closing since the config issue is more general and related to https://github.com/iterative/dvc/issues/2466

**Closed by efiop** 2021-07-15 14:26 UTC
Labels: awaiting response
