### ISSUE TITLE
dvc doctor: No module named 'public' (ActiveState Python)

### ISSUE THREAD

**Issue by JulianWgs** [iterative/dvc#9499] opened 2023-05-23 15:52 UTC
# Bug Report

## Description
```bash
$ python3.10 -m dvc doctor -v
2023-05-23 17:20:14,733 DEBUG: v2.55.0 (pip), CPython 3.10.11 on Linux-4.18.0-425.13.1.el8_7.x86_64-x86_64-with-glibc2.28
2023-05-23 17:20:14,733 DEBUG: command: doctor -v
2023-05-23 17:20:16,754 ERROR: unexpected error - No module named 'public'
Traceback (most recent call last):
  File "/net/home/XXX/.local/share/applications/XXX/usr/lib/python3.10/site-packages/dvc/cli/__init__.py", line 210, in main
    ret = cmd.do_run()
  File "/net/home/XXX/.local/share/applications/XXX/usr/lib/python3.10/site-packages/dvc/cli/command.py", line 40, in do_run
    return self.run()
  File "/net/home/XXX/.local/share/applications/XXX/usr/lib/python3.10/site-packages/dvc/commands/version.py", line 16, in run
    dvc_info = get_dvc_info()
  File "/net/home/XXX/.local/share/applications/XXX/usr/lib/python3.10/site-packages/dvc/info.py", line 38, in get_dvc_info
    with Repo() as repo:
  File "/net/home/XXX/.local/share/applications/XXX/usr/lib/python3.10/site-packages/dvc/repo/__init__.py", line 153, in __init__
    from dvc.lock import LockNoop, make_lock
  File "/net/home/XXX/.local/share/applications/XXX/usr/lib/python3.10/site-packages/dvc/lock.py", line 8, in <module>
    import flufl.lock
  File "/net/home/XXX/.local/share/applications/XXX/usr/lib/python3.10/site-packages/flufl/lock/__init__.py", line 1, in <module>
    from public import public as _public
ModuleNotFoundError: No module named 'public'

Traceback (most recent call last):
  File "/net/home/XXX/.local/share/applications/XXX/usr/lib/python3.10/site-packages/dvc/cli/__init__.py", line 210, in main
    ret = cmd.do_run()
  File "/net/home/XXX/.local/share/applications/XXX/usr/lib/python3.10/site-packages/dvc/cli/command.py", line 40, in do_run
    return self.run()
  File "/net/home/XXX/.local/share/applications/XXX/usr/lib/python3.10/site-packages/dvc/commands/version.py", line 16, in run
    dvc_info = get_dvc_info()
  File "/net/home/XXX/.local/share/applications/XXX/usr/lib/python3.10/site-packages/dvc/info.py", line 38, in get_dvc_info
    with Repo() as repo:
  File "/net/home/XXX/.local/share/applications/XXX/usr/lib/python3.10/site-packages/dvc/repo/__init__.py", line 153, in __init__
    from dvc.lock import LockNoop, make_lock
  File "/net/home/XXX/.local/share/applications/XXX/usr/lib/python3.10/site-packages/dvc/lock.py", line 8, in <module>
    import flufl.lock
  File "/net/home/XXX/.local/share/applications/XXX/usr/lib/python3.10/site-packages/flufl/lock/__init__.py", line 1, in <module>
    from public import public as _public
ModuleNotFoundError: No module named 'public'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/net/home/XXX/.local/share/applications/XXX/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/net/home/XXX/.local/share/applications/XXX/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/net/home/XXX/.local/share/applications/XXX/usr/lib/python3.10/site-packages/dvc/__main__.py", line 7, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/net/home/XXX/.local/share/applications/XXX/usr/lib/python3.10/site-packages/dvc/cli/__init__.py", line 236, in main
    ret = _log_exceptions(exc) or 255
  File "/net/home/XXX/.local/share/applications/XXX/usr/lib/python3.10/site-packages/dvc/cli/__init__.py", line 145, in _log_exceptions
    _log_unknown_exceptions()
  File "/net/home/XXX/.local/share/applications/XXX/usr/lib/python3.10/site-packages/dvc/cli/__init__.py", line 47, in _log_unknown_exceptions
    logger.debug("Version info for developers:
%s", get_dvc_info())
  File "/net/home/XXX/.local/share/applications/XXX/usr/lib/python3.10/site-packages/dvc/info.py", line 38, in get_dvc_info
    with Repo() as repo:
  File "/net/home/XXX/.local/share/applications/XXX/usr/lib/python3.10/site-packages/dvc/repo/__init__.py", line 153, in __init__
    from dvc.lock import LockNoop, make_lock
  File "/net/home/XXX/.local/share/applications/XXX/usr/lib/python3.10/site-packages/dvc/lock.py", line 8, in <module>
    import flufl.lock
  File "/net/home/XXX/.local/share/applications/XXX/usr/lib/python3.10/site-packages/flufl/lock/__init__.py", line 1, in <module>
    from public import public as _public
ModuleNotFoundError: No module named 'public'
```

### Reproduce

1. dvc doctor

### Expected

Output of dvc doctor.

### Environment information

This is the issue :)

Unfortunately I can't give you the information of the full environment. If you need more version information, I can give them to you.
| name | version      |
|-------|------|
|dvc       |   2.55.0 |
|dvc-data     |     0.47.1 |
|dvc-http     |     2.30.2 |
|dvc-objects |         0.21.2 |
|dvc-render    |      0.3.1 |
|dvc-studio-client |         0.6.2 |
|dvc-task  |        0.2.0 |
|flufl.lock    |      6.0 |

```

**Comment by dberenbaum** [comment] 2023-05-23 20:02
Thanks @JulianWgs! Looks like for some reason the [public](https://public.readthedocs.io/en/stable/) package isn't installed despite being listed as a [dependency](https://gitlab.com/warsaw/flufl.lock/-/blob/6.0/setup.py#L37) in `flufl.lock`.

**Comment by skshetry** [comment] 2024-03-25 11:05
Closing, this is likely fixed and/or is not a bug in dvc.

**Closed by skshetry** 2024-03-25 11:05 UTC
