### ISSUE TITLE
Expand checksums whenever possible

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#941] opened 2018-07-23 23:27 UTC
It would be great to expand checksum by file names when it is possible. Hashes have no meaning for a regular user.

```
 $ dvc pull
    (1/5): [##############################] 100% 3caf879afa11fc750cac4e15721a8741
    (2/5): [##############################] 100% f83c01a5634a9e7b8a04177a5533f67b
    (3/5): [##############################] 100% 2579801f17b00b0014d4e2a4847e3064.dir
    (4/5): [##############################] 100% 82986e112ecefabbcfbaf960e2c8fb36
    (5/5): [##############################] 100% 18d51187e9602848514499047bb6de7f
```

More details:
- In an ideal case, we should expand all the checksums but some data files might belong to another branch\commit. For now, it is probably okay to keep checksums if a data file was created outside of the current branch\commit.
- It might be okay to keep short checksums if it was not resolved.
- It might be useful to keep an option to show checksums.

**Comment by efiop** [comment] 2018-07-24 06:36
Duplicate of https://github.com/iterative/dvc/issues/884

**Comment by efiop** [comment] 2018-07-28 16:52
Fixed by https://github.com/iterative/dvc/pull/952

**Closed by efiop** 2018-07-28 16:52 UTC
Labels: enhancement
