### ISSUE TITLE
asyncio error when pulling

### ISSUE THREAD

**Issue by rmlopes** [iterative/dvc#6158] opened 2021-06-11 22:10 UTC
# Bug Report
## Description

In a repo where someone messed up and some files were pushed to git but not dvc, dvc2.3 will crash with the following message:

> ERROR: unexpected error - Task <Task pending coro=<_runner() running at /home/.../.venv/lib/python3.6/site-packages/fsspec/asyn.py:20> cb=[_chain_future.<locals>._call_set_state() at /usr/lib/python3.6/asyncio/futures.py:410]> got Future <Future pending> attached to a different loop

With dvc2.1 it will be ok (apart from the missing cache 😄 ) outputing at that stage:

> WARNING: No file hash info found for 'data-registry/...'. It won't be created. 

### Reproduce

1. Track a bunch of files 
2. Push to git (do not push to dvc)
3. I a new clone do a dvc pull

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.3.0 (pip)
---------------------------------
Platform: Python 3.6.9 on Linux-4.15.0-143-generic-x86_64-with-Ubuntu-18.04-bionic
Supports: azure, http, https
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/mapper/witch--vg-root
Caches: local
Remotes: azure
Workspace directory: ext4 on /dev/mapper/witch--vg-root
Repo: dvc, git

```

**Additional Information:**

Does not happen at 2.1.0+71ea12 (not sure what is exactly the most recent version where it is ok, since I had this one previously installed in a different environment)

Full stack trace:

```console
Traceback (most recent call last):
  File "/home/....venv/lib/python3.6/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/home/....venv/lib/python3.6/site-packages/dvc/command/base.py", line 50, in do_run
    return self.run()
  File "/home/....venv/lib/python3.6/site-packages/dvc/command/data_sync.py", line 40, in run
    glob=self.args.glob,
  File "/home/....venv/lib/python3.6/site-packages/dvc/repo/__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/....venv/lib/python3.6/site-packages/dvc/repo/pull.py", line 38, in pull
    run_cache=run_cache,
  File "/home/....venv/lib/python3.6/site-packages/dvc/repo/__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/....venv/lib/python3.6/site-packages/dvc/repo/fetch.py", line 63, in fetch
    used, jobs, remote=remote, show_checksums=show_checksums
  File "/home/....venv/lib/python3.6/site-packages/dvc/data_cloud.py", line 88, in pull
    show_checksums=show_checksums,
  File "/home/....venv/lib/python3.6/site-packages/dvc/remote/base.py", line 56, in wrapper
    return f(obj, *args, **kwargs)
  File "/home/....venv/lib/python3.6/site-packages/dvc/remote/base.py", line 489, in pull
    download=True,
  File "/home/....venv/lib/python3.6/site-packages/dvc/remote/base.py", line 326, in _process
    download=download,
  File "/home/....venv/lib/python3.6/site-packages/dvc/remote/base.py", line 168, in _status
    self._indexed_dir_hashes(cache, named_cache, dir_md5s)
  File "/home/....venv/lib/python3.6/site-packages/dvc/remote/base.py", line 240, in _indexed_dir_hashes
    dir_exists.update(self.odb.list_hashes_exists(dir_md5s - dir_exists))
  File "/home/....venv/lib/python3.6/site-packages/dvc/objects/db/base.py", line 362, in list_hashes_exists
    ret = list(itertools.compress(hashes, in_remote))
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/....venv/lib/python3.6/site-packages/dvc/objects/db/base.py", line 353, in exists_with_progress
    ret = self.fs.exists(path_info)
  File "/home/....venv/lib/python3.6/site-packages/dvc/fs/fsspec_wrapper.py", line 92, in exists
    return self.fs.exists(self._with_bucket(path_info))
  File "/home/....venv/lib/python3.6/site-packages/adlfs/spec.py", line 1259, in exists
    return sync(self.loop, self._exists, path)
  File "/home/....venv/lib/python3.6/site-packages/fsspec/asyn.py", line 53, in sync
    raise result[0]
  File "/home/....venv/lib/python3.6/site-packages/fsspec/asyn.py", line 20, in _runner
    result[0] = await coro
  File "/home/....venv/lib/python3.6/site-packages/adlfs/spec.py", line 1278, in _exists
    exists = await bc.exists()
  File "/home/....venv/lib/python3.6/site-packages/azure/core/tracing/decorator_async.py", line 74, in wrapper_use_tracer
    return await func(*args, **kwargs)
  File "/home/....venv/lib/python3.6/site-packages/azure/storage/blob/aio/_blob_client_async.py", line 481, in exists
    **kwargs)
  File "/home/....venv/lib/python3.6/site-packages/azure/storage/blob/_generated/aio/operations_async/_blob_operations_async.py", line 391, in get_properties
    pipeline_response = await self._client._pipeline.run(request, stream=False, **kwargs)
  File "/home/....venv/lib/python3.6/site-packages/azure/core/pipeline/_base_async.py", line 215, in run
    return await first_node.send(pipeline_request)
  File "/home/....venv/lib/python3.6/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/....venv/lib/python3.6/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  File "/home/....venv/lib/python3.6/site-packages/azure/core/pipeline/_base_async.py", line 83, in send
    response = await self.next.send(request)  # type: ignore
  [Previous line repeated 3 more times]
  File "/home/....venv/lib/python3.6/site-packages/azure/core/pipeline/policies/_authentication_async.py", line 73, in send
    await await_result(self.on_request, request)
  File "/home/....venv/lib/python3.6/site-packages/azure/core/pipeline/_tools_async.py", line 32, in await_result
    return await result  # type: ignore
  File "/home/....venv/lib/python3.6/site-packages/azure/core/pipeline/policies/_authentication_async.py", line 48, in on_request
    async with self._lock:
  File "/usr/lib/python3.6/asyncio/locks.py", line 79, in __aenter__
    yield from self.acquire()
  File "/usr/lib/python3.6/asyncio/locks.py", line 181, in acquire
    yield from fut
```

**Edit**
`adlfs==0.7.1`

**Comment by efiop** [comment] 2021-06-11 22:38
@rmlopes Could you show `pip freeze | grep adlfs`, please?

**Comment by isidentical** [comment] 2021-06-14 11:06
This seems like a duplicate of iterative/dvc/issues/6108.

**Closed by isidentical** 2021-06-14 11:06 UTC
Labels: awaiting response, fs: azure
