### ISSUE TITLE
SSH remote takes user name from environment

### ISSUE THREAD

**Issue by xodarcz** [iterative/dvc#6328] opened 2021-07-16 11:29 UTC
Hello,
I have tried to set remote for SSH connection in the way I have found in example:

dvc remote add --default ssh-storage ssh://example.com/path/to/storage
dvc remote modify --local ssh-storage user myname
dvc remote modify --local ssh-storage password 123456789

and in config and config.local, everything is set correctly. However, if set this way, ssh connection takes user name from the system, not from the config. If I set remote URL for ssh storage as myname@example.com (dvc remote add --default ssh-storage ssh://myname@example.com/path/to/storage) it works fine. However, i would presume, that if I set user name in the config.local, it should be used in the ssh connection instead of my system name. Is this some kind of bug or is there something that I am missing? Thank you

**Comment by pmrowla** [comment] 2021-07-19 05:40
this is likely a duplicate of https://github.com/iterative/dvc/issues/6225 which has already been fixed.

@xodarcz could you please make sure you are using the latest DVC release and then try again

**Closed** 2021-09-21 21:52 UTC
Labels: awaiting response
