### ISSUE TITLE
Cluttered output in noninteractive terminal

### ISSUE THREAD

**Issue by liviu-stoica** [iterative/dvc#8577] opened 2022-11-17 08:38 UTC
Hi, we are having some issues with how dvc prints the progress indication in our CI environment.

We run `dvc pull` inside a docker container run by Azure Pipelines. Dvc decides that stderr is a tty, and enables the progress indicator. The problem is, the terminal is not interactive, and docker logs collects all the ANSI escape sequences, which then get tailed by Azure DevOps.

For a folder with ~7000 files, the output ends up being 200000 lines of clutter. Is it possible to have dvc adjust when running in noninteractive terminals?

Thanks

**Comment by skshetry** [comment] 2022-11-17 09:54
Duplicate of https://github.com/iterative/dvc/issues/2664.

**Comment by skshetry** [comment] 2022-11-17 09:55
I think the problem is most likely that it does not support carriage return. We can think of introducing `--no-progress` or similar flags. Please subscribe or follow on that issue. Thanks.

**Closed by skshetry** 2022-11-17 09:55 UTC
