### ISSUE TITLE
dvc repro: only download the necessary artefacts to re-run the pipeline

### ISSUE THREAD

**Issue by ettadar** [iterative/dvc#4870] opened 2020-11-10 13:41 UTC
Let's say there is a 3 stages workflow: A -> B -> C:
- A run `a.py` and produce `a.json`,
- B run `b.py` that takes `a.json` as input and produce `b.json`,
- C run `c.py` that takes `b.json` as input and produce `c.json`.

It would be very handy to have a flag in `dvc repro` to download only what is necessary to rerun the stages that changed. For example, when working on a fresh clone of the repo:
- if I change nothing and run `dvc repro --new-flag` -> dvc download nothing and run nothing.
- if I change c.py and run `dvc repro --new-flag` -> dvc only download b.json and run step C.
- if I change b.py and run `dvc repro --new-flag` -> dvc download a.json and run steps B and C.

This become particularly useful when working with big pipelines that train multiple models. Downloading all the training data for all the model can takes a lot of time and a lot of space on the disk.

**Comment by dberenbaum** [comment] 2022-02-23 19:01
Seems like a duplicate of #4742, so I'll transfer the comment over there.

**Closed by dberenbaum** 2022-02-23 19:01 UTC
Labels: feature request, p3-nice-to-have
