### ISSUE TITLE
deprecate: using Dvcfile is confusing and maybe should be deprecated

### ISSUE THREAD

**Issue by dashohoxha** [iterative/dvc#2391] opened 2019-08-13 09:13 UTC
The command `dvc pipeline show --ascii <targets>` is supposed to work without any targets as well (as explained by the help message: `dvc pipeline show --help`). However it complains instead about the absence of `Dvcfile`:
```bash
WARNING: assuming default target 'Dvcfile'.
ERROR: failed to show pipeline for 'Dvcfile' - 'Dvcfile' does not exist.
```
This is confusing for the users. Without any targets, it should show all the pipelines available (as the help message says). This would be more reasonable than searching for a "Dvcfile".

Moreover, **I think that using `Dvcfile` as a default target should be deprecated in general.** It is much better to fail and ask for a `.dvc` file, when it is missing, than to assume that the default is `Dvcfile`.

**Comment by dashohoxha** [comment] 2019-08-13 09:15
Related: https://github.com/iterative/dvc/issues/2392

**Comment by pared** [comment] 2019-08-13 09:28
[Some context](https://discordapp.com/channels/485586884165107732/563406153334128681/610757855242485763)

**Comment by efiop** [comment] 2019-08-21 14:04
> Moreover, I think that using Dvcfile as a default target should be deprecated in general. It is much better to fail and ask for a .dvc file, when it is missing, than to assume that the default is Dvcfile.

Dvcfile is similar to Makefile and is used for other commands like `dvc repro` to provide a feature that allows you to run your command without a specific target, so the creator of the project could decide which targets should be reproduced by default. It is also useful when you have a dedicated directory for your pipeline step (e.g. https://github.com/nestauk/gateway_to_cookies/tree/master/pipe). I don't think that `pipeline show` issue is a good enough reason to abandon Dvcfile's in general, the reasons behind `pipeline show` behaviour are discussed #2392 . Also, removing Dvcfile would break backward compatibility.

**Comment by shcheklein** [comment] 2019-08-21 16:38
I think the help message should be updated. It looks like an UI bug to me at the very least.

**Comment by dashohoxha** [comment] 2019-08-21 17:46
> Dvcfile is similar to Makefile

@efiop Everything that you say about `Dvcfile` may be right, but IMHO the analogy with a `Makefile` is broken. I would love it if Dvcfile was similar to Makefile (or Dockerfile).

**Comment by efiop** [comment] 2019-08-21 18:48
@shcheklein It should be a part of https://github.com/iterative/dvc/issues/2392 , no need to keep a duplicate issue.

**Comment by efiop** [comment] 2019-08-21 18:51
@dashohoxha Sure, it is not a 1to1 conformity, I'm just saying that the idea behind a default file name is a similar one to both Makefile and Dockerfile.

**Comment by efiop** [comment] 2019-09-09 01:34
Closing in favor of https://github.com/iterative/dvc/issues/2392

**Closed by efiop** 2019-09-09 01:34 UTC
Labels: bug, enhancement, p2-medium, ui
