### ISSUE TITLE
exp show: Allow running while DVC is locked

### ISSUE THREAD

**Issue by rogermparent** [iterative/dvc#5739] opened 2021-03-30 23:07 UTC
While working on a way to consume `dvc exp show --show-json`'s output, we found that DVC being locked while running an experiment can pose an issue when trying to show the table, especially if a long-running experiment were to be started outside the repo and a user wanted to view it in VS Code.

Would it be possible to have DVC CLI not check for a lock on read-only commands like `exp show`? Doing so could be huge for applications that want to consume DVC's output like the VSCode extension.

#3783 may also be related in that is helps solve this sort of usage.

**Comment by efiop** [comment] 2021-04-06 20:08
@rogermparent Could you please elaborate? Some example would be great.

**Comment by rogermparent** [comment] 2021-04-06 22:29
> @rogermparent Could you please elaborate? Some example would be great.

Sure, any DVC project capable of `exp show` can serve as an example, but to be specific the project I encounter this issue on is an embedded `https://github.com/iterative/dvc-checkpoints-mnist` that we use to test the VSCode Extension against.

The extension uses `dvc exp show --show-json` to update the table, but this command can fail if it is run while another command, usually `dvc exp run`, is locking the repo. There are many ways around this on the VSCode Extension end, of course, but the question of "Why does a lock prevent a read-only command" has come up enough in discussion to warrant a ticket on the DVC CLI project, for clarification if nothing else.

There's also related discussion going on in #5750, some of it may actually be more appropriate for this Issue.

**Comment by dberenbaum** [comment] 2021-04-07 20:52
@rogermparent Is this an intermittent error, or is there some reproducible example you can provide of when this happens? I'm trying to reproduce it now but keep getting the output in #5750 instead of any kind of error. Also, do you have the error output?

**Comment by pmrowla** [comment] 2021-04-08 03:35
@dberenbaum this is an actual issue, but it will be difficult to reproduce manually due to the nature of the problem. The error  itself will be this message:
https://github.com/iterative/dvc/blob/02d9684c339e80f7f50a0a278720273b97d91598/dvc/lock.py#L19-L22

During `dvc exp run`, the repo will be unlocked while we run the user's pipeline commands. The repo *will* be completely locked while DVC is doing anything else (like writing git commits, managing exp refs, etc).

As far as actual CPU execution time goes, 99+% of the time will be spent executing the user's pipeline (giving the output in #5750). If you are trying to test it manually it's unlikely you will run `dvc exp show` at precisely the right time to trigger the problem raised in this issue. But if you wrote a script to constantly run `dvc exp show` in a loop, you would see this issue eventually.

**Comment by rogermparent** [comment] 2021-04-08 15:26
Thanks for the explanation @pmrowla!

> As far as actual CPU execution time goes, 99+% of the time will be spent executing the user's pipeline (so the repo will be unlocked, giving the output in #5750). If you are trying to test it manually it's unlikely you will run `dvc exp show` at precisely the right time to trigger the problem raised in this issue.

No wonder I was having such a difficult time trying to make an explicit replication!

> But if you wrote a script to constantly run `dvc exp show` in a loop, you would see the "repo is locked" error eventually.

With how much the vscode extension calls `dvc`, I'm not surprised at this replication. Is there another `dvc` command that reliably locks the repo for a while?

**Comment by pmrowla** [comment] 2021-04-09 00:46
The repo is locked during pretty much any DVC command - it only gets unlocked for commands which execute user stage code (`dvc run`, `dvc repro`, `dvc exp run`).

You should be able to reproduce it if you set up some long running `dvc add` (add a directory with a very large # of files) or `dvc push/pull` (push/pull a large # of files) operation

**Comment by dberenbaum** [comment] 2021-05-18 15:45
@rogermparent Is this still an issue, or is it sufficient to retry if the repo is locked?

**Comment by rogermparent** [comment] 2021-05-18 17:31
> @rogermparent Is this still an issue, or is it sufficient to retry if the repo is locked?

The integration in question (and similar ones) could certainly get by with just retrying when locked, but there seems to be interest in this issue outside of that initial issue. I'm not partial one way or the other in this regard, even if it's closed it can be reopened if necessary.

**Comment by dberenbaum** [comment] 2021-05-18 17:59
Thanks! We can leave it open but good to know it's not a blocker for you.

**Comment by pmrowla** [comment] 2021-06-15 11:42
While working on https://github.com/iterative/dvc/pull/6174 I found a bug that was locking the entire main repo while running experiments in the background (via `--temp` or `--queue/--run-all`).

After that PR is merged the underlying issues where the repo will be locked during certain write operations will still be present, but in general `exp show` should be much more usable for VSCode (even while running experiments)

**Comment by pmrowla** [comment] 2021-09-23 06:52
To clarify the existing partial fix, the main DVC repo will still be locked during write operations (basically whenever DVC needs to do any git fetch/merge/commit operation in the main repo).

For experiments that are run in the main workspace, this means that the repo gets locked when the experiment run completes (and the final state is committed) or when `make_checkpoint` is running for an intermediate checkpoint.

For temp dir/queue runs, the main repo gets locked whenever we have to collect any checkpoints/experiment runs which have been completed (since the collection operation is a git fetch). Normally this only occurs at the very end of the experiment run, when all of the queued experiments are collected at once. However, we now also do collection during `exp show` (to get the "live" updating/state behavior).

---

It looks like what may be happening is that the "live update" `exp show` call might be hitting the repo at the same time as a `make_checkpoint` operation? But in that situation I would expect the command to just fail with the locked repo exception rather than hanging for as long as it does in the demo, so it probably is a DVC issue and not a vscode one. I'm also not sure why there would be different behavior on linux vs macos.

**Comment by rogermparent** [comment] 2021-10-04 21:00
> I'm also not sure why there would be different behavior on linux vs macos.

Agreed that it's weird, but from the latest updates on vscode-dvc#828, the issue replicates on Codespaces but hasn't on Macs so far, with `exp show` stalling on Linux and exiting with a lock error on Macs. This leads me to believe that there really is some platform-specific inconsistency with locks. I'll try on Windows today and see what happens there, I haven't actually checked yet nor do I think anybody else has.

**Comment by rogermparent** [comment] 2021-10-05 00:40
Just recorded a (way too long) demo of this on Windows- weirdly enough, it displays a similar bug but `exp show --show-json` _does_ fail with a lock error as opposed to hanging the whole like on my Linux replications- however, the symptoms on the table are similar and the first run per session seems to update more reliably than subsequent runs.

Also catches a crash at 8:40, similar ones have happened on Linux replications.

https://user-images.githubusercontent.com/9111807/135942703-8f73c657-1a9d-44fb-9674-aa01cb9835ec.mp4

**Comment by mattseddon** [comment] 2021-12-18 01:27
I have been able to repro `exp show` hanging with just the terminal. Details [here](https://github.com/iterative/vscode-dvc/issues/828#issuecomment-996437072).

**Closed** 2022-04-21 06:46 UTC
Labels: feature request, p1-important, external-product, A: experiments, diff/show
