### ISSUE TITLE
Support OmegaConf custom resolvers when using Hydra integration 

### ISSUE THREAD

**Issue by asiron** [iterative/dvc#9731] opened 2023-07-13 09:02 UTC
It seems that currently custom resolvers (described here: https://omegaconf.readthedocs.io/en/2.1_branch/custom_resolvers.html) are not supported when using DVC with Hydra integration.

I would like to do the following:
```yaml
pipeline:
    - 
        func: some_transform_name
        params:
            some_param: ${cv2:BORDER_CONSTANT}
            other_param: ${cv2:INTER_LINEAR}
```
By writing a custom resolver, we can resolve `cv2` namespace to load `BORDER_CONSTANT` and `INTER_LINEAR` dynamically (and do error checking as well) during hydra composition, which means we don't have to do this in our application.

Normally, you can add custom resolvers like this:
```python
import hydra
from hydra.utils import get_original_cwd
from omegaconf.dictconfig import DictConfig

from omegaconf import OmegaConf

OmegaConf.register_new_resolver("test", lambda x: f'{x} AAA')

@hydra.main(version_base=None, config_path=".", config_name="params")
def main(cfg: DictConfig) -> None:
    print(cfg)

if __name__ == '__main__':
    main()
```
but that is not possible, because DVC's Hydra composition is called here https://github.com/iterative/dvc/blob/2ef2caafd3f7c540caed4cb60fe3d9ff0255caf9/dvc/utils/hydra.py#L16-L53 before our DVC stage defined in `dvc.yaml`. Is it even the same process ? It seems that it would be quite tricky to implement this ? I'd be happy to implement it

**Comment by lefos99** [comment] 2024-01-02 10:56
As already posted by me in https://github.com/iterative/dvc/issues/10186, supporting OmegaConf would be really useful for my team as well:

Posted by me:
>Our project relies on custom OmegaConf resolvers, which are important for our configuration management. As noted in issue https://github.com/iterative/dvc/issues/9731, DVC currently does not support these custom resolvers, making it infeasible to switch to direct params.yaml reading without losing important functionality.
Is there a possibility to enhance DVC's compatibility with Hydra's features, specifically to support custom OmegaConf resolvers? This would allow us to utilize --set-param overrides (and usage of the VS code DVC addon as well) effectively while maintaining our existing configuration setup.

Concretely, we are using 3 different resolvers:
1. `${replace_with_dvc_exp_name:experiment_model}` -> This resolver replaces the experiment name with `DVC_EXP_NAME` if set. (More info [here](https://dvc.org/doc/command-reference/exp/run#-n))
2. `${get_path:data/models}` -> This resolver replaces the relative to the current sub-project path to the absolute path. This replacement is skipped with dvc (`if current dir.contains(.dvc)`) but is being used when calling individual Python scripts without DVC.
3. `${get_path_persistent:code/training}/out` -> Similar to 2, but this resolver **also** replaces the relative paths to absolute paths for isolated experiments (e.g. `dvc exp run --temp`). This is useful because we want to maintain generated files/logs/artifacts from an isolated experiment, without needing to pollute our local cache.

**Comment by dberenbaum** [comment] 2024-01-02 19:03
@lefos99 In your case, I wonder if it's enough to escape those custom resolvers? Taking your example from #10186, modify `conf/config.yaml` to use an escaped custom resolver like this:

```yaml
training:
  pl_hparams:
    max_epochs: '\${plus_10:11}'
```

Then resolve it in your code by reading from `params.yaml`:

```python
from omegaconf import DictConfig, OmegaConf
from ruamel.yaml import YAML


OmegaConf.register_new_resolver("plus_10", lambda x: x + 10)

def main() -> None:
    cfg = DictConfig(YAML(typ="safe").load(open("params.yaml")))
    print(cfg.training.pl_hparams.max_epochs)

if __name__ == "__main__":
    main()
```

**Comment by lefos99** [comment] 2024-01-10 11:30
> @lefos99 In your case, I wonder if it's enough to escape those custom resolvers? Taking your example from #10186, modify `conf/config.yaml` to use an escaped custom resolver like this:
> 
> ```yaml
> training:
>   pl_hparams:
>     max_epochs: '\${plus_10:11}'
> ```
> 
> Then resolve it in your code by reading from `params.yaml`:
> 
> ```python
> from omegaconf import OmegaConf
> 
> 
> OmegaConf.register_new_resolver("plus_10", lambda x: x + 10)
> 
> def main() -> None:
>     cfg = OmegaConf.load("params.yaml")
>     print(cfg.training.pl_hparams.max_epochs)
> 
> if __name__ == "__main__":
>     main()
> ```
> 
> `dvc exp run` will print out the resolved value `21` and `params.yaml` will look like:
> 
> ```yaml
> training:
>   pl_hparams:
>     max_epochs: ${plus_10:11}
> ```

Thanks for the suggestion, @dberenbaum! It does look like a smart approach for DVC. However, it might not be ideal for our use with pure Python scripts. Here are the concerns:

1. We'd need to run `dvc exp run --dry` to generate `params.yaml` for Python usage, adding extra steps to our workflow. 
2. Including `OmegaConf.register_new_resolver(...)` in numerous scripts would be quite cumbersome. 
3. The readability of our configs would suffer, changing from `max_epochs: ${plus_10:11}` to `max_epochs: '${plus_10:11}'`. 

Your insights are invaluable, and any further thoughts or updates on this matter would be greatly appreciated! 🙏💡

**Comment by dberenbaum** [comment] 2024-01-10 13:06
Thanks for the thoughtful reply @lefos99 

> 2\. Including `OmegaConf.register_new_resolver(...)` in numerous scripts would be quite cumbersome.

Not sure I understand this point. If you want to work with pure Python scripts, how do you use custom resolvers without including `OmegaConf.register_new_resolver(...)` in each script?

**Comment by lefos99** [comment] 2024-01-10 13:18
> Not sure I understand this point. If you want to work with pure Python scripts, how do you use custom resolvers without including OmegaConf.register_new_resolver(...) in each script?

We're leveraging [Hydra's plugins system](https://hydra.cc/docs/0.11/advanced/plugins/). This allows us to define our custom resolvers just once in a dedicated file within our project, typically at `git_project/hydra_plugin/resolvers.py`. Here's a glimpse of how it's set up:

```python
# git_project/hydra_plugin/resolvers.py

from omegaconf import OmegaConf

def plus_10(x: int) -> int:
  return x + 10

OmegaConf.register_new_resolver('plus_10', plus_10)
```
  
```python
# another script that uses hydra
# I do not need to define any resolver here
from omegaconf import DictConfig
import hydra

@hydra.main(version_base=None, config_path='conf', config_name='config')
def main(cfg: DictConfig) -> None:
    print(cfg)
```


By doing this, we avoid having to register resolvers in each individual script, keeping our codebase clean and dry. It's quite handy!

**Comment by asiron** [comment] 2024-01-10 13:46
Interesting! Thanks for the comments on how you solved this issue. One question comes to my mind, it seems that you basically compose your own "params.yaml" file in the entry script and the discard DVC produced `params.yaml`. Are you then overwriting it ? How do you ensure reproducibility ?

**Comment by lefos99** [comment] 2024-01-10 14:59
> Interesting! Thanks @lefos99 for the comments on how you solved this issue.

Just to be transparent, we have **not** solved the issue! We still would like to have the OmegaConf custom resolvers for DVC! Otherwise, we cannot use features like setting params on the fly (`dvc exp run --set-param`). Right now we haven't encountered any issue because we are using the hydra resolvers for `paths`, that **are not tracked in DVC** (they are not dependencies in the `dvc.yaml`). We are **not** using the resolvers for actual hyperparameters that can affect the reproducibility of an experiment.

> One question comes to my mind, it seems that you basically compose your own "params.yaml" file in the entry script and the discard DVC produced params.yaml. Are you then overwriting it ? 

In the end of the day, we have two sources of truth:
1. DVC `params.yaml` which doesn't use the resolvers.
2. Hydra `config/config.yaml` which uses the resolvers.

These sources of truth are completely identical apart from the parameters that are wrapped around resolvers (e.g. `${minus_10: 35}`).
For example, if you have a `config/config.yaml`:

```yaml
# config/config.yaml
training:
  pl_hparams:
    learning_rate: 10
    output_folder: ${replace_with_absolute_path:code/training/out}
``` 

This will result into:
1. `params.yaml`
```yaml
# params.yaml
training:
  pl_hparams:
    learning_rate: 10
    output_folder: code/training/out
``` 

2. `python` + `hydra` resolving:

```yaml
# inside python with the hydra resolver
training:
  pl_hparams:
    learning_rate: 10
    output_folder: /home/user/project/code/training/out
``` 

We do not discard the `params.yaml` (this is being used by DVC to create the `dvc.lock` file etc) but we ignore it in our Python scripts. In our Python scripts, we are using our normal hydra configs (e.g. `conf/config.yaml`) with the pre-defined Hydra resolvers.

**Comment by asiron** [comment] 2024-01-10 15:14
I see, thanks for the clarification. Wouldn't then the simplest solution be that DVC would load project Hydra plugins and use them during `dvc exp run` when the `params.yaml` is composed. It seems that it'd be somewhat similar to what @daavoo initially aluded to in his comment.

**Comment by lefos99** [comment] 2024-01-10 15:31
> I see, thanks for the clarification. Wouldn't then the simplest solution be that DVC would load project Hydra plugins and use them during `dvc exp run` when the `params.yaml` is composed. It seems that it'd be somewhat similar to what @daavoo initially aluded to in his comment.

100% agree with you! :smiley: 
It would then work for us out of the box!

**Comment by dberenbaum** [comment] 2024-01-10 21:50
I didn't know you could use plugins this way to globally register custom resolvers. This could be a promising way to do things if DVC can load those plugins. 

However, I have not initially found any documented support for this pattern where you load a custom resolver in `hydra_plugins`, and it seems a bit outside the scope of plugins, which are otherwise particular types of plugin classes (launchers, sweepers, etc.) inside submodules loaded by hydra. Before going further down this route, it would help to raise an issue in https://github.com/facebookresearch/hydra to clarify how to support global custom resolvers.

> We do not discard the `params.yaml` (this is being used by DVC to create the `dvc.lock` file etc) but we ignore it in our Python scripts. In our Python scripts, we are using our normal hydra configs (e.g. `conf/config.yaml`) with the pre-defined Hydra resolvers.

To get back to your original issue in #10186, regardless of how DVC will handle custom resolvers, resolving this issue will still not pass parameters from `dvc exp run --set-param` to `@hydra.main()`.

**Comment by lefos99** [comment] 2024-01-11 09:43
> To get back to your original issue in https://github.com/iterative/dvc/issues/10186, regardless of how DVC will handle custom resolvers, resolving this issue will still not pass parameters from dvc exp run --set-param to @hydra.main().

Quote regarding my issue:
> However, it might not be ideal for our use with pure Python scripts. Here are the concerns:
> 1. We'd need to run dvc exp run --dry to generate params.yaml for Python usage, adding extra steps to our workflow.
> 2. Including OmegaConf.register_new_resolver(...) in numerous scripts would be quite cumbersome.
> 3. The readability of our configs would suffer, changing from max_epochs: ${plus_10:11} to max_epochs: '\${plus_10:11}'.


Yes, you are absolutely right. If somehow in the future DVC manages to "understand" resolvers (e.g. `${plus_10:11}` -> `21` in `params.yaml`), which basically resolves my `2 & 3` issues, then we will **change our code to either read from `params.yaml`** in "`dvc exp` mode" or from `conf/config.yaml` in `Python` mode.

**Comment by lefos99** [comment] 2024-01-11 10:02
> Before going further down this route, it would help to raise an issue in https://github.com/facebookresearch/hydra to clarify how to support global custom resolvers.

I created an [issue](https://github.com/facebookresearch/hydra/issues/2835) for that. Feel free to comment on it. :slightly_smiling_face:

**Comment by dberenbaum** [comment] 2024-01-11 12:44
> Yes, you are absolutely right. If somehow in the future DVC manages to "understand" resolvers (e.g. `${plus_10:11}` -> `21` in `params.yaml`), which basically resolves my `2 & 3` issues, then we will **change our code to either read from `params.yaml`** in "`dvc exp` mode" or from `conf/config.yaml` in `Python` mode.

Note that another option is to write your commands in `dvc.yaml` like `python train.py ${training}` (see https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#dictionary-unpacking).

**Comment by lefos99** [comment] 2024-01-11 16:30
> Note that another option is to write your commands in `dvc.yaml` like `python train.py ${training}` (see https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#dictionary-unpacking).

Unfortunately, this is not a viable option for us because we have `experiment_names`, `input` and `output` paths in our `conf/config.yaml`, e.g. `output/tensorboard/fancy_experiment_1`, which we don't have as dependencies in the `dvc.yaml` right now. 
Then according to your suggestion, this path will be also tracked in the `dvc.lock` and it will disturb the reproducability.

For example, if I have done a `fancy_experiment_1` in the past with `hyperparameter: 1`, and I forgot about it and would like to run another one called `fancy_experiment_2` with `hyperparameter: 1`, then DVC will re-run the experiment because the command (`python train.py ${training}`) changed in the `dvc.lock`, although it's exactly about the same experiment.

**Comment by dberenbaum** [comment] 2024-01-12 18:50
It looks like we can support the plugins in DVC. The only nuance is that since DVC is composing the hydra config for the entire repo/pipeline, we cannot import `hydra_plugins` relative to a particular script or working directory, so we will likely only be able to discover plugins relative to the DVC repo root path.

**Comment by lefos99** [comment] 2024-01-16 11:46
> It looks like we can support the plugins in DVC.

Oh nice, that's fantastic news! Thank you @dberenbaum for going into this deep rabbit hole! :slightly_smiling_face: 

> The only nuance is that since DVC is composing the hydra config for the entire repo/pipeline, we cannot import `hydra_plugins` relative to a particular script or working directory, so we will likely only be able to discover plugins relative to the DVC repo root path (like `repo/hydra_plugins/resolvers.py`).
> 
> Edit: The other alternative would be to provide a config option to specify the path to the Hydra plugins.

Both options sound good to me, but the latter would be the best for us. In our repo, we have multiple DVC sub-projects, which use custom resolvers. So defining only once and then specifying the hydra plugins path would be ideal!

**Closed** 2024-01-23 14:13 UTC
Labels: feature request, p3-nice-to-have, A: hydra
