### ISSUE TITLE
dvc pull --glob '*.extension' directory: does not filter based on extension. 

### ISSUE THREAD

**Issue by zoevannoppen** [iterative/dvc#6671] opened 2021-09-22 10:15 UTC
# Bug Report

## Description

Try pulling only files with a certain extension from my remote does not work. All files seem to be pulled independent of the extension. 

### Reproduce

1. Have a dvc tracked directory called _directory_name_ with certain files with extension _ext_. 
2. Make sure that the files within this directory are not located locally but only on the remote. 
3. run `dvc pull --glob '*.ext' directory_name`

### Expected

It is expected that only files with .ext extension get pulled locally. 

### Environment information

**Output of `dvc doctor`:**

```
DVC version: 2.7.4 (brew)
---------------------------------
Platform: Python 3.9.7 on macOS-11.5.2-x86_64-i386-64bit
Supports:
	azure (adlfs = 2021.9.1, knack = 0.8.2, azure-identity = 1.6.1),
	gdrive (pydrive2 = 1.9.4),
	gs (gcsfs = 2021.8.1),
	http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
	https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.5),
	s3 (s3fs = 2021.8.1, boto3 = 1.17.106),
	ssh (sshfs = 2021.8.1),
	webdav (webdav4 = 0.9.2),
	webdavs (webdav4 = 0.9.2)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s1s1
Caches: local
Remotes: gs
Workspace directory: apfs on /dev/disk1s1s1
Repo: dvc, git
```

**Additional Information (if any):**
A person named Pared in the dvc discord could already reproduce the issue.

**Comment by pared** [comment] 2021-09-22 12:48
Reproduction script:
```
#!/bin/bash

set -ex

pushd $TMPDIR

rm -rf test_wspace
mkdir test_wspace
pushd test_wspace

WSPACE=$(pwd)

mkdir test_repo
pushd test_repo

git init
dvc init

dvc remote add -d str $WSPACE/remote
echo data.txt >> data.txt
echo data.jpg >> data.jpg

dvc add data.txt data.jpg

git add -A
git commit -am "init"

dvc push

rm -rf .dvc/cache
rm data.txt data.jpg

dvc pull --glob *.txt
tree .dvc/cache
```

**Comment by pmrowla** [comment] 2021-09-23 02:48
This is a duplicate of https://github.com/iterative/dvc/issues/5864

The issue is just that the existing implementation of `--glob` is very naive - it can only apply glob patterns to files which already exist in the local workspace. It does not support globbing against outputs within the repo tree (that do not already exist in the workspace).

Basically `--glob` is currently only useful for updating some subset of previously checked out or pulled data, or for pushing some subset of the existing data in your workspace.

**Comment by pmrowla** [comment] 2021-09-23 02:50
Also, just noting that the reproduction script doesn't actually reproduce the issue:

```
dvc pull --glob *.txt
```

This should be

```
dvc pull --glob '*.txt'
```

Without the quotes, the glob pattern will be expanded in your shell (against the local filesystem) rather than being handled by DVC (as a target glob pattern)

**Comment by pmrowla** [comment] 2021-09-23 02:51
closing in favor of #5864

**Closed by pmrowla** 2021-09-23 02:51 UTC
Labels: :bug: bug, p2-medium
