### ISSUE TITLE
dvc checkout will leave empty folders

### ISSUE THREAD

**Issue by glema-gpsw** [iterative/dvc#2397] opened 2019-08-14 21:42 UTC
`dvc checkout` doesn't restore the exact snapshot as it was in a previous state.
For example if you create a new folder and add files, and want to go back to a previous commit, where this folder and the files didn't exist, it will still show the folder, but empty.

Below you will find a reproducer of the problem.

```
#!/bin/bash                            
                                       
set -e                                 
set -x                                 
                                       
rm -rf myrepo                          
mkdir myrepo                           
cd myrepo                              
                                       
git init                               
dvc init                               
                                       
mkdir dir                              
dvc run -o dir/foo 'echo foo > dir/foo'
                                       
rm foo.dvc                             
                                       
dvc checkout                           
                                       
tree
```

**Comment by efiop** [comment] 2019-08-14 22:25
Discord context https://discordapp.com/channels/485586884165107732/485596304961962003/611308909470416898

**Comment by efiop** [comment] 2019-09-10 15:47
We are most likely using utils.remove method, so we probably need to make it remove empty parent directories up to repo root.

**Comment by efiop** [comment] 2019-09-10 16:01
Ok, as we've discovered with @iterative/engineering , this
```
mkdir dir                              
dvc run -o dir/foo 'echo foo > dir/foo'
```
is actually wrong and `dvc repro` will break on it, because the command itself should be able to create all the needed subdirectories. 

But even if we include `mkdir sbudir`, when you `clone` this repo elsewhere and you `dvc checkout`, dvc will automatically create that directory, so it should also remove it when it checks out elsewhere.

**Comment by dmpetrov** [comment] 2020-02-03 09:10
@efiop you explained that the first case is not correct. Could you please clarify with the second one - does DVC works properly and should we close this issue?

**Comment by efiop** [comment] 2020-02-03 23:32
@dmpetrov No longer able to reproduce. Everything works as expected. Closing. Thanks for the heads up!

**Comment by pokey** [comment] 2020-10-12 11:00
I am still able to reproduce this issue:

```sh
➜ dvc init --no-scm
+---------------------------------------------------------------------+
|                                                                     |
|        DVC has enabled anonymous aggregate usage analytics.         |
|     Read the analytics documentation (and how to opt-out) here:     |
|             <https://dvc.org/doc/user-guide/analytics>              |
|                                                                     |
+---------------------------------------------------------------------+

What's next?
------------
- Check out the documentation: <https://dvc.org/doc>
- Get help and share ideas: <https://dvc.org/chat>
- Star us on GitHub: <https://github.com/iterative/dvc>
➜ ls -a
.dvc  .dvcignore
➜ mkdir foo
➜ dvc add foo
WARNING: 'foo' is empty.
➜ ls
foo/  foo.dvc
➜ cat foo.dvc
outs:
- md5: d751713988987e9331980363e24189ce.dir
  path: foo
➜ touch foo/bar.txt
➜ dvc checkout
file 'foo/bar.txt' is going to be removed. Are you sure you want to proceed? [y/n] y
M       foo/
➜ ls foo
➜ mkdir foo/bar
➜ dvc checkout
➜ ls foo
bar/
```

At the end, I'd expect `foo/bar` to have been removed

**Comment by pared** [comment] 2020-10-13 10:31
Seems like its still an issue:
```
def test_checkout_empty_dir(tmp_dir, dvc):
    tmp_dir.dvc_gen({"empty_dir":{}})
    tmp_dir.gen({"empty_dir": {"subdir": {}}})

    dvc.checkout()

    assert not os.path.exists(tmp_dir / "empty_dir" / "subdir")
```
This test fails. Seems like our [check](https://github.com/iterative/dvc/blob/0649242578b5d6dbbdf6e7e7124870fb26b3f173/dvc/cache/base.py#L553) falsely reports that the directory is unchanged. This is probably due to the way we calculate cache for dir: introducing empty directories does not influence dir hash. 

Obvious fix: introduce directories (even empty) information to dir hash is probably a no-go - that will make all dir hashes calculated prior to change invalid.

**Comment by efiop** [comment] 2020-10-18 09:00
>  This is probably due to the way we calculate cache for dir: introducing empty directories does not influence dir hash.

> Obvious fix: introduce directories (even empty) information to dir hash is probably a no-go - that will make all dir hashes calculated prior to change invalid.

Great points! Just for the record: that behaviour might be revisited in https://github.com/iterative/dvc/issues/829#issuecomment-711137723

But yeah, for now we could potentially just add some logic to clean up such cases.

**Comment by mvonpohle** [comment] 2022-01-28 01:40
I'll just chime in and say that I'm still experiencing this problem on DVC 2.4.1.

**Comment by alanbuxton** [comment] 2022-01-28 21:37
> I'll just chime in and say that I'm still experiencing this problem on DVC 2.4.1.

Same on 2.9.3. Deleted some directories on one machine, pushed to remote, pulled this to my other machine and the directories remained, but were empty.

**Comment by efiop** [comment] 2022-01-28 22:29
@alanbuxton Sounds like you are tracking an empty directory, right? If so, that is correct dvc behaviour (it saved that the dir is empty and re-creates it empty on pull/checkout). This ticket is about leaving empty directories when switching from one version to another.

**Comment by alanbuxton** [comment] 2022-03-13 14:18
@efiop yes makes sense. Apols for getting wrong end of the stick.

**Comment by narbhar** [comment] 2022-07-12 21:45
I still face this issue in version 2.13.0
In my case I created two versions of the dataset. Let's say the dataset folder is called "numbers". This has folders with all odd numbered named folders until 10 with, for e.g, "one", "three", "five"... and so on. I tag this on git as "odd"
Now I make changes to the dataset and remove all the folders inside "numbers" and replace then with a new set of folders whose folder names are all even numbered names now, for e.g, "two", "four", "six"... until 10.  I tag this on git as "even"
Note: I perform `dvc add <folder>` and those necessary steps to push the datasets. 

I delete the dataset folder now. If I type `dvc checkout` it rebuilds the dataset with "even" folders since it is the latest dataset in cache.
Now I wish to revert to "odd" dataset. I do
`git checkout odd`
`dvc checkout`

My numbers folder now has odd numbered folders and **empty folders** from "even" dataset.  
Now I want to go the latest head on git for latest version of dataset. I do
`git checkout -`
'dvc checkout`
This now has empty folders from "odd" dataset along with populated "even" folders.

**Comment by efiop** [comment] 2023-12-08 11:41
Checkout now deletes empty folders. Closing.

**Closed by efiop** 2023-12-08 11:41 UTC
Labels: bug, p2-medium
