### ISSUE TITLE
DVC diff tool support (like git difftool)

### ISSUE THREAD

**Issue by Voxelworld** [iterative/dvc#7657] opened 2022-04-28 16:17 UTC
Hi all

I had a discussion on _discord_ regarding a common usecase which may be of general interest.

I would like to use DVC for versioning a larger ML repo (~30K folders, 200K files). A typical workflow would be that a script or user is adding and improving data in the workspace, and afterwards I would like to check the changes for some samples, before adding them.
`dvc diff` lists the changed files and hashes, but currently there is no support to pass two file versions to a diff tool directly.

Ideally I would like to configure different tools for diffs on binary files (like images and masks) and text files (like json files) by its extension.
Is this a usecase worth supporting in future DVC versions?

'skshetry' suggested to extend it using dvc diff --json data and create an own script that calls specific difftools. Has someone in the community already implemented this workaround?

**Comment by casperdcl** [comment] 2023-01-27 16:56
Duplicate of #770?

**Comment by dberenbaum** [comment] 2023-01-27 17:12
Closing as duplicate

**Closed by dberenbaum** 2023-01-27 17:12 UTC
Labels: feature request, diff/show

**Comment by casperdcl** [comment] 2023-01-27 18:46
Thanks @Voxelworld for the request though, please do upvote/track #770 :)
