### ISSUE TITLE
remote add: does not fail in non-DVC repo 

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#3191] opened 2020-01-18 21:43 UTC
*Version:*

```
WARNING: Unable to detect supported link types, as cache directory '.dvc/cache' doesn't exist. It is usually auto-created by commands such as `dvc add/fetch/pull/run/import`, but you could create it manually to enable this check.
DVC version: 0.81.3+7f5e4a
Python version: 3.7.5
Platform: Darwin-18.2.0-x86_64-i386-64bit
Binary: False
Package: None
```

*Reproduce:*

```
mkdir project
cd project
dvc remote add storage gdrive://root/storage
```

should probably fail.

next command fails:

```
dvc remote modify storage gdrive_client_id test
ERROR: configuration error - config file error: unable to find remote section 'storage'
```

message should be different - no config file, or repo is not DVC, etc.

**Comment by mroutis** [comment] 2020-01-19 03:42
Closing, duplicate of https://github.com/iterative/dvc/issues/2309

**Comment by mroutis** [comment] 2020-01-19 03:43
ohhh, my bad @shcheklein, definitely related but this is about `add`, mine was about `modify`.

**Comment by mroutis** [comment] 2020-01-19 03:44
Anyways, I think both `add` and `modify` should fail if `--global` or `--system` is not specified.

**Comment by efiop** [comment] 2020-01-19 07:40
Closing in favor https://github.com/iterative/dvc/issues/2309

**Closed by efiop** 2020-01-19 07:40 UTC
Labels: triage
