### ISSUE TITLE
Mercurial SCM support

### ISSUE THREAD

**Issue by crobarcro** [iterative/dvc#1230] opened 2018-10-17 11:20 UTC
I've begun implementing a mercurial SCM class to allow supporting mercurial as the scm in my fork. See here: https://github.com/crobarcro/dvc/blob/master/dvc/scm.py

It requires you install python-hglib which you can do with

`pip install python-hglib`

I've not actually tested it, as I need some help finishing it off. Are you interested in helping with this, and would you then be willing to integrate into the main repo? The main issue is the 'install' method, and then testing it.

**Comment by crobarcro** [comment] 2018-10-17 11:36
Doh, just saw this: https://github.com/iterative/dvc/pull/1212

This is better than mine. At least you know there's demand!

**Comment by efiop** [comment] 2018-10-17 11:39
Hi @crobarcro !

No worries :slightly_smiling_face:  Thank you for your interest!

Closing as a duplicate of #945.

Thanks,
Ruslan

**Closed by efiop** 2018-10-17 11:39 UTC
