### ISSUE TITLE
push: ERROR: unexpected error - pickle protocol must be <= 4 

### ISSUE THREAD

**Issue by paprocki-r** [iterative/dvc#7324] opened 2022-01-31 13:20 UTC
# Bug Report

push: ERROR: unexpected error - pickle protocol must be <= 4 

### Reproduce

Following tutorial https://dvc.org/doc/start/data-and-model-versioning
dvc init

1. dvc init
2. Copy dataset to the directory (dozens of files, overall ~500MB)
3. dvc add dataset
4. dvc commit -m "new dataset"
5. dvc push

### Expected

I expected all files to appear on the remote 

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```

dvc doctor
---------------------------------

DVC version: 2.8.1 (snap)
Platform: Python 3.6.9 on Linux-4.15.0-163-generic-x86_64-with-Ubuntu-18.04-bionic
Supports:
        azure (adlfs = 2021.9.1, knack = 0.8.2, azure-identity = 1.6.1),
        gdrive (pydrive2 = 1.10.0),
        gs (gcsfs = 2021.10.0),
        webhdfs (fsspec = 2021.10.0),
        http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.6),
        s3 (s3fs = 2021.10.0, boto3 = 1.17.106),
        ssh (sshfs = 2021.9.0)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/mapper/vg01-root
Caches: local
Remotes: local
Workspace directory: ext4 on /dev/mapper/vg01-root

**Additional Information (if any):**

**Comment by efiop** [comment] 2022-01-31 13:23
Duplicate of https://github.com/iterative/dvc/issues/7220

We'll be releasing a new version this week ,but you could try upstream version for now: https://dvc.org/doc/install/pre-release

**Closed by efiop** 2022-01-31 13:23 UTC

**Comment by pmrowla** [comment] 2022-02-02 05:45
> Platform: Python 3.6.9 on Linux-4.15.0-163-generic-x86_64-with-Ubuntu-18.04-bionic

Also, please note that DVC no longer supports Python 3.6, so you won't be able to use the latest release (or the upstream version) without installing Python 3.7+ on that machine.
