### ISSUE TITLE
dvc file data size changes in windows and ubuntu

### ISSUE THREAD

**Issue by legendof-selda** [iterative/dvc#7422] opened 2022-02-25 20:16 UTC
# Bug Report

## Description

When multiple teammates use dvc in different systems and update data files, due to the difference in line endings, I believe that the size of the file saved in `.dvc` tracking file changes. This causes modified commits in git and increases the chances of merge conflicts. I have an automated script which  fetches files from an api, unzips it using pandas gzip compression, which we then update using dvc! Since, multiple teammates who uses different OS, when they download the same file, dvc detects the one pushed from windows to be different than the one pushed from ubuntu!

### Reproduce

1. In windows, pandas create a dataframe and save it as `.csv`
2. In windows do `dvc add` on a `.csv` file and do `dvc push`
3. Then do `git add` and then `git push`
4. Another user in ubuntu system, on the same branch does a `git pull` to get the latest `.dvc` file
5. The same dataframe is made in pandas and saved as `.csv` in the ubuntu system. Exact same contents
6. Now do `dvc add` to the file, the `.dvc` will be modified. The modification is only in the key `size` but the hash remains the same

### Expected

The dataset contents are the same, so should the hash and the size be as well! On running `ls -l` in ubuntu or looking at the file properties in windows, the number of bytes remain the same! But in the `.dvc` file the file sizes have changed.
Expected that the size calculation must take into consideration the line endings

### Environment information

Windows
```
DVC version: 2.9.3 (pip)
---------------------------------
Platform: Python 3.8.5 on Windows-10-10.0.19041-SP0
Supports:
        azure (adlfs = 0.7.2, knack = 0.8.1, azure-identity = 1.5.0),
        gdrive (pydrive2 = 1.9.0),
        hdfs (fsspec = 2022.1.0, pyarrow = 3.0.0),
        webhdfs (fsspec = 2022.1.0),
        http (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.7.4.post0, aiohttp-retry = 2.4.6)
Cache types: hardlink
Cache directory: NTFS on D:\
Caches: local
Remotes: azure
Workspace directory: NTFS on D:\
Repo: dvc, git
```

ubuntu
```
DVC version: 2.9.3 (pip)
---------------------------------
Platform: Python 3.8.12 on Linux-5.4.0-1070-azure-x86_64-with-glibc2.17
Supports:
        azure (adlfs = 2021.10.0, knack = 0.9.0, azure-identity = 1.7.1),
        webhdfs (fsspec = 2022.1.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sda1
Caches: local
Remotes: azure
Workspace directory: ext4 on /dev/sda1
Repo: dvc, git
```

**Additional Information (if any):**

**Comment by daavoo** [comment] 2022-02-28 08:38
Hi @legendof-selda , what is the result of running the following on the `.csv` file:

```
import os
os.stat(f'{csv_fie}').st_size
```
Is it different from ubuntu and windows?

**Comment by pmrowla** [comment] 2022-02-28 08:53
This is probably a duplicate of https://github.com/iterative/dvc/issues/6314 (and the linked original discussion from that issue). The problem is that we compute the hash using `dos2unix` line ending conversion on the CSV, but we don't use the conversion for the file size field (so the hash is consistent between windows/unix, but the size is whatever the OS reports, which will be bigger on windows due to CRLF line endings).

The workaround would be to explicitly set `line_terminator` in your code that uses panda `to_csv()`, so that you generate consistent line endings on both linux and windows.

**Comment by legendof-selda** [comment] 2022-03-02 12:31
I believe this work around is great! but it would be great while running `dvc add` this could be dealt with automatically rather than developers ensuring it. Feel free to close this issue but I would request that this feature be added in the next version of dvc.
Thank you so much @daavoo and @pmrowla for the quick response and support

**Comment by pmrowla** [comment] 2022-03-04 06:51
Closing in favor of #6314

**Closed by pmrowla** 2022-03-04 06:51 UTC
Labels: :bug: bug, A: data-management
