### ISSUE TITLE
add/etc: better handle file tracking crashes [qa]

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#4349] opened 2020-08-06 23:27 UTC
## Report

DVC moves data files to the cache and changes their file permissions (to 444), but if anything goes wrong (e.g. `dvc add` a file owned by another user, so DVC can't change the perms) the process crashes (some error is thrown) but not before disappearing the data file.

These complex operations should probably behave like transaction, or have some sort of backup mechanism to roll back the caching of the file if any error is thrown.

### Please provide information about your setup

DVC 1.3
(Tried on Linux)

**Additional Information (if any):**

Context: https://discord.com/channels/485586884165107732/485596304961962003/740974097063739423 (starts before that)

**Comment by efiop** [comment] 2020-08-07 01:14
Duplicate of https://github.com/iterative/dvc/issues/4348

**Closed by efiop** 2020-08-07 01:14 UTC
Labels: enhancement

**Comment by jorgeorpinel** [comment] 2020-08-07 02:09
Thanks. I looked for key words "add owner permissions" and didn't find any issues so opened this one.
