### ISSUE TITLE
exp run --queue ignores local untracked files

### ISSUE THREAD

**Issue by igordertigor** [iterative/dvc#8854] opened 2023-01-20 15:20 UTC
# Bug Report
This bug report is a [cram test](https://bitheap.org/cram/) and can run "as is".

```
When running dvc experiments in a queue, untracked local files are not included. To reproduce, use the following
  $ git init
  warning: templates not found in /home/ingo/Code/rcfiles/git/
  Initialized empty Git repository in /tmp/.* (re)
  $ dvc init
  Initialized DVC repository.
  
  You can now commit the changes to git.
  
  +---------------------------------------------------------------------+
  |                                                                     |
  |        DVC has enabled anonymous aggregate usage analytics.         |
  |     Read the analytics documentation (and how to opt-out) here:     |
  |             <https://dvc.org/doc/user-guide/analytics>              |
  |                                                                     |
  +---------------------------------------------------------------------+
  
  What's next?
  ------------
  - Check out the documentation: <https://dvc.org/doc>
  - Get help and share ideas: <https://dvc.org/chat>
  - Star us on GitHub: <https://github.com/iterative/dvc>
  $ git commit -m "Initial commit" .dvc/ .dvcignore
  [master (root-commit) *] Initial commit (glob)
   3 files changed, 6 insertions(+)
   create mode 100644 .dvc/.gitignore
   create mode 100644 .dvc/config
   create mode 100644 .dvcignore
  $ echo "
  > stages:
  >   needs local file:
  >     cmd: cp localfile.txt result.txt
  >     outs:
  >       - result.txt
  >     params:
  >       - id
  > " > dvc.yaml
Note two things here: (i) we added an id parameter here that isn't used explicitly, but makes sure we don't pull results from the cache (ii) we copy a localfile that *isn't tracked by git nor is listed as a dependency*. Let's make sure the local file actually exists.
  $ echo "some text" > localfile.txt
The issue is that we can access this file with some ways of running the experiment but not with others.

Let's first store the pipeline and params in git:
  $ echo "id: 1" > params.yaml
  $ git add dvc.yaml params.yaml
  $ git commit -m "Pipeline"
  [master *] Pipeline (glob)
   2 files changed, 10 insertions(+)
   create mode 100644 dvc.yaml
   create mode 100644 params.yaml

The first way of running an experiment is by running
  $ dvc repro && dvc exp save
  Running stage 'needs local file':
  ? cp localfile.txt result.txt (glob)
  Generating lock file 'dvc.lock'
  Updating lock file 'dvc.lock'
  
  To track the changes with git, run:
  
  * (glob)
  
  To enable auto staging, run:
  
  \tdvc config core.autostage true (esc)
  Use `dvc push` to send your updates to remote storage.
  \x1b[33mWARNING\x1b[39m: The following untracked files were present in the workspace before saving but will not be included in the experiment commit: (esc)
  * (glob)
  Experiment has been saved as: * (glob)
  
  To promote an experiment to a Git branch run:
  
  \tdvc exp branch <exp> <branch> (esc)
  
This works mostly without issues. But note the warning about untracked files.

The second way of running an experiment is by running:
  $ dvc exp run -S 'id=2'
  Running stage 'needs local file':
  ? cp localfile.txt result.txt (glob)
  Updating lock file 'dvc.lock'
  
  To track the changes with git, run:
  
  * (glob)
  
  To enable auto staging, run:
  
  \tdvc config core.autostage true (esc)
  
  Ran experiment(s): * (glob)
  Experiment results have been applied to your workspace.
  
  To promote an experiment to a Git branch run:
  
  \tdvc exp branch <exp> <branch> (esc)
  
Here, we set the id to 2 to keep dvc from using cached results.

Finally, we should be able to queue the experiment and then run it from the queue:
  $ dvc exp run --queue -S 'id=3'
  Queueing with overrides '{'params.yaml': ['id=3']}'.
  Queued experiment '.*' for future execution. (re)
  $ EXP=$(dvc queue status | grep Queued | awk '{print $2}')
  $ dvc queue start
  Started '1' new experiments task queue worker.
  $ sleep 4
  $ dvc queue logs "$EXP"
  Running stage 'needs local file':
  ? cp localfile.txt result.txt (glob)
  cp: cannot stat 'localfile.txt': No such file or directory
  ERROR: failed to reproduce 'needs local file': failed to run: cp localfile.txt result.txt, exited with 1
  ERROR: failed to reproduce 'needs local file': failed to run: cp localfile.txt result.txt, exited with 1
  
However, in this case, the local file `localfile.txt` can't be found. A typical case where this would happen is if we have an experiment that wasn't initally configured as a checkpoint experiment, but we stored a checkpoint and want to try using it for a single run.
```

I would have expected that the queued experiment runs the same as the non-queued. Personally, I would prefer a solution that respects the `localfile.txt`, but I could also live with a solution that generally doesn't respect it.

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.42.0 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.4.0-131-generic-x86_64-with-glibc2.29
Subprojects:
	dvc_data = 0.34.0
	dvc_objects = 0.18.1
	dvc_render = 0.0.17
	dvc_task = 0.1.11
	dvclive = 1.3.2
	scmrepo = 0.1.6
Supports:
	http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3)
```

**Comment by dberenbaum** [comment] 2023-01-21 12:51
Thanks for the report @igordertigor! It looks like a duplicate of #5800, so I'm going to close it since there's already a lot of discussion in that one.

**Closed** 2023-01-21 12:51 UTC
