### ISSUE TITLE
ssh: dvc hangs if the find command takes more than 8 seconds to run on remote

### ISSUE THREAD

**Issue by gcoter** [iterative/dvc#1104] opened 2018-09-09 14:45 UTC
As we discussed in #1059, I have been experiencing an issue when pushing data to my personal server through SSH: it just hangs forever. It turns out that it is related to the execution time of the `find` command (used to see which files have already been uploaded to the server).

Here is how I reproduced the bug:

1. I created an empty cache on my server
2. I ran `dvc push --jobs 4` and interrupted when half of the files were uploaded
3. On my server, I ran `time find my/remote/cache -type f -follow -print` to measure how much time it takes
4. I repeated steps 2 and 3 until step 2 hangs.

As long as the execution time of the `find` command (measured at step 3) is lower than 8 seconds, `dvc push` run without hanging. But when it exceeds 8 seconds, it hangs.

At this point, it is possible to solve the problem by adding: `import time; time.sleep(10)` at [this line](https://github.com/iterative/dvc/blob/0.18.14/dvc/remote/ssh.py#L115). In other words, we have to make the program wait longer than 8 seconds *before* the `stdout.channel.recv` call at [line 120](https://github.com/iterative/dvc/blob/0.18.14/dvc/remote/ssh.py#L120). It seems that `recv` cannot wait longer than 8 seconds, for some reason.

I am not sure whether this limit of 8 seconds depends on my particular setup. Maybe in your case, it will be 10 seconds, or 30 seconds. So, I don't think my fix with `time.sleep` is generic enough.

**Comment by efiop** [comment] 2018-09-09 14:51
Thank you for a such detailed description! Looking into it right now.

**Comment by efiop** [comment] 2018-09-09 16:05
Unfortunately I'm not able to reproduce on my servers :( Is there something special about your server or is it a classic linux server?

Looking at the code, there is a suspicion that maybe calling recv() before recv_ready() might cause such issues, so I've merged a patch for that into master. Could you please try it out by installing a development version from our git repo? I.e. `pip uninstall -y dvc; pip install git+https://github.com/iterative/dvc`.

**Comment by gcoter** [comment] 2018-09-09 19:09
It seems to work now!

My server is just a Raspberry Pi (Raspbian Stretch) with nothing special. It is strange that you couldn't reproduce the issue. But since it works now, it doesn't matter.

Thank you very much :)

**Comment by gcoter** [comment] 2018-09-09 19:11
I will push my other projects to my server soon, I will let you know if I encounter this issue again.

Thank you again!

**Comment by efiop** [comment] 2018-09-09 19:33
Glad to hear it worked!

> My server is just a Raspberry Pi (Raspbian Stretch) with nothing special. It is strange that you couldn't reproduce the issue. But since it works now, it doesn't matter.

Wouldn't call that a "classic linux server" since it is ARM after all :slightly_smiling_face: I also have one lying around and if the issue will arise again, I might pull it out to see if I will be able to reproduce :slightly_smiling_face:

Thank you so much for all the feedback you've provided!

**Comment by efiop** [comment] 2018-09-21 06:32
Closing this for now. Please feel free to reopen.

**Closed by efiop** 2018-09-21 06:32 UTC
Labels: bug
