### ISSUE TITLE
exp queue: start/stop queue processing

### ISSUE THREAD

**Issue by pmrowla** [iterative/dvc#7589] opened 2022-04-19 07:35 UTC
Implement basic CLI support for starting and stopping processing of the exp queue.

* [x] `dvc queue start`: start queue processing
    * Should support setting an initial `-j/--jobs` concurrency value
    * Subsequent calls should do nothing (other than informational messaging that queue is already running)
* [x] `dvc queue stop`: stop queue processing
    * Should use celery [shutdown](https://docs.celeryq.dev/en/v4.2.1/reference/celery.app.control.html#celery.app.control.Control.shutdown) to stop queue processing (after currently running experiments complete)
    * Likely requires setting up a celery [signal handler](https://docs.celeryq.dev/en/stable/userguide/signals.html) that runs when our exp cleanup tasks complete, and broadcasting the worker shutdown from there (since by default celery exits after completing the current task but we want it to exit after completing the current *task chain*)

**Comment by dberenbaum** [comment] 2022-05-20 18:29
It's hard to tell what's happening here without status commands, but here's what happens when I run `dvc queue start`:

```console
$ dvc exp run --queue -S train.min_split=0.04
Queued experiment '92aa804' for future execution.
$ dvc exp show --no-pager
 ────────────────────────────────────────────────────────────────────────────────────
  Experiment              Created   State    avg_prec   …   prepa…   …   data/d…   …
 ────────────────────────────────────────────────────────────────────────────────────
  workspace               -         -           0.925   …   0.2      …   22a1a29   …
  10-bigrams-experiment   May 06,   -          0.9202   …   0.2      …   22a1a29   …
                          2022
  └── 92aa804             02:27     Queued          -   -   0.2      …   22a1a29   …
                          PM
 ────────────────────────────────────────────────────────────────────────────────────
$ dvc queue start
Start 1 queue worker to process the queue tasks
$ dvc exp show --no-pager
 ────────────────────────────────────────────────────────────────────────────────────
  Experiment           Created       avg_prec   …   prepare.s…   …   data/data.…   …
 ────────────────────────────────────────────────────────────────────────────────────
  workspace            -                0.925   …   0.2          …   22a1a29       …
  bigrams-experiment   May 06,         0.9202   …   0.2          …   22a1a29       …
                       2022
 ────────────────────────────────────────────────────────────────────────────────────
$ cat .dvc/tmp/exps/run/92aa804c4ab54112377be94783004030cc3f2d42/92aa804c4ab54112377be94783004030cc3f2d42.out
'data/data.xml.dvc' didn't change, skipping
Stage 'prepare' didn't change, skipping
Stage 'featurize' didn't change, skipping
Running stage 'train':
> python src/train.py data/features model.pkl
Input matrix size (7996, 202)
X matrix size (7996, 200)
Y matrix size (7996,)
ERROR: failed to reproduce 'train': 'QueryingProgress' object has no attribute 'desc'
ERROR: failed to reproduce 'train': 'QueryingProgress' object has no attribute 'desc'
```

**Comment by dberenbaum** [comment] 2022-06-01 17:12
@pmrowla @karajan1001 I still see the error above when trying to run a queued experiment. Is that still expected?

**Comment by pmrowla** [comment] 2022-06-02 00:52
@dberenbaum it's expected due to the dev branch being behind main. I'll be rebasing it so everything is up to date today.

**Comment by pmrowla** [comment] 2022-06-02 03:58
dev branch has been rebased, the QueryingProgress error should be resolved now

**Comment by dberenbaum** [comment] 2022-06-02 15:06
Looks good, thanks!

**Comment by dberenbaum** [comment] 2022-06-02 17:35
`queue stop` seems like it fails to clear the currently running experiments from the queue once they complete:

```console
$ dvc exp run --queue -S prepare.split=0.1
Queued experiment 'd78dafd' for future execution.
$ dvc exp run --queue -S prepare.split=0.15
Queued experiment '4b9348a' for future execution.
$ dvc exp run --queue -S prepare.split=0.05
Queued experiment 'a0ece9c' for future execution.
$ dvc exp run --queue -S prepare.split=0.25
Queued experiment '2ffbb73' for future execution.
$ dvc exp run --queue -S prepare.split=0.3
Queued experiment 'dc2452e' for future execution.
$ dvc queue status
Rev                                       Name    Created    Status
dc2452ea4dc6e94be25fdc31ef82ea51ea46fc28          01:31 PM   Queued
a0ece9c6d03dc26251cc9664d6ccef47ccf4903b          01:31 PM   Queued
2ffbb7381ac8bd8b159a09af88cea559419324e8          01:31 PM   Queued
4b9348a2b8342d57f58f632c3034cf6119f405e1          01:31 PM   Queued
d78dafd9a7cdb112f9596f7d67a97028a7047f1c          01:30 PM   Queued
$ dvc queue start
Start 1 queue worker to process the queue tasks
$ dvc queue status
Rev                                       Name    Created    Status
dc2452ea4dc6e94be25fdc31ef82ea51ea46fc28          01:31 PM   Running
a0ece9c6d03dc26251cc9664d6ccef47ccf4903b          01:31 PM   Queued
2ffbb7381ac8bd8b159a09af88cea559419324e8          01:31 PM   Queued
4b9348a2b8342d57f58f632c3034cf6119f405e1          01:31 PM   Queued
d78dafd9a7cdb112f9596f7d67a97028a7047f1c          01:30 PM   Queued
$ dvc queue stop
Queue workers will be stopped after current tasks finished.
$ dvc queue status
Rev                                       Name    Created    Status
dc2452ea4dc6e94be25fdc31ef82ea51ea46fc28          01:31 PM   Queued
a0ece9c6d03dc26251cc9664d6ccef47ccf4903b          01:31 PM   Queued
2ffbb7381ac8bd8b159a09af88cea559419324e8          01:31 PM   Queued
4b9348a2b8342d57f58f632c3034cf6119f405e1          01:31 PM   Queued
d78dafd9a7cdb112f9596f7d67a97028a7047f1c          01:30 PM   Queued
$ dvc exp show --only-changed --no-pager
 ────────────────────────────────────────────────────────────────────────────────────
  Experiment                Created        State    avg_prec   …   prepare.split   …
 ────────────────────────────────────────────────────────────────────────────────────
  workspace                 -              -           0.925   …   0.2             …
  10-bigrams-experiment     May 19, 2022   -           0.925   …   0.2             …
  ├── 8e25550 [exp-1fff4]   01:32 PM       -         0.91476   …   0.3             …
  ├── dc2452e               01:31 PM       Queued          -   -   0.3             …
  ├── a0ece9c               01:31 PM       Queued          -   -   0.05            …
  ├── 2ffbb73               01:31 PM       Queued          -   -   0.25            …
  ├── 4b9348a               01:31 PM       Queued          -   -   0.15            …
  └── d78dafd               01:30 PM       Queued          -   -   0.1             …
 ────────────────────────────────────────────────────────────────────────────────────
```

**Comment by dberenbaum** [comment] 2022-06-02 17:43
`queue stop` also fails to stop all workers if there are multiple running:

```console
$ dvc exp run --queue -S prepare.split=0.1
Queued experiment '86ccdd4' for future execution.
$ dvc exp run --queue -S prepare.split=0.15
Queued experiment '7cd31f7' for future execution.
$ dvc exp run --queue -S prepare.split=0.05
Queued experiment 'bbcd1c2' for future execution.
$ dvc exp run --queue -S prepare.split=0.25
Queued experiment '9b6387d' for future execution.
$ dvc exp run --queue -S prepare.split=0.3
Queued experiment '9951472' for future execution.
$ dvc queue start -j 2
Start 2 queue workers to process the queue tasks
$ dvc queue status
Rev                                       Name    Created    Status
bbcd1c27d9bc72c1db316d6e7b72976ff55c0ccd          01:36 PM   Running
86ccdd402fe9b17a221cf8bfe0226188c357c91f          01:36 PM   Running
9b6387d354ddd820cbe98318a38a40fccbb1632f          01:36 PM   Queued
7cd31f74789bb3669e5e8c79a2d510656c995a0b          01:36 PM   Queued
9951472ee153a65ee38f57a2ac540306dd014779          01:37 PM   Queued
$ dvc queue stop
Queue workers will be stopped after current tasks finished.
# Wait a minute...
$ dvc queue status
Rev                                       Name    Created    Status
9b6387d354ddd820cbe98318a38a40fccbb1632f          01:36 PM   Running
bbcd1c27d9bc72c1db316d6e7b72976ff55c0ccd          01:36 PM   Queued
7cd31f74789bb3669e5e8c79a2d510656c995a0b          01:36 PM   Queued
9951472ee153a65ee38f57a2ac540306dd014779          01:37 PM   Queued
# Wait a few more minutes...
$ dvc queue status
$ dvc exp show --only-changed --no-pager
 ─────────────────────────────────────────────────────────────────────────────────
  Experiment                Created        avg_prec   roc_auc   prepare.split   …
 ─────────────────────────────────────────────────────────────────────────────────
  workspace                 -                 0.925   0.94602   0.2             …
  bigrams-experiment        May 19, 2022      0.925   0.94602   0.2             …
  ├── f97e223 [exp-1fff4]   01:39 PM        0.91476   0.93946   0.3             …
  ├── b698bc4 [exp-f374a]   01:39 PM        0.92968   0.95151   0.15            …
  ├── 71859f2 [exp-c47cb]   01:38 PM        0.91856   0.94113   0.25            …
  ├── a3c5e45 [exp-863a9]   01:38 PM        0.93169   0.95014   0.1             …
  └── 2a2f0b0 [exp-ae08e]   01:38 PM        0.92664   0.94595   0.05            …
 ─────────────────────────────────────────────────────────────────────────────────
```

**Comment by dberenbaum** [comment] 2022-06-08 20:05
Have you tested much with `-j`? It's hard for me to pinpoint issues with it because it is still pretty unstable and hard to reproduce. I can show some issues, but I'm not always sure what's causing them.

**Comment by pmrowla** [comment] 2022-06-09 05:05
`-j` is non-functional right now (internally we still only allow a single worker regardless of what you pass into `queue start -j`)

Looks like there is probably still a bug w/how we handle celery task prefetching and cancelling somewhere that affects `queue stop`, I'll look into it

**Comment by karajan1001** [comment] 2022-06-09 08:46
Yes, on my side I found 80% percent it works as intended when I start 2 workers. But sometimes it will only start one.

**Comment by karajan1001** [comment] 2022-07-05 12:06
Closed as all of the features had been implemented.

**Closed by karajan1001** 2022-07-05 12:06 UTC
Labels: ui, A: experiments
