### ISSUE TITLE
dvc metrics: error: too few arguments

### ISSUE THREAD

**Issue by gcoter** [iterative/dvc#865] opened 2018-07-06 23:12 UTC
Hello,

In one of my current projects, I have about 10 branches that I would like to compare. On each branch, there is a JSON file at the same location (`data/metrics.json`). So, I tried using dvc metrics:

```
dvc metrics --json-path data/metrics.json
```

And got the following output:

```
usage: dvc metrics [-h] [-q] [-v] [--json-path JSON_PATH]
                   [--tsv-path TSV_PATH] [--htsv-path HTSV_PATH]
                   path
dvc metrics: error: too few arguments
```

I am using dvc 0.9.7. Could you give a valid usage of dvc metrics with a JSON file?

**Comment by efiop** [comment] 2018-07-07 00:00
Hi @gcoter !

`--json-path` is used to specify JSON Path(similar to XPath, i.e. `key.subkey` is a JSON Path for `{'key': {'key': 'value'}} that will output 'value'), not the path to json file itself. For example, if your metrics.json looks like {"metrics": {"value": 12345}}, this would be a valid command:
```
$ dvc metrics --json-path metrics.value data/metrics.json
```

Also, note that there is 0.10.0 released. In it the command had changed a little bit, so the equivalent would be:
```
$ dvc metrics show --json-path metrics.value data/metrics.json
```

Thanks,
Ruslan

**Comment by gcoter** [comment] 2018-07-07 12:14
I ran the command you gave me:

```
dvc metrics --json-path RMSLE_training data/metrics.json
```

For each branch, I get this error message:

```
Unable to read metric in 'data/metrics.json': could not get source code
```

As if it couldn't find the file. I also tried with the absolute path but it didn't solve the problem.

**Comment by efiop** [comment] 2018-07-07 13:55
Could you please run it again with `-v` flag and show us the output? I.e.:
```
dvc metrics -v --json-path RMSLE_training data/metrics.json
```

Also, could you please try running this command and also provide the output:
```
dvc metrics -v data/metrics.json
```

Thanks,
Ruslan

**Comment by gcoter** [comment] 2018-07-07 16:41
Ok, so for each branch I get this:

```
λ dvc metrics -v --json-path RMSLE_training data/metrics.json
Removing 'data\report_preprocess.html'
Removing 'data\report.html'
Removing 'data\model.pickle'
Removing 'data\profile.pickle'
Removing 'data\test_preprocess.csv'
Removing 'data\train_preprocess.csv'
Removing 'data\train.csv'
Removing 'data\metrics.json'
Removing 'data\test.csv'
Removing 'data\submission.csv'
Removing 'data\profile_preprocess.pickle'
Checking out 'data\train_preprocess.csv' with cache '6d687edbbe8be1a0cfe67b3b86ff9bcc'
Dependency 'data\train_preprocess.csv' changed
Checking out 'data\train_preprocess.csv' with cache '.dvc\cache\6d\687edbbe8be1a0cfe67b3b86ff9bcc'
Cache type 'reflink' is not supported
Checking out 'data\test_preprocess.csv' with cache '092b77d9381dd366d26d2c5acd4ae922'
Dependency 'data\test_preprocess.csv' changed
Checking out 'data\test_preprocess.csv' with cache '.dvc\cache\09\2b77d9381dd366d26d2c5acd4ae922'
Cache type 'reflink' is not supported
Checking out 'data\profile_preprocess.pickle' with cache '78795b228e29e3cf4d09643c88f16c3a'
Dependency 'data\profile_preprocess.pickle' changed
Checking out 'data\profile_preprocess.pickle' with cache '.dvc\cache\78\795b228e29e3cf4d09643c88f16c3a'
Cache type 'reflink' is not supported
Checking out 'data\report_preprocess.html' with cache '11466d7fb452786c15fca3a3a80c576b'
Dependency 'data\report_preprocess.html' changed
Checking out 'data\report_preprocess.html' with cache '.dvc\cache\11\466d7fb452786c15fca3a3a80c576b'
Cache type 'reflink' is not supported
Checking out 'data\profile.pickle' with cache '2d6bc705cfa34caf8f7c5b29d6d57797'
Dependency 'data\profile.pickle' changed
Checking out 'data\profile.pickle' with cache '.dvc\cache\2d\6bc705cfa34caf8f7c5b29d6d57797'
Cache type 'reflink' is not supported
Checking out 'data\report.html' with cache '5fcb9119848c9b1443bdc666f8b84248'
Dependency 'data\report.html' changed
Checking out 'data\report.html' with cache '.dvc\cache\5f\cb9119848c9b1443bdc666f8b84248'
Cache type 'reflink' is not supported
Checking out 'data\submission.csv' with cache 'e1812da5ef97024ac7a7c234f7285511'
Dependency 'data\submission.csv' changed
Checking out 'data\submission.csv' with cache '.dvc\cache\e1\812da5ef97024ac7a7c234f7285511'
Cache type 'reflink' is not supported
Checking out 'data\model.pickle' with cache '8a01fb53f449b8b1375cc2258ada2d4a'
Dependency 'data\model.pickle' changed
Checking out 'data\model.pickle' with cache '.dvc\cache\8a\01fb53f449b8b1375cc2258ada2d4a'
Cache type 'reflink' is not supported
Checking out 'data\metrics.json' with cache 'f8f600c1dbe08f9d687abb7167cb241e'
Dependency 'data\metrics.json' changed
Checking out 'data\metrics.json' with cache '.dvc\cache\f8\f600c1dbe08f9d687abb7167cb241e'
Cache type 'reflink' is not supported
Checking out 'data\test.csv' with cache 'c692d603281493f6c1ec977a63adfd0e'
Dependency 'data\test.csv' changed
Checking out 'data\test.csv' with cache '.dvc\cache\c6\92d603281493f6c1ec977a63adfd0e'
Cache type 'reflink' is not supported
Checking out 'data\train.csv' with cache '0f28253b2c8f6ca67a4ba96e5f0ab0a2'
Dependency 'data\train.csv' changed
Checking out 'data\train.csv' with cache '.dvc\cache\0f\28253b2c8f6ca67a4ba96e5f0ab0a2'
Cache type 'reflink' is not supported
Traceback (most recent call last):
  File "dvc\project.py", line 301, in _read_metric
  File "dvc\project.py", line 271, in _read_metric_json
  File "site-packages\jsonpath_rw\parser.py", line 14, in parse
  File "site-packages\jsonpath_rw\parser.py", line 32, in parse
  File "site-packages\jsonpath_rw\parser.py", line 53, in parse_token_stream
  File "site-packages\ply\yacc.py", line 3293, in yacc
  File "site-packages\ply\yacc.py", line 2938, in validate_all
  File "site-packages\ply\yacc.py", line 2982, in validate_modules
  File "inspect.py", line 689, in getsourcelines
  File "inspect.py", line 537, in findsource
IOError: could not get source code

Unable to read metric in 'data/metrics.json': could not get source code
...
```

The exception is raised at this line: https://github.com/iterative/dvc/blob/91c16e21125966f51ee21c5750c302cced3fe3b2/dvc/project.py#L271

Apparently, it doesn't like the `json_path` I gave.

Here is an example of metrics.json:

```
{"RMSLE_training": 0.007339926241045231, "RMSLE_validation": 1.7577025792781877}
```

It is not formatted as the example you gave me (`{'key': {'key': 'value'}}`). Maybe that is the problem?

I also tried `dvc metrics data/metrics.json`, and for some reason, it worked:

```
λ dvc metrics data/metrics.json
preprocess-dropzeros-rf: {"RMSLE_training": 0.8790632414192884, "RMSLE_validation": 1.366426884843624}
preprocess-keepzeros-xgboost: {"RMSLE_training": 0.8850106102525068, "RMSLE_validation": 1.4212100403578354}
...
```

Actually, it prints the whole JSON file for each branch.

**Comment by efiop** [comment] 2018-07-07 17:01
Actually there seems to be a problem with the jsonpath_rw package. How did you install dvc? From binary package(if so, from which?) or from pypi?

**Comment by gcoter** [comment] 2018-07-07 20:30
I installed it from the binary for Windows (dvc-0.9.7.exe).

**Comment by efiop** [comment] 2018-07-07 20:52
Thank you for the info! Looks like the might is an issue with a windows binary package. I'll try to reproduce it on windows shortly.

For now, I would recommend you uninstall dvc binary package and install it from the pypi with `pip install dvc`, which should work correctly. Note that it will automatically install the most recent version(which is 0.10.1), where the syntax for the same command would be:
```
dvc metrics show --all-branches --json-path RMSLE_training data/metrics.json
```

Please let us know if pip package works for you.

Thanks,
Ruslan

**Comment by efiop** [comment] 2018-07-07 21:43
I was able to reproduce the issue with both 0.10.1 and 0.9.7 from Windows _binary_ packages. Both versions from pypi work properly though.

Working on the fix right now, will release 0.10.2 after it is merged.

**Comment by efiop** [comment] 2018-07-07 22:42
Ok, so the issue is caused by the bug in ply module (https://github.com/dabeaz/ply/issues/97). We build our binary packages with pyinstaller which doesn't carry a source code with it, thus causing ply to raise that error. The solution is to require ply>=3.9, where that bug is fixed. I've merged the fix and released 0.10.2 https://github.com/iterative/dvc/releases/tag/0.10.2 . Please feel free to upgrade.

Thank so much for the feedback! Please let us know if it worked for you.

- Ruslan

**Closed** 2018-07-12 08:09 UTC
Labels: awaiting response

**Comment by gcoter** [comment] 2018-07-21 10:04
Sorry for my very late reply. So I upgraded to 0.10.2 and here is what I get:

```
$ dvc metrics show --all-branches --json-path RMSLE_validation data/metrics.json --verbose
updater is not old enough to check for updates
preprocess-dropzeros-featureselection-lr:
        data\metrics.json: [1.3656112106868223]
preprocess-keepzeros-xgboost:
        data\metrics.json: [1.3656112106868223]
preprocess-dropzeros-featureselection-rf:
        data\metrics.json: [1.3656112106868223]
...
```

It prints the same metric value for every branch. Did I forget something in the command?

**Comment by efiop** [comment] 2018-07-21 11:01
Hi @gcoter !

How is `data/metrics.json` specified in a respective .dvc file? Could you show us the .dvc file for that stage please?

My first guess would be that you've probably specified data/metrics.json as a regular cached output in your `dvc run` command, which means that when `dvc metrics show` is checking out git branches, it sees the same data\metrics.json that is left from your current branch and thus showing you the same output.

The proper way would be to `dvc run -M data/metrics.json ....`, which would tell dvc that `data/metrics.json` should be marked as a metrics file and not cached by dvc, so you can track it directly with `git add data/metrics.json`.

Btw, we have released 0.14.1 yesterday, please consider upgrading.

Thanks,
Ruslan

**Comment by gcoter** [comment] 2018-07-22 14:53
Hi @efiop,

Indeed, I specified it as a regular output. In the previous version I was using, there was no `-M` option I think, so I specified my metrics with `-o`. But, it used to work quite well. I just had to run `dvc checkout` to retrieve the metrics (as the other files). So, I'm a bit confused about why it doesn't work anymore.

Anyway, I upgraded to the latest version and I will use `-M` from now on.

Thank you!

**Comment by efiop** [comment] 2018-07-22 15:50
Oh, sorry, looks like we had a regression 🙁 Somewhere after 0.9.7 we've made a decision that it is better to specify your metrics in a non cached files, so that they are not dependent on cache. And somewhere around that time, I've removed dvc.checkout() line when we are iterating over git branches.  I'll send a patch soon to try to mitigate that.

Thank you so much for the feedback! Please let us know if everything works for you now.

-- Ruslan

**Comment by gcoter** [comment] 2018-07-22 16:13
Ok I see, no problem :)

Yes, everything is fine now. Thanks!
