### ISSUE TITLE
s3 remote: unexpected error with session token

### ISSUE THREAD

**Issue by Christoph-1** [iterative/dvc#5130] opened 2020-12-18 09:10 UTC
# Bug Report

## Description

When using a session token for aws s3 remote the dvc push produces the following error:
ERROR: unexpected error - An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied

### Reproduce

1. Configure ~/aws/credentials with access_key, secret_access_key and session_token; profile name: myprofile
2. dvc remote add -d myremote s3://mybucket/path
3. dvc remote modify myremote profile myprofile
5. dvc add test.txt
4. dvc push

Alternative:
1. Configure an aws sso profile named myprofile
2. aws sso login --profile myprofile
3. dvc remote add -d myremote s3://mybucket/path
4. dvc remote modify myremote profile myprofile
5. dvc add test.txt
6. dvc push

### Expected

test.txt is pushed to the S3 bucket

### Environment information

**Output of `dvc version`:**

```console
$ dvc version
DVC version: 1.11.7 (brew)
---------------------------------
Platform: Python 3.9.1 on macOS-11.0.1-x86_64-i386-64bit
Supports: azure, gdrive, gs, http, https, s3, ssh, oss, webdav, webdavs
Cache types: reflink, hardlink, symlink
Caches: local
Remotes: s3
Repo: dvc, git
```

**Additional Information (if any):**

**Comment by efiop** [comment] 2020-12-18 09:23
For the record: More context on our mailing list.

**Comment by gbabbar** [comment] 2021-01-07 11:17
Maybe try setting env variables do the job:

export AWS_SECRET_ACCESS_KEY=<>
export AWS_ACCESS_KEY_ID=<>
export AWS_SESSION_TOKEN=<>

**Comment by Christoph-1** [comment] 2021-01-07 14:50
> Maybe try setting env variables do the job:
> 
> export AWS_SECRET_ACCESS_KEY=<>
> export AWS_ACCESS_KEY_ID=<>
> export AWS_SESSION_TOKEN=<>

I tried this, but unfortunately it didn't work. As we're using SSO, we cannot export env variables.
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html#envvars-set

**Comment by isidentical** [comment] 2021-01-13 11:57
Recently #5240 landed, maybe it can help?

**Comment by efiop** [comment] 2021-01-28 00:32
For the record: thanks to great research by @Christoph-1 :pray: , we were able to pinpoint the issue to us trying to list `folder` instead of `folder/` in https://github.com/iterative/dvc/blob/969a85efb6d4b758109778e8ee5d99d2f2ce0fd9/dvc/tree/s3.py#L213 , which resulted in access denied error as @Christoph-1 's rights are limited to `folder/` specifically.

**Comment by isidentical** [comment] 2021-05-06 09:21
Hey @Christoph-1, can you try and see whether you still experience the same problem by installing from the master? `pip install "dvc[s3] @ git+https://github.com/iterative/dvc.git"`

**Comment by Christoph-1** [comment] 2021-05-25 09:20
> Hey @Christoph-1, can you try and see whether you still experience the same problem by installing from the master? `pip install "dvc[s3] @ git+https://github.com/iterative/dvc.git"`

Hi @isidentical . Sorry for the late reply. I had some troubles signing into AWS recently.

I tried it with the latest version on master and get another error with Python 3.9.4:
<img width="941" alt="image" src="https://user-images.githubusercontent.com/36413742/119472799-d85af000-bd4a-11eb-8b06-4b49041e2448.png">
<img width="449" alt="image" src="https://user-images.githubusercontent.com/36413742/119472949-f9bbdc00-bd4a-11eb-9518-ea736fbc019f.png">

Last few lines of the stack trace:
```
File ../lib/python3.9/site-packages/s3fs/core.py", line 725, in _exists
    await self._info(path, bucket, key, version_id=version_id)
  File "../lib/python3.9/site-packages/s3fs/core.py", line 911, in _info
    out = await self._call_s3(
  File "../lib/python3.9/site-packages/s3fs/core.py", line 252, in _call_s3
    raise translate_boto_error(err)
PermissionError: Forbidden
```

**Comment by Christoph-1** [comment] 2021-05-25 09:24
On Python 3.8 I have a different error:
![image](https://user-images.githubusercontent.com/36413742/119473516-86669a00-bd4b-11eb-972e-cbecac39f274.png)
![image](https://user-images.githubusercontent.com/36413742/119473555-91212f00-bd4b-11eb-97af-19d7a9090b33.png)

```
File "../lib/python3.8/site-packages/fsspec/asyn.py", line 20, in _runner
    result[0] = await coro
  File "../lib/python3.8/site-packages/s3fs/core.py", line 571, in _find
    out = await self._lsdir(path, delimiter="")
  File "../lib/python3.8/site-packages/s3fs/core.py", line 547, in _lsdir
    raise translate_boto_error(e)
PermissionError: Access Denied
```

**Comment by Christoph-1** [comment] 2021-06-07 11:37
I tired today again with dvc version 2.3.0+2f8cf8. I'm getting the below error.

```
2021-06-07 13:24:37,271 DEBUG: Check for update is enabled.
2021-06-07 13:24:37,806 DEBUG: Preparing to upload data to 's3://mybucket/path/'
2021-06-07 13:24:37,806 DEBUG: Preparing to collect status from s3://mybucket/path/
2021-06-07 13:24:37,807 DEBUG: Collecting information from local cache...
2021-06-07 13:24:37,807 DEBUG: Collecting information from remote cache...                                                    
2021-06-07 13:24:37,807 DEBUG: Matched '0' indexed hashes
2021-06-07 13:24:37,808 DEBUG: Querying 1 hashes via object_exists
2021-06-07 13:24:38,380 ERROR: unexpected error - Forbidden: An error occurred (403) when calling the HeadObject operation: Forbidden
------------------------------------------------------------
Traceback (most recent call last):
  File ".../lib/python3.9/site-packages/s3fs/core.py", line 233, in _call_s3
    out = await method(**additional_kwargs)
  File ".../lib/python3.9/site-packages/aiobotocore/client.py", line 154, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".../lib/python3.9/site-packages/s3fs/core.py", line 1003, in _info
    out = await self._simple_info(path)
  File ".../lib/python3.9/site-packages/s3fs/core.py", line 916, in _simple_info
    out = await self._call_s3(
  File ".../lib/python3.9/site-packages/s3fs/core.py", line 252, in _call_s3
    raise translate_boto_error(err)
PermissionError: Access Denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../lib/python3.9/site-packages/s3fs/core.py", line 233, in _call_s3
    out = await method(**additional_kwargs)
  File ".../lib/python3.9/site-packages/aiobotocore/client.py", line 154, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".../lib/python3.9/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File ".../lib/python3.9/site-packages/dvc/command/base.py", line 50, in do_run
    return self.run()
  File ".../lib/python3.9/site-packages/dvc/command/data_sync.py", line 56, in run
    processed_files_count = self.repo.push(
  File ".../lib/python3.9/site-packages/dvc/repo/__init__.py", line 51, in wrapper
    return f(repo, *args, **kwargs)
  File ".../lib/python3.9/site-packages/dvc/repo/push.py", line 41, in push
    return len(used_run_cache) + self.cloud.push(
  File ".../lib/python3.9/site-packages/dvc/data_cloud.py", line 79, in push
    return remote_obj.push(
  File ".../lib/python3.9/site-packages/dvc/remote/base.py", line 57, in wrapper
    return f(obj, *args, **kwargs)
  File ".../lib/python3.9/site-packages/dvc/remote/base.py", line 477, in push
    ret = self._process(
  File ".../lib/python3.9/site-packages/dvc/remote/base.py", line 334, in _process
    dir_status, file_status, dir_contents = self._status(
  File ".../lib/python3.9/site-packages/dvc/remote/base.py", line 178, in _status
    self.hashes_exist(
  File ".../lib/python3.9/site-packages/dvc/remote/base.py", line 128, in hashes_exist
    return indexed_hashes + self.odb.hashes_exist(list(hashes), **kwargs)
  File ".../lib/python3.9/site-packages/dvc/objects/db/base.py", line 421, in hashes_exist
    remote_hashes = self.list_hashes_exists(hashes, jobs, name)
  File ".../lib/python3.9/site-packages/dvc/objects/db/base.py", line 372, in list_hashes_exists
    ret = list(itertools.compress(hashes, in_remote))
  File ".../lib/python3.9/concurrent/futures/_base.py", line 608, in result_iterator
    yield fs.pop().result()
  File ".../lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File ".../lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File ".../lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File ".../lib/python3.9/site-packages/dvc/objects/db/base.py", line 363, in exists_with_progress
    ret = self.fs.exists(path_info)
  File ".../lib/python3.9/site-packages/dvc/fs/fsspec_wrapper.py", line 92, in exists
    return self.fs.exists(self._with_bucket(path_info))
  File ".../lib/python3.9/site-packages/fsspec/asyn.py", line 72, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File ".../lib/python3.9/site-packages/fsspec/asyn.py", line 53, in sync
    raise result[0]
  File ".../lib/python3.9/site-packages/fsspec/asyn.py", line 20, in _runner
    result[0] = await coro
  File ".../lib/python3.9/site-packages/s3fs/core.py", line 746, in _exists
    await self._info(path, bucket, key, version_id=version_id)
  File ".../lib/python3.9/site-packages/s3fs/core.py", line 1007, in _info
    out = await self._version_aware_info(path, version_id)
  File ".../lib/python3.9/site-packages/s3fs/core.py", line 950, in _version_aware_info
    out = await self._call_s3(
  File ".../lib/python3.9/site-packages/s3fs/core.py", line 252, in _call_s3
    raise translate_boto_error(err)
PermissionError: Forbidden
------------------------------------------------------------
2021-06-07 13:24:38,438 DEBUG: Version info for developers:
DVC version: 2.3.0+2f8cf8 
---------------------------------
Platform: Python 3.9.5 on macOS-10.16-x86_64-i386-64bit
Supports: http, https, s3
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s5s1
Caches: local
Remotes: s3
Workspace directory: apfs on /dev/disk1s5s1
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-06-07 13:24:38,439 DEBUG: Analytics is enabled.
2021-06-07 13:24:38,536 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/var/folders/rp/vmcpy3p16zl1p87rcswcsf880000gn/T/tmphej1xayx']'
2021-06-07 13:24:38,538 DEBUG: Spawned '['daemon', '-q', 'analytics', '/var/folders/rp/vmcpy3p16zl1p87rcswcsf880000gn/T/tmphej1xayx']'
```

When I upload a file manually using:
```
import boto3
import os

os.environ['AWS_PROFILE'] = "myprofile"
s3 = boto3.resource('s3')
 s3.meta.client.upload_file(
        Filename="my_file", Bucket="my_bucket", key="path/my_file")
```
then it works and the file is uploaded to the S3 bucket. How can this issue be resolved? Do you need any more information to reproduce the issue?

**Comment by amin-nejad** [comment] 2021-06-21 18:20
Also get a similar problem on DVC 2.3.0

`botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: No AWSAccessKey was presented.`

I've confirmed I do have access to the S3 bucket and everything works normally on DVC 1

**Comment by isidentical** [comment] 2021-06-28 07:31
@Christoph-1 would you mind trying to use `bucket/path/cache` instead of `bucket/path` as the remote address? Since there are some oddities w.r.t. trailing slash, I think there is a chance that this approach can work.

**Comment by isidentical** [comment] 2021-06-28 07:31
@amin-nejad that seems like an irrelevant issue, please create another ticket.

**Comment by Christoph-1** [comment] 2021-06-28 13:38
@isidentical Thanks for the suggestion. I tried with different urls in the .dvc/config file:
`bucket/path/cache/`
`bucket/path/cache`
`bucket/path/`
`bucket/path`
Using the first two results in `AccessDenied` errors and the last two in the `Forbidden` error described above.

**Comment by isidentical** [comment] 2021-06-28 13:40
Interesting, `bucket/path/cache/ `should have worked. Can you please post the `dvc doctor` and the `dvc push -v`'s full traceback. Also please ensure that aws-cli works.

**Comment by Christoph-1** [comment] 2021-06-28 13:49
Here's the `dvc doctor` output:
```
DVC version: 2.4.1+7c1389 
---------------------------------
Platform: Python 3.9.5 on macOS-10.16-x86_64-i386-64bit
Supports: http, https, s3
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s5s1
Caches: local
Remotes: s3
Workspace directory: apfs on /dev/disk1s5s1
Repo: dvc, git
```

**Comment by Christoph-1** [comment] 2021-06-28 14:18
Here's the output of `dvc push -v`:
```
2021-06-28 16:11:01,977 DEBUG: Check for update is enabled.
2021-06-28 16:11:02,277 DEBUG: Preparing to upload data to 's3://bucket/path/cache/'
2021-06-28 16:11:02,277 DEBUG: Preparing to collect status from s3://bucket/path/cache/
2021-06-28 16:11:02,277 DEBUG: Collecting information from local cache...
2021-06-28 16:11:02,277 DEBUG: Collecting information from remote cache...                                              
2021-06-28 16:11:02,278 DEBUG: Matched '0' indexed hashes
2021-06-28 16:11:02,278 DEBUG: Querying 1 hashes via object_exists
2021-06-28 16:11:02,848 ERROR: unexpected error - Forbidden: An error occurred (403) when calling the HeadObject operation: Forbidden
------------------------------------------------------------
Traceback (most recent call last):
  File "../envs/dvc-env/lib/python3.9/site-packages/s3fs/core.py", line 246, in _call_s3
    out = await method(**additional_kwargs)
  File "../envs/dvc-env/lib/python3.9/site-packages/aiobotocore/client.py", line 154, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../envs/dvc-env/lib/python3.9/site-packages/s3fs/core.py", line 1057, in _info
    out = await self._simple_info(path)
  File "../envs/dvc-env/lib/python3.9/site-packages/s3fs/core.py", line 970, in _simple_info
    out = await self._call_s3(
  File "../envs/dvc-env/lib/python3.9/site-packages/s3fs/core.py", line 265, in _call_s3
    raise translate_boto_error(err)
PermissionError: Access Denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../envs/dvc-env/lib/python3.9/site-packages/s3fs/core.py", line 246, in _call_s3
    out = await method(**additional_kwargs)
  File "../envs/dvc-env/lib/python3.9/site-packages/aiobotocore/client.py", line 154, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../envs/dvc-env/lib/python3.9/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "../envs/dvc-env/lib/python3.9/site-packages/dvc/command/base.py", line 50, in do_run
    return self.run()
  File "../envs/dvc-env/lib/python3.9/site-packages/dvc/command/data_sync.py", line 57, in run
    processed_files_count = self.repo.push(
  File "../envs/dvc-env/lib/python3.9/site-packages/dvc/repo/__init__.py", line 51, in wrapper
    return f(repo, *args, **kwargs)
  File "../envs/dvc-env/lib/python3.9/site-packages/dvc/repo/push.py", line 44, in push
    pushed += self.cloud.push(objs, jobs, remote=remote)
  File "../envs/dvc-env/lib/python3.9/site-packages/dvc/data_cloud.py", line 79, in push
    return remote_obj.push(
  File "../envs/dvc-env/lib/python3.9/site-packages/dvc/remote/base.py", line 57, in wrapper
    return f(obj, *args, **kwargs)
  File "../envs/dvc-env/lib/python3.9/site-packages/dvc/remote/base.py", line 494, in push
    ret = self._process(
  File "../envs/dvc-env/lib/python3.9/site-packages/dvc/remote/base.py", line 351, in _process
    dir_status, file_status, dir_contents = self._status(
  File "../envs/dvc-env/lib/python3.9/site-packages/dvc/remote/base.py", line 195, in _status
    self.hashes_exist(
  File "../envs/dvc-env/lib/python3.9/site-packages/dvc/remote/base.py", line 145, in hashes_exist
    return indexed_hashes + self.odb.hashes_exist(list(hashes), **kwargs)
  File "../envs/dvc-env/lib/python3.9/site-packages/dvc/objects/db/base.py", line 438, in hashes_exist
    remote_hashes = self.list_hashes_exists(hashes, jobs, name)
  File "../envs/dvc-env/lib/python3.9/site-packages/dvc/objects/db/base.py", line 389, in list_hashes_exists
    ret = list(itertools.compress(hashes, in_remote))
  File "../envs/dvc-env/lib/python3.9/concurrent/futures/_base.py", line 608, in result_iterator
    yield fs.pop().result()
  File "../envs/dvc-env/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "../envs/dvc-env/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "../envs/dvc-env/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../envs/dvc-env/lib/python3.9/site-packages/dvc/objects/db/base.py", line 380, in exists_with_progress
    ret = self.fs.exists(path_info)
  File "../envs/dvc-env/lib/python3.9/site-packages/dvc/fs/fsspec_wrapper.py", line 92, in exists
    return self.fs.exists(self._with_bucket(path_info))
  File "../envs/dvc-env/lib/python3.9/site-packages/fsspec/asyn.py", line 87, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "../envs/dvc-env/lib/python3.9/site-packages/fsspec/asyn.py", line 68, in sync
    raise result[0]
  File "../envs/dvc-env/lib/python3.9/site-packages/fsspec/asyn.py", line 24, in _runner
    result[0] = await coro
  File "../envs/dvc-env/lib/python3.9/site-packages/s3fs/core.py", line 802, in _exists
    await self._info(path, bucket, key, version_id=version_id)
  File "../envs/dvc-env/lib/python3.9/site-packages/s3fs/core.py", line 1061, in _info
    out = await self._version_aware_info(path, version_id)
  File "../envs/dvc-env/lib/python3.9/site-packages/s3fs/core.py", line 1004, in _version_aware_info
    out = await self._call_s3(
  File "../envs/dvc-env/lib/python3.9/site-packages/s3fs/core.py", line 265, in _call_s3
    raise translate_boto_error(err)
PermissionError: Forbidden
------------------------------------------------------------
2021-06-28 16:11:02,886 DEBUG: Version info for developers:
DVC version: 2.4.1+7c1389 
---------------------------------
Platform: Python 3.9.5 on macOS-10.16-x86_64-i386-64bit
Supports: http, https, s3
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s5s1
Caches: local
Remotes: s3
Workspace directory: apfs on /dev/disk1s5s1
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2021-06-28 16:11:02,888 DEBUG: Analytics is enabled.
2021-06-28 16:11:02,984 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/var/folders/rp/vmcpy3p16zl1p87rcswcsf880000gn/T/tmpuel4lxqn']'
2021-06-28 16:11:02,986 DEBUG: Spawned '['daemon', '-q', 'analytics', '/var/folders/rp/vmcpy3p16zl1p87rcswcsf880000gn/T/tmpuel4lxqn']'
```

I tried with the aws-cli for this path (s3://bucket/path/cache/) with `s3 cp ` and it works without getting an error.

**Comment by Christoph-1** [comment] 2021-06-28 14:19
Is the `cache` a subfolder or is it something generated by dvc?

**Comment by isidentical** [comment] 2021-06-28 14:20
`cache` is just an arbitrary prefix, you can do `your/original/path/apple` etc. and DVC wil use `your/original/path/cache/<xx>/<yy>` instead of `your/original/path/<xx>/<yy>` which could have helped in the case of trailing slash. Looking into it.

**Comment by Christoph-1** [comment] 2021-06-29 09:29
@isidentical I tried again this morning and spoke to our infrastructure team. I didn't have access to `s3 ls` in the subfolders of the `bucket/path`.  That's why putting objects with the was-cli worked, but I assume that's also why dvc failed. We have resolved that access issue and now dvc works fine. Thanks for your help also @efiop .

**Comment by isidentical** [comment] 2021-06-29 09:30
@Christoph-1 really glad to see this issue has been resolved for you. Don't hesitate to let us know if you experience any other issue through discord / github.

**Closed by isidentical** 2021-06-29 09:30 UTC
Labels: fs: s3, research
