### ISSUE TITLE
dvc -S does not support  dash  '-' in parameter names

### ISSUE THREAD

**Issue by behrica** [iterative/dvc#8457] opened 2022-10-20 10:28 UTC
# Bug Report

Running 
```
dvc exp run -S validate.standarize-tf-map-with-wv=true
```

fails with 

```
ERROR: unexpected error - LexerNoViableAltException: validate.standarize-tf-map-with-wv=true
```

As parameters with dashes are support in `params.yaml`, I expect to be able to overwrite them via `-S`

dvc doctor
```

DVC version: 2.30.0 (pip)
---------------------------------
Platform: Python 3.10.8 on Linux-6.0.2-arch1-1-x86_64-with-glibc2.36
Subprojects:
	dvc_data = 0.17.1
	dvc_objects = 0.7.0
	dvc_render = 0.0.12
	dvc_task = 0.1.3
	dvclive = 0.11.0
	scmrepo = 0.1.1
Supports:
	azure (adlfs = 2022.10.0, knack = 0.10.0, azure-identity = 1.11.0),
	http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3)
Cache types: reflink, hardlink, symlink
Cache directory: xfs on /dev/sdc1
Caches: local
Remotes: azure
Workspace directory: xfs on /dev/sdc1
Repo: dvc, git
```

**Comment by daavoo** [comment] 2022-10-20 10:33
Hi @behrica ! Thanks for reporting. The issue is already tracked in https://github.com/iterative/dvc/issues/8151 and it should be fixed on the next Hydra release.

Closing as duplicate

**Closed by daavoo** 2022-10-20 10:33 UTC
