### ISSUE TITLE
a potential bug with dependencies on conda

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#2782] opened 2019-11-12 16:19 UTC
**Context:**

https://discordapp.com/channels/485586884165107732/485596304961962003/643841725831315456

-------------

I was able to reproduce with `pip` before I ran `pip install -U -e .[all,tests]`. After updating tqdm the issue was resolved.

It's clear why was that happening to me with dev version being not in sync with deps. Not sure if there is a bigger issue with how `conda` is managing dependencies or should we do something about it. @casperdcl you should have a better idea about it.

---------------

` conda create -n dvc -c conda-forge dvc`

installs DVC version 0.68.1, but it looks like it brings Tqdm 4.37 with it. This is not right.

**Comment by jaredsampson** [comment] 2019-11-12 16:46
It looks like the issue is tqdm 4.38.0 hasn't been propagated to conda.

```
$ conda search -c conda-forge tqdm
...<lots of versions>...
tqdm                          4.37.0            py_0  conda-forge
```

So 4.37.0 is the highest version available.  `tqdm` version 4.38.0 was just released 4 days ago, so this is understandable.  Based on the fact that the 4.37.0 release is also only 12 days old, I suspect if I just give it a couple days, the package maintainer for conda-forge will build the new version as well, but I'll also see if I can figure out how to ask for an update.

**Comment by casperdcl** [comment] 2019-11-12 17:09
fixed by https://github.com/conda-forge/tqdm-feedstock/commit/f8084ecc6b8a2187ef6a54aeea90f568aafc12ea generally always lags behind `pip install` a little. I should've made sure to release this one earlier.

**Closed by casperdcl** 2019-11-12 17:09 UTC
Labels: p0-critical

**Comment by jaredsampson** [comment] 2019-11-12 18:10
Great, thanks!

**Comment by efiop** [comment] 2019-11-12 18:23
Also my fault for not updating it in our conda deps. Updated https://github.com/conda-forge/dvc-feedstock/blob/master/recipe/meta.yaml . @casperdcl Thank you for fixing the tqdm package! @jaredsampson Sorry for the inconvenience and thank you for the feedback! 🙏
