### ISSUE TITLE
dvc get from subdir

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#2847] opened 2019-11-26 02:13 UTC
```
$ dvc -V
0.70.0+38be14
```

Regular `pull` works just fine for subdirs:
```
$ git clone https://github.com/dmpetrov/dataset
$ cd dataset
$ dvc pull dir1.dvc
$ ls dir1
file1 file2
```

`dvc get` does not work:
```
$ dvc get https://github.com/dmpetrov/dataset dir1/file1
ERROR: failed to get 'dir1/file1' from 'https://github.com/dmpetrov/dataset' - Output 'dir1/file1' not found in target repository 'https://github.com/dmpetrov/dataset'


Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

This is quite a basic scenario - high priority bug.
- [ ] Please make sure it covered by unit tests

EDITED: It worked before - regression.

**Comment by dmpetrov** [comment] 2019-11-26 02:25
It seems like it is not a regression. It fails only on data dirs, not in data files in a regular dir (which worked):

```
$ dvc get https://github.com/dmpetrov/dataset mydir/myfile
```

I'm removing high-pri tag.

**Comment by shcheklein** [comment] 2019-11-26 03:01
@dmpetrov is dataset public to reproduce? It looks like I don't have access to it.

**Comment by shcheklein** [comment] 2019-11-26 03:16
If I get it right.

Yes, I think it was never implemented. DVC in general never provided file-level granularity for directories. E.g. you can't `dvc pull dir1/file1` you have to pull the whole dir1. More or less for the same reason `dvc get` operates with the same assumptions - directory is a single manageable entity, you can't split it.

So, I would consider this as a feature request. That makes sense to me, even though would be the first time we go to intra-directory level of data management with DVC.

Initial implementation would be inefficient due to the reasons I described - we don't have a mean to fetch into cache a single file for a directory.

Also, should we support subdirectories? wildcards? any other considerations?

**Comment by efiop** [comment] 2019-11-26 07:12
Related https://github.com/iterative/dvc/issues/2458

**Comment by efiop** [comment] 2019-11-26 07:13
Closing as a duplicate of #2458

**Closed by efiop** 2019-11-26 07:13 UTC
Labels: enhancement, feature request
