### ISSUE TITLE
`signature_version='s3v4'` enforced with DVC-2

### ISSUE THREAD

**Issue by finkandreas** [iterative/dvc#5660] opened 2021-03-20 12:07 UTC
I have a remote that understands the S3 protocol, but does not understand the signature s3v4, it needs the old s3 signature.
With DVC-1 I could set the signature version in `~/.aws/credentials`:
```
[default]
aws_access_key_id=id
aws_secret_access_key=secret
s3 =
    signature_version = s3
```
This is not respected anymore, because it is explicitly set to s3v4 in your code, which has a higher priority than the setting in the config file.
https://github.com/iterative/dvc/blob/f2b216261ed84cce39449710f04cbe252a5a349e/dvc/fs/s3.py#L141

I did not manage to solve it with any config option, I had to remove the explicit `signature_version` in the source code, and `dvc push` was working again.

**Comment by pmrowla** [comment] 2021-03-31 08:08
Closing this as a duplicate of https://github.com/iterative/dvc/issues/5555

@finkandreas it would be helpful if you could provide some information about which S3-compatible storage you are using for your remote in the linked issue.

**Closed by pmrowla** 2021-03-31 08:08 UTC
