### ISSUE TITLE
DVC push hangs for a long time due to run-cache = True

### ISSUE THREAD

**Issue by michaelromagne** [iterative/dvc#10449] opened 2024-06-05 16:14 UTC
# Bug Report

## Issue name

push: hangs forever since 3.51.1 : https://github.com/iterative/dvc/pull/10433

## Description

The issue happens with Ubuntu, it's fixed when I run dvc push with the run_cache option at False or with dvc 3.50.2.
The remote is S3.
We often run heavy DVC pipelines which lead to many small files in the run cache. However even after cleaning cache the issue is still here.

Do you have any idea why ? Sorry for not providing more context. Thanks a lot

**Comment by dberenbaum** [comment] 2024-06-06 17:05
I'm not sure why it's slow to push the run-cache. Does it eventually push the run-cache successfully? Do you have a need for it or is it fine for you to push without the run-cache?

**Comment by michaelromagne** [comment] 2024-06-07 06:48
Our run-cache is pretty small. The run-cache is not eventually pushed, it hangs at the namespace step. It's fine for me not to push the run-cache, I will set it to False :smile: 

![Screenshot from 2024-06-07 08-44-40](https://github.com/iterative/dvc/assets/44051774/96aae2a5-b3ff-4598-9b88-2d04239feaa1)

![Screenshot from 2024-06-07 08-45-01](https://github.com/iterative/dvc/assets/44051774/3bfc8e5c-3b40-4745-b53b-4e7c1068dcaf)

**Comment by Wirg** [comment] 2024-06-18 14:33
I dug a little bit into this.

We are using s3 with s3 versioning. https://dvc.org/doc/user-guide/data-management/cloud-versioning
We have approximately 1000 runs keys that are looked for in `StageCache.transfer`. https://github.com/iterative/dvc/blob/main/dvc/stage/cache.py#L264

It turns out that what is taking a lot of time is `to_fs.fs.find` .
Apparently, we are stuck by `S3FileSystem.find` here https://github.com/fsspec/s3fs/blob/main/s3fs/core.py#L896 which runs in a lot of locks due to the sync.
![image](https://github.com/iterative/dvc/assets/17848620/078fb835-16b0-4903-8be0-23ffd0ce6f69)


Here is the detailed profile graph.
![profile_dvc_push](https://github.com/iterative/dvc/assets/17848620/f7519dc1-e55b-4091-bb19-d6db45edbd09)

**Comment by dberenbaum** [comment] 2024-06-20 13:33
Unfortunately, we are dropping support for cloud-versioned remotes due to a lot of small inconsistencies like this that have made it beyond what we have the capability to maintain. 

@michaelromagne Are you also using a cloud-versioned remote?

**Comment by michaelromagne** [comment] 2024-06-20 13:42
Yes S3

**Comment by shcheklein** [comment] 2024-06-20 15:35
@dberenbaum q - is it actually related to remotes being versioned, or does it affect also the regular one? (it's not obvious, just to clarify)

**Comment by dberenbaum** [comment] 2024-06-28 20:32
@michaelromagne @Wirg Can you try installing from https://github.com/iterative/dvc/pull/10472 (`pip install git+ssh://git@github.com:iterative/dvc.git@run-cache-push-force`)? Is it any faster?

**Comment by davies-w** [comment] 2024-07-15 19:24
I'm encountering this issue too. No idea what the solution is, but there should be better "progress" information, even if its just to say "not able to read cache", or "reading S3" or whatever it is.

**Comment by dberenbaum** [comment] 2024-07-15 19:36
@davies-w Can you try the suggestion above (`pip install git+ssh://git@github.com:iterative/dvc.git@run-cache-push-force`)?

**Comment by shcheklein** [comment] 2024-07-18 21:47
@dberenbaum I think your intuition re the exists check is correct. iterative/PyDrive2#353 fails in the `find` where is probably trying to get too many subdirectories at once (unfortunately, run cache consists of nested directories for some reason - and it breaks the search there - just too many objects). In case of other remotes I guess it might be listing the whole remote to check the existence or go and check them one-by-one - not sure. Anyways, it might become a slow operation. Similar to `dvc push` - we have a bunch of mechanics to optimize it.

**Comment by Wirg** [comment] 2024-07-24 16:28
Hi @dberenbaum , 

Sorry for the lack of response and thanks for the work.

I am going to try to reproduce this and see if the update works.
We had cleaned our cache since then and were not encountering the issue with a shorter cache.

**Comment by ywolff** [comment] 2024-07-26 08:51
Hi @dberenbaum,
I have the same issue of `dvc push` hanging for a (very) long time since 3.51.1.
Unfortunately, 3.52.0 does not solve the issue on my side.

My remote is an S3-compatible storage on OVH Cloud, with no cloud versioning enabled.
My only workaround is to move my run cache before running any `dvc push` and, but it's quite annoying since I use the DVC push git hook.

**Comment by dberenbaum** [comment] 2024-07-26 12:02
Thanks for the feedback @ywolff! Hopefully we can collect feedback from a few more folks on this to see if everyone is seeing the same.

**Comment by dberenbaum** [comment] 2024-07-29 12:39
Opening to solicit more feedback since the only feedback we have so far indicates the problem is not solved

**Comment by dhvu** [comment] 2024-07-29 14:26
@dberenbaum also see this happen with an SSH remote, both in push and push operations. As @Wirg said, the time is spent in waiting for a condition to be released in `to_fs.fs.find`, hence all being done in sequence. A server A which is co-located with the SSH remote server R wouldn't as quickly notice this issue, as it would see ping RTT of typically 100-150 microseconds. However another server B on another continent has ping RTTs of typically 80ms.

**Comment by dhvu** [comment] 2024-07-29 14:34
Test `dvc pull some_stage_already_pulled_before`

- With `dvc==3.51.2`: took 2'50" with `--run-cache`, 9" with `--no-run-cache`
- With `dvc==3.52.0`: took 4'33" with `--run-cache`, 11" with `--no-run-cache`

**Comment by dhvu** [comment] 2024-07-29 14:42
In the margin of this I would suggest to clarify the default behaviour at https://dvc.org/doc/command-reference/push etc and in the `--help` output of `dvc pull`, `dvc push`, `dvc fetch`.  Since `--run-cache` is listed first under the options section, I wrongly assumed that `--no-run-cache` is the default; for the same reason `--force` is not applied if not explicitly added to the command line.

**Closed** 2024-07-30 18:23 UTC
Labels: p1-important, performance, A: run-cache, A: cloud-versioning
