### ISSUE TITLE
diff: compare dirty vs committed workspace by default

### ISSUE THREAD

**Issue by shcheklein** [iterative/dvc#3386] opened 2020-02-23 01:05 UTC
By default `dvc diff` compares workspace to HEAD (or to a single commit if only one arg is provided). This is the one of the most important use cases. I would like to see the "uncommitted" (in a DVC-sense - when we update md5) changes to data files and directories:

```
git clone https://github.com/iterative/example-get-started
cd example-get-started
dvc pull
rm -f data/data.xml
touch data/features/foo
dvc diff
```

The last command produces an empty result. Not very informative to compare my "current" experiment with the baseline.

UPDATE:

Another interesting point that `dvc status` does exactly this - it analyzes actual changes.

**Comment by dmpetrov** [comment] 2020-02-24 08:26
> Another interesting point that `dvc status` does exactly this - it analyzes actual changes.

Exactly. We decided not to cover this case in the first `diff` implementation and created #3255.

**Comment by dmpetrov** [comment] 2020-02-24 08:27
Duplicate of #3255

**Comment by shcheklein** [comment] 2020-02-24 19:36
I would not consider this as a duplicate of that larger discussion (basically what status should be doing). They are relevant indeed, but if we more or less understand what do we expect from `dvc diff` let's focus on this one? And I would vote for showing the changes (uncommitted in the DVC sense).

**Comment by shcheklein** [comment] 2020-02-24 19:38
Reopening this for now, let's keep both since it's an important issue to discuss and solve if needed. If we are lucky enough to close both at once that would be a great outcome.

**Comment by jorgeorpinel** [comment] 2020-02-24 20:09
Seems like maybe this issue and #3385 could be merged? I'm just seeing lots of diff issues, may be hard to manage them.

**Closed** 2020-03-27 13:17 UTC
Labels: enhancement, p1-important

**Comment by shcheklein** [comment] 2020-03-27 16:54
@jorgeorpinel they are quite different issues/discussions.

we need to revise docs at some point when we get more or less `diff` leftovers fixed, btw..
