### ISSUE TITLE
dvc exp run: is much slower than dvc repro for running a stage

### ISSUE THREAD

**Issue by lefos99** [iterative/dvc#5897] opened 2021-04-29 12:27 UTC
# Bug Report

## Description

Right now, our team is using mainly `dvc repro` to reproduce stages. Since we updated to DVC 2.0, I tried the new `dvc exp run`, which can execute similarly my pipelines but much slower.

### Reproduce
In a simpler environment, I cannot see the problem, so I am going to describe how I executed it in my project.
`dvc dag generate_testing_data` looks like this:
```
+--------------------------------------------+                         +--------------------------------------+                         +---------------------------------+  
| ../../data/pd_l1/raw/hotspot_infos.csv.dvc |                         | ../../data/pd_l1/raw/annotations.dvc |                         | ../../data/pd_l1/raw/images.dvc |  
+--------------------------------------------+*****                    +--------------------------------------+                *********+---------------------------------+  
                                                   **********                             *                         ***********                                              
                                                             ***********                 *               ***********                                                         
                                                                        ******           *         ******                                                                    
                                                                            +-----------------------+                                                                        
                                                                            | generate_testing_data |                                                                        
                                                                            +-----------------------+              
```
Step list of how to reproduce the bug:
1. `time dvc repro generate_testing_data -f` (I use the `-f` flag to excecute the stage no matter what )
```
real	3m19.502s
user	12m17.486s
sys	0m40.838s

```
2. `time dvc exp run generate_testing_data -f` (I use the `-f` flag to excecute the stage no matter what )
```
real	5m45.788s
user	14m41.372s
sys	0m46.178s
```

### Expected
I would expect steps 1 and 2 to give me the same timings.

### Environment information

**Output of `dvc doctor`:**
```
DVC version: 2.0.17 (pip)
---------------------------------
Platform: Python 3.8.8 on Linux-5.4.0-72-generic-x86_64-with-glibc2.10
Supports: http, https, ssh
Cache types: symlink
Cache directory: ext4 on /dev/sda
Caches: local
Remotes: ssh
Workspace directory: ext4 on /dev/nvme1n1p6
Repo: dvc, git

```
**Additional Information:**
By running in verbose mode `time dvc exp run generate_testing_data -vf`, this is the head of the output:
```
2021-04-29 14:32:43,722 DEBUG: Check for update is enabled.
+-------------------------------------------+
|                                           |
|     Update available 2.0.17 -> 2.0.18     |
|      Run `pip install dvc --upgrade`      |
|                                           |
+-------------------------------------------+

2021-04-29 14:33:20,503 DEBUG: Detaching HEAD at 'HEAD'               
2021-04-29 14:33:20,545 DEBUG: Stashing workspace
2021-04-29 14:33:57,531 DEBUG: Stashing changes in 'refs/stash'
2021-04-29 14:33:57,650 DEBUG: Applying stash commit 'fbd9800110788ba43330a93ee7f712e10a731bd6'
2021-04-29 14:34:34,682 DEBUG: Stashing changes in 'refs/exps/stash'
2021-04-29 14:34:34,764 DEBUG: Stashed experiment '85fa01a' with baseline '8253ce3' for future execution.
2021-04-29 14:34:34,803 DEBUG: Restoring stashed workspace
2021-04-29 14:34:34,803 DEBUG: Popping from stash 'refs/stash'
2021-04-29 14:34:34,804 DEBUG: Applying stash commit 'fbd9800110788ba43330a93ee7f712e10a731bd6'
2021-04-29 14:34:34,843 DEBUG: Dropping 'refs/stash@{0}'
2021-04-29 14:34:34,847 DEBUG: Restore HEAD to 'master'
2021-04-29 14:34:34,887 DEBUG: Detaching HEAD at '8253ce3290c8ed5b9cd913dc6d0265bea6668e61'
2021-04-29 14:34:34,925 DEBUG: Popping from stash 'refs/exps/stash'
2021-04-29 14:34:34,926 DEBUG: Applying stash commit '85fa01ae204f3b8fe9790d8b1b43a2f28651f77e'
2021-04-29 14:34:34,966 DEBUG: Dropping 'refs/exps/stash@{0}'
2021-04-29 14:34:34,994 DEBUG: Running repro in '/home/eleftherios/git/ihc_cell_detection/ihc_cell_detection/pd_l1'
2021-04-29 14:34:34,994 DEBUG: Removing '/home/eleftherios/git/ihc_cell_detection/.dvc/tmp/repro.dat'
2021-04-29 14:34:35,006 DEBUG: Checking if stage 'generate_testing_data' is in 'dvc.yaml'
2021-04-29 14:34:35,073 DEBUG: Lockfile '../ki67_er_pr/dvc.lock' needs to be updated.
2021-04-29 14:34:36,640 DEBUG: Assuming 'generate_testing_data' to be a stage inside 'dvc.yaml'                                                                                                                                                                                    
Verifying data sources in stage: '../../data/pd_l1/raw/hotspot_infos.csv.dvc'
2021-04-29 14:34:36,962 DEBUG: {}
2021-04-29 14:34:36,962 DEBUG: Output '../../data/pd_l1/raw/hotspot_infos.csv' didn't change. Skipping saving.
2021-04-29 14:34:36,963 DEBUG: Computed stage: '../../data/pd_l1/raw/hotspot_infos.csv.dvc' md5: 'None'
2021-04-29 14:34:36,963 DEBUG: Checking out '../../data/pd_l1/raw/hotspot_infos.csv' with cache 'object md5: 54ab9d270775857245b02fbfb170c1eb'.
2021-04-29 14:34:36,964 DEBUG: Removing '../../data/pd_l1/raw/hotspot_infos.csv'
2021-04-29 14:34:36,964 DEBUG: Created 'symlink': ../../../../../../media/newhdd/data/ki67_er_pr/data/dvc_cache/54/ab9d270775857245b02fbfb170c1eb -> ../../data/pd_l1/raw/hotspot_infos.csv
2021-04-29 14:34:36,964 DEBUG: state save (16518848, 1613753314238722304, 69463) 54ab9d270775857245b02fbfb170c1eb
2021-04-29 14:34:36,969 DEBUG: stage: '../../data/pd_l1/raw/hotspot_infos.csv.dvc' was reproduced
2021-04-29 14:34:36,969 DEBUG: Saving information to '../../data/pd_l1/raw/hotspot_infos.csv.dvc'.
```

**Comment by courentin** [comment] 2021-05-01 15:56
might be linked to #5638, you can try the temporary fix https://github.com/iterative/dvc/issues/5638#issuecomment-823211616

**Comment by efiop** [comment] 2021-05-01 18:49
Hi @lefos99 !

Could you try adding `--cprofile --cprofile-dump repro.prof` to `dvc repro` and `--cprofile --cprofile-dump exp_run.prof` to `dvc exp` and post *.prof files, please?

**Comment by shcheklein** [comment] 2021-05-02 01:33
Same for me. Not sure if it is the same issue, or not. `dvc repro` vs `dvc exp run` is 30x or something (when there is nothing to run, pipeline is up to date). `dvc exp run` takes 100s doing pretty much nothing from user perspective on this repo https://github.com/iterative/dvc-get-started-mnist

**Profile:**

<img width="1029" alt="Screen Shot 2021-05-01 at 6 29 28 PM" src="https://user-images.githubusercontent.com/3659196/116799135-3594b600-aaab-11eb-8701-64e15dcb6444.png">
<img width="1153" alt="Screen Shot 2021-05-01 at 6 30 34 PM" src="https://user-images.githubusercontent.com/3659196/116799144-58bf6580-aaab-11eb-909c-422280c57e76.png">

https://www.dropbox.com/s/74yjzl8m5ojhhkh/exp_run.prof?dl=0

**Version:**

```
DVC version: 2.0.18+dba0aa
---------------------------------
Platform: Python 3.8.9 on macOS-10.15.6-x86_64-i386-64bit
Supports: All remotes
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s1
Caches: local
Remotes: https
Workspace directory: apfs on /dev/disk1s1
Repo: dvc, git
```

Looks like a dulwich problem?

**Comment by pmrowla** [comment] 2021-05-03 04:58
The issue @shcheklein is seeing is likely #5638 (it's already fixed in dulwich master). Without the profiling info it's hard to tell, but it's probably the same for @lefos99

**Comment by karajan1001** [comment] 2021-05-03 07:22
> Same for me. Not sure if it is the same issue, or not. `dvc repro` vs `dvc exp run` is 30x or something (when there is nothing to run, pipeline is up to date). `dvc exp run` takes 100s doing pretty much nothing from user perspective on this repo https://github.com/iterative/dvc-get-started-mnist
> 
> **Profile:**
> 
> <img alt="Screen Shot 2021-05-01 at 6 29 28 PM" width="1029" src="https://user-images.githubusercontent.com/3659196/116799135-3594b600-aaab-11eb-8701-64e15dcb6444.png">
> 
> <img alt="Screen Shot 2021-05-01 at 6 30 34 PM" width="1153" src="https://user-images.githubusercontent.com/3659196/116799144-58bf6580-aaab-11eb-909c-422280c57e76.png">
> 
> https://www.dropbox.com/s/74yjzl8m5ojhhkh/exp_run.prof?dl=0
> 
> **Version:**
> 
> ```
> DVC version: 2.0.18+dba0aa
> ---------------------------------
> Platform: Python 3.8.9 on macOS-10.15.6-x86_64-i386-64bit
> Supports: All remotes
> Cache types: reflink, hardlink, symlink
> Cache directory: apfs on /dev/disk1s1
> Caches: local
> Remotes: https
> Workspace directory: apfs on /dev/disk1s1
> Repo: dvc, git
> ```
> 
> Looks like a dulwich problem?

Excuse me, how to get this time tables?

**Comment by lefos99** [comment] 2021-05-03 07:43
Thank you for the replies guys! :smile_cat: 

> Hi @lefos99 !
> 
> Could you try adding `--cprofile --cprofile-dump repro.prof` to `dvc repro` and `--cprofile --cprofile-dump exp_run.prof` to `dvc exp` and post *.prof files, please?

Hey @efiop ,
Here are the two `.prof` files:
https://drive.google.com/drive/folders/1Iys5FkrMmTJvOBptvvvXNTX5hE0cKMsb?usp=sharing

**Comment by pmrowla** [comment] 2021-05-03 08:02
@lefos99 it looks like the dulwich status issue that is fixed upstream. See this issue for a temporary workaround while we are waiting for a formal dulwich release: https://github.com/iterative/dvc/issues/5638#issuecomment-823211616

**Comment by pmrowla** [comment] 2021-05-03 08:03
Closing as a duplicate of #5638. If for some reason that workaround does not address the issue for you, feel free to reopen this ticket.

**Closed by pmrowla** 2021-05-03 08:03 UTC
Labels: performance

**Comment by shcheklein** [comment] 2021-05-04 06:10
For the record, that workaround brought `dvc exp run` down to 3 seconds (vs 100s before).
