### ISSUE TITLE
dvc exp run --set-param: unable to parse python params.py

### ISSUE THREAD

**Issue by leonardcser** [iterative/dvc#9309] opened 2023-04-05 11:51 UTC
# Bug Report

## Description

When using a python file for the parameters, DVC ignores the override params flag if the value contains underscores:

```python
MYPARAM = 100000   # works
MYPARAM = 100_000  # does not work
```

DVC does not display any messages that this param has not been updated.

### Reproduce

1. Create `params.py`
2. Add a param with underscore as a value (see example above)
3. Run `dvc exp run -S 'params.py:MYPARAM=10'`

### Expected

The expected result would be DVC updating the `params.py` file with the value `10`, but it is left unchanged without any warning.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.52.0 (pip)
-------------------------
Platform: Python 3.11.2 on macOS-12.6.2-x86_64-i386-64bit
Subprojects:
	dvc_data = 0.46.0
	dvc_objects = 0.21.1
	dvc_render = 0.3.1
	dvc_task = 0.2.0
	scmrepo = 0.2.1
Supports:
	gs (gcsfs = 2023.3.0),
	http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	s3 (s3fs = 2023.3.0, boto3 = 1.24.59)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s5s1
Caches: local
Remotes: gs
Workspace directory: apfs on /dev/disk1s5s1
Repo: dvc, git
Repo.site_cache_dir: /Library/Caches/dvc/repo/b8e837d66d4510b7d7e38d810359f146
```

**Comment by aguschin** [comment] 2023-04-05 14:11
Thanks for reporting, @leonardcser. Reproduced this.

@dberenbaum, setting this as p2 since this is rarely used notation in python and there is a simple workaround. WDYT?

**Comment by pmrowla** [comment] 2023-04-05 14:20
@aguschin this is a known issue and is not supported. The python params implementation should really only be considered experimental and only works in a limited set of basic use cases

Closing as duplicate of https://github.com/iterative/dvc/issues/5777

**Closed by pmrowla** 2023-04-05 14:20 UTC
Labels: bug, p2-medium, A: params

**Comment by skshetry** [comment] 2023-04-05 15:09
If someone can propose a fix, we are happy to review the PR. But as @pmrowla said, we consider it experimental, and recommend using either of json/toml/yaml files for parameters.
