### ISSUE TITLE
is it possible to run more than one dvc pipeline in the same dvc context?

### ISSUE THREAD

**Issue by aabramovrepo** [iterative/dvc#2851] opened 2019-11-26 10:24 UTC
Hi,

   I'm trying to run multiple dvc pipelines (trainings) on the same data in the same dvc context. The only difference is .dvc config file. I'm getting the following error message:

`ERROR: cannot perform the cmd since DVC is busy and locked. Please retry the cmd later.`

Is it somehow possible to start multiple dvc processes at the same time?

Thanks!

Best,
Alexey

**Comment by efiop** [comment] 2019-11-26 10:57
Hi @aabramovrepo !

The issue is that dvc is not able to run multiple instances at the same time https://github.com/iterative/dvc/issues/755 . It is a known issue and we are working on a solution in https://github.com/iterative/dvc/pull/2584 , which should hopefully be done soon-ish. As a workaround, you could try re-running individual long-running commands by-hand and then `dvc commit`-ing the result.

I'll close this for now as a duplicate of #755

**Closed by efiop** 2019-11-26 10:57 UTC
Labels: triage

**Comment by aabramovrepo** [comment] 2019-11-26 14:47
@efiop: thanks for your response, we are waiting then...

**Comment by free-soellingeraj** [comment] 2021-03-02 19:04
Is this resolved?

**Comment by efiop** [comment] 2021-03-02 21:02
@free-soellingeraj We are releasing locks since #2584 Are you running into any particular issues?
