### ISSUE TITLE
dvc gc does not remove cache for uncommitted dvc-file

### ISSUE THREAD

**Issue by hhe** [iterative/dvc#3662] opened 2020-04-22 08:34 UTC
I removed a dvc-file prior to committing anything, because I accidentally added the wrong file. Afterwards I was not able to remove the cached data.

**Steps to reproduce:**
`dvc add example.txt`
`rm example.txt.dvc`
`dvc gc --all-commits` (although the other modes of `dvc gc` are likely affected too)

**Expected behavior:**
The blob for example.txt is removed from .dvc/cache

**Observed behavior:**
The blob for example.txt remains in .dvc/cache

**Version**: 0.88

**Platform**: Windows 10 x64, exe installation

**Notes:**
- The [unit test for `--all-commits`](https://github.com/iterative/dvc/pull/2643/files#diff-a5745c0218d9692adfa8ce207c638877) doesn't cover a case where a dvc-file is removed before being committed. It only checks that when multiple versions of the dvc-file are present (with some committed into git), only versions that were committed are kept in cache. So it wouldn't have caught this issue.

- Not sure if it's of any significance but in my case, an entry corresponding to my specific file in question remained in the `state` SQLite database.
![image](https://user-images.githubusercontent.com/4308710/79959162-a638d980-8438-11ea-8c05-24753d4b58f4.png)

**Comment by efiop** [comment] 2020-04-22 14:30
Hi @hhe !

.dvc/state doesn't matter, it just contains some history.

Are you sure that blob is not used anywhere else in your commit history? Or in other currently present dvc-files?

**Comment by hhe** [comment] 2020-04-23 01:25
I'm sure.

**Comment by efiop** [comment] 2020-04-28 13:06
@hhe Not able to reproduce:
```
#!/bin/bash            
                       
set -e                 
set -x                 
                       
rm -rf myrepo          
mkdir myrepo           
cd myrepo              
git init               
dvc init               
                       
echo foo > foo         
dvc add foo            
rm foo.dvc             
                       
tree .dvc/cache        
                       
dvc gc --all-commits -f
                       
tree .dvc/cache        
```

produces

```
+ tree .dvc/cache                                                                              
.dvc/cache                                                                                     
└── d3                                                                                         
    └── b07384d113edec49eaa6238ad5ff00                                                         
                                                                                               
1 directory, 1 file                                                                            
+ dvc gc --all-commits -f                                                                      
WARNING: This will remove all cache except items used in the working tree and all git commits o
f the current repo.                                                                            
+ tree .dvc/cache                                                                              
.dvc/cache                                                                                     
└── d3                                                                                         
                                                                                               
1 directory, 0 files                                                                           
```

Admittedly, I'm not running it on windows. It would be great, if you could give it a try and see if this script reproduces the issue for you. Might be able to try it on windows myself later.

**Comment by efiop** [comment] 2020-06-03 06:18
@hhe Also, you are using a very old dvc version, mind giving it a try with a newer one? E.g. with the pre-release: `pip install dvc --pre`.

**Comment by efiop** [comment] 2020-06-03 06:19
Closing for now. Please let us know if the newer versions work for you.

**Closed by efiop** 2020-06-03 06:19 UTC
Labels: awaiting response
