### ISSUE TITLE
artifacts: Review naming restrictions

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc#9821] opened 2023-08-08 17:41 UTC
The current name restriction seems too limiting (and the reasons for the current restrictions are not clear cc @aguschin ) :

https://github.com/iterative/dvc/blob/c71b07b99622ab37138d6d63f611a532c1dda142/dvc/repo/artifacts.py#L20

It has come up in different places:

https://iterativeai.slack.com/archives/CB41NAL8H/p1691411376466919
https://github.com/iterative/studio/issues/6897#issuecomment-1670034865

I think we should first clarify the reasons for the restrictions and then decide on allowing additional cases

---

Edit: go to https://github.com/iterative/dvc/issues/9821#issuecomment-1747205082

**Comment by dberenbaum** [comment] 2023-08-08 17:49
@aguschin @omesser Do you have any more background on why we choose these limitations for artifact names? I recall trying to be compatible with git tags, but we are being more restrictive now than what git tags allow (no uppercase letters, `_`, `.`, etc.)

**Comment by omesser** [comment] 2023-08-08 22:12
Couldn't find specific reasons for `_` for `.` actually.
I'm guessing it's a restriction in the `artifacts` section in dvc.yaml (where these might be keys 😄 ).
@aguschin  - had a hard time digging for the reason in GTO issue history, can you take a look please and tell us what prevented underscores, dots and capital letters?

**Comment by aguschin** [comment] 2023-08-09 04:50
That limitation was chosen just for simplicity: better to have it limited and lift it later than to allow everything and decide that we need to remove some characters.

So technically I think we can allow extra characters that don't interfere with gto special signs (@ and # and !) and with git tags limitations. The only other reason I can think of that worth considering is readability.

**Comment by dberenbaum** [comment] 2023-08-10 18:57
@aguschin Are there any restrictions within gto now (besides git tag limitations), or is it only enforced at the dvc level?

**Comment by shcheklein** [comment] 2023-08-10 18:58
@dberenbaum it's restricted on the GTO side AFAIK.

**Comment by omesser** [comment] 2023-08-11 14:26
We can change things on GTO side as well IMO if there's no deep reason not to (cc @aguschin)

**Comment by dberenbaum** [comment] 2023-09-08 20:19
Waiting on #9770 so we can use gto as a dep here and not duplicate the regex and other logic in dvc

**Comment by tapadipti** [comment] 2023-10-04 15:59
Discussions related to this issue are spread out in multiple GH issues and Slack threads. I’ve tried to summarize them below. Do the next steps make sense?

* Currently, the restriction on model (artifact) name is quite strict. We are discussing how much we should relax it.
* Issue reports and discussions:
    * [Reported by @mnrozhkov](https://iterativeai.slack.com/archives/CB41NAL8H/p1691411376466919)
    * [PACCAR issue](https://github.com/iterative/studio/issues/6897)
    * [Reported by @tibor-mach](https://iterativeai.slack.com/archives/C05L7S1TWAW/p1695300068062779)
    * @dberenbaum [recently added support for `_`](https://github.com/iterative/gto/pull/398)
    * In the above PR, we couldn’t agree on how to handle upper case letters, even though we agreed that we should allow uppercase letters in the model names.
    * Pending task from the [PACCAR issue](https://github.com/iterative/studio/issues/6897): fail fast in DVC (now it allows parsing even bad names)
    * In [Add A Model: Validate automated model name suggestion](https://github.com/iterative/studio/pull/7844), @jellebouwman is adding validation for model names entered in Studio.
    * Discussion to [Allow uppercase letters](https://github.com/iterative/gto/issues/403)
    * Discussion to [artifacts: Review naming restrictions](https://github.com/iterative/dvc/issues/9821)
    * Issue report: [Model Registry: Misleading errors for disallowed model names](https://github.com/iterative/studio/issues/7841#top)
* Next steps:
    * Immediate fixes:
        * Allow uppercase letters in model names in Studio and GTO
        * In GTO, when creating/working with Git tags for model actions, convert uppercase letters to lowercase
        * Merge PR [Add A Model: Validate automated model name suggestion](https://github.com/iterative/studio/pull/7844). It addresses the immediate bug.
    * Later:
        * Remove all naming restrictions (except for those that result in an invalid yaml). Do this in all products (DVC, Studio, GTO). Update validation rules and error messages accordingly.
        * In GTO, when creating Git tags for model actions, escape [characters that aren’t allowed in Git refs](https://git-scm.com/docs/git-check-ref-format). When returning the tags to the user/Studio,  unescape them. Decide the escape characters and method.
    * In GTO, for all model actions, [run the check on a tag name before creating the tag](https://iterativeai.slack.com/archives/C05L7S1TWAW/p1695608304241399?thread_ts=1695300068.062779&cid=C05L7S1TWAW).
* Questions:
    * One item [suggested by @shcheklein](https://iterativeai.slack.com/archives/C05L7S1TWAW/p1695677770979369?thread_ts=1695300068.062779&cid=C05L7S1TWAW) is “make DVC fail - so that people can’t create (annotate) model with names that we don’t support in GTO”. Do we need this if we remove all restrictions?

**Comment by dberenbaum** [comment] 2023-10-04 18:54
> * Allow uppercase letters in model names in Studio and GTO

There is a PR for this [here](https://github.com/iterative/gto/pull/420)

> * In GTO, when creating/working with Git tags for model actions, convert uppercase letters to lowercase

The above PR doesn't handle this. If we want it, we should probably add it in the same release so we don't have to make breaking changes.

> * One item [suggested by @shcheklein](https://iterativeai.slack.com/archives/C05L7S1TWAW/p1695677770979369?thread_ts=1695300068.062779&cid=C05L7S1TWAW) is “make DVC fail - so that people can’t create (annotate) model with names that we don’t support in GTO”. Do we need this if we remove all restrictions?

No, I think we agreed [here](https://github.com/iterative/studio/issues/6897#issuecomment-1743467584) that it won't be needed in that case.

**Comment by shcheklein** [comment] 2023-10-04 18:55
> The above PR doesn't handle this. If we want it, we should probably add it in the same release so we don't have to make breaking changes.

I think if we agree that we escape symbols, I would not do any other transformations. For upper case symbols -if GH accepts is - let's push it. WDYT?

**Comment by dberenbaum** [comment] 2023-10-04 19:44
I see that GH accepts it (see `gto-tag` and `GTO-tag` in https://github.com/iterative/lstm_seq2seq/tags), but would have to check BB/GL. More importantly, I'm finding issues in git cli. Sometimes, it seems to accept a new tag with different casing, other times I get an error that the tag already exists:

```
$ git tag gto-tag
$ git tag GTO-tag
fatal: tag 'GTO-tag' already exists
$ git tag -l
gto-tag
```

I'm not sure why it's happening, but feels like this is too fragile to depend on.

**Comment by pmrowla** [comment] 2023-10-05 00:54
> I'm not sure why it's happening, but feels like this is too fragile to depend on.

It's because you are on a platform with case-insensitive filesystems (windows or macos). Git ref names are technically case sensitive, and this would work as expected on linux (where the filesystems are case sensitive). But on windows/mac, this may or may not fail, depending on the state of your git repo.

(It fails if git tries to create the files `.git/refs/tags/gto-tag`, `.git/refs/tags/GTO-tag`, since on windows/mac both of these filenames point to the same file. However, it can actually succeed on windows/mac in the event that one of those tags is stored in a packed ref instead of in the `.git/refs/tags/...` file)

**Comment by dberenbaum** [comment] 2023-10-05 01:07
> This is only an issue when creating a tag that may overlap with an existing one though. There's not really any reason to prevent users from using capitalized letters in the tag name.

My concern would be what happens when users do create an overlapping tag since gto will see them as separate artifacts but may fail to create the tag, right? It is pretty unlikely, so maybe just warning about this or catching the exception is enough.

**Comment by dberenbaum** [comment] 2023-10-05 01:15
Let's say I have a tag like `My-Tag`. What happens if I create the tag on a case-insensitive filesystem and then push it? Will I lose the initial casing? If I pull on linux and try to checkout `My-Tag`, will it fail?

**Comment by pmrowla** [comment] 2023-10-05 01:29
> My concern would be what happens when users do create an overlapping tag since gto will see them as separate artifacts but may fail to create the tag, right?

Yes, this is correct

> Let's say I have a tag like `My-Tag`. What happens if I create the tag on a case-insensitive filesystem and then push it? Will I lose the initial casing? If I pull on linux and try to checkout `My-Tag`, will it fail?

No, git is case sensitive. Git can tell the difference between a tag named `My-Tag` and `my-tag`, and considers them to be two different tags. On a linux machine, the git client will always behave as expected.

The issue is specifically with what happens on windows/mac. In the event that you have an unpacked/loose ref file named `.git/tags/My-Tag`, you cannot create a new tag named `.git/tags/my-tag` (since windows/mac filesystems will report that the file already exists). Git tag lookups are still case sensitive though, so in this case assuming that you have both a set of packed refs containing the tag `My-Tag`, and a loose ref file named `.git/tags/my-tag`, Git will checkout the correct one if you do `git checkout My-Tag`.

**Comment by tapadipti** [comment] 2023-10-05 03:43
Considering the above comments, would this be better?
- do not change the casing
- before creating Git tag for an action, 
  - check if a Git tag with the same name (in any casing) exists
  - if yes, fail the action (coz the Git tag creation might fail depending on the user's platform)
This is basically a restriction that models/dirs/stages with the same name but different casing cannot not exist in the repo. We should make this restriction clear in the UI and docs.

**Comment by dberenbaum** [comment] 2023-10-05 11:49
I think that makes sense @tapadipti. Can we try to fail early and disallow having two artifacts in the same dvc.yaml with names that are only different in casing?

**Comment by tapadipti** [comment] 2023-10-05 15:12
I've updated the next steps in [this comment](https://github.com/iterative/dvc/issues/9821#issuecomment-1747205082). ptal.

**Comment by dberenbaum** [comment] 2023-10-05 18:01
Let's close this one and track there.

**Comment by dberenbaum** [comment] 2023-10-05 18:03
> * In GTO, when creating Git tags for model actions, escape [characters that aren’t allowed in Git refs](https://git-scm.com/docs/git-check-ref-format). When returning the tags to the user/Studio,  unescape them. Decide the escape characters and method.

Can we do this at the same time we remove all naming restrictions? Otherwise, I think it could introduce new errors and be a breaking change when we implement escape characters.

Also, we only need to escape characters disallowed in Git refs, but it's possible it will be simpler to take some existing escaping library and escape all characters that it handles even if many of them would be valid Git refs.

**Comment by tapadipti** [comment] 2023-10-06 03:36
> Let's close this one and track there.

The [comment with tasks](https://github.com/iterative/dvc/issues/9821#issuecomment-1747205082) is in this issue itself. So I'm re-opening it.


>> In GTO, when creating Git tags for model actions, escape [characters that aren’t allowed in Git refs](https://git-scm.com/docs/git-check-ref-format). When returning the tags to the user/Studio, unescape them. Decide the escape characters and method.
>
> Can we do this at the same time we remove all naming restrictions?

👍 

> it's possible it will be simpler to take some existing escaping library and escape all characters that it handles even if many of them would be valid Git ref

Agreed. I'll search for what library to use. If you have any suggestions, pls share.

**Comment by dberenbaum** [comment] 2023-10-06 12:22
@shcheklein mentioned URL escaping, and we could use [urllib.parse.quote](https://docs.python.org/3/library/urllib.parse.html) for that.

**Comment by tapadipti** [comment] 2023-10-10 11:24
@shcheklein You [mentioned](https://iterativeai.slack.com/archives/C05L7S1TWAW/p1695608304241399?thread_ts=1695300068.062779&cid=C05L7S1TWAW) that GTO "created and pushed the tag before actually running a check on the tag name". I'm looking into the code and I can see that the `assert_fullname_is_valid()` function is called on the full model name before `create_tag()` is called. Can you pls share which check you were referring to?

**Comment by jellebouwman** [comment] 2023-10-12 12:12
Hello! GTO got upgraded, DVC is using the latest GTO version, and Studio BE depends on the latest DVC version. https://github.com/iterative/studio/issues/7903 incorporates the new validation rules when adding models on the Studio FE.

**Comment by dberenbaum** [comment] 2023-10-12 12:42
@tapadipti Do you plan to start on the "Later" items in https://github.com/iterative/dvc/issues/9821#issuecomment-1747205082? Is there anything else needed before that?

**Comment by tapadipti** [comment] 2023-10-12 13:04
> Do you plan to start on the "Later" items in https://github.com/iterative/dvc/issues/9821#issuecomment-1747205082? Is there anything else needed before that?

I started working on one of the items in GTO ([here](https://github.com/iterative/gto/pull/427)), and will gradually pick the others. But probably not the DVC/Studio tasks.

**Comment by dberenbaum** [comment] 2023-11-27 14:46
Is this still p1? @tapadipti is it still in your plans?

**Comment by dberenbaum** [comment] 2023-12-12 12:24
Lowering the priority of the remaining items

**Closed** 2024-04-24 20:26 UTC
Labels: p2-medium, A: artifacts
