### ISSUE TITLE
poetry: dvc[s3] installation doesn't include boto3

### ISSUE THREAD

**Issue by markf94** [iterative/dvc#7475] opened 2022-03-17 03:41 UTC
# Bug Report

## Description

When installing the newest `dvc=2.9.5` into a `poetry` environment the `boto3` package doesn't get installed which results in the `dvc push` command to error out.

### Reproduce

```bash
$ poetry add dvc[s3]
```
or
```bash
$ poetry add dvc -E s3
```

Then try to `dvc add` and `dvc push` something. It will result in the following error message:

```bash
ERROR: failed to push data to the cloud - URL 's3://' is supported but requires these missing dependencies: ['boto3']. To install dvc with those dependencies, run:

	pip install 'dvc[s3]'

See <https://dvc.org/doc/install> for more info.
```

Interestingly, when I run `pip install 'dvc[s3]'` it **does** install `boto3` but this is an unsatisfactory solution since I need to integrate `dvc` with `poetry` in order to ensure that the code won't break on other machines.

### Expected

I would expect `dvc push` to work seemlessly after I ran `poetry install dvc[s3]`.

### Environment information

Fedora 33 / Python 3.9.9 / dvc 2.9.5

**Output of `dvc doctor`:**

```console
DVC version: 2.9.5 (pip)
---------------------------------
Platform: Python 3.9.9 on Linux-5.14.18-100.fc33.x86_64-x86_64-with-glibc2.32
Supports:
	webhdfs (fsspec = 2022.2.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	s3 (s3fs = 2022.2.0, boto3 = 1.20.24)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/mapper/fedora_carbon-home
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/mapper/fedora_carbon-home
Repo: dvc, git
```

**Comment by markf94** [comment] 2022-03-17 04:03
I've narrowed it down to commit 6034f0e since `poetry add dvc[s3]==2.9.2` still works.

**Comment by pmrowla** [comment] 2022-03-17 04:14
Closing as duplicate of https://github.com/iterative/dvc/issues/7257

the actual issue here is a poetry bug (poetry's dependency resolver doesn't handle nested/recursive extras properly): https://github.com/python-poetry/poetry/issues/4683

**Closed by pmrowla** 2022-03-17 04:14 UTC
