### ISSUE TITLE
repro --pull to retrieve tracked files/folders added using `add`

### ISSUE THREAD

**Issue by Xyand** [iterative/dvc#5159] opened 2020-12-25 07:06 UTC
Currently files tracked using `add` need to be manually pulled/checked-out although the dependency is specified in a pipeline.

**Comment by pmrowla** [comment] 2020-12-25 10:54
This is a known limitation, `repro --pull` currently only pulls run cache and not data. Closing as a duplicate of https://github.com/iterative/dvc/issues/4742

**Closed by pmrowla** 2020-12-25 10:54 UTC

**Comment by Xyand** [comment] 2020-12-25 11:17
I suggest to explain it in the docs until implemented. Current
documentation  is misleading.

**Comment by efiop** [comment] 2020-12-25 15:33
@Xyand Thanks for the suggestion! That feature is on our short todo list, stay tuned!
