### ISSUE TITLE
OAuth 2.0 Support for Accessing an Azure Blob Storage

### ISSUE THREAD

**Issue by MalouNetlight** [iterative/dvc#5045] opened 2020-12-07 16:00 UTC
Dear DVC team,

Thanks a lot for that awesome project! I love it but I'm currently struggling as I'm trying to setup a remote blob storage using the OAuth 2.0 authentication mechanism.

**First question**: Is there a way/trick to setup a remote blob storage using OAuth 2.0?

**Follow-up question**: If not, do you plan to do that?

Here's a link to the official microsoft documentation to OAuth 2.0: https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad?toc=/azure/storage/blobs/toc.json

Thanks a lot for your input!

Best, 

Malou

**Comment by shcheklein** [comment] 2020-12-09 05:36
This looks like a duplicate of #4635 ? A WIP PR by @JordanSimba should solve this as far as I understand. 

@JordanSimba @MalouNetlight could you correct me, if I'm wrong?

**Comment by MalouNetlight** [comment] 2020-12-09 08:59
Hi, thanks for making the link. I used App Registrations until now to connect using OAuth 2.0 but I guess that Service Principles would also do the trick. 
Actually, looking at the code, it seems that I could even use an App Registration's client id and secret to get the token. So yeah, the PR you mentioned should solve this. 

Hopefully this can be merged soon, that would be an awesome feature!

**Comment by shcheklein** [comment] 2020-12-09 19:18
Okay, closing this as a duplicate for now. @MalouNetlight please follow the PR and the #4635 for the progress. I also hope we'll get it done asap 🤞 (it's mostly me a bottleneck here- reviewing properly requires getting up to speed with a lot of details on the Azure auth process, @JordanSimba is doing great job educating and iterating with me on this)

**Closed by shcheklein** 2020-12-09 19:18 UTC
Labels: triage
