### ISSUE TITLE
Keep temporary clones of import source repos

### ISSUE THREAD

**Issue by johnyaku** [iterative/dvc#10511] opened 2024-08-07 06:26 UTC
When working with imports from other repos, many dvc operations make temporary clones of those repos in `.dvc/tmp`. The clones are then destroyed after the operation completes.

But then these same repos get cloned again and again with subsequent operations. Admittedly, cluttering up `.dvc/tmp` is inefficient, but then again so is all the cloning.

Then we run into a more serious problem in some HPC environments, where we have to choose between a queue that provides internet connectivity (but limited memory and only one CPU) and a queue with scalable resources (CPU, memory, etc). Some dvc operations fail with less than four CPUs available, or at least they have historically. But for many operations internet connectivity is only required briefly for these temporary clones.

Ideally, we'd like to be able to separate the steps that require connectivity and the steps that require CPUs. That is, we'd like keep the clones, and clean them up manually at our leisure. This would allow us to run things like `dvc data status` without connectivity, which we'd like to do as part of CI/CD (running on the HPC).

For this to work, we need the following:
1. A command to make/update temporary clones 
2. An option to use existing clones, without trying to reclone.
3. An option to not delete temporary clones at the end of an operation that uses them

I guess 2 and 3 should probably be the same option.

**Comment by skshetry** [comment] 2024-08-07 06:36
FYI `dvc data status` does not require cloning. The command only cares about data (i.e. outputs), and ignores dependencies.

**Comment by johnyaku** [comment] 2024-08-08 05:49
Apologies for the poor choice of example.

`dvc pull` and `dvc checkout` do make temporary clones, and I'm fairly sure that there are other examples.

**Comment by shcheklein** [comment] 2024-08-14 18:52
Related / duplicate of https://github.com/iterative/dvc/issues/3496 . If it makes sense, please migrate the comment and upvote that ticket please.

**Comment by dberenbaum** [comment] 2024-08-15 13:46
Closing since discussion has migrated to #3496

**Closed by dberenbaum** 2024-08-15 13:46 UTC
Labels: feature request, p1-important, performance, A: data-sync
