### ISSUE TITLE
`dvc pull -r storage`: Pull other storage together.

### ISSUE THREAD

**Issue by quant1216** [iterative/dvc#7366] opened 2022-02-10 04:28 UTC
# Bug Report
`dvc pull -r storage` pull other storage together.

## Description
I'm dividing the data into two GCP storages for some reasons. When I execute `dvc pull -r storage`, it pull other_storage data too.

### Reproduce
I tested as follows.

1. Put data only in the first storage (the second storage is empty)
2. `dvc pull -r second_storage`
3. It pull first storage data

### Expected
Only pull data from targeted storage.

### Environment information

.dvc/config 
```
['remote "storage"']
    url = gs://[FIRST-BUCKET-STORAGE]
['remote "other_storage"']
    url = gs://[SECOND-BUCKET-STORAGE]
```

**Comment by quant1216** [comment] 2022-02-10 13:04
Thank you for your reply. I'll check it again. 

If the same problem exists, I will try to find a code that can be reproduced.

Thank you!

**Comment by karajan1001** [comment] 2022-02-15 11:45
for 
```bash
dvc pull -r second_storage
```
It will try to pull all of the data from remote `second_storage` no matter where they were stored. If you only want to pull some special data, you need to specify your target file. 

For example, if I have `data1` stored in `remote1`, and `data2` in `remote2`. 
```bash
dvc pull data1 # pull cache of data1 from the default remote.
dvc pull -r remote1 # pull both data1 and data2 from remote1
dvc pull data1 -r remote1 # pull cache of data1 from remote1 remote.
```

**Comment by karajan1001** [comment] 2022-02-16 04:10
> Thank you for your reply.
> 
> I'm sorry, but I don't understand right away. When you have data1 stored in remote1, and data2 in remote2. How `dvc pull -r remote1` can pull data2 that is not in remote1? I think this is not related to default setting.

The data here to be pulled only depends on the positional argument `target` in (dvc pull --help).  And optional argument `-r` only affects the remote storage to pull from. `dvc pull -r remote1` means pull all of the data (because it has no positional argument) from remote1 ( because of the optional argument `-r`).

**Comment by efiop** [comment] 2022-07-03 12:25
Closing as expected behaviour

**Closed by efiop** 2022-07-03 12:25 UTC
Labels: awaiting response, A: data-sync
