### ISSUE TITLE
DVCFileSystem cannot be instantiated twice for a repo with http auth

### ISSUE THREAD

**Issue by signaleleven** [iterative/dvc#9012] opened 2023-02-12 13:56 UTC
# Bug Report

## Description

When declaring two DVCFileSystem instances for the same repo, where the repo is a remote url with http auth, the second invokation does not work.
(I can probably avoid doing that, I was adding this to existing code and this showed me that an object was instantiated more than once - but it's still surprising and probably unintended)

### Reproduce

```python repl
>>> from dvc.api import DVCFileSystem
>>> fs = DVCFileSystem("https://username:password@gitlab.com/somegroup/dataset-registry")
>>> # (repo gets cloned, and fs works as expected)
>>> fs = DVCFileSystem("https://username:password@gitlab.com/somegroup/dataset-registry")
﻿﻿
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/.venv/lib/python3.9/site-packages/fsspec/spec.py", line 76, in __call__
    obj = super().__call__(*args, **kwargs)
  File "/path/.venv/lib/python3.9/site-packages/dvc/fs/dvc.py", line 129, in __init__
    repo = self._make_repo(
  File "/path/.venv/lib/python3.9/site-packages/dvc/fs/dvc.py", line 192, in _make_repo
    with Repo.open(uninitialized=True, **kwargs) as repo:
  File "/opt/homebrew/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/path/.venv/lib/python3.9/site-packages/dvc/external_repo.py", line 45, in external_repo
    path = _cached_clone(url, rev, for_write=for_write)
  File "/path/.venv/lib/python3.9/site-packages/dvc/external_repo.py", line 175, in _cached_clone
    clone_path, shallow = _clone_default_branch(url, rev, for_write=for_write)
  File "/path/.venv/lib/python3.9/site-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/path/.venv/lib/python3.9/site-packages/funcy/flow.py", line 274, in wrap_with
    return call()
  File "/path/.venv/lib/python3.9/site-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/path/.venv/lib/python3.9/site-packages/dvc/external_repo.py", line 222, in _clone_default_branch
    _pull(git)
  File "/path/.venv/lib/python3.9/site-packages/dvc/external_repo.py", line 258, in _pull
    git.fetch(unshallow=unshallow)
  File "/path/.venv/lib/python3.9/site-packages/scmrepo/git/__init__.py", line 289, in _backend_func
    result = func(*args, **kwargs)
  File "/path/.venv/lib/python3.9/site-packages/scmrepo/git/backend/dulwich/__init__.py", line 358, in fetch
    fetch(
  File "/path/.venv/lib/python3.9/site-packages/dulwich/porcelain.py", line 1716, in fetch
    fetch_result = client.fetch(path, r, progress=errstream.write, depth=depth)
  File "/path/.venv/lib/python3.9/site-packages/dulwich/client.py", line 833, in fetch
    result = self.fetch_pack(
  File "/path/.venv/lib/python3.9/site-packages/dulwich/client.py", line 2136, in fetch_pack
    refs, server_capabilities, url = self._discover_references(
  File "/path/.venv/lib/python3.9/site-packages/dulwich/client.py", line 1992, in _discover_references
    resp, read = self._http_request(url, headers)
  File "/path/.venv/lib/python3.9/site-packages/dulwich/client.py", line 2276, in _http_request
    raise HTTPUnauthorized(resp.headers.get("WWW-Authenticate"), url)
dulwich.client.HTTPUnauthorized: No valid credentials provided
>>> 

```
### Expected

```python repl
>>> from dvc.api import DVCFileSystem
>>> fs = DVCFileSystem("https://username:password@gitlab.com/somegroup/dataset-registry")
>>> # (repo gets cloned, and fs works as expected)
>>> fs = DVCFileSystem("https://username:password@gitlab.com/somegroup/dataset-registry")
>>> # (fs still works as expected)
```

### Environment information

The problem does not present itself with a repo that can be cloned anonymously.

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.43.1 (pip)
---------------------------------
Platform: Python 3.9.15 on macOS-13.1-arm64-arm-64bit
Subprojects:
        dvc_data = 0.35.1
        dvc_objects = 0.19.0
        dvc_render = 0.0.17
        dvc_task = 0.1.11
        dvclive = 1.3.4
        scmrepo = 0.1.6
Supports:
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.1.0, boto3 = 1.24.59)

```

**Comment by skshetry** [comment] 2023-02-13 10:53
This is a bug in dulwich. DVC keeps an in-memory cache of a list of recently cloned repositories. Since the url matches, dvc tries to reuse the cloned-repo and tries to `fetch` from the remote for any new refs. The clone is successful (that happens on first instantiation), but dulwich strips the password from the remote url. The `fetch` that we do later then fails as a result.

Can be reproduced by:
```python
from dulwich.porcelain import clone, fetch

repo = clone(url, "test")
fetch(repo)
```
See https://github.com/jelmer/dulwich/blob/01d0ebaa6ff7e949626152ec081338239f7fb128/dulwich/client.py#L2145-L2158.

**Comment by signaleleven** [comment] 2023-02-13 10:58
Yep, the stack trace suggested that too... 
Alright, I have a workaround that implies cloning the dvc repository I was trying to access via http. I then access it locally.

Thanks for looking into it!

**Comment by skshetry** [comment] 2023-02-13 12:17
FYI, we do support git credential helpers.

**Comment by signaleleven** [comment] 2023-02-13 16:22
That's interesting, I am not familiar with that. 
I'm trying that.

**Comment by signaleleven** [comment] 2023-02-13 16:36
Great, it worked! 
It took me a minute because I was setting the credential helper for the local repository (the one using DVCFilesystem), but it didn't work until I configured it globally (which is correct, I'm cloning another repository...)

**Comment by signaleleven** [comment] 2023-02-13 16:39
For whoever might also be needing this: 

```
$ git config --global credential.helper store
$ echo 'https://token:MYTOKEN@gitlab.com' >> ~/.git-credentials
```

Of course some better helper rather than 'store' would be better, but I'm going to use this in throwaway cml runners, so it should be fine.

Thanks!

**Comment by skshetry** [comment] 2023-02-14 11:26
Closed by https://github.com/jelmer/dulwich/pull/1146.

**Closed by skshetry** 2023-02-14 11:26 UTC
Labels: bug, upstream

**Comment by skshetry** [comment] 2023-02-18 15:42
`dulwich==0.21.3` is released with the fix. Please try upgrading with:
```console
pip install -U dulwich
```
