### ISSUE TITLE
dvc import: Error when importing a file not originating from that directory

### ISSUE THREAD

**Issue by tadej-redstone** [iterative/dvc#5113] opened 2020-12-15 20:24 UTC
# Bug Report

## Description

Say you have 3 repositories: A, B, and C. In repository A a file is created, versioned with DVC, and uploaded to a remote. Repository B then imports the file with `dvc import`. Then, when I try to import the file to repository C from repository B, I get an error (see the reproduction step for stack trace).

### Reproduce

Create 3 repositories: `test-feed`, `test-main`, and `test-take`, run `dvc init` in them, and add the same (s3) remote to all of them. They should each have their own cache. Then, push all of this to github.

Now, create a file in `test-feed`, add it to DVC and push it to remote:
```
echo "this is a test" >> test.txt
dvc add test.txt
git add -A
git commit -m "added test.txt"
git push
dvc push
```

Next, import this in `test-main`
```
dvc import git@github.com:tadej-redstone/test-feed test.txt
git add -A
git commit -m "imported test.txt from test-feed"
git push
```

Finally, try to import this file (from `test-main`) in `test-take`
```
dvc import -v git@github.com:tadej-redstone/test-main test.txt
```

Here's the output/stack trace
```
2020-12-15 21:12:14,271 DEBUG: Check for update is enabled.
2020-12-15 21:12:14,273 DEBUG: fetched: [(3,)]                        
2020-12-15 21:12:14,554 DEBUG: Removing output 'test.txt' of stage: 'test.txt.dvc'.
Importing 'test.txt (git@github.com:tadej-redstone/test-main)' -> 'test.txt'
2020-12-15 21:12:14,555 DEBUG: Computed stage: 'test.txt.dvc' md5: 'eda333ca4ff04ef69c494d1b3380592d'
2020-12-15 21:12:14,555 DEBUG: 'md5' of stage: 'test.txt.dvc' changed.
2020-12-15 21:12:14,555 DEBUG: Creating external repo git@github.com:tadej-redstone/test-main@None
2020-12-15 21:12:14,556 DEBUG: erepo: git clone 'git@github.com:tadej-redstone/test-main' to a temporary dir
2020-12-15 21:12:16,575 DEBUG: Saving '../../../private/var/folders/14/dg5f_dxs5x74vzlc61hc19340000gq/T/tmp2juar86idvc-clone/test.txt' to '.dvc/cache/ac/761519fdaf77899202c34692d64c98'.
2020-12-15 21:12:16,576 DEBUG: cache '/Users/tadejsvetina/test-take/.dvc/cache/ac/761519fdaf77899202c34692d64c98' expected 'HashInfo(name='md5', value='ac761519fdaf77899202c34692d64c98', dir_info=None, size=12, nfiles=None)' actual 'None'
2020-12-15 21:12:16,576 DEBUG: cache '/Users/tadejsvetina/test-take/.dvc/cache/ac/761519fdaf77899202c34692d64c98' expected 'HashInfo(name='md5', value='ac761519fdaf77899202c34692d64c98', dir_info=None, size=12, nfiles=None)' actual 'None'
2020-12-15 21:12:16,684 DEBUG: Preparing to download data from 's3://pretrained-startup-artifacts/dvc'
2020-12-15 21:12:16,684 DEBUG: Preparing to collect status from s3://pretrained-startup-artifacts/dvc
2020-12-15 21:12:16,684 DEBUG: Collecting information from local cache...
2020-12-15 21:12:16,689 DEBUG: fetched: [(0,)]                                                                                       
2020-12-15 21:12:16,690 ERROR: unexpected error - [Errno 2] No such file or directory: '/Users/tadejsvetina/test-take/.dvc/cache/ac/761519fdaf77899202c34692d64c98'
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tadejsvetina/miniconda3/envs/test/lib/python3.8/site-packages/dvc/main.py", line 90, in main
    ret = cmd.run()
  File "/Users/tadejsvetina/miniconda3/envs/test/lib/python3.8/site-packages/dvc/command/imp.py", line 14, in run
    self.repo.imp(
  File "/Users/tadejsvetina/miniconda3/envs/test/lib/python3.8/site-packages/dvc/repo/imp.py", line 6, in imp
    return self.imp_url(
  File "/Users/tadejsvetina/miniconda3/envs/test/lib/python3.8/site-packages/dvc/repo/__init__.py", line 54, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/tadejsvetina/miniconda3/envs/test/lib/python3.8/site-packages/dvc/repo/scm_context.py", line 4, in run
    result = method(repo, *args, **kw)
  File "/Users/tadejsvetina/miniconda3/envs/test/lib/python3.8/site-packages/dvc/repo/imp_url.py", line 64, in imp_url
    stage.run()
  File "/Users/tadejsvetina/miniconda3/envs/test/lib/python3.8/site-packages/funcy/decorators.py", line 39, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/Users/tadejsvetina/miniconda3/envs/test/lib/python3.8/site-packages/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/Users/tadejsvetina/miniconda3/envs/test/lib/python3.8/site-packages/funcy/decorators.py", line 60, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/Users/tadejsvetina/miniconda3/envs/test/lib/python3.8/site-packages/dvc/stage/__init__.py", line 500, in run
    sync_import(self, dry, force)
  File "/Users/tadejsvetina/miniconda3/envs/test/lib/python3.8/site-packages/dvc/stage/imports.py", line 30, in sync_import
    stage.deps[0].download(stage.outs[0])
  File "/Users/tadejsvetina/miniconda3/envs/test/lib/python3.8/site-packages/dvc/dependency/repo.py", line 78, in download
    _, _, cache_infos = repo.fetch_external([self.def_path])
  File "/Users/tadejsvetina/miniconda3/envs/test/lib/python3.8/site-packages/dvc/external_repo.py", line 175, in fetch_external
    hash_info = self._fetch_to_cache(
  File "/Users/tadejsvetina/miniconda3/envs/test/lib/python3.8/site-packages/dvc/external_repo.py", line 142, in _fetch_to_cache
    cache.save(
  File "/Users/tadejsvetina/miniconda3/envs/test/lib/python3.8/site-packages/funcy/decorators.py", line 39, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/Users/tadejsvetina/miniconda3/envs/test/lib/python3.8/site-packages/dvc/cache/base.py", line 40, in use_state
    return call()
  File "/Users/tadejsvetina/miniconda3/envs/test/lib/python3.8/site-packages/funcy/decorators.py", line 60, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/Users/tadejsvetina/miniconda3/envs/test/lib/python3.8/site-packages/dvc/cache/base.py", line 317, in save
    self._save(path_info, tree, hash_info, save_link, **kwargs)
  File "/Users/tadejsvetina/miniconda3/envs/test/lib/python3.8/site-packages/dvc/cache/base.py", line 326, in _save
    self._save_file(path_info, tree, hash_info, save_link, **kwargs)
  File "/Users/tadejsvetina/miniconda3/envs/test/lib/python3.8/site-packages/dvc/cache/base.py", line 213, in _save_file
    with tree.open(path_info, mode="rb") as fobj:
  File "/Users/tadejsvetina/miniconda3/envs/test/lib/python3.8/site-packages/dvc/tree/repo.py", line 152, in open
    return dvc_tree.open(path_info, mode=mode, encoding=encoding, **kwargs)
  File "/Users/tadejsvetina/miniconda3/envs/test/lib/python3.8/site-packages/dvc/tree/dvc.py", line 107, in open
    return open(cache_path, mode=mode, encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/tadejsvetina/test-take/.dvc/cache/ac/761519fdaf77899202c34692d64c98'
```

### Expected

I would expect this to import the file normally.

### Environment information

```console
DVC version: 1.11.4 (conda)
---------------------------------
Platform: Python 3.8.6 on macOS-10.15.6-x86_64-i386-64bit
Supports: azure, gdrive, gs, hdfs, http, https, s3, ssh, oss
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: s3
Repo: dvc, git
```

**Comment by skshetry** [comment] 2020-12-16 05:24
Duplicate of https://github.com/iterative/dvc/issues/3305

**Comment by skshetry** [comment] 2020-12-16 05:27
@tadej-redstone, this is not supported right now. Is it possible to import directly from repository A for now? 

I am closing this issue for the existing #3305, please feel free to share your scenario there and/or upvote the issue so that we could prioritize. Thanks.

**Closed by skshetry** 2020-12-16 05:27 UTC
