### ISSUE TITLE
use git index to see force-added files

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#6291] opened 2021-07-06 09:07 UTC
We've received a few reports about people getting confused by dvc pull/etc not detecting their dvc files in configuration with such .gitignore:
```
/data
!**/*.dvc
```

as explained by @pmrowla , this is just a nonobvious git behavior and a workaround is:

```
/data/**
!/data/**/
!/data/**/*.dvc
```

But `dvc list` will see those files no problem, because it doesn't seem to use `is_ignore` (needs confimation), thus, we should use git index locally as well to detect force-added files even if they are gitignored.

**Comment by pmrowla** [comment] 2021-07-06 09:17
> But `dvc list` will see those files no problem, because it doesn't seem to use `is_ignore` (needs confimation)

this is correct, in `repo.ls()` we will end up just using `fs.walk()` on the git tree without checking for any ignores (there is no reason to check since the git fs can only contain paths which have already been (force) added and committed into git)

In `repo.stage.collect_repo()` we use `fs.walk()` but also check `is_out_or_ignored` to avoid traversing into git-ignored subdirs (for performance reasons). 
https://github.com/iterative/dvc/blob/98f7d1e481afb84e7bca858d4c990e32fe9bd198/dvc/repo/stage.py#L490
The problem is that this ends up filtering out ignored subdirs that have force-added git paths inside of them. So `is_out_or_ignored` probably needs to account for the possibilty of force-added paths here

**Comment by skshetry** [comment] 2021-07-06 09:18
Better to ask users to not ignore `.dvc` files at all, as DVC itself takes care of it. Using git index is one more complexity. 
Relared https://github.com/iterative/dvc/issues/6025.

**Comment by pmrowla** [comment] 2021-07-06 09:23
> Better to ask users to not ignore `.dvc` files at all, as DVC itself takes care of it

We do this to some extent now that we no longer allow `dvc add` when the resulting `.dvc` file would end up git-ignored, but that doesn't help in existing repos where the files are force-added (but git-ignored) in old revs

**Comment by skshetry** [comment] 2021-07-06 09:25
Right, we made some decisions in 2.0 that might be incompatible with the older repos. That's fine, the only reason why we do this is for performance. Complicating it further, I don't think is a good solution. If it's causing issues, we should drop this optimization.

**Comment by efiop** [comment] 2021-07-06 09:25
Also people use that trick to absolutely ensure that no large artifacs accidentally end up committed and pushed in git, so can't really blame them :slightly_frowning_face:

The optimization itself seems useful though, don't see why we need to drop it.

**Comment by pmrowla** [comment] 2021-07-06 09:28
I also don't think that this change would be all that complex. We already have the git fs tree and the actual trie containing all the paths which were explicitly added in git. Checking to see if some subdir prefix exists in the trie seems trivial to me.

**Comment by efiop** [comment] 2021-07-06 09:29
Let's give it a shot and we'll see how it is in terms of complexity and performance.

**Comment by skshetry** [comment] 2021-07-06 09:30
If we go this route, #6025 will no longer be an issue.

**Comment by karajan1001** [comment] 2021-07-06 13:39
I think this is enough.

```
/data/**
!**/*.dvc
```

**Comment by karajan1001** [comment] 2021-07-06 13:47
> I think this is enough.
> 
> ```
> /data/**
> !**/*.dvc
> ```

Only for the files inside `data/` not works with those inside sub directory

**Comment by SebbanSms** [comment] 2021-07-06 15:14
Is there no way to track a file on dvc remote that is not commited to git if its mentioned in my dvc.yaml?

If I have in .gitignore:
```
/data/
```

and in dvc.yaml:
```
deps:
  - data/input/my_data.csv
```

I still want to be able to `dvc push` and `dvc pull` the file from my dvc remote without having to litter github with my .csv file
But whatever is ignored by git seems to be ignored by dvc push/pull as well.

Otherwise I have to add all the files with dvc add and pull them separately with a bunch of
```
dvc pull path/to/file.csv.dvc
```
That feels odd to me.

Especially because `dvc pull` even deletes git ignored files that are in dvc.yaml and added with `dvc add`

**Comment by efiop** [comment] 2021-07-06 20:10
@SebbanSms Does adding an exclusion rule for *.dvc, as described above, work for you?

**Comment by SebbanSms** [comment] 2021-07-08 13:35
@efiop Yes it seems to work, but why do I need to `dvc add` input files to have separate `.csv.dvc` files to push my inputs when the input files are already listed as `deps` in the dvc.yaml.

All `outs` of the dvc.yaml are pushed without further hustle about any `.gitignore` changes or additional `.dvc` files. If `deps` could be pushed to and pulled from remote the same way, that would be less overhead.

Maybe there is a good reason for not doing that, which I'm missing?

**Comment by efiop** [comment] 2021-07-08 16:29
@SebbanSms `deps` only declare dependencies for that particular stage, they don't really do data management. Plus, same path could be declared as a dependency in multiple stages/dvc.yaml's , which is a bit problematic for us right now in terms of mapping of versions (aka md5s), while outs are unique and don't have that problem. We might reconsider this in the future though.

**Comment by skshetry** [comment] 2024-03-25 11:36
Closing as not planned.

**Closed by skshetry** 2024-03-25 11:36 UTC
