### ISSUE TITLE
run: allow tracking of all params in a file with `-p`

### ISSUE THREAD

**Issue by gcoter** [iterative/dvc#4112] opened 2020-06-25 13:43 UTC
### Please provide information about your setup

**Output of `dvc version`:**

```console
DVC version: 1.0.2
Python version: 3.6.8
Platform: Linux-4.15.0-106-generic-x86_64-with-LinuxMint-18.3-sylvia
Binary: False
Package: pip
Supported remotes: http, https, ssh
Cache: reflink - not supported, hardlink - supported, symlink - supported
Repo: dvc, git
```

**Additional Information (if any):**

I tried to use `dvc run` with two `-p` arguments (because I have two parameters files). It gives me this error:
```
ERROR: dependency 'params.yaml' does not exist
```

If I remove one of the two arguments, it works. So it looks like DVC doesn't enjoy having two `-p` arguments. Is it expected? If DVC doesn't support more than one parameters file, the ERROR message should indicate that more explicitly.

**Comment by skshetry** [comment] 2020-06-25 13:49
@gcoter, does the params.yaml exist? Can you give more verbose error message (and, your command that you tried)?

**Comment by gcoter** [comment] 2020-06-25 13:54
@skshetry thanks for your quick answer! My command looks like this:
```
dvc run -d training.py -p config/params_1.json -p config/params_2.json:data.training,model -o trained_model/ -n training python training.py
```

I prefer to use JSON files so `params.yaml` does not exist in my project.

**Comment by skshetry** [comment] 2020-06-25 13:56
@gcoter, is that a typo on `-p config/params_1.json` (i.e. there's no list of parameters eg: `-p config/params_1.json:loss`).

**Comment by gcoter** [comment] 2020-06-25 13:58
@skshetry No, I thought that specifying `config/params_1.json` would select everything inside this file. Should I specify explicitly the keys I want to select?

**Comment by skshetry** [comment] 2020-06-25 14:00
@gcoter, yes, you have to specify keys that you want.

**Comment by gcoter** [comment] 2020-06-25 14:01
@skshetry Ok, indeed it works if I specify manually the keys. I thought that DVC would list all the keys by default. But I don't mind listing them myself. Thank you for your help!

**Comment by skshetry** [comment] 2020-06-25 14:02
@gcoter, but, I can see it's usefulness. I'll log this as a feature request though.

**Comment by skshetry** [comment] 2020-06-25 14:04
@gcoter, another question, why do you choose to `-p` rather than tracking whole file? for granularity tracking of parameter values, right?

**Comment by gcoter** [comment] 2020-06-25 14:13
@skshetry I am at the beginning of the project, so it is not very clear in my mind, but I would like to benefit from the `dvc params diff` command. Basically, if I use `-d`, I cannot diff the params. Well, I could use `git diff` but `dvc params diff` formats the diff in a nice way in my opinion. And since this file is actually used to store configuration settings, it makes sense to me to use `-p`.

**Comment by lambdaofgod** [comment] 2020-11-18 13:22
# Simple workaround for json files

Define bash functions in `.bashrc`

```
function print_json_keys {
    json_file=$1
    if [ "$2" ]
    then
        sep="$2"
    else
        sep=','
    fi
    jq -r '[paths | join(".")]' $1 | sed -n 's/\ *"\(.*\)",/\1/p' | head -c -1 | tr '\r\n' $sep
}

function get_all_dvc_json_params {
    json_file=$1
    echo "$json_file:$(print_json_keys $json_file)"
}
```

then use, assuming you have params in `config.json`

```
dvc run -p $(get_all_dvc_json_params config.json)
```

@skshetry let me know if you think it makes sense to add this as default behavior for DVC when the parameters are not defined. I can to take add this to DVC if I receive some guidance.

**Comment by theoturner** [comment] 2020-11-24 17:05
For future reference, the file must be named `params.yaml`, not `params.yml` for DVC to see it.

**Comment by skshetry** [comment] 2020-11-25 04:37
@lambdaofgod, sure, go ahead. We might just need to support it as `-p params.yaml` or `-p params.json` (without explicit `:`). 
But, the main question is, what the behavior should be.

1) Should it work like your script, i.e. fetch all params and track each of them individually?
2) Or, should it just act like other output dependencies, in that the stage reproduces if you add/delete any params in the file?

If 1), then how should we specify them on `dvc.yaml`? Should that be limited to just this helper function?

**Comment by dberenbaum** [comment] 2022-01-04 19:12
Option 2 makes sense to me because:

1. If a new parameter is added, I would rather err on the side of being overly aggressive in detecting parameters changes rather than ignore it.
2. It's clean and simple in `dvc.yaml` (list the file instead of breaking out each individual key).
3. It seems consistent with how YAML section keys are handled now. I don't see much difference from the current handling of `-p foo` with a `params.yaml` like:

```yaml
foo:
  bar: 1
  baz: 2
```

**Comment by skshetry** [comment] 2022-03-04 09:01
We have two choices on syntax in `dvc.yaml`.
1. Using `null` to indicate track everything
```yaml
params:
  - params.yaml:
  - config.yaml:
```

  Pros:
  1. This does not require us to create our own syntax/DSL, it is YAML.
  2. (Better schema?)

  Cons:
  1.  This syntax requires filename to be explicitly specified, even for `params.yaml` file which we consider as being the default.
  2. The semantic meaning of `null` to mean track everything is questionable. However, it depends on the narrative we want to set. Currently, the purpose of `params` is that it can track parameters in a granular way. If we do change that to suggest that DVC can track params as a whole, but it can also support things at a granular level, it does make sense as well.

2 Using `*`
```yaml
params:
 - *   # means track everything from params.yaml
 - config.yaml:*   # means track everything from config.yaml
```

Pros:
1. Supports tracking `params.yaml` easily by just using `*`.

 Cons:
1. Requires us to create our own DSL, which may be confused with being a regex.

**Comment by daavoo** [comment] 2022-03-04 11:59
> We have two choices on syntax in `dvc.yaml`.

Why it's not possible to support:

```yaml
params:
  - custom_params.yaml  # full file
  - foo  # dvc will search for this as usual
```

**Comment by skshetry** [comment] 2022-03-04 12:04
> Why it's not possible to support the following?
> 
> ```yaml
> params:
>   - custom_params.yaml  # full file
>   - foo  # dvc will search for this as usual
> ```

It is ambiguous. The `foo` may be a params file, and `custom_params.yaml` may be just a hyperparameter `yaml` nested inside `custom_params`. Note that this is only a metadata, and the files don't have to necessarily be present in the workspace, eg: the file could have been deleted or be read from certain revisions, etc. so the fallback approaches are going to be ugly.

**Comment by daavoo** [comment] 2022-03-04 13:27
> It is ambiguous. The `foo` may be a params file, and `custom_params.yaml` may be just a hyperparameter `yaml` nested inside `custom_params`. 

I find it more intuitive than the other syntax, this is what users usually try first and report as a bug when it fails.

For conflicts, we can document the behavior and add priority for resolving: `checking if {name} is in `params.yaml > checking if {name} is a file and exists`. Although, tbh, I don't think it's common to use a parameters file without extension nor name a parameter with a extension.

> Note that this is only a metadata, and the files don't have to necessarily be present in the workspace, eg: the file could have been deleted or be read from certain revisions, etc. so the fallback approaches are going to be ugly.

Not sure if I understand why this is an issue only with this syntax

**Comment by skshetry** [comment] 2022-03-04 16:30
It's better to avoid ambiguity if possible. And, `diff` and `status` have stronger requirements.
For example, what will you show `dvc status` for `foo` if the `foo` file and `params.yaml` both don't exist at all? 

Also `dvc` supports any arbitrary file (it just fallbacks to yaml), so `foo.bar` could be a params file or an xpath to that parameters.

> I find it more intuitive than the other syntax, this is what users usually try first and report as a bug when it fails.

I know it's intuitive, but I don't think we have a much better choice. Given that we consider this to be an advanced feature, it's okay to consider it as a tradeoff.

**Comment by dberenbaum** [comment] 2022-03-07 20:58
> ```yaml
> params:
>   - custom_params.yaml  # full file
>   - foo  # dvc will search for this as usual
> ```

I think we could come up with consistent logic to deal with ambiguities here, so I think we should focus on whether the intuitiveness/convenience outweighs the ambiguity.

Can we assume any param that ends in `.yaml`, `.yml`, `.json`, `.toml`, or `.py` is a file path, and otherwise it's not? Is there a realistic scenario when this would be problematic?

> It's better to avoid ambiguity if possible. And, `diff` and `status` have stronger requirements.
> For example, what will you show `dvc status` for `foo` if the `foo` file and `params.yaml` both don't exist at all?

Doesn't the use of `.` to specify nested keys already introduce ambiguity (how do we know whether this is a nested key or just a top-level key with `.` in it)? Is this different?

> Also `dvc` supports any arbitrary file (it just fallbacks to yaml), so `foo.bar` could be a params file or an xpath to that parameters.

Aren't parameters limited to particular file types, and dvc uses the file extension to determine the type? It seems like the only added ambiguity is when dvc falls back to yaml, and I don't think it's unreasonable to expect `.yaml` or `.yml` there.

**Comment by skshetry** [comment] 2022-03-08 09:56
> Can we assume any param that ends in .yaml, .yml, .json, .toml, or .py is a file path, and otherwise it's not? Is there a realistic scenario when this would be problematic?

It's a weird restriction to not be able to track keys named `yaml`/`yml`/json`/`toml`/`py`. These file extensions are likely to expand in the future.

> Doesn't the use of . to specify nested keys already introduce ambiguity (how do we know whether this is a nested key or just a top-level key with . in it)? Is this different?

We don't support the keys with `.` at all. `.` is strictly a separator.

> Aren't parameters limited to particular file types, and dvc uses the file extension to determine the type? It seems like the only added ambiguity is when dvc falls back to yaml, and I don't think it's unreasonable to expect .yaml or .yml there.

yes, DVC uses file extensions to determine the type and falls back to yaml parser which supports `json` and `yaml` contents.

Overloading the schema to track parameters in granular and in whole may be confusing.

**Comment by dberenbaum** [comment] 2022-03-08 16:28
> ```yaml
> params:
>   - params.yaml:
>   - config.yaml:
> ```

How will this work in CLI? `dvc stage add -p config.yaml:`? Will that cause any issues?

> It's a weird restriction to not be able to track keys named `yaml`/`yml`/json`/`toml`/`py`. These file extensions are likely to expand in the future.

I think we can document that supported file extensions cannot be used as parameter keys.

> yes, DVC uses file extensions to determine the type and falls back to yaml parser which supports `json` and `yaml` contents.

So if we rely on file extensions, the breaking changes would be:
* Parameter keys like `yaml` or other file extensions are no longer supported.
* YAML/JSON parameter files can't use nonstandard extensions.

@skshetry Does that all sound right? If you think there's a good way to go with option 1 and have the CLI make sense without introducing breaking changes, I'm fine with that. Otherwise, I think the file extension approach is intuitive and the breaking changes aren't too bad as long as we document them.

**Comment by skshetry** [comment] 2022-03-11 11:31
> @daavoo mentioned that tracking params directories could come up in the future. It seems like option 1 would be better if we want to make future changes like this easier.

We currently don't have a way of tracking directory in `dvc.lock` as it only supports a key-value pair of `filename:tracked_params`, and all of those are arbitrary. We don't have support for additional/formal metadata there.
So I am not going to consider that here.

---

Regarding the syntax, I am going with the (1) option, i.e. using `null`, as it is simpler and closer to the implementation. We can easily support @daavoo's proposal in the future.

**Comment by skshetry** [comment] 2022-03-11 11:45
The current implementation along with `exp init` can be tested through #7413 PR.

**Closed** 2022-03-21 08:02 UTC
Labels: feature request, p2-medium, A: params

**Comment by jorgeorpinel** [comment] 2022-04-12 03:48
> We might just need to support it as `-p params.yaml`

Was this the way it was implemented? If so what happens if there's a `params.yaml` param inside the default `params.yaml`? That'd be ambiguous I think.

**Comment by daavoo** [comment] 2022-04-12 06:28
> > We might just need to support it as `-p params.yaml`
> 
> Was this the way it was implemented? If so what happens if there's a `params.yaml` param inside the default `params.yaml`? That'd be ambiguous I think.

Parameter names cannot contain file extensions supported for parameter files cannot. We need to mention this explicitly in the docs

**Comment by dberenbaum** [comment] 2022-04-12 15:18
> > We might just need to support it as `-p params.yaml`
> 
> Was this the way it was implemented? If so what happens if there's a `params.yaml` param inside the default `params.yaml`? That'd be ambiguous I think.

No, it needs to be `-p params.yaml:` if passed as a command line argument.

**Comment by jorgeorpinel** [comment] 2022-04-19 06:25
> Parameter names cannot contain file extensions supported for parameter files cannot.

Is this an actual error condition?

**Comment by dberenbaum** [comment] 2022-04-19 10:48
No, we discussed using file extensions that way that but decided to be more explicit and require `-p params.yaml:` so there is no confusion over what is a file and what is a parameter.

**Comment by jorgeorpinel** [comment] 2022-04-19 17:57
OK so something like
```yaml
params:
  - yami
  - yaml
  - yamj
```
is allowed in the params file scheme after all?

Sorry, just trying to make sure I get this right (for https://github.com/iterative/dvc.org/pull/3431#issuecomment-1102141094).

**Comment by dberenbaum** [comment] 2022-04-20 16:34
Yup, that should work. Feel free to test it.
