### ISSUE TITLE
exp push: rejected https git push in Gitlab-CI

### ISSUE THREAD

**Issue by BaptisteLoquette** [iterative/dvc#10096] opened 2023-11-15 11:34 UTC
I get this error with dvc exp push origin : 
`DEBUG: link type reflink is not available ([Errno 95] no more link types left to try out)`

Note that everything is done inside a .gitlab-ci.yml file. And I don't `dvc exp run`, the artifact etc... are logged through Live and DVCLiveCallBack
I have an Azure Blob Storage, when pushed the data is stored on the Blob Storage. I can pull them from the CI script.

When I `.log_artifact()` outside of the Live's dir the artifact is pushed to the remote Azure blob, and the CI script is able to finish. But no models/model.dvc is pushed to the repo.

But when the artifact is logged inside the Live's dir ("dvclive") then I get this error : `DEBUG: link type reflink is not available ([Errno 95] no more link types left to try out)`

I've tried to set up only hardlink and symlink, but I get the same.
I've also tried to log the model through the studio with the files stored on the blob, but I get an "Unexpected error" with no ability to see the Traceback.

```
DVC version: 3.29.0 (pip)
-------------------------
Platform: Python 3.8.10 on Linux-5.4.0-1109-azure-x86_64-with-glibc2.29
Subprojects:
	dvc_data = 2.20.0
	dvc_objects = 1.2.0
	dvc_render = 0.6.0
	dvc_task = 0.3.0
	scmrepo = 1.4.1
Supports:
	azure (adlfs = 2023.10.0, knack = 0.11.0, azure-identity = 1.15.0),
	http (aiohttp = 3.8.6, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.6, aiohttp-retry = 2.8.3)
Config:
	Global: /root/.config/dvc
	System: /etc/xdg/dvc
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdb1
Caches: local
Remotes: azure
Workspace directory: ext4 on /dev/sdb1
Repo: dvc, git
```

**Comment by BaptisteLoquette** [comment] 2023-11-16 09:56
Idk if it impacts anything but. Note that I didn't use SSH with git repo and wasn't using credential helpers. I just set up SSH, but still get same error.

**Comment by dberenbaum** [comment] 2023-11-17 12:58
@BaptisteLoquette Have you tried to do a regular git push in that CI script to see if it works?

**Comment by BaptisteLoquette** [comment] 2023-11-17 14:18
Regular meaning no-SSH, with only login and password. If so I did for last few days, I settled up SSH yesterday to see if it would resolve this.

**Comment by dberenbaum** [comment] 2023-11-17 14:39
When you run `dvc exp push` inside CI, you get an error because the Git push failed. What I mean is that you could try to replace `dvc exp push` by committing and pushing manually, like `git add && git commit && git push` and see if it works. That would tell you whether it's an issue with your git authentication or with how dvc is doing the push.

**Comment by BaptisteLoquette** [comment] 2023-11-17 15:16
Oh yeah inside the CI. Yeah Ill try that. I do think it's purely with the git creds and not dvc, though. Do you know if having a token set up for me to git push (not on the CI) and not through password can block the dvc exp push ?

**Comment by BaptisteLoquette** [comment] 2023-11-19 14:11
Okay so when manually done in the CI. git push works good. I think the error is about how I configure the studio

**Comment by BaptisteLoquette** [comment] 2023-11-19 14:40
So I removed everything related to the studio to check. And it still yields the same error, I think I'll just git push manually

**Comment by dberenbaum** [comment] 2023-11-20 00:32
Makes sense, @BaptisteLoquette. @pmrowla It looks like this is an issue in scmrepo then.

**Comment by dberenbaum** [comment] 2024-01-09 13:37
Lowering the priority since we haven't been able to identify what's happening here and haven't heard additional reports

**Comment by skshetry** [comment] 2024-03-27 09:08
@dberenbaum, I am closing the issue as we don't have enough information to reproduce, and we did not hear any more reports. Feel free to reopen if you think it's important.

**Closed by skshetry** 2024-03-27 09:08 UTC
Labels: bug, p2-medium, A: experiments, git
