### ISSUE TITLE
unexpected error - _register_s3_control_events() takes 2 positional arguments but 6 were given

### ISSUE THREAD

**Issue by danielbellsa** [iterative/dvc#8513] opened 2022-11-01 15:56 UTC
Only as of recently, have I had this error with DVC.

Tracback:
```
(venv) me@ubuntu-pcs:~/PycharmProjects/project$ dvc push
ERROR: unexpected error - _register_s3_control_events() takes 2 positional arguments but 6 were given                                                                                                                                                          

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!

(venv) me@ubuntu-pcs:~/PycharmProjects/project$ dvc doctor
DVC version: 2.28.0 (pip)
---------------------------------
Platform: Python 3.9.13 on Linux-5.15.0-52-generic-x86_64-with-glibc2.35
Subprojects:
        dvc_data = 0.13.0
        dvc_objects = 0.5.0
        dvc_render = 0.0.11
        dvc_task = 0.1.2
        dvclive = 0.12.1
        scmrepo = 0.1.1
Supports:
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2022.10.0, boto3 = 1.24.59)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p5
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/nvme0n1p5
Repo: dvc, git
```

`.dvc/config/`:
```
[core]
    remote = storage
    autostage = true
['remote "storage"']
    url = s3://bucket/project/dvcstore/
```

Let me know if I should add anything else to the post.

**Comment by skshetry** [comment] 2022-11-01 16:04
Looks like an issue with a recent release of botocore>=1.28.0. If you can pass the output of `dvc push -v`, we can trace where it's being called (most likely in `aiobotocore`). Meanwhile, you can install botocore<1.28.0.

**Comment by pared** [comment] 2022-11-01 16:25
@danielbellsa could you also run
`pip freeze | grep aiobotocore`?

**Comment by pared** [comment] 2022-11-01 16:31
I am able to reproduce for `botocore==1.28.3`

**Comment by efiop** [comment] 2022-11-01 16:36
aiobotocore requires a particular botocore version. What most likely happened is you probably installed some other package that conflicts with aiobotocore. Check that `pip check` doesn't complain about anything.

**Comment by efiop** [comment] 2022-11-01 16:50
Looks like some other package is messed up in your environment that is not related to dvc at all. Consider recreating the env or installing dvc through pipx/snap/conda/etc.

Closing since this is env issue.

**Closed by efiop** 2022-11-01 16:50 UTC
Labels: p2-medium, upstream

**Comment by efiop** [comment] 2022-11-02 11:44
@danielbellsa here is the problem I was talking about. You've installed packages with conflicting dependencies.

> aiobotocore 2.4.0 has requirement botocore<1.27.60,>=1.27.59, but you have botocore 1.29.0.
