### ISSUE TITLE
repro: `cache: false` does not respect `--no-commit`

### ISSUE THREAD

**Issue by alkatar21** [iterative/dvc#8582] opened 2022-11-18 13:02 UTC
# Bug Report

## Description

`cache: false` in a dvc.yaml does not respect `--no-commit` in `dvc repro --no-commit`. Outputs marked with `cache: false` will still be written to the cache.

For an detailed explaination and discussion with @daavoo see the following discord message with the corresponding thread: https://discord.com/channels/485586884165107732/485596304961962003/1042423353878790164

### Reproduce

1. Download and unzip [Example.zip](https://github.com/iterative/dvc/files/10041402/Example.zip)
1. Copy the Example folder to a git repo.
1. `cd Example`
1. Execute `dvc repro --no-commit example/dvc.yaml`
1. Look in the `dvc.lock` for the outs hash. The file will be present in the cache.

### Expected

That the outs files do not end up in the cache.

### Environment information
```console
DVC version: 2.34.2 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.4.0-125-generic-x86_64-with-glibc2.29
Subprojects:
        dvc_data = 0.25.3
        dvc_objects = 0.12.2
        dvc_render = 0.0.12
        dvc_task = 0.1.5
        dvclive = 1.0.1
        scmrepo = 0.1.3
Supports:
        http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
        ssh (sshfs = 2022.6.0)
Cache types: symlink
Cache directory: ext4 on /dev/sdc1
Caches: local
Remotes: ssh
Workspace directory: ext4 on /dev/sda1
Repo: dvc (subdir), git
```

**Comment by dberenbaum** [comment] 2022-11-18 15:17
Thanks for reporting @alkatar21! I think it's a duplicate of https://github.com/iterative/dvc/issues/4428.

If it's causing you major problems, please let us know so we can consider prioritizing it higher or helping with other ways to address your needs.

**Closed by dberenbaum** 2022-11-18 15:17 UTC
