### ISSUE TITLE
push: Unnotified error when pushing data into HTTP remote

### ISSUE THREAD

**Issue by atekoa** [iterative/dvc#7564] opened 2022-04-10 21:02 UTC
# Bug Report

## Issue name
push: Unnotified error when pushing data into HTTP remote

## Description
This issue happens when pushing a bulk of files into a HTTP dvc remote. dvc push reports that everything is correct. However, when downloading the files, some of them have not been uploaded correactly and thus, they do not exist on the remote.

### Reproduce
* download a dataset
* adds it to dvc
* push the data (-> No error)
* remove the cache and tmp folder inside .dvc to assure we will download the data from remote
* pull the data again (-> Some files missing)
* Push the data again (-> Everything updated!)

More detailed:

1. export DATASET_FOLDER=cars_train 
1. export REMOTE_NAME=my_http_remote
// Download random dataset
1. wget http://ai.stanford.edu/~jkrause/car196/cars_train.tgz
1. tar -xf cars_train.tgz 
1. rm cars_train.tgz 
1. export REMOTE_NAME_FILE="${REMOTE_NAME/"-"/"_"}" 
// Try with HTTP remote:
// Add and push the data
1. dvc remote default ${REMOTE_NAME}
1. dvc add $DATASET_FOLDER
1. dvc push -v $DATASET_FOLDER
// Download the data and check
1. dvc remote default ${REMOTE_NAME}
1. rm -rf $DATASET_FOLDER
1. rm -rf .dvc/cache
1. rm -rf .dvc/tmp
1. dvc pull -v $DATASET_FOLDER

// Try to push again the data
```console
$ dvc push -v $DATASET_FOLDER
Everything is up to date.
```

### Expected
All the data in the remote, of course ;)

### Environment information

**Output of `dvc doctor`:**
```console
$ dvc doctor
DVC version: 2.10.1 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.4.0-104-generic-x86_64-with-glibc2.29
Supports:
        azure (adlfs = 2021.10.0, knack = 0.9.0, azure-identity = 1.7.1),
        webhdfs (fsspec = 2022.1.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        ssh (sshfs = 2021.11.2)
```

**Additional Information (if any):**
We had the "Session is Closed" problem prevously:
pull: Using jobs>1 fails with RuntimeError: Session is closed in http remote #7421

Solved with:
fs.http: prevent hangs under some network conditions #7460 

And we have proposed this:
dvc push doesn't recognise that files are missing in remote storage #4164
Force push option #7268
push: add --force option to force push without .dir optimization #7532

but the problem is more serious because you don't really know that it had failed (we would have to ask the users to try it at least twice to ensure that the data has been uploaded correctly...)

Additionally, when you try to push the files again, the .dir optimization precludes to upload again the files and dvc thinks that everything is uploaded. If the dataset have subfolders, the problem is even worse, as re-adding the files do not correct the issue due to .dir optimization.

**Comment by daavoo** [comment] 2022-04-11 06:43
cc @dtrifiro could you take a look?

**Comment by dtrifiro** [comment] 2022-06-07 16:35
Thanks! I will look into it asap

**Comment by dtrifiro** [comment] 2022-06-10 14:16
Hi @atekoa,

I tried following your instructions but it seems I cannot get the remote (simple case) to work:

``` failed to transfer 'md5: 878750719fec346635c5beb4c2132a46': ClientOSError: [Errno None] Can not write request body for http://localhost:8080/remote?remote=0/87/8750719fec346635c5beb4c2132a46```

**Comment by skshetry** [comment] 2022-06-10 14:21
Also, note that DVC `http` does not support path in query part or fragment part, it has to be a part of the path.

**Comment by atekoa** [comment] 2022-06-13 11:07
I have re-launched everything from the beginning and it has worked correctly for me. I have corrected some paths in the Readme that were wrong, but that would not be the problem.
Maybe it's a permissions issue. I'm running this example on Ubuntu 20.04 with docker-compose version 1.29.2, build 5becea4c and Docker version 20.10.12, build e91ed57

**Comment by atekoa** [comment] 2022-06-13 12:09
@dtrifiro maybe I can give you some temporary access (via email?) to our remote http dev environment so you can focus on the dvc calling part, keeping in mind we had other bugs before and maybe related
https://github.com/iterative/dvc/issues/7421
https://github.com/iterative/dvc/pull/7460

**Comment by dtrifiro** [comment] 2022-07-06 08:27
Hi @atekoa,
I've been a bit busy in the past few weeks, so I haven't had time to work on this. I should be able to have another go sometime next week though :slightly_smiling_face:

**Comment by dtrifiro** [comment] 2022-07-18 12:24
I could not reproduce the issue. Closing this as it's likely related to the custom remote being used.

**Closed by dtrifiro** 2022-07-18 12:24 UTC
Labels: :bug: bug, research, fs: http, A: data-sync

**Comment by guysmoilov** [comment] 2022-08-11 18:11
Possibly related: #8100

**Comment by dtrifiro** [comment] 2022-08-16 08:41
Hey @atekoa, would you mind trying the fix suggested in the above issue to see if it solves your issue? `pip install dvc-data==0.1.15
`

**Comment by samtzai** [comment] 2022-08-22 10:36
> Hey @atekoa, would you mind trying the fix suggested in the above issue to see if it solves your issue? `pip install dvc-data==0.1.15 `

I have tried the fix over a multi-folder dataset against our http remote and we do not get the error now.  We will check this during next week and will provide additional info.

**Comment by atekoa** [comment] 2022-08-30 12:14
> dvc-data==0.1.15

It works!
