### ISSUE TITLE
DVC `diff`: doesn't respond for an average dataset (~20k)  

### ISSUE THREAD

**Issue by MarcelNasser** [iterative/dvc#6173] opened 2021-06-15 08:33 UTC
# Bug Report

## Description

When, I run `dvc diff` on my datataset the command just freeze.

### Reproduce

1. dvc init
2. dvc get-url https://s3.amazonaws.com/fast-ai-imageclas/imagenette2-160.tgz
3. tar -xvf imagenette2-160.tgz
4. dvc add imagenette2-160
5. git commit -a -m "add imagenette dataset"
6. dvc commit
7. dvc diff

### Expected

List of changes between dvc commit.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```

DVC version: 2.3.0 (snap)
---------------------------------
Platform: Python 3.6.9 on Linux-5.8.0-55-generic-x86_64-with-Ubuntu-20.04-focal
Supports: azure, gdrive, gs, http, https, s3, ssh
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme0n1p2
Caches: local
Remotes: s3
Workspace directory: ext4 on /dev/nvme0n1p2
Repo: dvc, git

**Comment by skshetry** [comment] 2021-06-15 08:45
@MarcelNasser, could you please see running with `dvc diff -v`? I have noticed that it does not really print status, so it might look like it's frozen, when it's just being slow (possibly related to https://github.com/iterative/dvc/issues/5746).

**Comment by skshetry** [comment] 2021-06-15 15:34
DVC does not show any useful information even with `-vv`. That's really bad. If the issue is it being slow, it's probably due to #5746 and might just seem to be frozen. Anyway, could you please try running `dvc diff -vv`, and when it seems frozen, use `Ctrl + C` multiple times till it exits? Please post the log and the traceback that you get.

**Comment by MarcelNasser** [comment] 2021-06-15 15:43
@skshetry the output of dvc diff -vv  and ctr+C
`2021-06-15 17:42:04,455 TRACE: Assuming '/home/marcel/Upstride/bug-dvc/.dvc/cache/c5/261f96ce891b0da90173fb43f3950d.dir' is unchanged since it is read-only
2021-06-15 17:42:04,520 TRACE: Assuming '/home/marcel/Upstride/bug-dvc/.dvc/cache/c5/261f96ce891b0da90173fb43f3950d.dir' is unchanged since it is read-only
2021-06-15 17:42:04,584 TRACE: Assuming '/home/marcel/Upstride/bug-dvc/.dvc/cache/c5/261f96ce891b0da90173fb43f3950d.dir' is unchanged since it is read-only
2021-06-15 17:42:04,653 TRACE: Assuming '/home/marcel/Upstride/bug-dvc/.dvc/cache/c5/261f96ce891b0da90173fb43f3950d.dir' is unchanged since it is read-only
2021-06-15 17:42:04,718 TRACE: Assuming '/home/marcel/Upstride/bug-dvc/.dvc/cache/c5/261f96ce891b0da90173fb43f3950d.dir' is unchanged since it is read-only
2021-06-15 17:42:04,783 TRACE: Assuming '/home/marcel/Upstride/bug-dvc/.dvc/cache/c5/261f96ce891b0da90173fb43f3950d.dir' is unchanged since it is read-only
^C2021-06-15 17:42:04,789 ERROR: interrupted by the user
------------------------------------------------------------
Traceback (most recent call last):
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/fs/git.py", line 102, in info
    st = self.trie.stat(key)
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/scm/git/objects.py", line 120, in stat
    obj = self.trie[key]
  File "/snap/dvc/1305/lib/python3.6/site-packages/pygtrie.py", line 859, in __getitem__
    node, _ = self._get_node(key_or_slice)
  File "/snap/dvc/1305/lib/python3.6/site-packages/pygtrie.py", line 552, in _get_node
    raise KeyError(key)
KeyError: ('imagenette2-160', 'val', 'n03394916', 'n03394916_23742.JPEG')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/fs/repo.py", line 423, in info
    return fs.info(path_info)
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/fs/git.py", line 105, in info
    errno.ENOENT, os.strerror(errno.ENOENT), path_info
FileNotFoundError: [Errno 2] No such file or directory: PosixPathInfo: 'imagenette2-160/val/n03394916/n03394916_23742.JPEG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/command/base.py", line 50, in do_run
    return self.run()
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/command/diff.py", line 138, in run
    self.args.a_rev, self.args.b_rev, self.args.targets
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/repo/__init__.py", line 50, in wrapper
    return f(repo, *args, **kwargs)
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/repo/diff.py", line 49, in diff
    results[rev] = _paths_checksums(self, repo_fs, targets_path_infos)
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/repo/diff.py", line 114, in _paths_checksums
    return dict(_output_paths(repo, repo_fs, targets))
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/repo/diff.py", line 155, in _output_paths
    yield from _dir_output_paths(repo_fs, output, targets)
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/repo/diff.py", line 167, in _dir_output_paths
    yield str(fname), get_file_hash(fname, repo_fs, "md5").value
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/objects/stage.py", line 60, in get_file_hash
    hash_info = _get_file_hash(path_info, fs, name)
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/objects/stage.py", line 30, in _get_file_hash
    info = fs.info(path_info)
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/fs/repo.py", line 425, in info
    return dvc_fs.info(path_info)
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/fs/dvc.py", line 233, in info
    meta = self.metadata(path_info)
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/fs/dvc.py", line 229, in metadata
    meta.isdir = meta.isdir or self.check_isdir(meta.path_info, meta.outs)
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/fs/dvc.py", line 123, in check_isdir
    self._get_granular_hash(path_info, out)
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/fs/dvc.py", line 51, in _get_granular_hash
    out.get_dir_cache(remote=remote)
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/output.py", line 805, in get_dir_cache
    self.obj = objects.load(self.odb, self.hash_info)
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/objects/__init__.py", line 44, in load
    return Tree.load(odb, hash_info)
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/objects/tree.py", line 115, in load
    tree = cls.from_list(raw)
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/objects/tree.py", line 93, in from_list
    obj = HashFile(None, None, hash_info)
  File "/snap/dvc/1305/lib/python3.6/site-packages/dvc/objects/file.py", line 13, in __init__
    self.fs = fs
KeyboardInterrupt
------------------------------------------------------------
2021-06-15 17:42:04,791 DEBUG: Analytics is enabled.
2021-06-15 17:42:04,804 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmp3f9i445_']'
2021-06-15 17:42:04,805 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmp3f9i445_']'
`

**Comment by karajan1001** [comment] 2021-06-17 09:13
Reproduced on my computer. Using `dvc diff -vv`, it is continously print 
```
2021-06-17 17:12:37,902 TRACE: Assuming '/Users/gao/Code/test/test_6173/.dvc/cache/c5/261f96ce891b0da90173fb43f3950d.dir' is unchanged since it is read-only
2021-06-17 17:12:37,974 TRACE: Assuming '/Users/gao/Code/test/test_6173/.dvc/cache/c5/261f96ce891b0da90173fb43f3950d.dir' is unchanged since it is read-only
2021-06-17 17:12:38,046 TRACE: Assuming '/Users/gao/Code/test/test_6173/.dvc/cache/c5/261f96ce891b0da90173fb43f3950d.dir' is unchanged since it is read-only
2021-06-17 17:12:38,126 TRACE: Assuming '/Users/gao/Code/test/test_6173/.dvc/cache/c5/261f96ce891b0da90173fb43f3950d.dir' is unchanged since it is read-only
2021-06-17 17:12:38,198 TRACE: Assuming '/Users/gao/Code/test/test_6173/.dvc/cache/c5/261f96ce891b0da90173fb43f3950d.dir' is unchanged since it is read-only
2021-06-17 17:12:38,269 TRACE: Assuming '/Users/gao/Code/test/test_6173/.dvc/cache/c5/261f96ce891b0da90173fb43f3950d.dir' is unchanged since it is read-only
2021-06-17 17:12:38,349 TRACE: Assuming '/Users/gao/Code/test/test_6173/.dvc/cache/c5/261f96ce891b0da90173fb43f3950d.dir' is unchanged since it is read-only
2021-06-17 17:12:38,422 TRACE: Assuming '/Users/gao/Code/test/test_6173/.dvc/cache/c5/261f96ce891b0da90173fb43f3950d.dir' is unchanged since it is read-only
2021-06-17 17:12:38,494 TRACE: Assuming '/Users/gao/Code/test/test_6173/.dvc/cache/c5/261f96ce891b0da90173fb43f3950d.dir' is unchanged since it is read-only
2021-06-17 17:12:38,572 TRACE: Assuming '/Users/gao/Code/test/test_6173/.dvc/cache/c5/261f96ce891b0da90173fb43f3950d.dir' is unchanged since it is read-only
2021-06-17 17:12:38,643 TRACE: Assuming '/Users/gao/Code/test/test_6173/.dvc/cache/c5/261f96ce891b0da90173fb43f3950d.dir' is unchanged since it is read-only
2021-06-17 17:12:38,714 TRACE: Assuming '/Users/gao/Code/test/test_6173/.dvc/cache/c5/261f96ce891b0da90173fb43f3950d.dir' is unchanged since it is read-only
2021-06-17 17:12:38,792 TRACE: Assuming '/Users/gao/Code/test/test_6173/.dvc/cache/c5/261f96ce891b0da90173fb43f3950d.dir' is unchanged since it is read-only
```

**Comment by skshetry** [comment] 2021-06-21 05:57
Assigning myself for the UI part that will be worked on in the coming days. More than the performance, `diff` not providing any information at all is unacceptable.

**Comment by karajan1001** [comment] 2021-06-24 08:16
The total time cose profile result.
![image](https://user-images.githubusercontent.com/6745454/123226087-e8125380-d505-11eb-836a-1c7eb498baea.png)

About half of the cost in `from_list` and `from_dict`
![image](https://user-images.githubusercontent.com/6745454/123227533-3ffd8a00-d507-11eb-8df5-5983ae60f1ea.png)
Another half in pygtrie
![image](https://user-images.githubusercontent.com/6745454/123227581-4c81e280-d507-11eb-88d5-df5f3703a438.png)


More details in file.
[dump.prof.zip](https://github.com/iterative/dvc/files/6707469/dump.prof.zip)

**Comment by shcheklein** [comment] 2021-07-09 22:02
I hit the same issue with the https://github.com/iterative/get-started-experiments . It is ~70K or something files. `dvc diff` doesn't respond at all, nothing in logs. I wasn't able to wait to let it complete (1h+).

We depend on `dvc diff` in VS Code (cc @mattseddon ), and this repo is supposed to be simple :), but we hit issues (cc @iesahin )

**Comment by efiop** [comment] 2021-07-09 22:46
Looks like we've lost `.dir` caching and loading it every time from scratch for each file in a dir, which creates this problems. We've introduced some changes in the recent days, that might fix that. Taking a closer look...

**Comment by efiop** [comment] 2021-07-09 23:31
Yeah, caching it reduces the time to around 1m total for `dvc-bench` (which is still a lot, but at leat not hours). There is some obj-related code that we are now ready to improve (specifically `get_dir_cache` that is no longer needed, really) there, so I'll try to prepare a little bit more wholesome PR than just a quick hack.

**Comment by efiop** [comment] 2021-09-13 22:09
Closing. It is now around 5sec for get-started-experiments, which is still a lot, but that will be addressed after https://github.com/iterative/dvc/issues/6594

**Closed by efiop** 2021-09-13 22:09 UTC
Labels: :bug: bug, p1-important, ui, performance
