### ISSUE TITLE
ImportError on `dvc pull` in Alpine env

### ISSUE THREAD

**Issue by AlexJoz** [iterative/dvc#2334] opened 2019-07-28 16:57 UTC
`dvc pull` fails in Docker based on **Alpine 3.10**  with latest **dvc (0.53.1)** 

```
Traceback (most recent call last):
  File "/usr/bin/dvc", line 6, in <module>
    from dvc.main import main
  File "/usr/lib/python3.7/site-packages/dvc/__init__.py", line 11, in <module>
    import dvc.logger
  File "/usr/lib/python3.7/site-packages/dvc/logger.py", line 5, in <module>
    from dvc.utils.compat import str, StringIO
  File "/usr/lib/python3.7/site-packages/dvc/utils/__init__.py", line 29, in <module>
    from ruamel.yaml import YAML
ImportError: cannot import name 'YAML' from 'ruamel.yaml' (/usr/lib/python3.7/site-packages/ruamel/yaml/__init__.py)
```

Dockerfile to reproduce:
```
FROM alpine:3.10

RUN apk add --update build-base python3 python3-dev zlib-dev jpeg-dev linux-headers git bash

RUN pip3 install --no-cache-dir --upgrade pip
RUN pip3 install dvc[gs]
RUN dvc pull my.dvc
```

Going through history, found [commit](https://github.com/iterative/dvc/commit/fc99ebed591c8eb3d96de7369bf5f2ff92ad8e61#diff-2eeaed663bd0d25b7e608891384b7298) after which this error has appeared. 
Basically, using ruamel.yaml ver. 0.15.9 fixes the issue.  

Latest working tag:
`pip3 install dvc[gs]==0.40.0`

**Comment by efiop** [comment] 2019-07-28 18:20
Hi @AlexJoz ! Thanks for reporting this! This is pretty weird, I am able to reproduce this with your dockerfile, but it works fine for me locally with the same yaml version. Looking into it.

**Comment by efiop** [comment] 2019-07-28 18:22
Looks like the issue is not on our side, more tailored reproducer
```
FROM alpine:3.10

RUN apk add --update build-base python3 python3-dev zlib-dev jpeg-dev linux-headers git bash

RUN pip3 install --no-cache-dir --upgrade pip
RUN pip3 install ruamel.yaml
RUN python3 -c 'from ruamel.yaml import YAML'
```

shows that there is something wrong with ruamel itself. Mind opening an issue in ruamel please?

**Comment by efiop** [comment] 2019-07-28 18:24
For the record ruamel.yaml==0.15.100 works fine.

**Comment by AlexJoz** [comment] 2019-07-28 18:25
@efiop, ok!
Thanks for a quick response =)

**Comment by mroutis** [comment] 2019-07-28 18:26
@efiop , could it be related to alpine using musl libc? :thinking:

**Comment by mroutis** [comment] 2019-07-28 18:30
check the following: https://bitbucket.org/ruamel/yaml/commits/tag/0.16.0
`split off C library into separate package` 

it doesn't seem like a relevant update, what about installing ruamel.yaml 1.15.9 before `dvc`?

**Comment by AvdN** [comment] 2019-07-28 19:18
This almost certainly has to do with ruamel.yaml having been split it up and the second package (ruamel.yaml.clib which contains the C loader/dumper) installing an __init__.py and .pth file (which it shouldn't).
It might be a few days before I can look into this, you should pin to "ruamel.yaml<0.16" until this is resolved.

**Comment by AlexJoz** [comment] 2019-07-28 19:25
@AvdN Cool, thanx!

@mroutis 
seems a bit late, but lets link: https://bitbucket.org/ruamel/yaml/issues/299 =))

**Comment by efiop** [comment] 2019-07-28 19:40
@AvdN Thank you! :slightly_smiling_face: 

@AlexJoz Btw, maybe you'd like to submit a quick fix for `ruamel.yaml<0.16` in our setup.py? :wink: I'll release a new dvc version with it right after that.

**Comment by efiop** [comment] 2019-07-28 21:51
@AlexJoz Big thanks for the fix! I'll trigger the release in a moment. Let's keep this issue open until ruamel.yaml is fixed, so we don't forget to update requirements in dvc :slightly_smiling_face:

**Comment by efiop** [comment] 2019-07-28 23:29
@AlexJoz FYI: [0.53.2 is out](https://github.com/iterative/dvc/releases/tag/0.53.2). Please feel free to upgrade! :slightly_smiling_face:

**Comment by AlexJoz** [comment] 2019-07-28 23:31
@efiop already done =) Works fine! Thanks

**Comment by AvdN** [comment] 2019-08-07 21:03
I set the [issue on bitbucket](https://bitbucket.org/ruamel/yaml/issues/299) to resolved, as I think this got fixed by releasing a new version of ruamel.yaml.clib (you should use ruamel.yamlclib>=0.1.2).
Unless you have pinned the previous version of ruamel.yaml.clib, clean rebuilding should now get a working version.

**Comment by efiop** [comment] 2019-08-07 23:28
@AvdN Great news! Thank you so much!

**Comment by efiop** [comment] 2019-08-08 03:35
It would be best to wait for the next ruamel.yaml release, which, I suppose, will have updated requirements for clib. But if it works for you @AlexJoz already, we could relax the requirements right away without waiting for the next release.

**Comment by AvdN** [comment] 2019-08-08 06:26
@efiop There is a new ruamel.yaml. (0.16.1) which has that requirement

**Comment by efiop** [comment] 2019-08-08 11:25
@AvdN Oh, that is perfect! Thank you!

**Closed** 2019-08-08 11:26 UTC
Labels: build
