### ISSUE TITLE
Unable to track metrics on state file name not ending with "dvc"

### ISSUE THREAD

**Issue by pared** [iterative/dvc#1053] opened 2018-08-24 13:29 UTC
**Please provide information about your setup**
DVC version(i.e. `dvc --version`), Platform and method of installation (pip, homebrew, pkg Mac, exe (Windows), DEB(Linux), RPM(Linux))

**Comment by efiop** [comment] 2018-08-24 13:36
Hi @pared,

Could you please elaborate on this?

**Comment by efiop** [comment] 2018-08-24 13:43
Ok, looks like a duplicate of https://github.com/iterative/dvc/issues/1054

**Closed by efiop** 2018-08-24 13:43 UTC
