### ISSUE TITLE
encoding error after dvc add

### ISSUE THREAD

**Issue by wardvl-ixor** [iterative/dvc#856] opened 2018-07-04 07:45 UTC
Hi!

We are looking into dvc to see if we can use it in our AI practice in Belgium. It looks very promising!
I stumbled upon this problem:

There is a folder containing some pdf files in the data path.
when running 'dvc add data/pdffolder' I get
Unexpected error: 'utf-8' codec can't decode byte 0xe2 in position 11: invalid continuation byte

which is weird because I would assume all files are read in binary mode?

Thanks!

**Comment by efiop** [comment] 2018-07-04 13:34
Hi @wardvl-ixor !

What version are you using? (`dvc --version`)

**Comment by wardvl-ixor** [comment] 2018-07-10 07:06
Hi Im using version dvc 0.9.7

**Comment by efiop** [comment] 2018-07-10 07:32
Hi @wardvl-ixor !

We had a what seems to be the same bug in our file_md5 function, it is now fixed in 0.10(available through `pip install --upgrade dvc` or standalone packages https://github.com/iterative/dvc/releases/tag/0.10.2) . Could you please upgrade and try reproducing it once more to see if it is fixed or not?

Thanks,
Ruslan

**Comment by wardvl-ixor** [comment] 2018-07-10 07:34
Hi @efiop,

This indeed solved the issue, thanks!

**Comment by efiop** [comment] 2018-07-10 07:40
@wardvl-ixor Glad it helped :) Thank you for the feedback!

**Closed by efiop** 2018-07-10 07:40 UTC
Labels: awaiting response
