### ISSUE TITLE
dvc checkout: too many values to unpack

### ISSUE THREAD

**Issue by dmpetrov** [iterative/dvc#1205] opened 2018-10-11 06:06 UTC
DVC was installed from source.

```
$ dvc --version
0.19.8+13a2e4
```

I go through the tutorial till `git commit -m 'Add source dataset'`.
Then replace data file by a random one: `cp ~/Downloads/photo.png data/Posts.xml.tgz`

```
$ dvc checkout -v
Debug: updater is not old enough to check for updates
Error: Traceback (most recent call last):
  File "/Users/dmitry/src/dvc/dvc/main.py", line 22, in main
    ret = cmd.run_cmd()
  File "/Users/dmitry/src/dvc/dvc/command/base.py", line 40, in run_cmd
    return self.run()
  File "/Users/dmitry/src/dvc/dvc/command/checkout.py", line 7, in run
    self.project.checkout()
  File "/Users/dmitry/src/dvc/dvc/project.py", line 409, in checkout
    all_stages = self.active_stages()
  File "/Users/dmitry/src/dvc/dvc/project.py", line 932, in active_stages
    for G in self.pipelines():
  File "/Users/dmitry/src/dvc/dvc/project.py", line 886, in pipelines
    ends = [node for node, in_degree in G.in_degree() if in_degree == 0]
ValueError: too many values to unpack
Error: Unexpected error: too many values to unpack
```

**Comment by efiop** [comment] 2018-10-11 18:58
As it turned out in the private conversation the cause for this error is that there is an old version(1.11) of networkx installed, while we require 2.1 and newer, which is reflected in our requirements.txt and setup.py. Closing.

**Closed by efiop** 2018-10-11 18:58 UTC
Labels: bug
