### ISSUE TITLE
`dvc exp run --dry --allow-missing` modifies dvc files

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#9817] opened 2023-08-08 04:01 UTC
Reproduction steps:

```bash
cd "$(mktemp -d)"
git init && dvc init
echo -e "outs:\n- path: data" > data.dvc
dvc stage add -n test -d data ls
cat data.dvc
echo "data" >> .gitignore
git add .
git commit -m "init"
dvc exp run --dry --allow-missing -vv
cat data.dvc
```

**Comment by daavoo** [comment] 2023-08-11 13:49
@skshetry could you clarify why this is p1?
 
 It looks like this is coming from the internal `commit` operation done as part of `dvc exp run`:
 
 ```
cd "$(mktemp -d)"
git init && dvc init
echo -e "outs:\n- path: data" > data.dvc
dvc stage add -n test -d data ls
cat data.dvc
echo "data" >> .gitignore
git add .
git commit -m "init"
python -c "from dvc.repo import Repo; Repo().commit(allow_missing=True, force=True)"
cat data.dvc
```

**Comment by skshetry** [comment] 2023-08-11 14:07
It is breaking this scenario: [Verify Pipeline Status](https://dvc.org/doc/user-guide/pipelines/running-pipelines#verify-pipeline-status), specifically, this

> However, if data is missing, --dry will fail because DVC does not know whether that data simply needs to be pulled or is missing for some other reason. To check which stages to run and ignore any missing data, use [dvc exp run --dry --allow-missing](https://dvc.org/doc/command-reference/exp/run#--dry).


So, `--dry --allow-missing` is supposed to be used in scenario when you have not pulled, but it instead modifies the file with empty hash value.

Even without `--allow-missing`, `--dry` should not commit or change anything.

**Comment by skshetry** [comment] 2023-08-11 14:09
Discord: https://discord.com/channels/485586884165107732/563406153334128681/1138124181268074516

**Comment by daavoo** [comment] 2023-08-11 14:23
> `--dry` should not commit or change anything.

Afaik, this was never the case since the introduction of `dvc exp run`, the logic for `commit_deps` happens when creating the experiment, before `reproduce`

**Comment by skshetry** [comment] 2023-08-11 14:27
I see virtual directory being a problem in a similar manner. We really need better ways to handle partial checkout.

**Comment by pmrowla** [comment] 2023-08-11 17:09
Should `exp run` even support `--dry`? If anything it seems like if `--dry` is used, it should just directly call `repo.reproduce(dry=True)` instead of trying to do any of the actual experiment setup

**Comment by efiop** [comment] 2023-08-15 12:33
@pmrowla What if `--dry` would automatically imply `--temp`? Seems like that should do the trick. Not ideal, but maybe quick and simple enough for now? The ideal solution is something that could build the workspace virtually (related to run-cache discussions too), but that's way out of scope here for now.,

**Closed** 2023-09-13 06:06 UTC
Labels: bug, p1-important, A: experiments
