### ISSUE TITLE
`data status`: reports unchanged data as modified after experiment run (fresh clone w/ 3.0)

### ISSUE THREAD

**Issue by mattseddon** [iterative/dvc#9602] opened 2023-06-14 02:38 UTC
# Bug Report

## Description

This one was picked up by the `vscode-dvc` e2e tests when moving to `3.0.0`.

After running `dvc pull` + `dvc exp run` on a fresh clone of `vscode-dvc-demo` the "unchanged" data files all show up as modified in `data status`. 

![image](https://github.com/iterative/dvc/assets/37993418/0a7f9ee6-219e-4529-95e6-b240310a4379)

The only reason that I am raising this issue is because this does not happen when the repository had data before upgrading to `3.0.0` (couldn't recreate it locally with my usual copy of the demo project).

### Reproduce

1. `git clone git@github.com:iterative/vscode-dvc-demo.git`
2. `cd vscode-dvc-demo`
3. `python -m venv .env`
4. `source .env/bin/activate`
5. `dvc pull`
6. `dvc exp run -S params.yaml:lr=0.0005`
7. wait for experiment to finish
8. `dvc data status --granular --unchanged --json` <= will show extra modified data

Note: committing the modified data ensures that it does not appear modified again.

### Expected

Unchanged data does not appear as modified.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 3.0.0 (pip)
------------------------
Platform: Python 3.10.10 on macOS-13.4-arm64-arm-64bit
Subprojects:
        dvc_data = 1.11.0
        dvc_objects = 0.23.0
        dvc_render = 0.5.3
        dvc_task = 0.3.0
        scmrepo = 1.0.3
Supports:
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.6.0, boto3 = 1.26.76)
Config:
        Global: /Users/mattseddon/Library/Application Support/dvc
        System: /Library/Application Support/dvc
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: https
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
Repo.site_cache_dir: /Library/Caches/dvc/repo/26e95498e98e2134dc78f5683b8f095e
```

**Additional Information (if any):**

This may be expected. Just wanted to raise an issue for visibility. Please let me know if you need anything else.

Thanks

**Comment by dberenbaum** [comment] 2023-06-14 11:52
I think we force commit even the dependencies when running the experiment, and that's causing them to be rewritten into the 3.0 cache, which marks them as modified, even when the md5 didn't change. The only change I see in `data.dvc` is the added `hash: md5` field. Since the `md5` itself didn't change, I don't think we should show it as modified, but not sure if it's worth fixing or we should just warn people they might see this when files are converted to 3.0 cache.

**Comment by daavoo** [comment] 2023-06-29 10:36
Hi @mattseddon , I am not able to reproduce the bug using the latest DVC version. 

I followed the steps but installed the latest DVC version:

```
DVC version: 3.2.2 (pip)
------------------------
Platform: Python 3.10.6 on Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Subprojects:
        dvc_data = 2.3.1
        dvc_objects = 0.23.0
        dvc_render = 0.5.3
        dvc_task = 0.3.0
        scmrepo = 1.0.4
Supports:
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3)
Config:
        Global: /home/daavoo/.config/dvc
        System: /etc/xdg/dvc
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdc
Caches: local
Remotes: https
Workspace directory: ext4 on /dev/sdc
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/d6892d6b5d1ea3e0e4e894c697fe15b9
```

![Screenshot 2023-06-29 123544](https://github.com/iterative/dvc/assets/12677733/ec9c8fb5-17d6-4b35-839f-4e835c5b0f8b)

**Comment by pmrowla** [comment] 2023-06-29 14:17
This was probably resolved by https://github.com/iterative/dvc/pull/9643

**Comment by efiop** [comment] 2023-06-29 14:23
Let's close for now.

**Closed by efiop** 2023-06-29 14:23 UTC
Labels: awaiting response, A: status
