### ISSUE TITLE
[dvc pull version >= 3.24] ERROR: unexpected error - failed to load directory

### ISSUE THREAD

**Issue by themaikelman** [iterative/dvc#10030] opened 2023-10-18 10:35 UTC
# Bug Report

pull: ERROR, doesn't create the cache directory and crash.

## Description

Collecting                                                                                                                                        |0.00 [00:00,    ?entry/s]

Fetching

ERROR: unexpected error - failed to load directory ('60', '36c8668869290419aec048f26f8deb.dir'): [Errno 2] No such file or directory: '/mnt/data2/users/myuser/project/.dvc/cache/files/md5/60/36c8668869290419aec048f26f8deb.dir'

**With DVC version 3.23.0 it works OK!
DVC >= 3.24 fails**

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor

DVC version: 3.24.0 (pip)

-------------------------

Platform: Python 3.10.12 on Linux-5.15.0-84-generic-x86_64-with-glibc2.35

Subprojects:
        dvc_data = 2.18.1
        dvc_objects = 1.0.1
        dvc_render = 0.6.0
        dvc_task = 0.3.0
        scmrepo = 1.4.0

Supports:
        http (aiohttp = 3.8.6, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.6, aiohttp-retry = 2.8.3)

Config:
        Global: /mnt/data2/users/myuser/.config/dvc
        System: /etc/xdg/dvc

Cache types: hardlink, symlink
Cache directory: ext4 on /dev/nvme2n1
Caches: local
Remotes: https
Workspace directory: ext4 on /dev/nvme2n1
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/fb1190580eb02ee00297b6211011d5af
```

**Comment by efiop** [comment] 2023-10-18 10:49
@atekoa Please run `dvc pull -v` and post full log.

**Comment by dberenbaum** [comment] 2023-10-26 13:13
I'm not able to reproduce it. @kcchu @atekoa Are either of you able to generate a simple reproducible example of the problem?

**Comment by dberenbaum** [comment] 2023-10-27 13:29
Also, could you each try to drop everything in the `Repo.site_cache_dir` location and see if the problem persists?

**Comment by davebulaval** [comment] 2023-10-27 23:01
I had the same problem. In my case, it was an error 18. I forgot to do `dvc push` from one server,; the message was "explicit" it was trying to pull some data that was not on the remote.

**Comment by dberenbaum** [comment] 2023-10-30 14:36
@efiop Should we try to bump the path for `site_cache_dir` so it forces a new cache for existing repos?

**Comment by efiop** [comment] 2023-11-01 21:37
Need to look into why it is happening first, otherwise it will only obscure it till the next report.

**Comment by PythonFZ** [comment] 2023-11-09 07:30
I've encountered the same issue. I tried to pull data but forgot to set the credentials to the S3 remote in `config.local`. After setting the credentials, I encountered the same error. The suggested fix could resvolve it.

**Comment by dberenbaum** [comment] 2023-11-09 14:43
> Need to look into why it is happening first, otherwise it will only obscure it till the next report.

@efiop I think it's an index issue we fixed already (maybe in https://github.com/iterative/dvc/issues/9785?) but for people who have an index that predates that change, they will still run into this issue, so forcing the index to be regenerated should resolve it. WDYT?

**Comment by efiop** [comment] 2023-11-10 01:37
Hm, we've changed index cache key a few times since then, so it shouldn't pick it up in newer versions. It is possible we are handling this particular case badly, directiories that failed to load should not be marked as loaded thus we should be making an attempt to load them next time. Need to check, maybe there is another bug there somewhere...

**Comment by PythonFZ** [comment] 2023-11-10 13:45
This also happens in our CI https://github.com/zincware/IPSuite/actions/runs/6825380182/job/18563548993?pr=218
see `prepare repo`.

**Comment by dberenbaum** [comment] 2023-11-10 16:09
I'm still unclear and would like to hear from users watching this issue:
1. Does deleting `site_cache_dir` fix the problem for everyone?
2. Does the problem come back after that?

**Comment by PythonFZ** [comment] 2023-11-10 16:13
> I'm still unclear and would like to hear from users watching this issue:
> 
> 1. Does deleting `site_cache_dir` fix the problem for everyone?
> 2. Does the problem come back after that?

For me, this is also happening in a GitHub CI runner. The `site_cache_dir` should only be created upon starting the runner. The CI was using `url = https://dagshub.com/PythonFZ/IPS-Examples.dvc`.
Furthermore, I've seen this on a local machine with a S3 remote, but I can't excactly tell you how I fixed it then. Now I've just pinned the DVC version to 3.23.

**Comment by dberenbaum** [comment] 2024-01-03 16:59
> The CI was using `url = https://dagshub.com/PythonFZ/IPS-Examples.dvc`.

Could you give more detail on what's happening? How does that url get used in your CI script?

**Comment by PythonFZ** [comment] 2024-01-04 08:00
> This also happens in our CI https://github.com/zincware/IPSuite/actions/runs/6825380182/job/18563548993?pr=218 see `prepare repo`.

https://dagshub.com/PythonFZ/IPS-Examples contains some example scripts for our package [IPSuite](https://github.com/zincware/IPSuite), which we test as follows

```yaml
  run: |
    git clone https://github.com/PythonFZ/IPS-Examples
    cd IPS-Examples
    git fetch origin
    git checkout ${{ matrix.branch }}
    poetry run dvc pull
- name: run notebook
  run: |
    cd IPS-Examples
    poetry run jupyter nbconvert --to notebook --execute main.ipynb
- name: dvc repro
  run: |
    cd IPS-Examples
    poetry run dvc repro -f
```



I've updated the remote to S3, but prior to that it was using
```toml
['remote "origin"']
    url = https://dagshub.com/PythonFZ/IPS-Examples.dvc
```

**Comment by tonycusackData** [comment] 2024-01-24 18:41
> @PythonFZ @themaikelman Mind giving 3.38.0 a try?

Was having the same issues above. Deleting everythin in `Repo.site_cache_dir` didn't work but this finally fixed it -  `pip install --upgrade dvc[gs]==3.38.0`

Thank you!

**Comment by dberenbaum** [comment] 2024-01-24 18:45
Thanks for the feedback @tonycusackData! Let's close this then and we can reopen if needed.

**Closed by dberenbaum** 2024-01-24 18:45 UTC
Labels: awaiting response, p1-important, research

**Comment by sherwoac** [comment] 2024-04-23 14:36
> WDYT

having the same issue, how do you force the index to rebuild?

thanks.

**Comment by dberenbaum** [comment] 2024-04-23 17:04
@sherwoac `dvc doctor` will show you the location of the `site_cache_dir`. You can safely delete everything there, which will force dvc to rebuild the index and related temporary data.
