### ISSUE TITLE
Does `dvc get` need to hold open all the files it tries to download?

### ISSUE THREAD

**Issue by koodzi** [iterative/dvc#7395] opened 2022-02-17 08:55 UTC
I got dataset of 5000 files. I tried to download the dataset on the server using `dvc get` but it failed. `Too many open file`

I try to use `ulimit -n 4096` and `--jobs 1` and `_JOBS=1` (as I use SFTP) But it always fails.
https://dvc.org/doc/user-guide/troubleshooting#many-files

On the other hand `dvc import/pull` works fine. 

**So question is does `dvc get` needs to keep opened all that files?**

```
DVC version: 2.9.4 (pip)
---------------------------------
Platform: Python 3.7.5 on Linux-4.15.0-166-generic-x86_64-with-Ubuntu-18.04-bionic
Supports:
        webhdfs (fsspec = 2022.1.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
        ssh (sshfs = 2021.11.2)
```

**Comment by pmrowla** [comment] 2022-02-17 10:00
This is likely the same underlying issue as https://github.com/iterative/dvc/issues/7319 (there is an existing bug where `--jobs` is not respected properly for SSH connections.

We can keep this issue open for now and double check that the problem is resolved once the other fix is merged (which should be soon @koodzi)

**Comment by pmrowla** [comment] 2022-02-18 00:49
@koodzi the fix for the other issue is now available, can you please try installing from `main` to see if this resolves your issue (see https://dvc.org/doc/install/pre-release)

**Comment by koodzi** [comment] 2022-02-21 16:10
I have tried also different approach. I have 5000 samples in 5 directories (1000 each)

First, I added all the files using `dvc add data/**/*.sample` - this created 5000 *.dvc files.
Second, I added whole directory `dvc add data` - this created 1 `data.dvc` file

I both cases `dvc get` fails with too many opened files.

**Comment by pmrowla** [comment] 2022-02-22 06:26
@koodzi can you try installing the linked PR branch and see if it resolves the issue:

```
pip install "git+https://github.com/iterative/dvc.git@refs/pull/7412/head#egg=dvc[s3]"
```

**Comment by koodzi** [comment] 2022-02-25 15:07
Hi, sorry for late response. The fix did not work.

Can you point me to correct `dvc[ssh]` repository?

https://github.com/iterative/dvc-ssh - this one is empty

**Comment by pmrowla** [comment] 2022-02-28 08:37
There is not a separate `dvc[ssh]` repository, the relevant code in core DVC is here: https://github.com/iterative/dvc/blob/main/dvc/fs/ssh.py and the fsspec backend (sshfs) is here: https://github.com/fsspec/sshfs

**Comment by koodzi** [comment] 2022-02-28 10:57
> There is not a separate `dvc[ssh]` repository, the relevant code in core DVC is here: https://github.com/iterative/dvc/blob/main/dvc/fs/ssh.py and the fsspec backend (sshfs) is here: https://github.com/fsspec/sshfs
> 
> @koodzi did you try the patch with both `-j 1` and `-j 2`?

1. Thanks for the source point. 
2. Yes, I tried with `-j 1` and `-j 2`

**Comment by koodzi** [comment] 2022-02-28 12:36
```python
import asyncio, pathlib, yaml
import dvc.fs.ssh as dfs

async def run_client() -> None:
	sftp = dfs.SSHFileSystem(host="thehost")
	i = 0
	for x in pathlib.Path('/home/user/code/dvc-large-dataset/data').iterdir():
		if not x.is_file():
			for y in x.glob("*.dvc"):
				with open(y, 'r') as f:
					hs = yaml.load(f)["outs"][0]["md5"]
				print(f"{i} {hs}")
				prefix, sufix = hs[:2], hs[2:]
				sftp.get_file(f"/mnt/archive/user/test-dataset/{prefix}/{sufix}", f"x_{hs}")

				i += 1
					

asyncio.get_event_loop().run_until_complete(run_client())
```

I have downloaded 5000 files from remote host using the code above. `SSHFileSystem` may not be a problem - something else might hold files open.

**Comment by dberenbaum** [comment] 2022-03-14 17:46
@pmrowla Any thoughts on this issue?

**Comment by pmrowla** [comment] 2022-03-15 10:27
It's not clear right now what would be causing the difference in behavior between `get` and `fetch/pull` (other than the ThreadPoolExecutor PR which does not resolve the issue). It will probably take some more time to debug this.

**Comment by efiop** [comment] 2023-01-01 21:16
closing as stale

**Closed by efiop** 2023-01-01 21:16 UTC
Labels: bug, research, fs: ssh, A: data-sync
