### ISSUE TITLE
import-url: issue with importing data if no ETag is present

### ISSUE THREAD

**Issue by ambarish-deopujari-konvergeai** [iterative/dvc#6257] opened 2021-06-30 17:10 UTC
# Bug Report

## Description
If ETag is not present in response to a particular file that is hosted on the localhost a proper validation message should be there. Currently, it just throws `AttributeError: 'NoneType' object has no attribute 'endswith'`

### Reproduce

1. Copy any sample.csv file in a particular folder
2. Run `python3 -m http.server PORT_NUMBER` in the same folder
3. Create a separate dummy folder and `cd` to it
3. Run `dvc init`
4. Run `dvc import-url http://127.0.0.1:PORT_NUMBER/FILE_NAME.csv`

### Expected

FILE_NAME.csv should get downloaded. 
If ETag is not present in the headers then a proper validation message should be thrown instead of 
`AttributeError: 'NoneType' object has no attribute 'endswith'`

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.4.3 (pip)
---------------------------------
Platform: Python 3.8.8 on Linux-5.8.0-59-generic-x86_64-with-glibc2.10
Supports: gdrive, hdfs, webhdfs, http, https, oss

```

**Comment by karajan1001** [comment] 2021-07-03 14:33
Thanks for your report, I can reproduce it. And this is the traceback on my computer

```
Traceback (most recent call last):
  File "/Users/gao/Code/dvc/dvc/main.py", line 55, in main
    ret = cmd.do_run()
  File "/Users/gao/Code/dvc/dvc/command/base.py", line 50, in do_run
    return self.run()
  File "/Users/gao/Code/dvc/dvc/command/imp_url.py", line 14, in run
    self.repo.imp_url(
  File "/Users/gao/Code/dvc/dvc/repo/__init__.py", line 51, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/gao/Code/dvc/dvc/repo/scm_context.py", line 14, in run
    return method(repo, *args, **kw)
  File "/Users/gao/Code/dvc/dvc/repo/imp_url.py", line 80, in imp_url
    stage.run(jobs=jobs)
  File "/Users/gao/anaconda3/envs/dvc/lib/python3.8/site-packages/funcy/decorators.py", line 39, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/Users/gao/Code/dvc/dvc/stage/decorators.py", line 36, in rwlocked
    return call()
  File "/Users/gao/anaconda3/envs/dvc/lib/python3.8/site-packages/funcy/decorators.py", line 60, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/Users/gao/Code/dvc/dvc/stage/__init__.py", line 517, in run
    sync_import(self, dry, force, jobs)
  File "/Users/gao/Code/dvc/dvc/stage/imports.py", line 46, in sync_import
    stage.save_deps()
  File "/Users/gao/Code/dvc/dvc/stage/__init__.py", line 452, in save_deps
    dep.save()
  File "/Users/gao/Code/dvc/dvc/output.py", line 537, in save
    self.hash_info = self.get_hash()
  File "/Users/gao/Code/dvc/dvc/output.py", line 410, in get_hash
    return ostage(
  File "/Users/gao/Code/dvc/dvc/objects/stage.py", line 216, in stage
    _, obj = _get_file_obj(path_info, fs, name, odb, state, upload)
  File "/Users/gao/Code/dvc/dvc/objects/stage.py", line 70, in _get_file_obj
    path_info, fs, get_file_hash(path_info, fs, name, state=state)
  File "/Users/gao/Code/dvc/dvc/objects/stage.py", line 55, in get_file_hash
    hash_info = _get_file_hash(path_info, fs, name)
  File "/Users/gao/Code/dvc/dvc/objects/stage.py", line 32, in _get_file_hash
    assert not info[name].endswith(".dir")
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by dberenbaum** [comment] 2022-07-05 15:46
I think it's a duplicate of https://github.com/iterative/dvc/issues/5560. Please comment if you think there's something different than that issue and I can reopen.

**Closed by dberenbaum** 2022-07-05 15:46 UTC
Labels: :bug: bug, p2-medium, A: data-sync
