### ISSUE TITLE
Directory hashes are inconsistent on different machines

### ISSUE THREAD

**Issue by Danila89** [iterative/dvc#9624] opened 2023-06-16 23:18 UTC
# Bug Report

## Description

When having a stage with dependency on directory, caching is not working properly when the pipeline is executed on other machine.
I believe that the reason is that directories' hashes are inconsistent on different machines.
Here are two identical notebooks on different services:
https://colab.research.google.com/drive/1t_unGlKjWkUbgHhSNVm4fjaZIvKOzPOf?usp=sharing
https://www.kaggle.com/daniel89/dvc-hashes
Notice that directory hashes (cell 2) differ while file hashes (cell 3) are same.

### Reproduce

Step list of how to reproduce the bug

1. Calculate of same directory MD5 hash on different machines (e.g. git clone https://github.com/iterative/dvc-learn-project.git and calculate dvc-learn-project directory md5 cache using dvc)

### Expected

Hashes are equal regardless the machine.

### Environment information

**Output of `dvc doctor`:**

Check the output in the notebooks by the links above

**Comment by efiop** [comment] 2023-06-16 23:29
@Danila89 Is one of the machines windows while the other is not?

**Comment by efiop** [comment] 2023-06-16 23:37
@Danila89 Also, maybe there are some additional files in the current directory?

**Comment by Danila89** [comment] 2023-06-17 00:09
Seems that the problem is with some files in .git subdirectory (for example `dvc-learn-project/.git/index` does not match). And the problem that was the reason to write this issue was about `__pycache__` file. In both cases the files were not tracked by git. The example with dvc-learn-project is artificial of course, but is there any workaround about __pycache__ files? Should I explicitly delete all __pycache__ files or should I commit them to the repo if the parent directory is in any stage's deps?

**Comment by efiop** [comment] 2023-06-17 00:48
@Danila89 Have you considered https://dvc.org/doc/user-guide/project-structure/dvcignore-files ?

**Comment by efiop** [comment] 2023-06-17 00:50
Also, are you trying to `dvc add .`? If you are - that is not recommended. Unlike git we take `.` litteraly and try to create 1 data artifact from the whole current directory, which is not what you want. Try adding individual data files/directories instead.

**Comment by Danila89** [comment] 2023-06-17 07:37
I'm not using `dvc add`, I'm using `dvc exp push/pull`.
I've constructed a simplistic example. Here is a repo with the pipeline https://github.com/Danila89/dvc_dir_hashes.
The pipeline has just one stage and I want the cache of this stage to be invalidated once something in src directory changed.
I do:
1. `dvc exp run -n experiment_name`
2. `dvc exp push origin experiment_name`
3. Go to another machine
4. `git clone https://github.com/Danila89/dvc_dir_hashes`
5. `dvc exp pull origin experiment_name --no-cache` (no-cache because I didn't specify dvc remote)
6. Now if I do `dvc status` I see that `src` directory changed
7. If I do `dvc exp apply experiment_name` I see the `__pycache__` directory appearing inside the `src` directory
Addind `__pycache__/` to `.dvcignore` does not solve the issue.
The problem is that `__pycache__/` appears once python scripts are executed and it is machine-dependent. Thus I have to make dvc to ignore `__pycache__/` somehow. Is there a way to do this?

**Comment by pmrowla** [comment] 2023-06-20 05:29
`__pycache__/` should be added to your `.gitignore`. Since `src` is a stage dependency and is not a DVC data directory (it is not tracked with `dvc add`), it will be tracked with git when you do `dvc exp run`.

(adding `__pycache__` to `.dvcignore` will not help here since `src` gets tracked with git and not DVC)

**Comment by Danila89** [comment] 2023-06-20 09:40
Seems that .gitignore does not always help. I updated the repo (added `__pycache__` to gitignore, added more python modules), here is a way to reproduce bug on a single machine
1. `git clone https://github.com/Danila89/dvc_dir_hashes.git && cd dvc_dir_hashes`
2. `python -m src.script` - run code to initialize `__pycache__`
3. `dvc exp run -n experiment_name`
4.  `dvc status` - the output is "Data and pipelines are up to date"
5. `rm -rf src/__pycache__ && dvc status` - the output is "changed deps"
To reproduce with `dvc exp pull` on other machine you have to fork repo before cloning and replace 4-5 with:
4. `dvc exp push origin experiment_name`
5. Go to another machine and clone repo
6. `dvc exp pull origin experiment_name --no-cache`
7. `dvc exp apply experiment_name`
8. `dvc status` - it will output "changed deps"

It seems that there is some bug with ignoring `__pycache__` when calculating md5 of directory

**Comment by Danila89** [comment] 2023-06-20 11:10
At the repo's HEAD https://github.com/Danila89/dvc_dir_hashes.git there is .gitignore with __pycache__ now. And with .gitignore `dvc exp apply` does not produce `__pycache__`. But still after `dvc exp apply` `dvc status` says that there are changes. What am I doing wrong? Or is it a bug on DVC side?

**Comment by pmrowla** [comment] 2023-06-20 11:49
@Danila89 `dvc status` reporting that there are changes is a DVC bug

**Comment by pmrowla** [comment] 2023-06-21 06:32
Ok, so looking into this a bit more, I think this is actually expected behavior. The fix is that `__pycache__/` is required in both `.gitignore` and `.dvcignore`.

There's two separate issues here:

1. DVC computes platform specific dir hashes when there are platform specific files in the directory (i.e. `.pyc` files from `__pycache__`). This is resolved by adding `__pycache__/` or `*.pyc` to `.dvcignore`.
2. Non-DVC tracked dependency dirs are `git add`ed by `exp run`, which also forces adding any non-gitignored files in the dependency dir. This is resolved by adding `__pycache__/` or `*.pyc` to `.gitignore`.

It is a bit non-intuitive that the user needs to add entries to both ignore files, but in this case they are doing two separate things, and DVC can't safely load both sets of ignores together when computing a dir hash (since there may be files that are supposed to be ignored by git but not DVC, and vice-versa).

**Comment by pmrowla** [comment] 2023-06-21 06:32
@Danila89 can you please verify that adding `__pycache__/` to both `.gitignore` and `.dvcignore` resolves this in your test repo?

**Closed** 2023-06-21 14:51 UTC
Labels: awaiting response
