### ISSUE TITLE
Pushing only diffs

### ISSUE THREAD

**Issue by emilijapur** [iterative/dvc#7546] opened 2022-04-05 09:00 UTC
DVC pushes whole file to remote server, while pulling only diffs. Since I am working with big datasets (~50 GB of data before model) and a lot of iterations it would be nice if only diffs were pushed to remote server. Since whole file is pushed to the remote server multiple times it fills up space pretty quickly. Is it possible to solve this problem with big data?

**Comment by pmrowla** [comment] 2022-04-05 09:03
Unfortunately DVC only supports deduplication at the file level, and does not do any diffing within files. There is an existing feature request for this that you can follow for future updates: https://github.com/iterative/dvc/issues/829

Closing as duplicate of #829

**Closed by pmrowla** 2022-04-05 09:03 UTC

**Comment by emilijapur** [comment] 2022-04-05 10:57
Excuse me, can you explain me further what do you mean by saying "DVC only supports deduplication at the file level", please clarify. As I push the same file to dvc remote after minor changes, multiple versions of the same file is being stored. Is this part of dedublication?

**Comment by pmrowla** [comment] 2022-04-05 11:29
It means that DVC stores files according to their hashes, as [content addressable storage](https://dvc.org/doc/user-guide/project-structure/internal-files#structure-of-the-cache-directory). So if you have two different files that have the same data content, DVC will only store one copy of that file. Likewise, if you have two tracked revisions of a file where the file is the same between those two revisions, DVC would only store one copy of that file. So DVC does de-duplication at the whole file level.

As you have noted, if you have a small change in a large file, this means that DVC still has to store the entire file twice (since they have different binary content).

**Comment by shcheklein** [comment] 2022-04-06 00:05
@emilijapur here is also some explanation that might help - https://stackoverflow.com/questions/60365473/by-how-much-can-i-approx-reduce-disk-volume-by-using-dvc/60366262#60366262

The only possible (if it makes sense at all in your use case) workaround to this problem at this moment is to use directories and try to split large files into smaller one. E.g. if it's a CSV that you keep appending data to, could you split it by date, or by some other field?

**Comment by emilijapur** [comment] 2022-04-06 05:37
Sadly I can not split my data in any blocks or parts due to project specifics. However, I thought since git tracks only diffs (not whole files), that DVC can do the same. From your answers I understand that this feature is not going to be implemented in the future?

**Comment by pmrowla** [comment] 2022-04-06 05:45
It is planned to be implemented at some point, but there is no timetable on when that will be (see the issue I linked earlier: https://github.com/iterative/dvc/issues/829)
