### ISSUE TITLE
`dvc exp show` truncates branch names if they contain a `/`

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [iterative/dvc#8413] opened 2022-10-07 18:19 UTC
# Bug Report

## Description

If your branch name contains a `/` when using `dvc exp show`, everything before (and including) the `/` will be truncated.

### Reproduce

```
mkdir foo
cd foo
git init
git checkout -b uh/oh
dvc init
curl -OL https://gist.githubusercontent.com/ivyleavedtoadflax/91b21bdb9f2c7e53d102e0f871642d56/raw/98d159e94cf819ebb03a9e6e2dec862576f9cf9c/dvc.yaml
dvc repro 
git add . && git commit -m 'Initial commit' 
dvc exp show --md --no-pager --verbose
>>>
| Experiment   | Created   | f1-score   |
|--------------|-----------|------------|
| workspace    | -         | 0.99       |
| oh           | 08:17 PM  | 0.99       |

2022-10-07 20:18:23,030 DEBUG: Analytics is enabled.
2022-10-07 20:18:23,090 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpq4v_7wrj']'
2022-10-07 20:18:23,091 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpq4v_7wrj']'
```

### Expected

```
| Experiment   | Created   | f1-score   |
|--------------|-----------|------------|
| workspace    | -         | 0.99       |
| uh/oh        | 08:17 PM  | 0.99       |
```

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.29.0 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.29
Subprojects:
        dvc_data = 0.14.0
        dvc_objects = 0.5.0
        dvc_render = 0.0.11
        dvc_task = 0.1.3
        dvclive = 0.10.0
        scmrepo = 0.1.1
Supports:
        http (aiohttp = 3.8.1, aiohttp-retry = 2.6.1),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.6.1),
        s3 (s3fs = 2022.7.1, boto3 = 1.21.21)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdb
Caches: local
Remotes: None
Workspace directory: ext4 on /dev/sdb
Repo: dvc, git
```

**Comment by karajan1001** [comment] 2022-10-10 11:33
might be duplicated with some related issues #7933 #6819 #6143.
All these issues are related to the naming validation.

**Comment by pmrowla** [comment] 2022-10-10 14:05
This is a duplicate of #7933 (we don't display branches and tags that contain `/` properly). This issue is not related to `dvc exp` names containing `/` (which are not allowed and get rejected).

closing in favor of #7933

**Closed by pmrowla** 2022-10-10 14:05 UTC
Labels: A: experiments
