### ISSUE TITLE
ssh get-url throws  ERROR: unexpected error - 'NoneType' object has no attribute 'cache'

### ISSUE THREAD

**Issue by mathias3** [iterative/dvc#4174] opened 2020-07-07 07:43 UTC
### Please provide information about your setup

**Output of `dvc version`:**

```console
$ dvc version
```
DVC version: 1.0.1
Python version: 3.7.1
Platform: Linux-5.3.0-62-generic-x86_64-with-debian-buster-sid
Binary: True
Package: deb
Supported remotes: azure, gdrive, gs, hdfs, http, https, s3, ssh, oss
Filesystem type (workspace): ('ext4', '/dev/mapper/ubuntu--vg-root')

**Additional Information (if any):**

If applicable, please also provide a `--verbose` output of the command, eg: `dvc add --verbose`.

```020-07-07 09:42:33,048 DEBUG: Establishing ssh connection with '116xxxxxxxxxxxxxx' through port '22' as user 'root'
2020-07-07 09:42:34,195 ERROR: unexpected error - 'NoneType' object has no attribute 'cache'
------------------------------------------------------------
Traceback (most recent call last):
  File "dvc/main.py", line 53, in main
  File "dvc/command/get_url.py", line 17, in run
  File "dvc/repo/get_url.py", line 19, in get_url
  File "dvc/output/base.py", line 264, in save
  File "dvc/output/base.py", line 192, in save_info
  File "dvc/remote/base.py", line 756, in save_info
  File "dvc/remote/base.py", line 323, in save_info
  File "dvc/remote/base.py", line 291, in get_hash
  File "dvc/remote/base.py", line 304, in get_dir_hash
  File "dvc/remote/base.py", line 183, in cache
AttributeError: 'NoneType' object has no attribute 'cache'

**Comment by efiop** [comment] 2020-07-07 10:17
Hi @mathias3 . Could you please upgrade to the latest version (1.1.7 as of right now) and try again?

**Comment by mathias3** [comment] 2020-07-07 10:55
> Hi @mathias3 . Could you please upgrade to the latest version (1.1.7 as of right now) and try again?

``` sudo apt-get install --only-upgrade dvc```
returns
```dvc is already the newest version (1.0.1).```

**Comment by efiop** [comment] 2020-07-07 11:05
@mathias3 I think you need to `sudo apt update` first. I can confirm that 1.1.7 is in our deb repo already.

**Comment by mathias3** [comment] 2020-07-07 11:10
```dvc version
DVC version: 1.1.7
Python version: 3.7.1
Platform: Linux-5.3.0-62-generic-x86_64-with-debian-buster-sid
Binary: True
Package: deb
Supported remotes: azure, gdrive, gs, hdfs, http, https, s3, ssh, oss
Filesystem type (workspace): ('ext4', '/dev/mapper/ubuntu--vg-root')```
```

``` dvc get-url -v  ssh://root@116.xxxxxxxxxxxxxxx/dvc/test2 ```
still returns
```
2020-07-07 13:09:02,481 DEBUG: Establishing ssh connection with '116.xxxxxxxxxx' through port '22' as user 'root'
2020-07-07 13:09:03,515 ERROR: unexpected error - 'NoneType' object has no attribute 'cache'
------------------------------------------------------------
Traceback (most recent call last):
  File "dvc/main.py", line 53, in main
  File "dvc/command/get_url.py", line 17, in run
  File "dvc/repo/get_url.py", line 19, in get_url
  File "dvc/output/base.py", line 268, in save
  File "dvc/output/base.py", line 192, in save_info
  File "dvc/remote/base.py", line 769, in save_info
  File "dvc/remote/base.py", line 334, in save_info
  File "dvc/remote/base.py", line 302, in get_hash
  File "dvc/remote/base.py", line 315, in get_dir_hash
  File "dvc/remote/base.py", line 184, in cache
AttributeError: 'NoneType' object has no attribute 'cache'
------------------------------------------------------------

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!

**Comment by efiop** [comment] 2020-07-07 11:18
@mathias3 Thanks! Indeed, it is a known bug when trying to get-url a directory. https://github.com/iterative/dvc/issues/4144 For now, you could just use scp or rsync with the same effect.

**Comment by efiop** [comment] 2020-07-07 11:23
I'll close this issue as a duplicate of #4144. Thank you for the feedback!

**Closed by efiop** 2020-07-07 11:23 UTC
Labels: awaiting response, bug
