### ISSUE TITLE
`exp run --set-param`: Doesn't support `-` in param name

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc#8151] opened 2022-08-19 13:43 UTC
Introduced in #8067 

Appears to be a Hydra limitation that the author doesn't plan to address:

https://github.com/facebookresearch/hydra/issues/514

**Comment by daavoo** [comment] 2022-08-19 15:24
> My reading of the author's concerns appear to be limited to using `--` preceding a parameter name, not use of `-` anywhere in the parameter name. Are you reading it differently?

I guess the thing is that the restriction of `-` is currently embedded in the grammar rules, no matter where it is used.
Allowing `-` in some cases but not in others would require new rules.

We could explain our use case and see if it makes a difference or there is an alternative for us.

**Comment by z1ga** [comment] 2022-08-27 14:41
I ran into same problem while trying to queue experiments with `--set-param` options. The binaries in my DVC pipeline use many `--some-argument-name` style arguments, which work great with DVC's [dict unpacking](https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#dict-unpacking) and YAML's support for keys that contain `-`.

It would be great if `--set-param` would support these as well.

**Comment by dberenbaum** [comment] 2022-09-16 17:04
@daavoo What do you think about adding this to the backlog since it is a regression in DVC?

**Comment by daavoo** [comment] 2022-09-16 18:40
> @daavoo What do you think about adding this to the backlog since it is a regression in DVC?

I assume you mean about patching on our side, right?

**Comment by dberenbaum** [comment] 2022-09-16 19:17
No, I meant contributing to hydra 😄 , but patching on our side is also fine.

**Comment by daavoo** [comment] 2022-09-16 20:06
> No, I meant contributing to hydra 😄 , but patching on our side is also fine.

I just felt that https://github.com/facebookresearch/hydra/pull/2094 is pretty much done and would fix this issue. 
I don't see any comment requiring changes, it looks blocked pending the resolution of the discussion so not sure what we could contribute

**Comment by dberenbaum** [comment] 2022-09-19 12:25
Got it. Let's follow in https://github.com/facebookresearch/hydra/issues/2363. Again, no problem with patching on our side for now if that's going to be quicker/easier.

**Comment by dberenbaum** [comment] 2022-09-29 22:04
Should be fixed in the next hydra release

**Closed** 2022-12-12 16:44 UTC
Labels: A: experiments, regression, upstream
