### ISSUE TITLE
`dvc init` gives : No such file or directory: '.dvc/.gitignore'

### ISSUE THREAD

**Issue by courentin** [iterative/dvc#3803] opened 2020-05-14 21:24 UTC
Hello,

I've encounter the error bellow when re-initilizing a dvc project in my repo.

`dvc init -v` gives:

<details open>
<summary>Error log details</summary>

```
2020-05-14 23:04:22,539 ERROR: unexpected error - [Errno 2] No such file or directory: '.dvc/.gitignore'
------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/corentinhembise/.local/share/virtualenvs/speech-XlnoNrSS/lib/python3.6/site-packages/dvc/main.py", line 48, in main
    ret = cmd.run()
  File "/Users/corentinhembise/.local/share/virtualenvs/speech-XlnoNrSS/lib/python3.6/site-packages/dvc/command/init.py", line 19, in run
    subdir=self.args.subdir,
  File "/Users/corentinhembise/.local/share/virtualenvs/speech-XlnoNrSS/lib/python3.6/site-packages/dvc/repo/__init__.py", line 160, in init
    init(root_dir=root_dir, no_scm=no_scm, force=force, subdir=subdir)
  File "/Users/corentinhembise/.local/share/virtualenvs/speech-XlnoNrSS/lib/python3.6/site-packages/dvc/repo/init.py", line 107, in init
    scm.add([os.path.join(dvc_dir, scm.ignore_file)])
  File "/Users/corentinhembise/.local/share/virtualenvs/speech-XlnoNrSS/lib/python3.6/site-packages/dvc/scm/git/__init__.py", line 236, in add
    self.repo.index.add(paths)
  File "/Users/corentinhembise/.local/share/virtualenvs/speech-XlnoNrSS/lib/python3.6/site-packages/git/index/base.py", line 740, in add
    entries_added.extend(self._entries_for_paths(paths, path_rewriter, fprogress, entries))
  File "/Users/corentinhembise/.local/share/virtualenvs/speech-XlnoNrSS/lib/python3.6/site-packages/git/util.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/corentinhembise/.local/share/virtualenvs/speech-XlnoNrSS/lib/python3.6/site-packages/git/index/util.py", line 91, in set_git_working_dir
    return func(self, *args, **kwargs)
  File "/Users/corentinhembise/.local/share/virtualenvs/speech-XlnoNrSS/lib/python3.6/site-packages/git/index/base.py", line 626, in _entries_for_paths
    entries_added.append(self._store_path(filepath, fprogress))
  File "/Users/corentinhembise/.local/share/virtualenvs/speech-XlnoNrSS/lib/python3.6/site-packages/git/index/base.py", line 587, in _store_path
    st = os.lstat(filepath)     # handles non-symlinks as well
FileNotFoundError: [Errno 2] No such file or directory: '.dvc/.gitignore'
------------------------------------------------------------
```

</details>

After some investigations, I figured out that the problem come from my `.git/info/exclude`, where I've ignored the `.dvc` folder.
Removing the line in `.git/info/exclude` fixed the problem.

However, the error was not very explicit and I spent quite a few time fixing it.
I don't know if it is something you want/can fix, but at least it is now documented here if other people encounter this error.

(Tested on dvc version 1.0.0a installed with pip on Mac OS.)

Thank you for your work on this project, which is awesome btw!

**Comment by efiop** [comment] 2020-05-15 00:17
Hi @courentin !

Nice catch! Indeed, I think we could catch that and show a hint that it might be gitignored or something.

Thanks for reporting the issue!

**Comment by skshetry** [comment] 2020-05-15 01:43
Duplicate of https://github.com/iterative/dvc/issues/3738

**Closed** 2020-05-15 01:44 UTC
Labels: enhancement, p3-nice-to-have, ui
