### ISSUE TITLE
Unknown publisher smart-screen warnings (Windows installer)

### ISSUE THREAD

**Issue by ryanraposo** [iterative/dvc#5192] opened 2021-01-03 13:59 UTC
### Description

When installing on Windows using the self-contained binary installer, there are strong warnings/prompts to do with installing from unknown publishers. These security features go as far as hiding the way forward in the installation. 

### Reproduce

Download & run the installer (ex https://github.com/iterative/dvc/releases/download/1.10.2/dvc-1.10.2.exe)

On a Windows installation without obscure developer features turned on, you should see:

- Standard UAC warning for unknown publishers. I'd say this is more or less expected/acceptable, there is always a similar prompt for any binary.

- Windows Defender SmartScreen prompt, obscures the 'Proceed' option. (Note: if you do navigate past it, it won't come up again. I think this is do to with the binary being marked as a 'safe' unknown publisher binary?)

![unknown-pub](https://user-images.githubusercontent.com/38861352/103480109-4c96f600-4da0-11eb-976e-744e96e78302.png)

### Expected

Not so much an 'expected' thing, but one would certainly feel more comfortable installing without these scary warnings. 

Less of an issue with this tool's demographic, for sure, but some users might not be able to move past the warning, even if they want to.

### Additional Information

[Helpful link](https://stackoverflow.com/a/55404324) about the certificates/techniques you can use to better identify your installer package for recognition in Windows

**Comment by skshetry** [comment] 2021-01-03 14:15
@ryanraposo, this is a known issue that happens because the binary packages are not signed. Closing this as a duplicate of #936. 

We are also considering removing binary packages in #2760.

**Closed by skshetry** 2021-01-03 14:15 UTC

**Comment by efiop** [comment] 2021-01-03 22:35
Also, we might want to consider removing the `download` button from https://dvc.org/ and having something like `install` that will redirect to recommended ways of installation (pip, brew, conda, etc). This is discussed in https://github.com/iterative/dvc.org/issues/919
