### ISSUE TITLE
version:  development version not showing the latest git commit hash

### ISSUE THREAD

**Issue by ryokugyu** [iterative/dvc#2179] opened 2019-06-24 01:32 UTC
I tried installing DVC with the help of guide in [command-reference](https://dvc.org/doc/commands-reference/version).
Also from [user-guide](https://dvc.org/doc/user-guide/development) 

![dvc_code](https://user-images.githubusercontent.com/16274905/59985150-6012be00-964d-11e9-9af2-faa7d76b1319.png)
 But the output is not the same as described the `version` command reference. 
![dvc_version](https://user-images.githubusercontent.com/16274905/59985202-c7c90900-964d-11e9-86c3-e1fd4d2513d8.png)
> Development version: `pip install git+git://github.com/iterative/dvc` will install DVC using the master branch of DVC's repository. Another way of setting up the development version is to clone the repository and run `pip install . `. The master branch is continuously being updated with changes which might not be ready to publish yet. Therefore installing using the above command might have issues regarding its usage. So to trace any error reported with this setup, we need to know exactly which version is being used. For this, we rely on git commit hash which is displayed in output as `0.40.2+292cab.mod`. The part before + is the BASE_VERSION and the latter part is the git commit hash which is one of the commits in the master branch (also, optional suffix .mod means that code is modified).

But, in my Windows machine, it is working fine.
![dvc_version_windows](https://user-images.githubusercontent.com/16274905/59985288-4d4cb900-964e-11e9-9ef4-f6c42465f194.PNG)

**Comment by ryokugyu** [comment] 2019-06-24 01:35
is this because of the python version?

**Comment by shcheklein** [comment] 2019-06-24 03:17
@ryokugyu could you run `which dvc` please? I can't reproduce it on my machine.

**Comment by ryokugyu** [comment] 2019-06-24 03:45
> @ryokugyu could you run `which dvc` please? I can't reproduce it on my machine.
```
ryokugyu@ub:~$ which dvc
/home/ryokugyu/.local/bin/dvc
````

**Comment by shcheklein** [comment] 2019-06-24 04:07
are you using virtualenv or something similar? could you run `pip show dvc` as well please

**Comment by ryokugyu** [comment] 2019-06-24 15:00
> are you using virtualenv or something similar? could you run `pip show dvc` as well please

![dvc_version_pip_show](https://user-images.githubusercontent.com/16274905/60029452-ce439900-96be-11e9-9229-447b97af7b13.png)

**Comment by mroutis** [comment] 2019-06-24 16:23
@ryokugyu , I also couldn't reproduce it, here are my steps:
```bash
#!/usr/bin/env bash
git clone https://github.com/iterative/dvc.git
cd dvc
virtualenv --python=/usr/bin/python2 .venv
source .venv/bin/activate
pip install .
dvc version
```

As @shcheklein mentioned, you may have two conflicting versions of DVC (for example, one installed with `apt-get` or `pip install dvc` and the other one with `git clone ... && pip install .`)

Maybe you can `pip uninstall dvc` and check if `which dvc` outputs anything, if so, you need to also remove the other version.

Hope it helps :)

**Comment by shcheklein** [comment] 2019-07-14 04:54
@ryokugyu closing this since we failed to reproduce. Please, try to provide a clear instruction on how we can do this if it's still an existing issue.

**Closed by shcheklein** 2019-07-14 04:54 UTC
