### ISSUE TITLE
push: does not take into account the no_proxy env var

### ISSUE THREAD

**Issue by Hish15** [iterative/dvc#8835] opened 2023-01-18 12:35 UTC
# Bug Report

## Description

At work we are behind a proxy. Recently we moved from an outer storage solution to an internal solution. Since then we can push if we don't set any proxy, but setting a proxy and adding our storage url to the no_proxy list does not work.

### Reproduce

Set up a storage in a location that does not work with a given proxy
Add the storage to the no_proxy list
Try to push

### Expected

Adding the url to the no_proxy env var, should be the same as running without proxy.

### Environment information

We work windows PC and use the CLI interface to perform dvc related commands

**Comment by efiop** [comment] 2023-01-20 02:40
@Hish15 Please post full `dvc doctor` output and full log for `dvc push -v`

**Comment by wdixon** [comment] 2023-01-20 15:49
I am facing the same issue - needed to unset my proxy variables even thought no_proxy was set

DVC version: 2.38.1 (pip)
---------------------------------
Platform: Python 3.10.9 on Linux-3.10.0-1160.81.1.el7.x86_64-x86_64-with-glibc2.27
Subprojects:
	dvc_data = 0.28.4
	dvc_objects = 0.14.0
	dvc_render = 0.0.15
	dvc_task = 0.1.8
	dvclive = 1.3.2
	scmrepo = 0.1.4
Supports:
	http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	s3 (s3fs = 2022.11.0, boto3 = 1.24.59)

**Comment by efiop** [comment] 2023-01-20 19:45
@wdixon Please post full log for `dvc push -v`, so we can see where the error is.

Also looks like you've removed part of your `dvc doctor` log, as I don't see which remote types you are using

**Comment by wdixon** [comment] 2023-01-20 22:54
That was the complete output of dvc doctor (when not run in a project with dvc)...
Inside a dvc project - the following additional information comes out:

```bash
Cache types: hardlink, symlink
Cache directory: nfs on somecompany.com:/nas_projects
Caches: local
Remotes: s3
Workspace directory: nfs on somecompany.com:/nas_projects
Repo: dvc, git
```

Here is the output of the dvc push -v

```bash
2023-01-20 17:51:08,366 DEBUG: Preparing to transfer data from '/projects/shared_dvc_cache' to 'dvc-projects/datasets/regression'                                   
2023-01-20 17:51:08,366 DEBUG: Preparing to collect status from 'dvc-projects/datasets/regression'
2023-01-20 17:51:08,367 DEBUG: Collecting status from 'dvc-projects/datasets/regression'
2023-01-20 17:51:08,367 DEBUG: Querying 7 oids via object_exists                                                                                                                                       
2023-01-20 17:51:08,838 DEBUG: Indexing new .dir 'b3867c4de20b4fea28a4489755a4ce44.dir' with '328' nested files                                                                                        
2023-01-20 17:51:08,848 DEBUG: Indexing new .dir '3effabd0e54a9c23d80f15a1c6c045fa.dir' with '12' nested files
2023-01-20 17:51:08,850 DEBUG: Indexing new .dir '06fd9af5b6e1670a1fea3f038efced2a.dir' with '64' nested files
2023-01-20 17:51:08,852 DEBUG: Indexing new .dir 'e00a0270c53569ee3a548db50bc64e9e.dir' with '15' nested files
2023-01-20 17:51:08,854 DEBUG: Indexing new .dir 'cb63daedbc6e11a7817f9eb07601a95e.dir' with '133' nested files
2023-01-20 17:51:08,859 DEBUG: Indexing new .dir '641af77fd772a40ed7101223ec63f76e.dir' with '28' nested files
2023-01-20 17:51:08,860 DEBUG: Indexing new .dir '13e5a8c993ab31a697979d7496227fba.dir' with '32' nested files
Everything is up to date.
2023-01-20 17:51:08,868 DEBUG: Analytics is enabled.
2023-01-20 17:51:08,918 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/var/tmp/pbs.1718264.scinfra2/tmpo0u4ex30']'
2023-01-20 17:51:08,920 DEBUG: Spawned '['daemon', '-q', 'analytics', '/var/tmp/pbs.1718264.scinfra2/tmpo0u4ex30']'

```

**Comment by efiop** [comment] 2023-01-20 23:16
@wdixon You've re-set the proxy env vars, right? I see that the dvc push finished successfully and there are no errors in your log.

**Comment by wdixon** [comment] 2023-01-21 00:15
Actually, my situation may have been slightly different.  I encountered the error on a project where I was attempting to perform a dvc pull (not a push), but on a project with imported dvc resources.

dvc pull and push seem to work with the proxy/noproxy environment variables set within a dvc project without imported resources; however, imported dvc resources do not seem to work properly with the noproxy environment variable.  

It perhaps looks like an underlying problem with the dulwich library:

```bash

wdixon@leb1mlgpu3:/home/wdixon/experimental/examples$ env | grep proxy

https_proxy=http://proxy.somecompany.com:80
http_proxy=http://proxy.somecompany.com:80
no_proxy=somecompany.com


wdixon@leb1mlgpu3:/home/wdixon/experimental/examples$ dvc pull -v
2023-01-20 18:54:22,603 DEBUG: Creating external repo https://github.build.somecompany.com/project/datasets_483483_1017.git@bb1eeb24a29c536b06fbc8fd80babc3928b8c04f
2023-01-20 18:54:22,603 DEBUG: erepo: git clone 'https://github.build.somecompany.com/project/datasets_483483_1017.git' to a temporary dir
2023-01-20 18:54:22,923 ERROR: failed to pull data from the cloud - Failed to clone repo 'https://github.build.somecompany.com/project/datasets_483483_1017.git' to '/var/tmp/pbs.1718264.scinfra2/tmpv3vu9mtqdvc-clone'                                  
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 369, in connect
    self._tunnel()
  File "/usr/lib/python3.10/http/client.py", line 924, in _tunnel
    raise OSError(f"Tunnel connection failed: {code} {message.strip()}")
OSError: Tunnel connection failed: 502 Bad Gateway

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/scmrepo/git/backend/dulwich/__init__.py", line 200, in clone
    repo = clone_from()
  File "/usr/local/lib/python3.10/dist-packages/dulwich/porcelain.py", line 551, in clone
    return client.clone(
  File "/usr/local/lib/python3.10/dist-packages/dulwich/client.py", line 760, in clone
    result = self.fetch(path, target, progress=progress, depth=depth)
  File "/usr/local/lib/python3.10/dist-packages/dulwich/client.py", line 837, in fetch
    result = self.fetch_pack(
  File "/usr/local/lib/python3.10/dist-packages/dulwich/client.py", line 2076, in fetch_pack
    refs, server_capabilities, url = self._discover_references(
  File "/usr/local/lib/python3.10/dist-packages/dulwich/client.py", line 1934, in _discover_references
    resp, read = self._http_request(url, headers)
  File "/usr/local/lib/python3.10/dist-packages/dulwich/client.py", line 2206, in _http_request
    resp = self.pool_manager.request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/request.py", line 74, in request
    return self.request_encode_url(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/poolmanager.py", line 533, in urlopen
    return super(ProxyManager, self).urlopen(method, url, redirect=redirect, **kw)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.build.somecompany.com', port=443): Max retries exceeded with url: /project/datasets_483483_1017.git/info/refs?service=git-upload-pack (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 502 Bad Gateway')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/dvc/scm.py", line 145, in clone
    git = Git.clone(url, to_path, progress=pbar.update_git, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/scmrepo/git/__init__.py", line 143, in clone
    backend.clone(url, to_path, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/scmrepo/git/backend/dulwich/__init__.py", line 203, in clone
    raise CloneError(url, to_path) from exc
scmrepo.exceptions.CloneError: Failed to clone repo 'https://github.build.somecompany.com/project/datasets_483483_1017.git' to '/var/tmp/pbs.1718264.scinfra2/tmpv3vu9mtqdvc-clone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/dvc/commands/data_sync.py", line 31, in run
    stats = self.repo.pull(
  File "/usr/local/lib/python3.10/dist-packages/dvc/repo/__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/dvc/repo/pull.py", line 34, in pull
    processed_files_count = self.fetch(
  File "/usr/local/lib/python3.10/dist-packages/dvc/repo/__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/dvc/repo/fetch.py", line 85, in fetch
    d, f = _fetch(
  File "/usr/local/lib/python3.10/dist-packages/dvc/repo/fetch.py", line 141, in _fetch
    used = repo.used_objs(
  File "/usr/local/lib/python3.10/dist-packages/dvc/repo/__init__.py", line 432, in used_objs
    for odb, objs in self.index.used_objs(
  File "/usr/local/lib/python3.10/dist-packages/dvc/repo/index.py", line 332, in used_objs
    for odb, objs in stage.get_used_objs(
  File "/usr/local/lib/python3.10/dist-packages/dvc/stage/__init__.py", line 710, in get_used_objs
    for odb, objs in out.get_used_objs(*args, **kwargs).items():
  File "/usr/local/lib/python3.10/dist-packages/dvc/output.py", line 1050, in get_used_objs
    return self.get_used_external(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/dvc/output.py", line 1108, in get_used_external
    return dep.get_used_objs(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/dvc/dependency/repo.py", line 99, in get_used_objs
    used, _, _ = self._get_used_and_obj(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/dvc/dependency/repo.py", line 113, in _get_used_and_obj
    with self._make_repo(locked=locked, cache_dir=local_odb.path) as repo:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/dvc/external_repo.py", line 39, in external_repo
    path = _cached_clone(url, rev, for_write=for_write)
  File "/usr/local/lib/python3.10/dist-packages/dvc/external_repo.py", line 169, in _cached_clone
    clone_path, shallow = _clone_default_branch(url, rev, for_write=for_write)
  File "/usr/local/lib/python3.10/dist-packages/funcy/decorators.py", line 45, in wrapper
    return deco(call, *dargs, **dkwargs)
  File "/usr/local/lib/python3.10/dist-packages/funcy/flow.py", line 274, in wrap_with
    return call()
  File "/usr/local/lib/python3.10/dist-packages/funcy/decorators.py", line 66, in __call__
    return self._func(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/dvc/external_repo.py", line 239, in _clone_default_branch
    git = clone(url, clone_path)
  File "/usr/local/lib/python3.10/dist-packages/dvc/scm.py", line 150, in clone
    raise CloneError(str(exc))
dvc.scm.CloneError: Failed to clone repo 'https://github.build.somecompany.com/project/datasets_483483_1017.git' to '/var/tmp/pbs.1718264.scinfra2/tmpv3vu9mtqdvc-clone'
------------------------------------------------------------
2023-01-20 18:54:22,937 DEBUG: Analytics is enabled.
2023-01-20 18:54:22,981 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/var/tmp/pbs.1718264.scinfra2/tmpccby_d8p']'
2023-01-20 18:54:22,982 DEBUG: Spawned '['daemon', '-q', 'analytics', '/var/tmp/pbs.1718264.scinfra2/tmpccby_d8p']'
wdixon@leb1mlgpu3:/home/wdixon/experimental/examples$ 
```

==================================================================================
But if i explicitly unset the proxy environment variables, and repeat the dvc pull on imported resources, it succeeds:

```bash
wdixon@leb1mlgpu3:/home/wdixon/experimental/examples$ unset http_proxy
wdixon@leb1mlgpu3:/home/wdixon/experimental/examples$ unset https_proxy
wdixon@leb1mlgpu3:/home/wdixon/experimental/examples$ dvc pull -v
```

SUCCESS!

**Comment by efiop** [comment] 2023-01-22 23:45
@wdixon Looks like the issue is https://github.com/jelmer/dulwich/issues/932 in your case.

**Comment by Hish15** [comment] 2023-01-23 17:41
> @wdixon Looks like the issue is [jelmer/dulwich#932](https://github.com/jelmer/dulwich/issues/932) in your case.

This is exactly my situation too! Does this projects use urllib3 and therefore does not handle no_proxy?

**Comment by efiop** [comment] 2023-01-23 17:50
@Hish15 We don't use it directly, but it is a dependency of our dependency. I'll close this one in favor of https://github.com/jelmer/dulwich/issues/932 in case anyone is interested in contributing.

**Closed by efiop** 2023-01-23 17:50 UTC
Labels: awaiting response
