### ISSUE TITLE
Import example on website not working on Mac

### ISSUE THREAD

**Issue by charlesbaynham** [iterative/dvc#4526] opened 2020-09-03 21:58 UTC
## Bug Report

The example for dvc import in the documentation at https://dvc.org/doc/command-reference/import fails. 

### Please provide information about your setup

Mac OSX 10.13.6

**Output of `dvc version`:**

```console
$ dvc version
(venv) Charless-MacBook-Pro:test_dvc_git charles$ dvc version
DVC version: 1.6.6 (pip)
---------------------------------
Platform: Python 3.6.10 on Darwin-17.7.0-x86_64-i386-64bit
Supports: http, https
```

**Additional Information (if any):**

Commands to reproduce:

```
mkdir test_reg
cd test_reg
git init
dvc init
git add .
git commit -m Init

dvc import git@github.com:iterative/example-get-started \
             data/data.xml
```

Output:

```
(venv) Charless-MacBook-Pro:test_dvc_git charles$ ./test.sh 
Initialized empty Git repository in /Users/charles/test_dvc_git/test_reg/.git/

You can now commit the changes to git.

+---------------------------------------------------------------------+
|                                                                     |
|        DVC has enabled anonymous aggregate usage analytics.         |
|     Read the analytics documentation (and how to opt-out) here:     |
|              https://dvc.org/doc/user-guide/analytics               |
|                                                                     |
+---------------------------------------------------------------------+

What's next?
------------
- Check out the documentation: https://dvc.org/doc
- Get help and share ideas: https://dvc.org/chat
- Star us on GitHub: https://github.com/iterative/dvc
[master (root-commit) f6cc28a] Init
 7 files changed, 131 insertions(+)
 create mode 100644 .dvc/.gitignore
 create mode 100644 .dvc/config
 create mode 100644 .dvc/plots/confusion.json
 create mode 100644 .dvc/plots/default.json
 create mode 100644 .dvc/plots/scatter.json
 create mode 100644 .dvc/plots/smooth.json
 create mode 100644 .dvcignore
Importing 'data/data.xml (git@github.com:iterative/example-get-started)' -> 'data.xml'
ERROR: unexpected error - [Errno 2] No such file or directory: '/Users/charles/test_dvc_git/test_reg/.dvc/cache/a3/04afb96060aad90176268345e10355'

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

If applicable, please also provide a `--verbose` output of the command, eg: `dvc add --verbose`.

**Comment by efiop** [comment] 2020-09-03 22:49
Hi @charlesbaynham ! Thank you for reporting this issue! This one is caused by https://github.com/iterative/dvc/issues/4423 , as `example-get-started` is using a chained import, which we don't support well (nor do we provide a good error for) right now. An alternative command is:
```
dvc import https://github.com/iterative/dataset-registry get-started/data.xml
```

I'll close this issue in favor of https://github.com/iterative/dvc/issues/3305.

**Closed by efiop** 2020-09-03 22:49 UTC
