### ISSUE TITLE
`artifacts get`: stopped working with the studio token

### ISSUE THREAD

**Issue by tibor-mach** [iterative/dvc#10077] opened 2023-11-08 22:45 UTC
# Bug Report

## Description

Artifacts get doesn't work with the Studio token (it works with DVC remote credentials).

### Reproduce

Configure studio token (replace stars with the actual token)
```
dvc config --global studio.token ****************
```

Go to repo where you have a versioned artifact in the MR and make sure you don't use DVC remote credentials and that the remote is not publicly accessible

```
dvc artifacts get . my-model
```

### Expected

I expect to be able to download the model using the Studio token.

### Environment information

**Output of `dvc doctor`:**
```
DVC version: 3.28.0 (pip)
-------------------------
Platform: Python 3.11.5 on Linux-6.5.9-1-MANJARO-x86_64-with-glibc2.38
Subprojects:
	dvc_data = 2.20.0
	dvc_objects = 1.1.0
	dvc_render = 0.6.0
	dvc_task = 0.3.0
	scmrepo = 1.4.1
Supports:
	http (aiohttp = 3.8.6, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.6, aiohttp-retry = 2.8.3)
Config:
	Global: /home/tibor/.config/dvc
	System: /etc/xdg/dvc
```

**Additional Information (if any):**

I run these commands (from inside the repo but with DVC remote credentials removed.

(I am replacing the actual token with stars here)

```
dvc config --global studio.token ****************
dvc artifacts get . pool-segmentation --rev v1.0.3 -v                                 
```

This is the output including some env info:

```
2023-11-08 19:47:51,402 DEBUG: v3.28.0 (pip), CPython 3.11.5 on Linux-6.5.9-1-MANJARO-x86_64-with-glibc2.38
2023-11-08 19:47:51,403 DEBUG: command: /home/tibor/.local/bin/dvc artifacts get . pool-segmentation --rev v1.0.3 -v
2023-11-08 19:47:51,603 DEBUG: Trying to download artifact 'pool-segmentation' via studio
2023-11-08 19:47:51,690 DEBUG: Trying to download artifact 'pool-segmentation' via studio
2023-11-08 19:47:51,691 DEBUG: Trying to download artifact 'pool-segmentation' via DVC
2023-11-08 19:47:51,733 ERROR: Failed to download artifact 'pool-segmentation' via Studio - No studio config
Traceback (most recent call last):
  File "/home/tibor/.local/pipx/venvs/dvc/lib/python3.11/site-packages/dvc/repo/artifacts.py", line 224, in _download_studio
    for path, url in get_download_uris(
                     ^^^^^^^^^^^^^^^^^^
  File "/home/tibor/.local/pipx/venvs/dvc/lib/python3.11/site-packages/dvc_studio_client/model_registry.py", line 36, in get_download_uris
    raise ValueError("No studio config")
ValueError: No studio config

2023-11-08 19:47:51,733 ERROR: failed to get 'pool-segmentation' from '.' - Failed to download artifact 'pool-segmentation' via DVC remote: s3 is supported, but requires 'dvc-s3' to be installed: No module named 'dvc_s3'
Traceback (most recent call last):
  File "/home/tibor/.local/pipx/venvs/dvc/lib/python3.11/site-packages/dvc_objects/fs/__init__.py", line 89, in __getitem__
    return _import_class(entry["class"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tibor/.local/pipx/venvs/dvc/lib/python3.11/site-packages/dvc_objects/fs/__init__.py", line 78, in _import_class
    module = importlib.import_module(mod)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dvc_s3'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tibor/.local/pipx/venvs/dvc/lib/python3.11/site-packages/dvc/repo/artifacts.py", line 333, in get
    return repo.artifacts.download(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tibor/.local/pipx/venvs/dvc/lib/python3.11/site-packages/dvc/repo/artifacts.py", line 191, in download
    count = fs_download(
            ^^^^^^^^^^^^
  File "/home/tibor/.local/pipx/venvs/dvc/lib/python3.11/site-packages/dvc/fs/__init__.py", line 56, in download
    desc=f"Downloading {fs.path.name(fs_path)}",
                        ^^^^^^^
  File "/home/tibor/.local/pipx/venvs/dvc/lib/python3.11/site-packages/dvc/fs/dvc.py", line 456, in path
    return self.fs.path
           ^^^^^^^
  File "/usr/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/tibor/.local/pipx/venvs/dvc/lib/python3.11/site-packages/dvc/fs/dvc.py", line 445, in fs
    return _DVCFileSystem(**self.fs_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tibor/.local/pipx/venvs/dvc/lib/python3.11/site-packages/fsspec/spec.py", line 79, in __call__
    obj = super().__call__(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tibor/.local/pipx/venvs/dvc/lib/python3.11/site-packages/dvc/fs/dvc.py", line 182, in __init__
    self._datafss[key] = DataFileSystem(index=repo.index.data["repo"])
                                              ^^^^^^^^^^^^^^^
  File "/home/tibor/.local/pipx/venvs/dvc/lib/python3.11/site-packages/funcy/objects.py", line 25, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
                                                  ^^^^^^^^^^^^^^^^^^^
  File "/home/tibor/.local/pipx/venvs/dvc/lib/python3.11/site-packages/dvc/repo/index.py", line 481, in data
    _load_storage_from_out(data_index.storage_map, key, out)
  File "/home/tibor/.local/pipx/venvs/dvc/lib/python3.11/site-packages/dvc/repo/index.py", line 166, in _load_storage_from_out
    remote = out.repo.cloud.get_remote(out.remote)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tibor/.local/pipx/venvs/dvc/lib/python3.11/site-packages/dvc/data_cloud.py", line 94, in get_remote
    cls, config, fs_path = get_cloud_fs(self.repo.config, name=name)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tibor/.local/pipx/venvs/dvc/lib/python3.11/site-packages/dvc/fs/__init__.py", line 161, in get_cloud_fs
    cls = get_fs_cls(remote_conf)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tibor/.local/pipx/venvs/dvc/lib/python3.11/site-packages/dvc_objects/fs/__init__.py", line 112, in get_fs_cls
    return registry.get(scheme)
           ^^^^^^^^^^^^^^^^^^^^
  File "<frozen _collections_abc>", line 774, in get
  File "/home/tibor/.local/pipx/venvs/dvc/lib/python3.11/site-packages/dvc_objects/fs/__init__.py", line 91, in __getitem__
    raise ImportError(entry["err"]) from exc
ImportError: s3 is supported, but requires 'dvc-s3' to be installed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tibor/.local/pipx/venvs/dvc/lib/python3.11/site-packages/dvc/commands/artifacts.py", line 19, in run
    count, out = Artifacts.get(
                 ^^^^^^^^^^^^^^
  File "/home/tibor/.local/pipx/venvs/dvc/lib/python3.11/site-packages/dvc/repo/artifacts.py", line 346, in get
    raise DvcException(
dvc.exceptions.DvcException: Failed to download artifact 'pool-segmentation' via DVC remote

2023-11-08 19:47:51,735 DEBUG: Analytics is enabled.
2023-11-08 19:47:51,757 DEBUG: Trying to spawn ['daemon', 'analytics', '/tmp/tmp9x0nd4xb', '-v']
2023-11-08 19:47:51,762 DEBUG: Spawned ['daemon', 'analytics', '/tmp/tmp9x0nd4xb', '-v'] with pid 62304
```

**Comment by dberenbaum** [comment] 2023-11-08 22:59
I can confirm, and I am able to download successfully from the Studio API:

```
$ curl "https://studio.iterative.ai/api/model-registry/get-download-uris?repo=github:iterative/example-get-started-experiments&name=pool-segmentation&version=v0.1.0" --header "Authorization:token ***"
{"models/model.pkl":"https://remote.dvc.org/get-started-pools/files/md5/8e/790992eed47d33b14b1f7b7247c251"}%

$ wget https://remote.dvc.org/get-started-pools/files/md5/8e/790992eed47d33b14b1f7b7247c251
--2023-11-08 17:56:10--  https://remote.dvc.org/get-started-pools/files/md5/8e/790992eed47d33b14b1f7b7247c251
Resolving remote.dvc.org (remote.dvc.org)... 104.21.81.205, 172.67.164.76
Connecting to remote.dvc.org (remote.dvc.org)|104.21.81.205|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://s3-us-east-2.amazonaws.com/dvc-public/remote/get-started-pools/files/md5/8e/790992eed47d33b14b1f7b7247c251 [following]
--2023-11-08 17:56:11--  https://s3-us-east-2.amazonaws.com/dvc-public/remote/get-started-pools/files/md5/8e/790992eed47d33b14b1f7b7247c251
Resolving s3-us-east-2.amazonaws.com (s3-us-east-2.amazonaws.com)... 52.219.101.241, 52.219.108.225, 52.219.178.209, ...
Connecting to s3-us-east-2.amazonaws.com (s3-us-east-2.amazonaws.com)|52.219.101.241|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 200656 (196K) [binary/octet-stream]
Saving to: ‘790992eed47d33b14b1f7b7247c251’

790992eed47d33b14b1f7b 100%[=========================>] 195.95K  --.-KB/s    in 0.1s

2023-11-08 17:56:11 (1.33 MB/s) - ‘790992eed47d33b14b1f7b7247c251’ saved [200656/200656]
```

**Comment by shcheklein** [comment] 2023-11-08 23:01
If it's an actual bug (regression) we need to review and add full test coverage for this please.

**Comment by pmrowla** [comment] 2023-11-09 04:28
I can reproduce this with `config --global` but should also note that `artifacts get` works for me with the token set in the environment (with no remote credentials)

```
$ DVC_STUDIO_TOKEN=*** dvc artifacts get https://github.com/pmrowla/artifacts-get-demo.git my-model -f --rev v1.0.0
Downloaded 1 file(s) to 'model.pkl'
```

**Comment by pmrowla** [comment] 2023-11-09 05:08
Issue was with a kwarg variable name change which was causing the merged global/system level config to get dropped before it was passed into dvc-studio-client

**Closed** 2023-11-09 07:19 UTC
Labels: bug, p1-important
