### ISSUE TITLE
config: `dvc config` doesn't throw an error when used outside of a dvc repository without --system or --global

### ISSUE THREAD

**Issue by ghost** [iterative/dvc#2309] opened 2019-07-22 14:54 UTC
```
DVC version: 0.52.1+1e9f1d
Python version: 3.7.3
Platform: Linux-5.2.1-arch1-1-ARCH-x86_64-with-arch
Binary: False
Filesystem type (workspace): ('xfs', '/dev/mapper/vg-root')
```
---

```bash
rm -rf .dvc
dvc remote modify something whatever yeah
```

#### Expected
```
ERROR: you are not inside of a dvc repository (checked up to mount point '/')
```

**Comment by efiop** [comment] 2019-07-22 16:35
@mroutis Remotes can be defined in global or system configs. This is not a bug.

**Comment by efiop** [comment] 2019-07-22 16:36
Ah, wait. So the .dvc is removed... So looks like running that command anywhere will create .dvc/config, right? Re-opening. Sorry for jumping on this one.

**Comment by mroutis** [comment] 2019-07-22 19:03
@efiop , running `dvc remote modify` on a directory which is not a DVC repository doesn't do anything at all. You are right, `--system` and `--global` shouldn't throw an error, but for `--local` and without any flag, it should.

**Comment by efiop** [comment] 2020-01-19 07:39
Issue is relevant for `dvc config` in general, as `dvc remote` derives from it. Some explanation https://github.com/iterative/dvc/pull/3194#pullrequestreview-344982907 . Adjusting the naming...

**Comment by efiop** [comment] 2020-01-28 16:04
Related https://github.com/iterative/dvc/issues/2234 , should be fixed by the redesign.

**Comment by efiop** [comment] 2020-01-28 16:54
For the record, this might require full config refactor (and likely will), so please check back before tackling this one, just to make sure that we are on the same page.

**Comment by efiop** [comment] 2021-05-03 15:23
Fixed.

**Closed by efiop** 2021-05-03 15:23 UTC
Labels: :bug: bug, p1-important
