### ISSUE TITLE
fetch -a: failed to load directory when using a local relative remote 

### ISSUE THREAD

**Issue by oadams** [iterative/dvc#10054] opened 2023-10-27 04:48 UTC
# Bug Report

## Description

When using a local relative remote,`dvc fetch -a` results in output along the lines of:
ERROR: unexpected error - failed to load directory ('46', '5a62c55506cd2fa10372c1f9ba4b5e.dir')

The file in question is in the remote. Moreover, `dvc fetch` by itself when on the appropriate branch will actually fetch the file that failed with `dvc fetch -a`.

The issue doesn't seem to happen if the local remote is absolute.

### Reproduce

```
mkdir repo_x
cd repo_x/
git init
dvc init
dvc remote add -d myremote ../remote
dvc config core.autostage true
git add .dvc/config
git commit -m 'init'
cd ../
git clone repo_x repo_y
cd repo_x/
mkdir data
echo 'a' > data/a.txt
dvc add data
git commit -m 'a'
dvc push
cd ../repo_y/
git fetch
git merge origin/main
dvc fetch -a
```
Then the error occurs. Then:
```
dvc fetch
```
runs fine and fetches the offending data.

### Expected

`dvc fetch -a` not to fail here. If `dvc fetch` works on a specific branch, and `dvc fetch -a` is to fetch from all branches, then it should successfully fetch from the specific branch too.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 3.27.0 (pip)
-------------------------
Platform: Python 3.11.1 on macOS-13.6-x86_64-i386-64bit
Subprojects:
	dvc_data = 2.18.1
	dvc_objects = 1.0.1
	dvc_render = 0.6.0
	dvc_task = 0.3.0
	scmrepo = 1.4.0
Supports:
	gdrive (pydrive2 = 1.17.0),
	http (aiohttp = 3.8.6, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.6, aiohttp-retry = 2.8.3)
Config:
	Global: /Users/oadams/Library/Application Support/dvc
	System: /Library/Application Support/dvc
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk1s5s1
Caches: local
Remotes: local
Workspace directory: apfs on /dev/disk1s5s1
Repo: dvc, git
Repo.site_cache_dir: /Library/Caches/dvc/repo/05f2d1d04a316e0ae240c493d4a72d2f
```

**Additional Information (if any):**

I've tried this on main branch on `4a0d56a79` and on the commit tagged with 3.27.0 (`c39ce6157`).

When `fetch -a` we have:

- In the first iteration of the loop (workspace) at line 45 of `dvc/repo/fetch.py` line 52 we have `repo.root_dir` is `'/Users/oadams/code/dev-cookiecutter/y'`. This is correct, and results in path to the remote LocalHashFileDB (`repo.index.data['repo'].storage_map[('data',)].remote.path`) correctly `'/Users/oadams/code/dev-cookiecutter/remote/files/md5'`
- On second iteration of that loop (main branch) `repo.root_dir` becomes '/'. It seems this absolute root gets combined with the relative remote (`../remote`) such that the remote storage LocalHashFileDB (`repo.index.data['repo'].storage_map[('data',)].remote.path`) becomes '/remote/files/md5'. Then this causes the load fails because it's looking in the wrong place.

So it seems the cause is to do with erroneous path construction.

Verbose error output:
```
2023-10-27 15:19:26,588 DEBUG: v3.27.0 (pip), CPython 3.11.1 on macOS-13.6-x86_64-i386-64bit
2023-10-27 15:19:26,588 DEBUG: command: /Users/oadams/.pyenv/versions/cookiecutter/bin/dvc fetch -a --verbose
2023-10-27 15:19:27,054 DEBUG: failed to load ('data',) from storage local (/Users/oadams/code/dev-cookiecutter2/repo_y/.dvc/cache/files/md5) - [Errno 2] No such file or directory: '/Users/oadams/code/dev-cookiecutter2/repo_y/.dvc/cache/files/md5/46/5a62c55506cd2fa10372c1f9ba4b5e.dir'
Traceback (most recent call last):
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/index/index.py", line 552, in _load_from_storage
    _load_from_object_storage(trie, entry, storage)
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/index/index.py", line 488, in _load_from_object_storage
    obj = Tree.load(storage.odb, root_entry.hash_info, hash_name=storage.odb.hash_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/hashfile/tree.py", line 193, in load
    with obj.fs.open(obj.path, "r") as fobj:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_objects/fs/base.py", line 228, in open
    return self.fs.open(path, mode=mode, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_objects/fs/local.py", line 136, in open
    return open(path, mode=mode, encoding=encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/oadams/code/dev-cookiecutter2/repo_y/.dvc/cache/files/md5/46/5a62c55506cd2fa10372c1f9ba4b5e.dir'

2023-10-27 15:19:27,059 DEBUG: failed to load ('data',) from storage local (/remote/files/md5) - [Errno 2] No such file or directory: '/remote/files/md5/46/5a62c55506cd2fa10372c1f9ba4b5e.dir'
Traceback (most recent call last):
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/index/index.py", line 552, in _load_from_storage
    _load_from_object_storage(trie, entry, storage)
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/index/index.py", line 488, in _load_from_object_storage
    obj = Tree.load(storage.odb, root_entry.hash_info, hash_name=storage.odb.hash_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/hashfile/tree.py", line 193, in load
    with obj.fs.open(obj.path, "r") as fobj:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_objects/fs/base.py", line 228, in open
    return self.fs.open(path, mode=mode, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_objects/fs/local.py", line 136, in open
    return open(path, mode=mode, encoding=encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/remote/files/md5/46/5a62c55506cd2fa10372c1f9ba4b5e.dir'

2023-10-27 15:19:27,061 DEBUG: failed to load ('data',) from storage local (/Users/oadams/code/dev-cookiecutter2/repo_y/.dvc/cache/files/md5) - [Errno 2] No such file or directory: '/Users/oadams/code/dev-cookiecutter2/repo_y/.dvc/cache/files/md5/46/5a62c55506cd2fa10372c1f9ba4b5e.dir'
Traceback (most recent call last):
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/index/index.py", line 552, in _load_from_storage
    _load_from_object_storage(trie, entry, storage)
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/index/index.py", line 488, in _load_from_object_storage
    obj = Tree.load(storage.odb, root_entry.hash_info, hash_name=storage.odb.hash_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/hashfile/tree.py", line 193, in load
    with obj.fs.open(obj.path, "r") as fobj:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_objects/fs/base.py", line 228, in open
    return self.fs.open(path, mode=mode, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_objects/fs/local.py", line 136, in open
    return open(path, mode=mode, encoding=encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/oadams/code/dev-cookiecutter2/repo_y/.dvc/cache/files/md5/46/5a62c55506cd2fa10372c1f9ba4b5e.dir'

2023-10-27 15:19:27,062 DEBUG: failed to load ('data',) from storage local (/remote/files/md5) - [Errno 2] No such file or directory: '/remote/files/md5/46/5a62c55506cd2fa10372c1f9ba4b5e.dir'
Traceback (most recent call last):
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/index/index.py", line 552, in _load_from_storage
    _load_from_object_storage(trie, entry, storage)
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/index/index.py", line 488, in _load_from_object_storage
    obj = Tree.load(storage.odb, root_entry.hash_info, hash_name=storage.odb.hash_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/hashfile/tree.py", line 193, in load
    with obj.fs.open(obj.path, "r") as fobj:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_objects/fs/base.py", line 228, in open
    return self.fs.open(path, mode=mode, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_objects/fs/local.py", line 136, in open
    return open(path, mode=mode, encoding=encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/remote/files/md5/46/5a62c55506cd2fa10372c1f9ba4b5e.dir'

2023-10-27 15:19:27,064 DEBUG: failed to load ('data',) from storage local (/Users/oadams/code/dev-cookiecutter2/repo_y/.dvc/cache/files/md5) - [Errno 2] No such file or directory: '/Users/oadams/code/dev-cookiecutter2/repo_y/.dvc/cache/files/md5/46/5a62c55506cd2fa10372c1f9ba4b5e.dir'
Traceback (most recent call last):
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/index/index.py", line 552, in _load_from_storage
    _load_from_object_storage(trie, entry, storage)
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/index/index.py", line 488, in _load_from_object_storage
    obj = Tree.load(storage.odb, root_entry.hash_info, hash_name=storage.odb.hash_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/hashfile/tree.py", line 193, in load
    with obj.fs.open(obj.path, "r") as fobj:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_objects/fs/base.py", line 228, in open
    return self.fs.open(path, mode=mode, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_objects/fs/local.py", line 136, in open
    return open(path, mode=mode, encoding=encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/oadams/code/dev-cookiecutter2/repo_y/.dvc/cache/files/md5/46/5a62c55506cd2fa10372c1f9ba4b5e.dir'

2023-10-27 15:19:27,064 DEBUG: failed to load ('data',) from storage local (/remote/files/md5) - [Errno 2] No such file or directory: '/remote/files/md5/46/5a62c55506cd2fa10372c1f9ba4b5e.dir'
Traceback (most recent call last):
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/index/index.py", line 552, in _load_from_storage
    _load_from_object_storage(trie, entry, storage)
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/index/index.py", line 488, in _load_from_object_storage
    obj = Tree.load(storage.odb, root_entry.hash_info, hash_name=storage.odb.hash_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/hashfile/tree.py", line 193, in load
    with obj.fs.open(obj.path, "r") as fobj:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_objects/fs/base.py", line 228, in open
    return self.fs.open(path, mode=mode, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_objects/fs/local.py", line 136, in open
    return open(path, mode=mode, encoding=encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/remote/files/md5/46/5a62c55506cd2fa10372c1f9ba4b5e.dir'

Collecting                                                                                                         |1.00 [00:00, 56.5entry/s]
2023-10-27 15:19:27,070 DEBUG: failed to load ('46', '5a62c55506cd2fa10372c1f9ba4b5e.dir') from storage local (/remote/files/md5) - [Errno 2] No such file or directory: '/remote/files/md5/46/5a62c55506cd2fa10372c1f9ba4b5e.dir'
Traceback (most recent call last):
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/index/index.py", line 552, in _load_from_storage
    _load_from_object_storage(trie, entry, storage)
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/index/index.py", line 488, in _load_from_object_storage
    obj = Tree.load(storage.odb, root_entry.hash_info, hash_name=storage.odb.hash_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/hashfile/tree.py", line 193, in load
    with obj.fs.open(obj.path, "r") as fobj:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_objects/fs/base.py", line 228, in open
    return self.fs.open(path, mode=mode, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_objects/fs/local.py", line 136, in open
    return open(path, mode=mode, encoding=encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/remote/files/md5/46/5a62c55506cd2fa10372c1f9ba4b5e.dir'

2023-10-27 15:19:27,071 DEBUG: failed to load ('46', '5a62c55506cd2fa10372c1f9ba4b5e.dir') from storage local (/Users/oadams/code/dev-cookiecutter2/repo_y/.dvc/cache/files/md5) - [Errno 2] No such file or directory: '/Users/oadams/code/dev-cookiecutter2/repo_y/.dvc/cache/files/md5/46/5a62c55506cd2fa10372c1f9ba4b5e.dir'
Traceback (most recent call last):
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/index/index.py", line 552, in _load_from_storage
    _load_from_object_storage(trie, entry, storage)
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/index/index.py", line 488, in _load_from_object_storage
    obj = Tree.load(storage.odb, root_entry.hash_info, hash_name=storage.odb.hash_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/hashfile/tree.py", line 193, in load
    with obj.fs.open(obj.path, "r") as fobj:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_objects/fs/base.py", line 228, in open
    return self.fs.open(path, mode=mode, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_objects/fs/local.py", line 136, in open
    return open(path, mode=mode, encoding=encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/oadams/code/dev-cookiecutter2/repo_y/.dvc/cache/files/md5/46/5a62c55506cd2fa10372c1f9ba4b5e.dir'

Fetching
2023-10-27 15:19:27,076 ERROR: unexpected error - failed to load directory ('46', '5a62c55506cd2fa10372c1f9ba4b5e.dir'): [Errno 2] No such file or directory: '/Users/oadams/code/dev-cookiecutter2/repo_y/.dvc/cache/files/md5/46/5a62c55506cd2fa10372c1f9ba4b5e.dir'
Traceback (most recent call last):
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/index/index.py", line 552, in _load_from_storage
    _load_from_object_storage(trie, entry, storage)
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/index/index.py", line 488, in _load_from_object_storage
    obj = Tree.load(storage.odb, root_entry.hash_info, hash_name=storage.odb.hash_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/hashfile/tree.py", line 193, in load
    with obj.fs.open(obj.path, "r") as fobj:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_objects/fs/base.py", line 228, in open
    return self.fs.open(path, mode=mode, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_objects/fs/local.py", line 136, in open
    return open(path, mode=mode, encoding=encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/oadams/code/dev-cookiecutter2/repo_y/.dvc/cache/files/md5/46/5a62c55506cd2fa10372c1f9ba4b5e.dir'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc/cli/__init__.py", line 209, in main
    ret = cmd.do_run()
          ^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc/cli/command.py", line 26, in do_run
    return self.run()
           ^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc/commands/data_sync.py", line 88, in run
    processed_files_count = self.repo.fetch(
                            ^^^^^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc/repo/__init__.py", line 61, in wrapper
    return f(repo, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc/repo/fetch.py", line 164, in fetch
    fetch_transferred, fetch_failed = ifetch(
                                      ^^^^^^^
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/index/fetch.py", line 65, in fetch
    [
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/index/fetch.py", line 65, in <listcomp>
    [
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/index/index.py", line 691, in iteritems
    self._load(key, entry)
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/index/index.py", line 647, in _load
    self.onerror(entry, exc)
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/index/index.py", line 579, in _onerror
    raise exc
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/index/index.py", line 645, in _load
    _load_from_storage(self._trie, entry, self.storage_map[key])
  File "/Users/oadams/.pyenv/versions/3.11.1/envs/cookiecutter/lib/python3.11/site-packages/dvc_data/index/index.py", line 567, in _load_from_storage
    raise DataIndexDirError(f"failed to load directory {entry.key}") from last_exc
dvc_data.index.index.DataIndexDirError: failed to load directory ('46', '5a62c55506cd2fa10372c1f9ba4b5e.dir')

2023-10-27 15:19:27,109 DEBUG: Version info for developers:
DVC version: 3.27.0 (pip)
-------------------------
Platform: Python 3.11.1 on macOS-13.6-x86_64-i386-64bit
Subprojects:
	dvc_data = 2.18.1
	dvc_objects = 1.0.1
	dvc_render = 0.6.0
	dvc_task = 0.3.0
	scmrepo = 1.4.0
Supports:
	gdrive (pydrive2 = 1.17.0),
	http (aiohttp = 3.8.6, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.6, aiohttp-retry = 2.8.3)
Config:
	Global: /Users/oadams/Library/Application Support/dvc
	System: /Library/Application Support/dvc
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: local
Workspace directory: apfs on /dev/disk1s5s1
Repo: dvc, git
Repo.site_cache_dir: /Library/Caches/dvc/repo/160389cdc599f93beb72fd57e54c9bdc

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2023-10-27 15:19:27,111 DEBUG: Analytics is enabled.
2023-10-27 15:19:27,201 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/var/folders/dd/x0xwkv8d3hz86wpl2ld85m600000gn/T/tmp4_uyvlf0']'
2023-10-27 15:19:27,203 DEBUG: Spawned '['daemon', '-q', 'analytics', '/var/folders/dd/x0xwkv8d3hz86wpl2ld85m600000gn/T/tmp4_uyvlf0']'
```

> ``

**Comment by dberenbaum** [comment] 2023-11-06 22:29
@oadams Thanks for the report and sorry for the delayed response! I am able to reproduce on 3.27.0 but not on the latest main, so it looks like this has since been resolved. Closing.

**Closed by dberenbaum** 2023-11-06 22:29 UTC
