### ISSUE TITLE
Install shell autocomplete scripts from the DEB package

### ISSUE THREAD

**Issue by dashohoxha** [iterative/dvc#2374] opened 2019-08-07 09:20 UTC
I installed dvc from the DEB repository (for Debian/Ubuntu). Then I installed the autocomplete scripts manually for bash, like this: 
```bash
sudo wget \
    -O /etc/bash_completion.d/dvc \
    https://raw.githubusercontent.com/iterative/dvc/master/scripts/completion/dvc.bash
```

I would expect them to be installed automatically by the deb package, so that this manual step is not necessary.

**Note:** I could not find the code that builds the deb package, so I am reporting this here.

**Comment by pared** [comment] 2019-08-07 09:37
Hi @dashohoxha! Thanks for reporting this, I believe it belongs to this repository, so I transferred it.

**Comment by efiop** [comment] 2019-08-07 13:58
Closing as a duplicate of https://github.com/iterative/dvc/issues/2181

**Closed by efiop** 2019-08-07 13:58 UTC
