### ISSUE TITLE
dvc repro don't check cmd have not changed

### ISSUE THREAD

**Issue by MatthieuBizien** [iterative/dvc#3947] opened 2020-06-03 12:47 UTC
## Bug Report

When modifying cmd in dvc.yaml, the stage is not re-run when I apply dvc repro.

Minimal example:
```
dvc run -d a -o b -n stage_b "echo 1 > b"
sed -i "s/1/2/g" dvc.yaml
dvc repro
cat b  # is 1, should be 2
```

Full log : https://pastebin.com/A6dzDUxY

With version of git master: https://pastebin.com/fS8xhsMU

### Please provide information about your setup

```console
$ dvc version
DVC version: 1.0.0a6
Python version: 3.6.7
Platform: Darwin-18.7.0-x86_64-i386-64bit
Binary: False
Package: pip
Supported remotes: azure, gdrive, gs, hdfs, http, https, s3, ssh, oss
Cache: reflink - supported, hardlink - supported, symlink - supported
Repo: dvc, git
```

**Additional Information (if any):**

It seems that the issue was not present in 0.94.0 https://pastebin.com/ZFLt54tc

**Comment by skshetry** [comment] 2020-06-03 13:11
Hi @MatthieuBizien. This should be fixed in [v1.0.0a7](https://github.com/iterative/dvc/releases/tag/1.0.0a7). Can you upgrade and give it a try?
```console
$ pip install -U --pre dvc
```

Thanks. I am marking this as a duplicate of https://github.com/iterative/dvc/issues/3918 (fixed by #3922).

**Comment by skshetry** [comment] 2020-06-03 13:12
Duplicate of https://github.com/iterative/dvc/issues/3918

**Closed** 2020-06-03 21:14 UTC
Labels: bug

**Comment by MatthieuBizien** [comment] 2020-06-04 07:58
Great, thanks!
