### ISSUE TITLE
SSH password authentication not working for dvc push

### ISSUE THREAD

**Issue by thomasryck** [iterative/dvc#2305] opened 2019-07-22 10:34 UTC
DVC version: 0.52.1
Platform and method of installation: Windows 10 + pip installed

I am using remote cache and storage (ssh) to version folders of image. However when I try to 

`dvc push`

 I have a strange comportment. Indeed, I have been asked to enter my ssh password once but it does check the local cache first and later it asked 4 times in my password if I enter it once it does not work and if I press enter 4 times I get the following error.

I did not have this issue for `dvc add`

![image](https://user-images.githubusercontent.com/37658138/61626059-83e11800-ac7c-11e9-8dfe-9ac93d9bdf43.png)

**Comment by mroutis** [comment] 2019-07-22 16:42
@efiop , this issue is slightly different than the one in #2310 

This is specifically related to not `push`ing anything, even if the password was entered. I assume that the problem is due to the long `TIMEOUT` to establish a connection to the SSH server.
There might be any error on the URL or configuration and it is waiting for the time out (maybe because it can't reach the SSH server) instead of closing the connection right away with a `Permission denied`.

The other issue ( #2310 ) is about the interface (asking for password multiple times -- once for each worker)

**Comment by thomasryck** [comment] 2019-07-22 17:28
@mroutis So why I would have an error when using a passphrase and why it would work without any passphrase ?

**Comment by mroutis** [comment] 2019-07-22 17:36
:eyes: ! @thomasryck , my bad! I didn't notice the `Authentication Failed` error.
I thought that it hung for more than 10 minutes without error :thinking:

**Comment by mroutis** [comment] 2019-07-22 17:38
When I tried to reproduce it I was able to make a successful connection with the prompt (see #2310)

**Comment by thomasryck** [comment] 2019-07-22 17:45
I think that there are multiple issues under the hood. The authentication issue is probably on my side  but it is hard to debug with the other problems.

**Comment by thomasryck** [comment] 2019-07-22 19:52
To be precise when it hang for a long time, some time when I keyboard interrupt sometimes I get `Keyboard Interrupt` and sometimes I get `Authentication failed`

**Comment by Suor** [comment] 2019-07-23 09:27
If we have any other error here besides several password prompts then it effectively masked. So I will go for that first.

**Closed** 2019-07-23 16:54 UTC
Labels: bug, p0-critical

**Comment by mroutis** [comment] 2019-07-23 20:13
@thomasryck , does this solved your issue?

**Comment by thomasryck** [comment] 2019-07-24 07:02
It works at least for the password authentication, I did not try yet with a key and a passphrase.
