### ISSUE TITLE
`data status`: produces non-serializable JSON string on Windows

### ISSUE THREAD

**Issue by mattseddon** [iterative/dvc#9409] opened 2023-05-05 10:19 UTC
# Bug Report

## Description

A user is having issues with the extension (https://github.com/iterative/vscode-dvc/issues/3802) whilst working through possible causes I discovered that his `data status --json` output cannot be serialized back into JSON from the provided string. I believe that the path separators need extra escape characters. I.e '\\\\\\\\' should be provided instead of '\\\\'.

See https://github.com/iterative/vscode-dvc/issues/3802#issuecomment-1535879581 for user's the output.

### Reproduce

Run `data status --json` on a Windows machine

### Expected

Output can be serialized back into JSON. 

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```
User reported the issue on `2.55.0`.

**Additional Information (if any):**

**Comment by shcheklein** [comment] 2023-05-05 21:09
The output seems right to me. I also can't reproduce it on Windows. Closing this for now. Looking more into the original ticket. @mattseddon let me know if you were able to reproduce this or why it's not a valid JSON and feel free to reopen it if needed.

**Closed by shcheklein** 2023-05-05 21:09 UTC
Labels: p1-important, product
