### ISSUE TITLE
Track annotations with git and images with dvc from same folder

### ISSUE THREAD

**Issue by aurelm95** [iterative/dvc#8598] opened 2022-11-21 16:11 UTC
Suppose my dataset has the following schema:

```
dataset/
├─ annotation1.txt
├─ img1.jpg
├─ annotation2.txt
├─ img2.jpg
.
.
.
```

On one hand, I would like to track my `.txt` annotations files with git so I can see their updates. On the other hand, I would like to track images with dvc. Furthermore, I would like to track all images at once, I mean, without a `.dvc`file for each image inside the `dataset/` folder.

I am new in dvc but I think this is not possible and it would be a good feature for some people.

What do you think?

**Comment by daavoo** [comment] 2022-11-21 16:51
Hi @aurelm95 , I believe this is a duplicate of https://github.com/iterative/dvc/issues/8574 . Closing as duplicate but don't hesitate on commenting there

**Closed by daavoo** 2022-11-21 16:51 UTC
