### ISSUE TITLE
diff: support targets

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/dvc#3388] opened 2020-02-23 11:49 UTC
```sh
dvc diff -t models HEAD^ HEAD
```
```sh
ERROR: unrecognized arguments: -t HEAD
```

**Please provide information about your setup**
Ubuntu 18.04
Dvc 0.84.0

**Comment by dmpetrov** [comment] 2020-02-24 09:26
It is a good feature idea but probably not a critical one.

@DavidGOrtega I'd appreciate it if you provide more context to understand how critical the issue is?

**Comment by DavidGOrtega** [comment] 2020-02-24 13:48
@dmpetrov I tried it according to the docs and I found that issue. For ci is not an issue aside of having more features.

**Comment by jorgeorpinel** [comment] 2020-02-24 19:35
This feature was removed in #3229. Do we remember why? 🙂 Cc @efiop

**Comment by dmpetrov** [comment] 2020-02-25 02:37
@jorgeorpinel as far as I remember it was removed for two reasons: it was not a priority and it seems fine not to have it because `git diff` does not support any targets.

Is there a good use case when we need targets (except backward compatibility)? It is important to understand the priority.

**Comment by jorgeorpinel** [comment] 2020-02-25 02:52
Ohhh I see. I think this issue is mainly about a discrepancy between `dvc diff` and its cmd ref in https://dvc.org/doc/command-reference/diff so we can probably transfer it to iterative/dvc.org ?

In fact I thought it was addressed in iterative/dvc.org/pull/953 but I see not. Lmk if you guys agree and I'll transfer it so it's addressed ASAP.

**Comment by shcheklein** [comment] 2020-02-25 03:03
@dmpetrov 

> because git diff does not support any targets

Looks like it does.

`git diff HEAD^ -- dvc/api.py`

returns:

```diff
diff --git a/dvc/api.py b/dvc/api.py
index def9e8cf..d1312baa 100644
--- a/dvc/api.py
+++ b/dvc/api.py
@@ -18,10 +18,10 @@ class UrlNotDvcRepoError(DvcException):


 def get_url(path, repo=None, rev=None, remote=None):
-    """
-    Returns the full URL to the data artifact specified by its `path` in a
-    `repo`.
-    NOTE: There is no guarantee that the file actually exists in that location.
+    """Returns URL to the storage location of a data artifact tracked
+    by DVC, specified by its path in a repo.
+
+    NOTE: There's no guarantee that the file actually exists in that location.
```

https://git-scm.com/docs/git-diff

**Comment by shcheklein** [comment] 2020-02-25 03:04
@jorgeorpinel 

> In fact I thought it was addressed in iterative/dvc.org/pull/953 but I see not. Lmk if you guys agree and I'll transfer it so it's addressed ASAP.

not sure I understand this, could you elaborate please?

**Comment by jorgeorpinel** [comment] 2020-02-25 05:19
Yeah, `git diff` supports targets indeed.

@shcheklein I was confused. The `--target` options and `-t` examples were indeed removed in that PR! I guess David opened this issue before that PR was merged.

So should we close this issue? The docs are up to date now.

**Comment by shcheklein** [comment] 2020-02-25 05:21
Let's keep it. This is a pretty relevant feature. Especially considering that there was some confusion around `git diff`.

**Comment by jorgeorpinel** [comment] 2020-02-25 05:36
OK

> Looks like (`dvc diff`) does (support targets).
> `git diff HEAD^ -- dvc/api.py`

You don't even need `--`, so if we're re-implementing this, maybe just make it an implicit (and optional) cmd param like in fetch/pull/push.

**Comment by sandeepmistry** [comment] 2020-11-23 01:56
I've started a draft pull request on this if anyone would like to give early feedback the changes: https://github.com/iterative/dvc/pull/4938

**Closed** 2020-12-15 14:19 UTC
Labels: feature request, p2-medium, product
