### ISSUE TITLE
dvc pull message

### ISSUE THREAD

**Issue by leehanchung** [iterative/dvc#2838] opened 2019-11-22 22:57 UTC
Future request: dvc pull message.

Thank you for the tool. This section [in the tutorial](https://dvc.org/doc/get-started/retrieve-data) talked about `dvc pull`. Ran the command on windows and I found the only thing that dvc outputs is `Everything is up to date` after the pull.  

I find that message confusing. It does not say which file it pulled from remote or how big of a difference it has. For git, it lists the files it pulled and the respective differences expressed with the number of `+`.

**Comment by jorgeorpinel** [comment] 2019-11-22 23:11
Example provided by Hanchung:

```console
(base) PS B:\user\example-get-started> ls .\data\

    Directory: B:\user\example-get-started\data

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       11/22/2019  12:52 PM             11 .gitignore
-a----       11/22/2019  12:52 PM            155 data.xml.dvc

(base) PS B:\user\example-get-started> dvc pull
Everything is up to date.
(base) PS B:\user\example-get-started> ls data

    Directory: B:\user\example-get-started\data
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       11/22/2019  12:52 PM             11 .gitignore
-a----       11/22/2019   2:52 PM       37916850 data.xml
-a----       11/22/2019  12:52 PM            155 data.xml.dvc
```
> basically it doesnt tell what is pulled/changed at the moment

(Windows Powershell, I think.)

**Comment by shcheklein** [comment] 2019-11-22 23:16
@jorgeorpinel I think it's a duplicate of https://github.com/iterative/dvc/issues/1838 and https://github.com/iterative/dvc/issues/2667

**Comment by jorgeorpinel** [comment] 2019-11-22 23:32
A duplicate of duplicate issues haha. OK I'll close it in favor of the older one, #1838. I'll copy my previous comment over there.

**Closed by jorgeorpinel** 2019-11-22 23:32 UTC
Labels: triage
