### ISSUE TITLE
ssh: ask for password once

### ISSUE THREAD

**Issue by mroutis** [iterative/dvc#2310] opened 2019-07-22 16:22 UTC
**Version**:
```
DVC version: 0.52.1+1e9f1d
Python version: 3.7.3
Platform: Linux-5.2.1-arch1-1-ARCH-x86_64-with-arch
Binary: False
Cache: reflink - True, hardlink - True, symlink - True
Filesystem type (cache directory): ('xfs', '/dev/mapper/vg-root')
Filesystem type (workspace): ('xfs', '/dev/mapper/vg-root')
```

**Reproduction script**:
```bash
dvc init --no-scm --force
dvc remote add ssh ssh://dvc-storage/home/mroutis/cache  # Replace it with your URL
dvc remote modify ssh ask_password true

# Remove any previous identity from the key-agent
ssh-add -D

mkdir data
for x in {1..10000}; do echo $x > "data/${x}.txt"; done
dvc add data
dvc push -r ssh
```

**Current**:

Every worker asks for password, expecting the user to enter 4 times the password.
In this case, I only entered it once and it stopped at 25% (the first worker).
```
Collecting information from remote cache...
Enter a private key passphrase or a password for host 'xxx' port '22' user 'mroutis':
Enter a private key passphrase or a password for host 'xxx' port '22' user 'mroutis':
Enter a private key passphrase or a password for host 'xxx' port '22' user 'mroutis':
Enter a private key passphrase or a password for host 'xxx' port '22' user 'mroutis':

[#######                       ] 25% /home/mroutis/cache/64/cdd912368129628445802d965ad42a
````

**Expected**:
```
Collecting information from remote cache...
Enter a private key passphrase or a password for host 'xxx' port '22' user 'mroutis':

[#######                       ] 100%
```

**Comment by efiop** [comment] 2019-07-22 16:31
Duplicate of https://github.com/iterative/dvc/issues/2305

**Closed by efiop** 2019-07-22 16:31 UTC

**Comment by Suor** [comment] 2019-07-23 09:33
@mroutis thanks for script)
