### ISSUE TITLE
exp list/show: --rev HEAD shows nothing, but using commit SHA of HEAD works

### ISSUE THREAD

**Issue by aschuh-hf** [iterative/dvc#9744] opened 2023-07-18 17:27 UTC
# Bug Report

## Description

Command `dvc exp list [--rev HEAD]` does not show any experiments, but when using the explicit Git commit SHA as `--rev` argument, it displays the expected list of experiments. Same for `dvc exp show`. This could be related to #9260.

My HEAD commit also has refs refs/exps/exec/EXEC_HEAD and refs/exps/apply/ORIG_HEAD as I have "rebased" the experiments onto the current `main` HEAD commit using `dvc exp apply` followed by `dvc exp save`.

### Expected

After having run (`dvc exp run`) or saved (`dvc exp save`) experiments, I would expect `dvc exp list` and `dvc exp show` to display those experiments without any `--rev` argument or when given `--rev HEAD` instead of `--rev $(git rev-parse HEAD)`.

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 3.5.1 (conda)
--------------------------
Platform: Python 3.10.6 on Linux-3.10.0-1127.8.2.el7.x86_64-x86_64-with-glibc2.17
Subprojects:
        dvc_data = 2.5.0
        dvc_objects = 0.23.0
        dvc_render = 0.5.3
        dvc_task = 0.3.0
        scmrepo = 1.0.4
Supports:
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        s3 (s3fs = 2023.6.0, boto3 = 1.26.76)
Config:
        Global: /home/aschuh/.config/dvc
        System: /etc/xdg/dvc
Cache types: hardlink, symlink
Cache directory: xfs on /dev/sda1
Caches: local
Remotes: s3, s3
Workspace directory: xfs on /dev/sda1
Repo: dvc (subdir), git
Repo.site_cache_dir: /var/tmp/dvc/repo/764b1d03f8b416f032df6c50c3809e7f
```

**Additional Information (if any):**

**Comment by pmrowla** [comment] 2023-07-20 01:02
Closing as duplicate of #9260

**Closed by pmrowla** 2023-07-20 01:02 UTC
