### ISSUE TITLE
no-scm and docker production builds

### ISSUE THREAD

**Issue by argideritzalpea** [iterative/dvc#3574] opened 2020-04-01 18:13 UTC
I would like to use .dvc to pull files in a production Docker container without uploading the entire .git folder that is associated with it to keep the size of the container down. The .dvc folder is copied into a folder in the image., but the .git folder is very big. I understand that there is the `-no-scm` option upon dvc initialization to remove git tracking, but the dvc repo in question is already initialized for use with a git repository, and is simply mounted in the docker container upon container initialization. Is there any way use dvc to download the correct files at their respective paths without copying the full .git folder into the container?

**Comment by shcheklein** [comment] 2020-04-01 18:48
@argideritzalpea hi! can you tru to run `dvc config core.no_scm true` in the Docker image (entry point, or image create)? This way you don't need to copy the whole `.git` directory.

**Comment by shcheklein** [comment] 2020-04-01 19:08
@argideritzalpea another good option that @dmpetrov reminded is to use `git clone --depth 1` instead of copying your files with `cp`.

Could you clarify your use case a little bit, btw? Do you run `dvc pull` in the Docker image when you run it? Do you need all data and code files (DVC tracked and Git tracked)?

**Comment by Steiniche** [comment] 2020-04-06 11:42
We have the same use case.
What we do is copy all .dvc files such that we can call dvc pull when running training and have all data files available without "baking" them into the container which would be an anti-pattern.
We copy the needed code files into the container on build.

It used to work with
`dvc init --no-scm` in version `0.82.9` but in `0.92.1` we start to see errors:
```
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
```
The fix is do do what the error says and silence the error with
`ENV GIT_PYTHON_REFRESH=quiet`

**Comment by shcheklein** [comment] 2020-04-06 16:59
@Steiniche hi! what command did produce this `Bad git executable` error? could you run it with `-v` and share the output, please?

**Comment by efiop** [comment] 2020-04-07 10:52
@Steiniche Hi! Could you try setting `dvc config core.no_scm true` when you copy your .dvc files over? That should fix it. The error you are getting is from missing or bad git executable that dvc tries to use (it won't with `no_scm true`).

**Comment by Steiniche** [comment] 2020-04-13 11:27
@efiop I need to understand this a little better to be able to test it.
Why is there a difference between `dvc init --no-scm` and the configuration `core.no_scm true`?
Should these not be the exact same thing or are there some use cases I am not seeing?

**Comment by efiop** [comment] 2020-04-13 19:36
@Steiniche There is no difference right now, `dvc init --no-scm` will set that config option. We've changed the behaviour a few versions back though, so it wasn't like that before.

**Comment by Steiniche** [comment] 2020-04-14 19:30
@efiop thanks for clearing that up.
I initiate the repo with `dvc init --no-scm` so I guess it is already tested.
Still need `ENV GIT_PYTHON_REFRESH=quiet` for it to work.

I dont know if this is the intended behavior but it seems a little strange to me when the repo is initialized with `--no-scm`

**Comment by shcheklein** [comment] 2020-04-14 20:38
@Steiniche 

> I initiate the repo with `dvc init --no-scm` so I guess it is already tested.

it makes total sense! what changed is the way this command works. The difference is that after one the recent releases `dvc init --no-scm` saves a flag into `.dvc/config` (`core.no_scm = True`). And DVC rely on this explicit flag to determine either it should use Git or not. Before it was pretty much implicit - DVC was trying to find `.git` in the repo to make that decision.

The bottom line here probably is:

if you initialized your repo before that release (that happened really ~a month ago) you need to run dvc config `dvc config core.no_scm true` to update the config and make new DVC version not complain about the `git` command.

**Comment by efiop** [comment] 2020-06-23 00:02
Closing for now, since it is our expected behaviour these days.

**Closed by efiop** 2020-06-23 00:02 UTC
Labels: awaiting response
