### ISSUE TITLE
DVCFileSystem.get: running it on a folder multiple times results in nested folder structure while Repo.open().dvcfs.get does not

### ISSUE THREAD

**Issue by Lhenzo** [iterative/dvc#10182] opened 2023-12-18 14:11 UTC
# Bug Report

## Description

Repo A have dvc data stored with this structure:

```bash
data/
├── mydata-dvc
│   └── repo_a
│       └── mytracked_data.dvc
```

When calling in Repo B `DVCFileSystem(repo_a_url, rev="main").get(str(data/mydata-dvc/repo_a/mytracked_data), str(root_path/data/my-data-dvc/repo_b/my_tracked_data), recursive=True)`, I get this folder structure:

```bash
data/
├── mydata-dvc
│   └── repo_b
│       └── mytracked_data
│           └── somefile.json
```

which is fine. But running this command again returns:

```bash
data/
├── mydata-dvc
│   └── repo_b
│       └── mytracked_data
│           └── somefile.json
│           └── mytracked_data
│               └── somefile.json
```

which is not an expected behavior

### Reproduce

1. in repo A, set a remote storage "anyname"
2. in repo A, `dvc add anyfile`
3. in repo A, `dvc commit -m "added anyfile"` and push
4. in repo B, set the remote to be the same as repo A, "anyname"
5. in repo B, try retrieving the file with the get function

### Expected

```bash
data/
├── mydata-dvc
│   └── repo_b
│       └── mytracked_data
│           └── somefile.json
```

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.34.3 (pip)
---------------------------------
Platform: Python 3.10.6 on Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Subprojects:
        dvc_data = 0.28.0
        dvc_objects = 0.14.0
        dvc_render = 0.0.14
        dvc_task = 0.1.6
        dvclive = 2.0.2
        scmrepo = 0.1.3
Supports:
        gs (gcsfs = 2023.10.0),
        http (aiohttp = 3.9.1, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.9.1, aiohttp-retry = 2.8.3)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdc
Caches: local
Remotes: gs
Workspace directory: ext4 on /dev/sdc
Repo: dvc, git
```

**Additional Information (if any):**
Yes, we are pretty behind the latest dvc release but here the issue might be lying inside fsspec which is always bumped (`fsspec`                                is `2023.10.0`). This issue was not happening before this bump of `fsspec`.

In fact, from what I understood so far, recent bump of fsspec induced by other packages from `2023.6.0` to `2023.10.0` changed the behavior of a `get` function.

Indeed, inside the get, you now have `exists` that is correctly turning to True if it sees the folder already downloaded via the get func. 
But instead of saying "I have the data cause the folder exists" it says :

```docstring
    exists: bool (optional)
        For a str destination, it is already exists (and is a dir), files should
        end up inside.
```

Hence the multiple level of downloading

It does so because `_DVCFileSystem(AbstractFileSystem)` so it inherits whatever is inside `fsspec/spec.py`

Also, running:

```python
from dvc.repo import Repo
with Repo.open(repo_a_url, rev="main") as repo:
    repo.dvcfs.get(str(data/mydata-dvc/repo_a/mytracked_data), str(root_path/data/my-data-dvc/repo_b/my_tracked_data), recursive=True)
```

does not duplicate the folder structure and understands it's already there

**Comment by pmrowla** [comment] 2024-01-09 13:58
As you noted, this is expected behavior as per the change made in the fsspec `fs.get()` API. `dvc.api.DVCFilesystem` is strictly compatible with fsspec's API, and when you use `dvc.api.DVCFilesystem.get()` it calls fsspec's `AbstractFilesystem.get()` implementation.

The reason you get different behavior when using the internal DVC `Repo.dvcfs.get()` is that the internal `Repo.dvcfs` is not a pure fsspec filesystem - it's an instance of a DVC wrapper for fsspec filesystems and it has an overridden `get()` implementation with some DVC specific behavior changes (that is not strictly compliant with fsspec's implementation).

If this is an issue for you, your options would be to either use the internal DVC `Repo.dvcfs`, or to pin fsspec to a version prior to their API change

**Comment by pmrowla** [comment] 2024-01-09 13:58
Closing as expected behavior

**Closed by pmrowla** 2024-01-09 13:58 UTC
Labels: A: api, A: data-sync, A: get
