### ISSUE TITLE
dvc add moves actual data into .dvc/cache after dvc cache configure as symlink

### ISSUE THREAD

**Issue by GBJim** [iterative/dvc#2368] opened 2019-08-05 03:42 UTC
Hi all:

> DVC version is 0.54.0
> Ubuntu 18.04

The background is I have two disks, an SSD(code) and an HDD(data) disk.
I want to use DVC to track data on HDD disk without duplicates data in my SSD.
What I did is the following:
```
dvc config cache.type symlink
dvc add /HDD/data

```
What I expected is DVC create symlinks in my .dvc/cache. But what happened is DVC moves all the data into my .dvc/cache directory and creates the symlink in my HDD instead.
I also use the df command to inspect the disk storage changes. It also proves this.

**Comment by efiop** [comment] 2019-08-05 11:08
Hi @GBJim !

This is the intended behaviour. Cache should _store_ the data, because it will need it to checkout your workspace file if you delete it. Maybe you don't need that file to be cached at all? If so, you could simply specify it as a dependency in your next `dvc run` stage and dvc will detect changes in it, but won't cache it and won't be able to reconstruct older version of it or create it if it is removed.

**Comment by shcheklein** [comment] 2019-08-05 15:41
Closing as intended behavior. More context here: https://discordapp.com/channels/485586884165107732/485596304961962003/607776080811655184

**Closed by shcheklein** 2019-08-05 15:41 UTC
Labels: question
