### ISSUE TITLE
Support declaring environment variables in DVC file

### ISSUE THREAD

**Issue by robogeek** [iterative/dvc#2042] opened 2019-05-22 22:54 UTC
Obviously some command-line tool configuration is set using environment variables.  DVC does not support setting environment variables in a DVC file.  Neither [DVC file reference](https://dvc.org/doc/user-guide/dvc-file-format) nor [dvc run command reference](https://dvc.org/doc/commands-reference/run) show anything about setting an environment variable.

As to how it should be visible to the users:

* `dvc run -e VARIABLE=value` -- support setting this option multiple times
* In the top level of a DVC file have an `env` tag, like so:

```yaml
cmd: echo This is a command
env:
    - VARIABLE_NAME=value
    - VARIABLE_NAME2=value
    - VARIABLE_NAME3=value
```

OR

```yaml
cmd: echo This is a command
env:
    VARIABLE_NAME: value
    VARIABLE_NAME2: value
    VARIABLE_NAME3: value
```

For comparison, this is exactly how environment variables are defined in a Docker Compose file: https://docs.docker.com/compose/compose-file/#environment

**Comment by efiop** [comment] 2019-05-22 22:56
Great idea @robogeek ! We've actually been discussing something like this with @mroutis and @pared . Along with dvc being able to resolve things like `$(VARIABLE_NAME)` in commands and paths, it should get us covered for the parametrization feature as well. :slightly_smiling_face:

**Comment by shcheklein** [comment] 2019-05-22 23:00
might be a duplicate of https://github.com/iterative/dvc/issues/1416 to some extent, there was a discussion about introducing `-e`

**Comment by efiop** [comment] 2019-05-22 23:02
@shcheklein Indeed, closing in favor of that.

**Comment by shcheklein** [comment] 2019-05-22 23:03
@robogeek please, give a vote to that initial ticket. And thanks for the feedback :)

**Closed by efiop** 2019-05-22 23:02 UTC
Labels: feature request, p2-medium
