### ISSUE TITLE
dvc pipeline issues error

### ISSUE THREAD

**Issue by andrethrill** [iterative/dvc#1174] opened 2018-09-28 15:00 UTC
```
$ dvc --version
0.19.2
```

Hi!

I'm trying to execute `dvc pipeline show --ascii some.dvc` but I get the following error:

`Error: Unexpected error: Canvas cols/lines must be in range [1..1000]`

I don't execute this command much often, but I remember it was working on my machine a couple of weeks ago. So maybe this is a bug introduced in the more recent versions?

Thanks,
André

**Comment by efiop** [comment] 2018-09-28 15:11
Hi @andrethrill !

I suspect your pipeline is so wide that ascii canvas has ran out of horizontal space :slightly_frowning_face: Could you please try running the following commands and show us the resulting image?

```
$ dvc pipeline show --dot g.dot some.dvc
$ dot g.dot -Tpng -o img.png
```

P.S. Big thanks to @pared for recently submitting this extremely useful `--dot` feature!

Thanks,
Ruslan

**Comment by efiop** [comment] 2018-09-28 15:14
EDIT: it ran out of _vertical_ space, hence the pipeline is so long. This is easily fixable, I am preparing a patch right now. Still, it would be great if you could show the us the img.png so I can confirm this.

**Comment by efiop** [comment] 2018-09-29 20:06
Fixed by https://github.com/iterative/dvc/pull/1175/commits/f4fc3f47e4bda6a29f1d84699962f5761afa7cc5 . Preparing to release 0.19.5 right now. Should be ready in a few hours.

**Closed by efiop** 2018-09-29 20:06 UTC
Labels: bug

**Comment by efiop** [comment] 2018-09-29 20:59
0.19.5 is out. Please consider upgrading.

Thanks,
Ruslan

**Comment by andrethrill** [comment] 2018-10-01 08:05
Hi @efiop ,

Thanks for the great support. I've updated DVC and the error is gone (although it's not really readable because of the pipeline size...

Anyway, just for reference, here is the output of your `dot` command above (Ihad to change some names):

![img](https://user-images.githubusercontent.com/25300892/46276697-d835d280-c558-11e8-81e4-c0459b51da7b.png)


I guess the issue was horizontal space rather than vertical :)

**Comment by efiop** [comment] 2018-10-01 08:35
Hi @andrethrill !

Thank you so much for sharing the image of your graph! It really helps to get a better perspective on what is going on. Looks like it was indeed a horizontal space :slightly_frowning_face: It should still be possible to view it in terminal if it supports horizontal scrolling instead of breaking the lines, but it is more of a hack, since not all terminals do that :slightly_frowning_face: Maybe this is the point where CLI viewer scope ends, but I will try to give it another thought to see if there are any automatic folding/compacting technics we could use to provide a distraction-less CLI experience. E.g. first idea that comes to mind is to use Ncurses to provide vertical and horizontal scrolling. Created #1177 to track the progress on it.

Thanks,
Ruslan

**Comment by efiop** [comment] 2018-10-09 18:16
Hi @andrethrill !

I'm releasing 0.19.8 right now(ETA is 1 hour), which has support for horizontal and vertical scrolling of graphs, which makes it possible to view big graphs in any terminal. Could you please give it a try on your project and tell us if that works well for you or not?

Thanks,
Ruslan

**Comment by efiop** [comment] 2018-10-09 18:49
0.19.8 is out. Please feel free to upgrade.

**Comment by andrethrill** [comment] 2018-10-11 17:53
Hi @efiop!

I had the chance to try it now! It is working fine.

This may be just my ignorance: do you know if there is other way for scrolling beside using the direction keys? It just moves one char at the time which makes it painful to navigate through the entire dag.

**Comment by efiop** [comment] 2018-10-11 17:59
Hi @andrethrill !

So sorry, I totally forgot to add a help line at the bottom of the screen to note that you can use such keys to navigate:

* Arrows - move one line/column up/down/right/left;
* Page Up/Down - move one screen up/down;
* a/w/s/d keys - move one line/column left/up/down/right;
* A/W/S/D keys(so SHIFT + a/w/s/d) - move one screen left/up/down/right;

Created https://github.com/iterative/dvc/issues/1208 to track the progress on that. Will send a patch ASAP and release 0.19.10.

Thanks,
Ruslan

**Comment by andrethrill** [comment] 2018-10-11 18:06
@efiop those shortcuts help a lot indeed! Thanks.

Personally I would like to have something in between 1 line/col and 1 screen. Like move, say 10 or 20 line/columns (not sure about the exact step size without trying it) at a time. Do you think that would make sense to support that from your side?

**Comment by efiop** [comment] 2018-10-11 18:20
Sure! I totally agree that it would be great to have something in between those two. I thought about making pg dn/up shift for something like 50% of the screen size, but moving 1 full screen size seems pretty useful  as well so I'm not sure it is worth replacing. How about adding yet another set of keys for 25% screen navigation? Something like h,j,k,l(e.g. like in vim :))? Created https://github.com/iterative/dvc/issues/1209 for that.

Thanks,
Ruslan

**Comment by efiop** [comment] 2018-10-11 18:22
Actually, we can utilize mouse movements if that is something that would be comfortable. What do you think @andrethrill ?

**Comment by andrethrill** [comment] 2018-10-11 18:38
@efiop well having the option to do it, is usually better than not having it :)

The 25% navigation option would be already awesome! I think the mouse movements option although not essential, depending on how much dev effort it requires,  would be great addition.

**Comment by efiop** [comment] 2018-10-11 18:43
Thank you for the feedback! I will look into it shortly.
