### ISSUE TITLE
dvc: QA local/nfs/cifs/overlay/etc

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#5562] opened 2021-03-07 18:40 UTC
When working with local repos, dvc uses a lot of `exists()` and `stat()` calls, which is fine with normal filesystems, but could be extremely slow with filesystems like nfs/cifs/etc (e.g. `stat()` can be 100x slower). We should look into conserving such calls, similar to what we do with remotes, where we know that an api call to s3/gdrive/etc is pretty slow, so we try to do as little calls as possible.

* https://discord.com/channels/485586884165107732/728693131557732403/818168922393673738

Another issue with nfs/cifs/overlay is problems with sqlite database (e.g. freezeing locks) that we use for local optimization https://github.com/iterative/dvc/issues/4420 . Dvc itself is also often affected by it, which is why we provide an option to use `flufl.lock` as repo lock instead of flock-based lock. For sqlite it is not an option, so a solution might be to place it somewhere on a normal filesystem (e.g. /tmp is usually fine).

**Comment by jorgeorpinel** [comment] 2021-03-10 20:04
Idk if this is the right issue or if we need another one but users are reporting DVC 2.0 to be very slow with basic operations. Sounds like something to prioritize perhaps?

Also @dberenbaum @efiop @shcheklein WDYT about establishing some non-functional requirements such as basic operation speeds and designing some way to test them at least for major and minor releases (no patches)? Thanks

> Sorry, that should definitely be a separate issue.

**Comment by efiop** [comment] 2021-03-10 21:57
@jorgeorpinel Just for the record: Both links are not related to this issue.

> Also @dberenbaum @efiop @shcheklein WDYT about establishing some non-functional requirements such as basic operation speeds and designing some way to test them at least for major and minor releases (no patches)? Thanks

We have dvc-bench that tests scenarios end-to-end, we are filling it with stuff from time to time.

**Comment by brbarkley** [comment] 2021-03-16 22:36
Looking forward to this feature...

https://discord.com/channels/485586884165107732/563406153334128681/821510730565025823

**Comment by brbarkley** [comment] 2021-05-19 16:18
Any update on this issue? I see it's been delayed a few times.

**Comment by efiop** [comment] 2021-05-19 16:24
Hey @brbarkley , thanks for the interest! We are currently actively working on improving the internals in order for them to accommodate the optimizations that will be the result of this QA. So far ETA for the active phase of this ticket is around the beginning of June.

**Comment by shcheklein** [comment] 2021-06-03 21:15
For the record, from Discord:

> We have a shared DVC cache on a NAS (NFS mount). We’re running into a problem where DVC operations like checkout, commit, etc. are taking a very long time (in some cases days), seemingly due to hashing. I remember reading in some ticket that DVC cache ops are not optimized for network mounts. What are your current plans regarding this situation?
DVC cache is not feasible to store outside of NAS due to its size.

**Comment by jmblackmer** [comment] 2021-06-07 14:02
@efiop Do you have an updated ETA? I was having another issue [described here](https://discuss.dvc.org/t/error-with-dvc-import/755/4) that turned into [this issue](https://github.com/iterative/dvc/issues/4420) after upgrading to 2.3.0 on Friday. My team is doing a large amount of restructuring of storage for our projects in 2 weeks and I'd like to have a plan or workaround when we start. Is it likely that a version of DVC that works in this type of environment will be released in that time frame?

**Comment by efiop** [comment] 2021-06-09 09:37
Hi @jmblackmer . Thank you for your interest! As you've noticed, thanks to @agurtovoy we have #6111 :pray: that solves those particular issues. I can't give an ETA on it yet, as there are a few questions that we need to discuss there first. Just to make it clear, #6111 solves the issues, but we just want to make sure that we are providing the most seamless solution or have a clear plan to improve it in the future.

**Comment by ZhengRui** [comment] 2021-07-06 13:55
Hi @efiop , thanks for the great tool you guys are building . I have a question, from my test recently, it is working fine if I put cache or remote storage in a mounted NFS volume, but if the workspace folder is in an NFS volume, `dvc add` will be super slow almost frozen and if I terminate it, some data will be deleted and lost, I just want to confirm here that this is expected behavior up to version 2.5.0 ? If so, is there any hack to mitigate this issue right now? Thanks.

**Comment by efiop** [comment] 2021-07-06 20:05
Hi @ZhengRui That sounds correct, yes. Using nfs only for cache (or as a local remote) is the workaround. Seeming data loss is just dvc not transferring everything completely, but the files should be intact in `.dvc/cache` if they are no longer present in the workspace. We'll be improving the rollback mechanism in the near future, so stay tuned :slightly_smiling_face:

**Comment by ZhengRui** [comment] 2021-07-07 01:10
Thanks @efiop , looking forward to the new features :) keep up the great work !

**Comment by brbarkley** [comment] 2021-10-12 18:14
Seeking clarification on status of this issue. From above, @efiop writes:

> As you've noticed, thanks to @agurtovoy we have #6111 🙏 that solves those particular issues. I can't give an ETA on it yet, as there are a few questions that we need to discuss there first. Just to make it clear, #6111 solves the issues, but we just want to make sure that we are providing the most seamless solution or have a clear plan to improve it in the future.

I see PR #6111 was closed in favor of PR #6419, which was merged on 9/18/21. Does that mean this issue #5562 is resolved in the v2.8.0 release on 10/11/21?

Thanks!

**Comment by efiop** [comment] 2021-10-12 18:40
@brbarkley Correct. This particular issue is about other things too, like optimizing, which is on our todo list.

**Comment by brbarkley** [comment] 2021-10-13 20:05
@efiop looks like it's best to stay at v1.11 if shared cache and workspace are both on nfs/cifs. At v2.8, it took about 5 minutes to compute hash of directory with 100 files whereas it took a few seconds on v1.11.

Thanks again for your continued work! Hope I can move to v2.X soon...

**Comment by daavoo** [comment] 2022-01-17 17:17
Two related issues on discord:

https://discord.com/channels/485586884165107732/485596304961962003/932563413777924096
https://discord.com/channels/485586884165107732/485596304961962003/932663444329615420

**Comment by bgroenks96** [comment] 2022-01-18 22:46
Happy to see that there has been some progress on this. This unfortunately makes dvc pretty much unsusale for me at the moment, except for small-data projects.

**Comment by bgroenks96** [comment] 2022-01-18 23:02
Also @brbarkley , 5 mins sounds great... I have been waiting over an hour for dvc to compute hashes on a directory with 1000+ files....

**Comment by bgroenks96** [comment] 2022-01-19 08:39
Upgrading to DVC 2.9.x and adding the config options suggested above seems to resolve this.

**Comment by karajan1001** [comment] 2022-04-12 08:18
> Hi! what is the latest news on this issue? Is it fixed? Updating and using the suggested config options fixed the `dvc init` error but it is still very slow.

We had updated several versions to improve it, but still not solved for now.
Could you please provide some more details? the info from `dvc doctor`

**Comment by EyescannerJE** [comment] 2022-04-12 14:05
@karajan1001 of course:
```
dvc doctor
DVC version: 2.9.3 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.13.0-39-generic-x86_64-with-glibc2.29
Supports:
	hdfs (fsspec = 2022.1.0, pyarrow = 7.0.0),
	webhdfs (fsspec = 2022.1.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	s3 (s3fs = 2022.1.0, boto3 = 1.20.24)
```
Maybe I have unrealistic time expectations, how long should i expect `dvc add` to take for a dataset of 139 GB with 1100 files to take?

**Comment by efiop** [comment] 2022-04-12 15:24
@EyescannerJE Could you please run `dvc doctor` inside of a dvc repository? It will have additional info about your setup.

Regarding the timing, it highly depends on the particular setup. We don't yet have benchmarks for NFS(or other similar setups), so I can't even give you an approximate estimate. We currently only have regular benchmarks for around ~20K image dataset on regular local filesystem, the results can be seen here https://docs.iterative.ai/dvc-bench/ We will be introducing bigger datasets to our benchmarks in the future. https://github.com/iterative/dvc-bench/issues/306

**Comment by EyescannerJE** [comment] 2022-04-13 05:41
@efiop I see, here is the output of `dvc doctor` from inside the dvc repository
```
DVC version: 2.9.3 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.13.0-39-generic-x86_64-with-glibc2.29
Supports:
	hdfs (fsspec = 2022.1.0, pyarrow = 7.0.0),
	webhdfs (fsspec = 2022.1.0),
	http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),
	s3 (s3fs = 2022.1.0, boto3 = 1.20.24)
Cache types: hardlink
Cache directory: cifs on //192.168.50.122/data
Caches: local
Remotes: local
Workspace directory: cifs on //192.168.50.122/data
Repo: dvc, git
```
Some benchmarks for NAS setups would be very much appreciated!

**Comment by hhoeflin** [comment] 2022-04-25 12:21
I was trying out the `state.dir`  and `index.dir` options and this does indeed solve the performance issue. However, I was wondering about another issue ... does this mean that I now have to do all my `dvc checkout` operations from the same machine (as /tmp is not shared across a cluster)? Is there a workaround for this?

Thanks!

**Comment by karajan1001** [comment] 2022-04-25 12:48
> I was trying out the `state.dir` and `index.dir` options and this does indeed solve the performance issue. However, I was wondering about another issue ... does this mean that I now have to do all my `dvc checkout` operations from the same machine (as /tmp is not shared across a cluster)? Is there a workaround for this?
> 
> Thanks!

Hi, @hhoeflin , These files are only local database caches (store some metadata), not the file cache. So it will not affect your `checkout` operation in other machines.

**Comment by pwrightkcl** [comment] 2022-06-07 17:57
I just wanted to add my own experience using DVC on NFS. I just came from Discord, where @dtrifiro started a thread [dvc slow on nfs](https://discordapp.com/channels/485586884165107732/983743637320003654) that led me to this issue, which seems to be the main one on the topic.

The `dvc add’ step took about 18 hours to process about 2000 files totalling about 100 GB.

```console
$ dvc add rawdata/
100% Adding...|████████████████████|1/1 [18:29:08, 66548.78s/file]
$ find rawdata/ -type f | wc -l
2102
$ du -h rawdata --max-depth 0
100G  rawdata
```

I then ran `dvc push` and this took about 4 mins, with most of the files showing about 20-30 MB / sec.

Here is my `dvc doctor`:

```
DVC version: 2.10.2 (pip)                                 
---------------------------------                         
Platform: Python 3.8.10 on Linux-4.15.0-180-generic-x86_64-with-glibc2.29                                     
Supports:                                                 
        webhdfs (fsspec = 2022.5.0),                      
        http (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),    
        https (aiohttp = 3.8.1, aiohttp-retry = 2.4.6),   
        ssh (sshfs = 2022.3.1)                            
Cache types: hardlink, symlink                            
Cache directory: nfs on 172.31.11.11:/flexgroup1          
Caches: local                                             
Remotes: local                                            
Workspace directory: nfs on 172.31.11.11:/flexgroup1  
Repo: dvc, git
```

I should also point out I'm running from an interactive docker container with the /nfs directory mounted. I'm not sure if this affects it.

**Comment by karajan1001** [comment] 2022-06-08 04:46
> Is there a timeline for fixing this compatibility issue @efiop ? I'm trying to get my company to adopt DVC but we use elastic filesystems (NFS) and DVC is dreadfully slow on them.

Have you tried setting `state.dir` and `index.dir` to some local paths?

**Comment by d-walkama** [comment] 2022-06-08 13:57
> 

Hello! Can it be a temporary directory?

**Comment by d-walkama** [comment] 2022-06-08 13:58
> > Is there a timeline for fixing this compatibility issue @efiop ? I'm trying to get my company to adopt DVC but we use elastic filesystems (NFS) and DVC is dreadfully slow on them.
> 
> Have you tried setting `state.dir` and `index.dir` to some local paths?

Hello! Can it be a temporary directory?

**Comment by d-walkama** [comment] 2022-06-08 17:57
> > > Is there a timeline for fixing this compatibility issue @efiop ? I'm trying to get my company to adopt DVC but we use elastic filesystems (NFS) and DVC is dreadfully slow on them.
> > 
> > 
> > Have you tried setting `state.dir` and `index.dir` to some local paths?
> 
> Hello! Can it be a temporary directory?

Update, this worked for me!!!!

**Comment by dberenbaum** [comment] 2022-06-08 18:32
Maybe we need to add a section to https://dvc.org/doc/user-guide/troubleshooting to explain this until we have a better solution?

**Comment by pwrightkcl** [comment] 2022-06-09 08:59
Small update: it worked for me even after deleting directories, so it looks like DVC creates them if they don't exist. Handy since mine are ephermeral.

**Comment by brbarkley** [comment] 2022-08-04 02:02
I can also confirm that performance is greatly improved as of v2.9 for shared cache configurations on CIFS and NFS. However, the traditional local cache and remote configuration seems to be very slow now (not sure if I tested that before; previous comments were based only on shared caches). 

> @hhoeflin You are correct, since tmp is moved to a local filesystem and not shared between machines it will indeed mean that checkout on another machine will not know to cleanup old files. The support for multiple machines on nfs is on our todo list as a part of this ticket and will require checkout mechanism to be adjusted

@efiop and @hhoeflin - what is the practical implication of dvc checkout not being able to clean up old files due to state and index being in local tmp? Will it fail? Just take a little longer? Something else?

**Comment by johan-sightic** [comment] 2023-02-08 14:01
What is the status of this now? Would mounting the NAS with SMB and Unix Extensions solve the problem of having to move index and state to local file system?

**Comment by zamzz** [comment] 2023-04-17 03:45
Going to +1 this issue. We've been trying to use smb/cifs as a shared cache but it seems computing/comparing hashes on the cifs-side is still a bit too much slower compared to using it as a local remote (using`2.54.0`). Appreciate the work though, this software has been super helpful overall.
A very surface-level (and uneducated) question: does the cache itself keep some sort of knowledge about what hashes it contains?

**Comment by dberenbaum** [comment] 2023-04-21 21:10
@efiop Maybe you could give your thoughts here? Do you see additional "low-hanging fruit" left for this scenario?

**Comment by efiop** [comment] 2023-04-21 22:23
For the record: we've moved sqlite stuff into a global directory in 2.48.0 to avoid running into problems on nfs/etc, so configuring `state.dir` and `index.dir` is no longer needed. CC @johan-sightic 

Next steps are just to optimize data mgmt operations in `dvc-data` to use as little fs calls as possible etc.

> A very surface-level (and uneducated) question: does the cache itself keep some sort of knowledge about what hashes it contains?

@zamzz The hash is in the name of the object and that's about all the info that cache itself has.

**Comment by dberenbaum** [comment] 2024-08-21 14:03
I think we have done what we can here for now and it would be more helpful to open a narrower issue if there are any problems remaining

**Closed by dberenbaum** 2024-08-21 14:03 UTC
Labels: enhancement, p2-medium, performance
