### ISSUE TITLE
run/repro: remove/hide deprecated `--remove-outs` option from output

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#2988] opened 2019-12-20 00:42 UTC
- [x] `-c`, `--cwd`
- [x] `-y`, `--yes`
- [x] `--remove-outs`

> Followup to #1853. More context in https://github.com/iterative/dvc.org/pull/877#discussion_r359993767
> Also related to #2985

**Comment by efiop** [comment] 2019-12-24 16:43
Closing as a duplicate of https://github.com/iterative/dvc/issues/2339

**Comment by efiop** [comment] 2019-12-24 16:46
Though, this ticket is about the action, so keeping it opened for now.

**Closed** 2020-12-08 01:26 UTC
Labels: c5-half-a-day, enhancement, good first issue, p2-medium
