### ISSUE TITLE
Azure OAuth failure

### ISSUE THREAD

**Issue by ctafabiano** [iterative/dvc#9833] opened 2022-10-10 10:29 UTC
# Bug Report

## Description
When using OAuth authentication to connect to Azure with DVC and executing push/pull operations the following error is returned:
`ERROR: unexpected error - Cannot combine AUTHORIZATION header with AUTH argument or credentials encoded in URL`

This behaviour has been reported in a similar case: https://github.com/iterative/dvc/issues/5589, but the error we receive is a new one.
We are currently following Iterative's guide for configuring DVC<>Azure: https://iterative.ai/blog/azure-remotes-in-dvc

When trying any of the suggested workarounds we still receive the same error. It is possible we are doing something wrong or our Azure accounts config is not right, but in that case it would be helpful to have a different error message or update the guide :) 

Related links we found around:
https://github.com/iterative/dvc/issues/2200
https://github.com/iterative/dvc.org/issues/462
https://github.com/Azure/azure-sdk-for-python/issues/18012

### Reproduce

```
0. brew update && brew install azure-cli
1. dvc init
2. dvc remote add -d storage azure://RESOURCE/FOLDER
3. az login
4. dvc remote modify storage account_name 'USERNAME'
5. dvc add data/.
6. dvc push
```
If doing pull from an already uploaded DVC repo on Azure, we get the same error message:
`ERROR: unexpected error - Cannot combine AUTHORIZATION header with AUTH argument or credentials encoded in URL`

### Expected
Files on `data` folder to be uploaded to Azure.
We are currently able to work fine (push and pull) with token authentication using `AZURE_STORAGE_KEY`, but this is a temporary solution for us and would like to move to full OAuth.

### Environment information
**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 2.29.0 (pip)
---------------------------------
Platform: Python 3.10.7 on macOS-12.5.1-arm64-arm-64bit
Subprojects:
	dvc_data = 0.14.0
	dvc_objects = 0.5.0
	dvc_render = 0.0.11
	dvc_task = 0.1.3
	dvclive = 0.11.0
	scmrepo = 0.1.1
Supports:
	azure (adlfs = 2022.10.0, knack = 0.10.0, azure-identity = 1.11.0),
	http (aiohttp = 3.8.3, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.3, aiohttp-retry = 2.8.3)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s8s1
Caches: local
Remotes: azure
Workspace directory: apfs on /dev/disk3s8s1
Repo: dvc
```

**Comment by dberenbaum** [comment] 2023-08-10 14:53
Transferred to dvc for more visibility and since it directly impacts dvc usage.

**Comment by efiop** [comment] 2023-08-11 22:08
Ok, can reproduce as well now (not sure why I wasn't the last time, maybe used an admin account by accident or something). Seems like we need to add some other role than just `Storage Blob Data Contributor` by the look of it. Investigating...

**Comment by efiop** [comment] 2023-08-11 22:29
Btw, just for the record: a workaround is to use another auth mechanism (e.g. connection string).

**Closed** 2023-08-11 23:13 UTC
Labels: bug, p1-important, fs: azure, A: cloud-versioning

**Comment by efiop** [comment] 2023-08-11 23:17
@ctafabiano @smarais Hey folks, could you please upgrade `dvc-azure` package with `pip install -U dvc-azure` (make sure it is 2.22.1) and see if that fixes it for you?

Turns out there was a bug in `dvc-azure`, where we accidentally made `adlfs` default to anon login when `version_aware` was enabled.

**Comment by smarais** [comment] 2023-08-14 15:24
Hi @efiop, this seems to have resolved the issue for me.
I appreciate the quick turnaround!
