### ISSUE TITLE
Stage dependency with imported data attempts to source control data

### ISSUE THREAD

**Issue by tjjack1226** [iterative/dvc#9347] opened 2023-04-19 14:09 UTC
# Bug Report

## Description

Imported data listed as stage dependency in dvc.yaml is staged as changes to be pushed to remote.

### Reproduce

```
dvc import <source-repo> <import-to-directory>
dvc stage add -n <name> -d <import-to-directory>
dvc exp run
```
I'm using the DVC VSCode extension, and at this point, the imported dataset is being listed as a change to push to remote.

### Expected

Imported dataset should be ignored by DVC in this current repo, since it's files are managed in the repo where it's being imported from.  This was the behavior observed in previous versions of dvc (previously using 2.30.1) 

### Environment information

VSCode extension v0.7.9
dvc                    2.54.0
dvc-data            0.47.2
dvc-http            2.30.2
dvc-objects        0.21.1
dvc-render         0.3.1
dvc-s3                2.21.0

**Output of `dvc doctor`:**

```console
dvc doctor
DVC version: 2.54.0 (pip)
-------------------------
Platform: Python 3.9.16 on Windows-10-10.0.19042-SP0
Subprojects:
        dvc_data = 0.47.2
        dvc_objects = 0.21.1
        dvc_render = 0.3.1
        dvc_task = 0.2.0
        scmrepo = 1.0.2
Supports:
        http (aiohttp = 3.8.1, aiohttp-retry = 2.5.2),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.5.2),
        s3 (s3fs = 2022.5.0, boto3 = 1.21.21)
Cache types: hardlink
Cache directory: NTFS on C:\
Caches: local
Remotes: s3
Workspace directory: NTFS on C:\
Repo: dvc, git
Repo.site_cache_dir: C:\ProgramData\iterative\dvc\Cache\repo\a7f6484c79a07b609045727ec75265ff
```

**Additional Information (if any):**

I have a feeling this could be related to bug [#9346](https://github.com/iterative/dvc/issues/9346) but as the use case is different, I thought it best to report this one as well.

**Comment by daavoo** [comment] 2023-04-26 08:40
Thanks @tjjack1226 !
I am closing this as duplicate of https://github.com/iterative/dvc/issues/9346 as the underlying bug is the same

Please refer to that issue for more info.

**Closed by daavoo** 2023-04-26 08:40 UTC
Labels: bug, A: status
