### ISSUE TITLE
DVC not supporting templating for artifacts

### ISSUE THREAD

**Issue by mnrozhkov** [iterative/dvc#9999] opened 2023-10-05 14:29 UTC
I tried to use the templating artifacts section in dvc.yaml file, but Studio can't parse it and there are not artifact updates in `dvc.lock` (should it be there?)
Example repo: https://github.com/mnrozhkov/monorepo-reusable-pipelines

Here is dvc.yaml example:
```yaml
artifacts:
  pipeline_a_segment_model:
    path: pipeline_a_segment/${target}/${model_dir}/model_pipeline_a_segment_${target}_UPPER.file
    type: model
```

**Comment by dberenbaum** [comment] 2023-10-05 17:58
Related: https://github.com/iterative/dvc/issues/8696

**Comment by dberenbaum** [comment] 2023-10-05 17:59
@skshetry What would it take to support templating for other top-level sections (not including foreach/matrix, just interpolation)?

**Comment by dberenbaum** [comment] 2024-02-06 13:42
Closing as a duplicate of #8696 to consolidate.

**Closed by dberenbaum** 2024-02-06 13:42 UTC
Labels: A: templating, A: artifacts
