### ISSUE TITLE
dvc: dvc move doesn't update deps

### ISSUE THREAD

**Issue by Suor** [iterative/dvc#3007] opened 2019-12-26 06:06 UTC
Situation:

```bash
dvc add foo
dvc run -d foo -o foo_refined ./refine.py
dvc move foo proper_name
```

The last command will:
- rename `foo` to `proper_name`
- rename `foo.dvc` to `proper_name.dvc`
- replace `foo` with `proper_name` in `.gitignore`

However, it won't update dep path in `foo_refined.dvc`

**Comment by shcheklein** [comment] 2019-12-26 21:14
`dvc move` handles only `dvc add`-ed file - see https://dvc.org/doc/command-reference/move . Also, I believe this a duplicate of https://github.com/iterative/dvc/issues/1489 . Also, see this https://github.com/iterative/dvc/issues/2516 and related tickets. 

Bottom line - it's not that easy to fix `move`.

**Closed** 2019-12-26 22:00 UTC
Labels: triage
