### ISSUE TITLE
dvc.api.get_url() with rev arg fails

### ISSUE THREAD

**Issue by jorgeorpinel** [iterative/dvc#5620] opened 2021-03-15 03:36 UTC
# Bug Report

> Context: https://groups.google.com/a/iterative.ai/forum/?utm_medium=email&utm_source=footer#!msg/support/z_7ieP8iJ90/NyE61iEdBwAJ

## Description

> I can't specify neither tag name nor commit hash into 'rev' parameter.

### Reproduce

> The code snippet is simply as follows:
![image](https://user-images.githubusercontent.com/1477535/111100195-cbc94880-850c-11eb-978d-50467759bc9b.png)
>
> If I don't specify the 'rev' here at all - no errors, dvc provides the latest version just fine.
But if I specify 'rev' then the error is as following:
![image](https://user-images.githubusercontent.com/1477535/111100247-ec919e00-850c-11eb-94a2-44f38716bdb7.png)

### Environment information

> My dvc version is 2.0.1.

**Additional Information (if any):**

> my remote storage is set locally:
![image](https://user-images.githubusercontent.com/1477535/111100336-282c6800-850d-11eb-88ce-3556a3f806d8.png)

> also the data was definitely pushed with dvc push. It can be pulled with the latest version.
Versions themselves was also tagged:
![image](https://user-images.githubusercontent.com/1477535/111100321-1cd93c80-850d-11eb-88c0-154e43ab7107.png)

**Comment by jorgeorpinel** [comment] 2021-03-15 03:37
I've asked the user to subscribe here in order to get more info from him if needed.

**Comment by skshetry** [comment] 2021-03-15 03:42
Duplicate of https://github.com/iterative/dvc/issues/5590

**Closed** 2021-03-16 13:36 UTC
Labels: api, bug, p0-critical, regression
